### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by alechash** [duino-coin/duino-coin#10]
Not sure if this is cause I'm running on a Mac, Ill try later on a Linux but just wanted to get that out there just in case it is a problem. I'm running Version 1.1.

I'll post updates if it works on Linux. I'm sure it will though.
<img width="1068" alt="Screen Shot 2020-03-25 at 3 25 16 PM" src="https://user-images.githubusercontent.com/55750096/77577264-d67a7000-6eac-11ea-971b-5b21da462a7a.png">

**Comment by revoxhere** [comment]
You can install it manually using `python3 -m pip install configparser`. Linux version isn't pre-compiled so libraries aren't attached to it, but I'll try to do something about it.

**Comment by alechash** [comment]
Yes, this is my bad. Been a long time since I've used python. I was using 2.7 not 3
