### ISSUE TITLE
Can't start mining on my ubuntu

### ISSUE THREAD

**Issue by ppzstudio** [duino-coin/duino-coin#1005]
i have error on my ubuntu
05:09:55  net0  Searching for the fastest node to connect to
05:09:55  net0  Error fetching mining node: No active exception to reraise, retrying in 15s

**Comment by revoxhere** [comment]
Hey, can you try now with the lastest miner?

**Comment by ppzstudio** [comment]
![image](https://user-images.githubusercontent.com/90672907/133890800-514a02c0-ff4a-403f-b1a8-3ec6d6b250a8.png)
I have already updated by git pull

**Comment by revoxhere** [comment]
Can you access https://server.duinocoin.com/getPool in your browser?

**Comment by ppzstudio** [comment]
"error":"You're using a Proxy, VPN, VPS or a similar service. This is against our Terms of Service","success":false
Ok, not support vps.
Thanks
