### ISSUE TITLE
Dosen't connect to WiFi on ESP32

### ISSUE THREAD

**Issue by Mowglli** [duino-coin/duino-coin#1007]
I've run a miner on ESP32 with v2.5, which worked fine. I updated to v2.7.2, and now i cant se my miner on wallet.duino or on a lan sweep with network analyser.
I've tried with 2.4GHz and 5GHz, with no luck.
Am i doing something wrong ?

**Comment by bradbyte** [comment]
Can you inspect Serial Monitor and see if it's connecting but the API side isn't recognizing it?

**Comment by Mowglli** [comment]
Hello, i've actually just connected it and looked at the serial monitor with baud 500000. Suddenly it connected and started mining. I think i have made a mistake before in the code. Thanks for answering. I'll close the issue
