### ISSUE TITLE
ESP32 /getPool error

### ISSUE THREAD

**Issue by sagaardu** [duino-coin/duino-coin#1012]
Hello good,

I have several Wemos D1 mini working normally, however I am trying to put an ESP32 on and I can't get it to work, the whole ratro is trying to connect and restarting when it gets three consecutive failed attempts.

This is what comes out of the console:

```
Please, check if your WiFi network is on the list and check if it's strong enough (greater than -90).
ESP32 will reset itself after 60 seconds if can't connect to the network
Connecting to: WLAN_XXXX............
Connected to WiFi!
    IP address: 10.30.1.106
      Rig name: Esp32

Fetching pool... 
[HTTP] GET... failed, error: connection refused
Fetching pool... 
[HTTP] GET... failed, error: connection refused
Fetching pool... 
[HTTP] GET... failed, error: connection refused
Fetching pool... 
E (71486) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (71486) task_wdt:  - WiFirec (CPU 0)
E (71486) task_wdt: Tasks currently running:
E (71486) task_wdt: CPU 0: IDLE
E (71486) task_wdt: CPU 1: loopTask
E (71486) task_wdt: Aborting.

abort() was called at PC 0x400e738f on core 0


Backtrace:0x400e7e51:0x3ffbe9c00x40093919:0x3ffbe9e0 0x40099229:0x3ffbea00 0x400e738f:0x3ffbea80 0x40085d0d:0x3ffbeab0 0x401723bb:0x3ffbd3a0 0x400e7c45:0x3ffbd3c0 0x40094ee3:0x3ffbd3e0 


ELF file SHA256: 0000000000000000

Rebooting...
x[00][00]øx[00][00][00][00]xxxxø[00][00][00][00][00][00][00][00]

Duino-Coin Official ESP32 Miner 2.73
```

Any idea what the problem may be?

Greetings

**Comment by revoxhere** [comment]
Hello, can you access https://server.duinocoin.com/getPool in your browser?

**Comment by sagaardu** [comment]
> Hello, can you access https://server.duinocoin.com/getPool in your browser?

Hello, 

Yes, 
It returns a JSON with the fields

{"name": "xxxx", "ip": "X.X.X.X", "port": xxxx, "success": true}

**Comment by revoxhere** [comment]
Can you check now?

**Comment by sagaardu** [comment]
> Can you check now?

Hi, not work.

Fetching pool... 
deserializeJson() failed: InvalidInput

**Comment by gsrbr** [comment]
Hello @sagaardu ,I believe this was a connection error, try to access this [link](https://server.duinocoin.com/getPool) using the same network you are mining on, if it returns an ip and some more information, try to mine again, if this did not work please tell us what appears when you try to access it

**Comment by sagaardu** [comment]
> Hello @sagaardu ,I believe this was a connection error, try to access this [link](https://server.duinocoin.com/getPool) using the same network you are mining on, if it returns an ip and some more information, try to mine again, if this did not work please tell us what appears when you try to access it

Hi, link show me this:

{"name":"svko-pool-2","ip":"5.230.69.132","port":6002,"success":true}

But Esp32 not work:


```
Please, check if your WiFi network is on the list and check if it's strong enough (greater than -90).
ESP32 will reset itself after 60 seconds if can't connect to the network
Connecting to: WLAN_XXXX............
Connected to WiFi!
    IP address: 10.30.1.108
      Rig name: ESP32-2

Fetching pool... 
deserializeJson() failed: InvalidInput
```

**Comment by sagaardu** [comment]
Hello good,

If I restart several times the ESP32 sometimes manages to connect.

I think the problem may be due to my internet connection (although I don't understand why it only fails with the Esp32), I have to check it in another connection.

Greetings

**Comment by gsrbr** [comment]
Hello @sagaardu we are experiencing some instabilities, our team is already analyzing what may be happening
