### ISSUE TITLE
New Diff for Raspberry Pi Zero

### ISSUE THREAD

**Issue by celoibarros** [duino-coin/duino-coin#1013]
**Is your feature request related to a problem? Please describe.**
Raspberry Pi Zero mining too slow.

**Describe the solution you'd like**
A specific DIFF for Raspberry Pi Zero

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/16102901/133603744-1f40b15f-0c62-49fd-8ee2-25cf6dce2467.png)

**Comment by gsrbr** [comment]
Hello @celoibarros what diff are you using?

**Comment by celoibarros** [comment]
HI @gsrbr ,

I am using LOW, on PC_Miner.

**Comment by revoxhere** [comment]
Hello, there's no need for a separate diff for the Pi Zero, the screenshot you attached is from an external website.
