### ISSUE TITLE
PC_Miner share_print function should show hashrate instead of total_hashrate 

### ISSUE THREAD

**Issue by celoibarros** [duino-coin/duino-coin#1014]
**Describe the bug**
PC_Miner share_print function should print hashrate

**To Reproduce**
Start PC_Miner with more than 1 thread

**Expected behavior**
Show correct hashrate of each thread

**Screenshots/photos**
![image](https://user-images.githubusercontent.com/16102901/133604178-cfcaddd4-70f2-4313-a504-c320323f0e04.png)

**System (please complete the following information):**

**Additional context**

**Comment by revoxhere** [comment]
PC miner shows the total hashrate, not separate
