### ISSUE TITLE
PC Miner REST and/or a TCP API

### ISSUE THREAD

**Issue by blackmennewstyle** [duino-coin/duino-coin#1015]
Hi guys,

Could it be possible to have the **PC_MIner.py**, while running, being able to output statistics data over some REST API?

There is a lot of mining software out there, which allow users to have access to statistics data over some REST API or/and even over TCP connection. I was wondering if Duino-coin "PC_Miner.py" could offer us the same possibility in the future.

**Comment by revoxhere** [comment]
We may consider this for the future

**Comment by blackmennewstyle** [comment]
Thank you, that would be amazing :)
Have a great weekend <3
