### ISSUE TITLE
Term of service about difficulty and Setup

### ISSUE THREAD

**Issue by ipinyulun** [duino-coin/duino-coin#1016]
Thank you for the coin

with my old computer Intel® Celeron(R) CPU J3160 @ 1.60GHz × 4 
what difficulty should i mine so it doesnt violate term of service

![image](https://user-images.githubusercontent.com/44455228/133745174-7ff67cf7-48d3-4e0e-ba32-e09289bcf31e.png)

following the guide from PC_Miner.py setup.. i should choose low
as its an older PC...
however its also works on MEDIUM difficulyy

therefore what is the recommended difficulty setting for me?

**Comment by revoxhere** [comment]
Hello, there's no need to worry about difficulty setting as you'll get adjusted by the Kolka system accordingly.

**Comment by ipinyulun** [comment]
alright. Thanks bro. 
nice to hear that.



Have a nice day!
