### ISSUE TITLE
Crome file download

### ISSUE THREAD

**Issue by GTmanbru** [duino-coin/duino-coin#1019]
Can you add a file for Crome OS 
![image](https://user-images.githubusercontent.com/90293665/133858488-861d8119-6415-40d2-a54b-c57c275cfaea.png)

**Comment by gsrbr** [comment]
Hi, thanks for the suggestion, we currently use PyInstaller to create the specific builds, and it doesn't support chromeOS, only Windows, Mac OS X, and GNU/Linux, I believe you can normally use the python version of the source code

**Comment by revoxhere** [comment]
We're not planning on supporting chromeOs natively, sorry.
