### ISSUE TITLE
CPU Intensity setting disabled in 2.7.3

### ISSUE THREAD

**Issue by cjlcams** [duino-coin/duino-coin#1021]
I have used 2.7.3 and have noticed that cpu usage is always at 100% even though i set the intensity to 60% only at the settings.cfg. On 2.7 it follows the intensity set in the settings config. So reverted back to 2.7 for the meantime for PC miner.

**Comment by BastelPichi** [comment]
hmmm. What if you set it really low to something like 10%?

**Comment by cjlcams** [comment]
still the same. notice the CPU usage at the pic.
![image](https://user-images.githubusercontent.com/90971690/133910611-e242f36b-f8f5-4115-82a1-18136dfd6395.png)

on 2.7 when I set it to 10% intensity, it follows
![image](https://user-images.githubusercontent.com/90971690/133910623-4f84762b-26fe-41fb-9e7e-c1bcdf495c3f.png)

**Comment by gsrbr** [comment]
Hello @cjlcams , by reading the source code we can confirm that in this latest release the efficiency feature was not added to pc_miner, I believe it is due to some problems with some linux distros, which simply froze when the efficiency handling resources were used, we will study the feasibility of reactivating this feature in the future

**Comment by cjlcams** [comment]
Okay thanks. Hope this feature will be enabled again. For the meantime, I will be using 2.7 for PC miner. Thanks again.

**Comment by gsrbr** [comment]
Hello @cjlcams are you okay?
The CPU Intensity setting was enabled again by Revox on the [last release](https://github.com/revoxhere/duino-coin/releases/tag/2.7.4) can you test if this resolve your problem?

**Comment by lghustle** [comment]
REMOVEEEEE!!!!!!!

L.G.

**Comment by BastelPichi** [comment]
> REMOVEEEEE!!!!!!! L.G.
> […](#)
> On Sep 18, 2021, at 7:00 PM, cjlcams ***@***.***> wrote: ﻿ still the same. on 2.7 when I set it to 10% intensity, it follows — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

STop commenting that on every issue.

**Comment by cjlcams** [comment]
When starting the app, cpu usage spikes as shown, after a minute when the diff normalizes it will now react to whatever cpu intensity is set unlike the previous release. On 2.7 it handles cpu usage more beautiful coz it will gradually increase usage until it will normalize to whatever intensity is set. If it can't be helped then its much better than constant 100% cpu usage. Thanks for the fix.
![image](https://user-images.githubusercontent.com/90971690/142744813-8a00649f-3161-4ce1-9089-f46f87615dd8.png)
