### ISSUE TITLE
Error connecting to the AVR! 

### ISSUE THREAD

**Issue by aroshad7** [duino-coin/duino-coin#1022]
**Describe the bug**
"Error connecting to the AVR!" message appears for one AVR when there are more than 2 devices connected. Other two devices works fine. Connection verified multiple times - not a connection issue as suggested. Happened on both windows and RPi as host modes. Reason goes as follows. 

**To Reproduce**
1. Connect at least 3 AVR devices with firmware. 
2. Run AVR Miner and wait

**Expected behavior**
All 3 AVRs mining successfully.

**Screenshots/photos**
![image](https://user-images.githubusercontent.com/17607362/133894279-c377526c-7044-4d57-a9d8-bd44ac8e8859.png)

**System**
 - OS: Windows 10 and Raspberry Pi OS lite (Buster lite)
 - AVR Miner
 - Version 2.7.3

**Comment by gsrbr** [comment]
Hello, this it's a communication error with the AVR, there are basically 3 causes to this:

1. Older/Corrupted sketch on AVR, try to reflash the code to the AVR
2. AVR read timeout, try to change the time on the config file, changing the parameter `avr_timeout = 4` to 6 or more
3. Some issue on AVR energy supply or USB connection, if you are using a USB hub, try to without it, or try to change de usb cable

**Comment by aroshad7** [comment]
@gsrbr Thanks for quick update. I think the problem was running arduino sketch version 2.7.2 with miner version 2.7.3. It seems fine now. Will update here if anything comes up. Kudos for the whole thing 💖

**Comment by zhuyingqin** [comment]
16:39:24  net0  Error fetching mining node: HTTPSConnectionPool(host='server.duinocoin.com', port=443): Max retries exceeded with url: /getPool (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))), retrying in 15s

**Comment by BastelPichi** [comment]
> 16:39:24 net0 Error fetching mining node: HTTPSConnectionPool(host='server.duinocoin.com', port=443): Max retries exceeded with url: /getPool (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))), retrying in 15s

Hmmm. Can you try again now?

**Comment by BastelPichi** [comment]
Closed due to no reply and solve.
