### ISSUE TITLE
Cannot Login To Wallet - Server Maintenance?

### ISSUE THREAD

**Issue by JordanEJ** [duino-coin/duino-coin#1032]
Hey,

I have been mining Duino coin on some esp8266's and 3 AVR miners for a few weeks now. Over the last two days, I have not been able to get into my account. It just says that the server is under maintenance. 
![image](https://user-images.githubusercontent.com/91357710/135363950-0d249c93-6344-40e8-9d61-d0b490cea8b4.png)

I have tried to get a preview of my wallet on the Lukas dashboard but that fails as well. It shows that there are some problems with some of the servers. Over the last few days, different servers have been shown to have different problems.
![image](https://user-images.githubusercontent.com/91357710/135364092-d570986d-9e10-46cb-bb0f-ea5af7f42c04.png)

I am just wondering if anyone else has been getting the same problem as me. I have tried logging in on multiple devices but all have failed.

**System**
 - OS: [Windows, IOS]
 - Software [ESP8266, AVR Miner]
 - Version [2.7.3]

Hopefully, this can be fixed. 🤞

**Comment by gsrbr** [comment]
Hello @JordanEJ , we are experiencing some instabilities, our team is already analyzing what may be happening... If you wish you can enter our [discord](https://discord.gg/kvBkccy) server to follow the updates

**Comment by JordanEJ** [comment]
Just making sure that you knew about it. Keep up the good work!! 👍
