### ISSUE TITLE
錢包故障

### ISSUE THREAD

**Issue by tyng1977** [duino-coin/duino-coin#1035]
你好，錢包還是進不去，請問還需維修多長時間呢?

**Comment by primitt** [comment]
Hello! We are currently facing a ddos attack, so the wallet wont work for now.

**Comment by tyng1977** [comment]
謝謝你們的努力，加油

**Comment by Bilaboz** [comment]
Wallets, PC mining and AVR mining are working again
ESP mining will be operational within 12 hours

**Comment by tyng1977** [comment]
謝謝

Bilaboz ***@***.***> 於 2021年10月2日 週六 上午8:15寫道：

**Comment by mahesh1987-16** [comment]
No miners detected help!!!!!!!!!!!!!!!
