### ISSUE TITLE
No miners detected 

### ISSUE THREAD

**Issue by mahesh1987-16** [duino-coin/duino-coin#1040]
No miners detected

**Comment by gsrbr** [comment]
Hello @mahesh1987-16 , we were experiencing some instabilities, could you check again now please, you may need to restart your miners

**Comment by mahesh1987-16** [comment]
> Hello @mahesh1987-16 , we were experiencing some instabilities, could you check again now please, you may need to restart your miners

I have restarted many times.
Rig are working too.
Reward are being generated.
Just not detecting the minier

**Comment by blazecoding2009** [comment]
Hey @mahesh1987-16 , The servers were getting attacked, the servers are slowly coming back but no guarantee when it'll be back. Hopefully in the next few days. Also if your miners aren't getting detected, don't panic. It's because some of the pools are down.

**Comment by revoxhere** [comment]
Should be fixed since yesterday
