### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by lawal12345** [duino-coin/duino-coin#1043]
Hi when will the server back online

**Comment by niki-94** [comment]
I cant login to my account.

**Comment by blazecoding2009** [comment]
There are issues with the servers currently (DDoS) Once the servers are back fully, they'll send out an announcement

**Comment by gravedigger21** [comment]
нихрена не работает

**Comment by uvicorn** [comment]
> 
> 
> нихрена не работает

нихрена и не работало

**Comment by gravedigger21** [comment]
> 
> 
> > нихрена не работает
> 
> нихрена и не работало

+100500 ))

**Comment by blackmennewstyle** [comment]
> There are issues with the servers currently (DDoS) Once the servers are back fully, they'll send out an announcement

I think the situation highlights in some way the limitations of a centralized project. And don't get me wrong the Duino-coin project is really fun and very interesting in so many aspects. But maybe having a decentralized network, blockchain and wallet, could actually be more secure-proof and future-proof in the log term.
The project is still young and the white-paper is pretty clear about the reasons for a centralized project regarding the hardware utilized for mining. But again maybe now is another opportunity to reconsider that choice.

**Comment by tyng1977** [comment]
> > 當前服務器存在問題 (DDoS) 一旦服務器完全恢復，他們將發出通知
> 
> 我認為這種情況在某種程度上突出了中心化項目的局限性。不要誤會我的意思，Duino-coin 項目真的很有趣，而且在很多方面都非常有趣。但也許擁有一個去中心化的網絡、區塊鍊和錢包，在日誌方面實際上可以更安全、更經得起考驗。 該項目還很年輕，白皮書非常清楚地說明了有關用於挖礦的硬件的中心化項目的原因。但也許現在又是一個重新考慮這個選擇的機會。



我覺得他講得非常棒!!
去中心化可以讓Duino coin這個好項目走的更長遠，也可以讓區塊鏈技術保護錢包的安全

**Comment by BastelPichi** [comment]
It seems like the DDoS has stopped. I can use all DuinoCoin services without a problem

**Comment by tyng1977** [comment]
謝謝

Robert Piotrowski ***@***.***> 於 2021年10月8日 週五 下午2:36寫道：
