### ISSUE TITLE
The translation was made without me

### ISSUE THREAD

**Issue by pinokio240** [duino-coin/duino-coin#1044]
The user transferred 10 coins to himself without my participation, now I can only change the password. Found this by looking at my statistics at https://explorer.duinocoin.com/ login Pinokio240
• 18/09/2021 18:11:36 Sent 5 DUCO to Faucet_Furimos69420 (d02caad9)
• 18/09/2021 18:11:23 Sent 5 DUCO to Faucet_Furimos69420 (58047b30)

**Comment by pinokio240** [comment]
The password could not be updated says "Your old password doesn't match!" although the password was entered correctly

**Comment by pinokio240** [comment]
Now, in general, he writes an incorrect password how to recover it?

**Comment by primitt** [comment]
Hello! It is not possible to recover it, so you will have to make a new account. (your password is your "private key") I will look into this incident.

**Comment by primitt** [comment]
Hello! This user Faucet_Furmos420 is the Furim Faucet Raffle ticket account. Someone could have figured out your account password and used it to buy a raffle ticket.
