### ISSUE TITLE
arduino nano 33 ble unique id

### ISSUE THREAD

**Issue by strik3** [duino-coin/duino-coin#1054]
when attempting to compile and upload the arduino_code.ino its throwing an error as the nrf52840 chip is not supported.

would it it be possible to add support for this chipset?

**Comment by revoxhere** [comment]
You will need to write the code for it yourself, none of us owns this board

**Comment by revoxhere** [comment]
Reopen if needed

**Comment by yit6yoit** [comment]
After vibe coding a little bit with ai i transformed the avr code to work with arm devices

https://github.com/yit6yoit/Arduino_arm_duco
