### ISSUE TITLE
Raspberry pi pico keeps getting rejected shares

### ISSUE THREAD

**Issue by codeoffun2** [duino-coin/duino-coin#1070]
I get this error while mining with a raspberry pi pico and it rejects all my shares
00:24:16.004720 DEBUG: COM15: retrieved feedback: BAD,Incorrect device
00:24:16  avr15  Rejected 0/15 (0%) ∙ 00.2s ∙ 3 kH/s @ diff 6 ∙ ping 140ms
00:24:16.044617 DEBUG: COM15: Requesting job
00:24:16.060240 DEBUG: COM15: Received:
00:24:16  net15  Error connecting to the server. Retrying in 10s (err handling result: list index out of range)
00:24:19  sys15  Closed COM port COM15

**Comment by codeoffun2** [comment]
it starts mining after a while

**Comment by gsrbr** [comment]
Hello @Codeofun , it's very difficult to maintain support for each individual board, currently PICO is having some problems with our codes, what you can try to do is increase `avr_timeout = 4` to `10` or more, in the config file `Settings.cfg`, if it works please let us know

**Comment by BastelPichi** [comment]
Closed due to inactivity. Feel free to reopen if needed.

**Comment by lghustle** [comment]
reMOVE

L.G.
