### ISSUE TITLE
can it work with Atmega168 ?

### ISSUE THREAD

**Issue by werdegars** [duino-coin/duino-coin#1080]
hello,

i have some arduino pro mini 168 (3.3v 8Mhz version) laying around
will it work?

**Comment by JK-Rolling** [comment]
yes, it'll work. but you'll need usb-serial to upload the sketch. 2 ways to mine, usb-serial or i2c to connect to the host machine

**Comment by BastelPichi** [comment]
Yes. Should work. You just either need an i2c host or need to have a usb to ftdi breakout board connected all the time.

**Comment by werdegars** [comment]
I tried to use i2c using https://github.com/ricaun/DuinoCoinI2C
but they keep saying TIMEOUT, why?
but not with the pro mini 328

**Comment by BastelPichi** [comment]
Its a different processor. Thats why it may not work. Also you need to be careful with 3.3v/5v voltage levels. Try to use a USB to FDTI first, and then try to use i2c.

> I tried to use i2c using https://github.com/ricaun/DuinoCoinI2C but they keep saying TIMEOUT, why? but not with the pro mini 328

**Comment by lghustle** [comment]
REMOVE

L.G.

**Comment by BastelPichi** [comment]
OK...
