### ISSUE TITLE
sha1.h no such file or directory found

### ISSUE THREAD

**Issue by dvoorkamp1** [duino-coin/duino-coin#1083]
I tried to download the arduino software onto my mega board, and upon verifying or uploading it gives me the same error message " sha1.h no such file or directory found."

**To Reproduce**
Not sure if this is reproducible, found this project from the instructables page and downloaded the code from there

**Expected behavior**
I expected it to download without this issue
**Screenshots/photos**
![image](https://user-images.githubusercontent.com/93497391/139606343-d527cd0e-0b57-46a1-abfc-8b8c7e539094.png)

**System (please complete the following information):**
Windows 10 
Arduino Mega
Duinocoin software from instructables download

**Additional context**
I'm new to all this found an old arduino of mine figured I'd give this a shot, don't give me too much shit if I did something 
ridiculously stupid

**Comment by JK-Rolling** [comment]
unzip the whole .zip file and open Arduino_Code.ino **IN** the directory. there should be multiple files within that directory

**Comment by dvoorkamp1** [comment]
From what I can tell I have the whole file unzipped, but what do you mean by opening that file IN the directory? I've been opening the Arduino_Code.ino file by downloads>duino-coin_2.2_windows>arduino_code and then selecting the code file. once again I'm really not great at this so don't be too mad if the issue is something simple

**Comment by BastelPichi** [comment]
Hey,
youre using on really old realease. Download the latest version from [here](https://github.com/revoxhere/duino-coin), then try again.

**Comment by dvoorkamp1** [comment]
Hey! Tried again, now it's throwing the same error, except this time it's doing it for the UniqueID.h file

**Comment by BastelPichi** [comment]
hmmmm, thats weard. Try using the latest [source version](https://github.com/revoxhere/duino-coin) (you need python) or try installing the uniqeID library via the Library Manager (sketch -> Include Librarys -> Library Manager). If this dotn works, try reinstalling the Arduino IDE.

**Comment by revoxhere** [comment]
Are you still facing this issue?

**Comment by BastelPichi** [comment]
Closed due to inactivity. Feel free to reopen if needed.
