### ISSUE TITLE
Webminer stucks on 0/0 Accepted Shares

### ISSUE THREAD

**Issue by LiteItOn** [duino-coin/duino-coin#1085]
![obraz_2021-11-01_110508](https://user-images.githubusercontent.com/91718743/139655330-2c8f9f1b-322d-483d-a443-8ec27aa82d00.png)

**Comment by revoxhere** [comment]
Can you try again now?

**Comment by LiteItOn** [comment]
> Can you try again now?


Still nothing ;p
![image](https://user-images.githubusercontent.com/91718743/139695182-862e7a99-34d7-4ffd-8f31-04bc5e034761.png)

**Comment by LiteItOn** [comment]
I also tried on Firefox and I have exactly the same as in the picture

**Comment by LiteItOn** [comment]
Okay, now it works ;D
![image](https://user-images.githubusercontent.com/91718743/139731133-2b6ea249-0b1a-42db-b774-92d556c624ee.png)

**Comment by LiteItOn** [comment]
i think we can close this issue

**Comment by Kira1605** [comment]
Здраствуйте у меня такая же проблема что мне сделать что бы все работало
