### ISSUE TITLE
Error fetching mining node: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by LiteItOn** [duino-coin/duino-coin#1086]
Raspberry Pi 4B 
Raspberry pi OS
![image](https://user-images.githubusercontent.com/91718743/139689182-d7d53d44-1dbf-4d37-ab18-efd32cc02aac.png)

**Comment by revoxhere** [comment]
Can you try again now?

**Comment by Astro8052** [comment]
I just tried It and it gives me the same message

**Comment by LiteItOn** [comment]
> Can you try again now?

Yup, now it's works thanks!
![image](https://user-images.githubusercontent.com/91718743/139695425-6761da33-7005-4aed-a3dc-be88f8176705.png)
