### ISSUE TITLE
Cannot run Wallet.exe

### ISSUE THREAD

**Issue by duoduo6666** [duino-coin/duino-coin#1094]
![捕获](https://user-images.githubusercontent.com/69453266/140659104-4781978e-4d15-4878-b281-5bba921218e9.PNG)

**Comment by revoxhere** [comment]
Hello, the GUI wallet has been deprecated, please use the web wallet.

**Comment by duoduo6666** [comment]
How do I Wrapping DUCO

**Comment by duoduo6666** [comment]
> 您好，GUI钱包已被弃用，请使用网页钱包。

How should I Wrapping DUCO

**Comment by BastelPichi** [comment]
If you still want to use the wallet, please make shure youre on 64bit system. If you are, try to open a CMD in the location the wallet is (click on the path-bar in windows explorere and type cmd) and launch the wallet from there by typing "start Wallet.exe". Then send the errors here.

**Comment by blazecoding2009** [comment]
Hello @duoduo6666 
The GUI wallet which comes with the .zip is deprecated and no longer maintained. We recommend you use the web wallet (https://wallet.duinocoin.com)

**Comment by BastelPichi** [comment]
Closed due to inactivity. Feel free to reopen if needed.

**Comment by lghustle** [comment]
Remove

L.G.
