### ISSUE TITLE
Can't start mining

### ISSUE THREAD

**Issue by Ibnu79** [duino-coin/duino-coin#1098]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ibnu79** [comment]
can't start mining the issues is writen : 
 Error connecting to the server. Retrying in 10s (connection err: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)

**Comment by Ibnu79** [comment]
can't start mining the issues is writen :
Error connecting to the server. Retrying in 10s (connection err: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)

**Comment by BastelPichi** [comment]
Maybe  IP banneyourebanned the server. If you cant see https://server.duinocoin.com/getPool , write an email to duino.coin@gmail.com with your ip.
