### ISSUE TITLE
Coin from exchange does not appear on wallet

### ISSUE THREAD

**Issue by haxorcitoz** [duino-coin/duino-coin#1105]
I buy 40.000 duino coin from https://exchange.duinocoin.com/trx.html

Today i receive notification on my wallet saying that my coin is received but whe i check my balance on my wallet the 40.000 coin does not appear. My wallet only show the coin that i've been mined.

Can anyone please help me.

This is screenshot of my wallet

![Screenshot_20211116-182858_WhatsApp](https://user-images.githubusercontent.com/94447147/141978344-aeefafac-1c40-4c4d-b608-962d5f48d2f9.jpg)

**Comment by revoxhere** [comment]
Hello, we will contact you about this via mail and troubleshoot what went wrong

**Comment by haxorcitoz** [comment]
Thank you for the respons.
I will wait for further information.

**Comment by BastelPichi** [comment]
Closed as this dont really belongs here, feel free to reopen if needed.
