### ISSUE TITLE
Connect to wifi using wifimulti on ESP32/ESP8266

### ISSUE THREAD

**Issue by haxorcitoz** [duino-coin/duino-coin#1108]
As i saw in the ESP32/ESP8266 code still using WiFi.begin(wifi_ssid, wifi_password) to connect wifi.
Can you please change the code (WiFi.begin) using WiFiMulti so it's more easier to input known wifi ssid and password into the code so when we change the wifi ssid the ESP automatically connect.
for example now i'm using my wifi modem to connect the ESP to internet using ssid let's say WIFICONNECT1
it's all going well until my wifi modem broken and to connect ESP to internet i use my phone with ssid let's say WIFICONNECT2
because the ssid is changing, my ESP miner cannot connet to internet and i should change the code an reupload to the board
if the code using WiFiMulti, at the beginning we can input the ssid and password that we already know and then when the ssid changing the ESP will automatically connect to the ssid because it's already save into the code earlier

**Comment by BastelPichi** [comment]
Hey,
This will be very annoying for people using large amounts of ESPs(imagine typing in your wifi credentials 60 times) and also would be very annoying if you restart the esp. Implementing this would be quite easy, but i think it wouldnt make sence, as uploading a new code only takes 30seconds.

**Comment by haxorcitoz** [comment]
Im sorry but i dont understand why it's annoying and dont make sense since i use this WifiMulti for another project and working fine. Pardon me but if it quite easy can you show me how to modify the code because i'm struggling with it.

**Comment by BastelPichi** [comment]
Sorry, understood you wrong. The library is okay, but i think it would be easyer to just use an for-loop.

**Comment by haxorcitoz** [comment]
I never use for-loop before. Can you post the code or maybe it can be next update for the ESP code thay make easier in case of changing ssid

**Comment by revoxhere** [comment]
Hello, WiFi Multi library requires more downloads, which we try to prevent to make the basic code as accessible as possible. User can edit the code themselves to suit their needs.
