### ISSUE TITLE
Bugs in the web wallet

### ISSUE THREAD

**Issue by GoldLion2895** [duino-coin/duino-coin#1111]
**Bugs on the website**
There are two bugs, a spelling mistake and an invalid discord link @revoxhere.

**First bug:**
Instead of "Furims Services", "Furime Services" has been entered.

**Second bug:**
The invite link to join the discord server is a vanity link (discord.gg/duinocoin). The server has insufficient boosts to have this vanity so, discord removed it.

**To Reproduce**
1. Go to the [web wallet](https://wallet.duinocoin.com)
2. Click on the gear icon below your username
3. Scroll down to both bugs

**Screenshots**
First Bug:
![image](https://user-images.githubusercontent.com/45636569/142716385-88be6249-0335-406e-af32-90967c6bb450.png)

Second bug:
![image](https://user-images.githubusercontent.com/45636569/142716396-7545e9e7-de5f-45fb-9ee1-639ce98bec40.png)
![image](https://user-images.githubusercontent.com/45636569/142716411-f7ac82bb-81de-47d1-a1fe-f94060465818.png)
![image](https://user-images.githubusercontent.com/45636569/142716504-21c6ae4d-1882-4e9a-88d2-1aa3f0f877ec.png)

**Additional context**
My discord username is GoldLion, you can dm me for further information.

**Comment by revoxhere** [comment]
Hello, the Furime services name is not a bug, I was told by Furim himself that it's the correct form that should be used.
About the Discord link - thanks for noticing. We will correct it in a second. What's your DUCO username?

**Comment by GoldLion2895** [comment]
> Hello, the Furime services name is not a bug, I was told by Furim himself that it's the correct form that should be used. About the Discord link - thanks for noticing. We will correct it in a second. What's your DUCO username?

GoldLion2895
