### ISSUE TITLE
./PC_Miner: No such file or directory

### ISSUE THREAD

**Issue by thealidev** [duino-coin/duino-coin#1112]
-bash: ./PC_Miner: No such file or directory
Error in kali linux

**Comment by revoxhere** [comment]
Are you in the duino-coin directory?

**Comment by thealidev** [comment]
> Are you in the duino-coin directory?

No
I downloaded official linux release and then type
./PC_Miner
To start it with simple bash

**Comment by BastelPichi** [comment]
You need to cd into the directory you downloaded it first. If you downloaded it with git, simply run `cd duino-coin` before running the PCMiner. If you downloaded it manually, right click in the file explorer(in the folder you downloaded it), select Open in terminal or Open Terminal here and then type `./PC_Miner`. That should fix your issue.

**Comment by lghustle** [comment]
REMOVE!!!!

L.G.

**Comment by BastelPichi** [comment]
ahyes

**Comment by alixgamer175** [comment]
Done it
I just used old release
New release have sme bug

**Comment by thealidev** [comment]
Plzz
Solve it
I also tryed

> You need to cd into the directory you downloaded it first. If you downloaded it with git, simply run `cd duino-coin` before running the PCMiner. If you downloaded it manually, right click in the file explorer(in the folder you downloaded it), select Open in terminal or Open Terminal here and then type `./PC_Miner`. That should fix your issue.

Same issue
Thx
PC_Miner

**Comment by BastelPichi** [comment]
Its your error. Please run pwd in a terminal, send the output here, and tell how you downloaded duinocoin(git or browser), so we can help you. If you wa<nt faster replies, feel free to [join our discord](discord.gg/Jx6rfr92EE).

**Comment by thealidev** [comment]
Output after pwd
/home/ubuntu/duco
I downloaded it from browser this one
https://github.com/revoxhere/duino-coin/releases/download/2.7.4/Duino-Coin_2.7.4_linux.zip

**Comment by thealidev** [comment]
I am using Android terminal called
UserLand

**Comment by thealidev** [comment]
I just used commands in terminal
`wget https://github.com/revoxhere/duino-coin/releases/download/2.7.4/Duino-Coin_2.7.4_linux.zip`
`./PC_Miner`

**Comment by thealidev** [comment]
I used it from releases of duino coin

**Comment by thealidev** [comment]
I got it
After testing file with `file PC_Miner` it says that
```
PC_Miner: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=2658c04de63e2fdc0fce25e3d835af099253bb9c, for GNU/Linux 2.6.32, stripped
```
And My Cpu Has Arm Processer

**Comment by revoxhere** [comment]
You haven't read the getting started guide.
![image](https://user-images.githubusercontent.com/50244265/142757189-ccde4528-4015-4fef-8736-71e520cc7a4b.png)
https://github.com/revoxhere/duino-coin#installing-duino-coin

**Comment by BastelPichi** [comment]
> I got it After testing file with `file PC_Miner` it says that
> 
> ```
> PC_Miner: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=2658c04de63e2fdc0fce25e3d835af099253bb9c, for GNU/Linux 2.6.32, stripped
> ```
> 
> And My Cpu Has Arm Processer
Just launch from source or use our mining app. Thats much easyer. Or if you have a lniux pc compile it for 32bit.

**Comment by thealidev** [comment]
> You haven't read the getting started guide. ![image](https://user-images.githubusercontent.com/50244265/142757189-ccde4528-4015-4fef-8736-71e520cc7a4b.png) https://github.com/revoxhere/duino-coin#installing-duino-coin

Yess ofc
