### ISSUE TITLE
Ordering of Miners on wallet.duinocoin.com

### ISSUE THREAD

**Issue by vishnoor** [duino-coin/duino-coin#1116]
**Describe the bug**
The web wallet shows the order of the connected rigs by sorting them by name and not in the actual order of rig connection. As a result a Rig that has more processing power but with a name lower in the English Alphabet is shown to have a Kolka drop off percentage, while that may not be so in the actual pool. This is disorienting for users of the web wallet as they would wonder why a machine that was first to join the pool gets a Kolka penalty

**To Reproduce**
1. Attach a Rig named RIG-RAPI4-01 first. Wait for it to show up in wallet
2. Attach another Rig named RIG-RAPI3-01. Wait for it to show up in wallet

RIG-RAPI3-01 is shown as the first rig with 100 % Efficiency
RIG-RAPI4-01 is shown as second rig with 80% efficiency

**Expected behavior**
RIG-RAPI4-01 is shown as first rig with 100% efficiency
RIG-RAPI3-01 is shown as the second rig with 80 % Efficiency

**System (please complete the following information):**
 - OS: Any
 - Software Official PC Miner 2.74 -> wallet.duinocoin.com
 - Version 2.74

**Comment by revoxhere** [comment]
This is being worked on as we speak, yesterday I added the kolka ID to the rest api and will implement the correct percentages on the wallet soon. What's your DUCO username?

**Comment by lghustle** [comment]
Remove me from ALL LIST!!!!!
Unsubscribe button does NOTHING!!!

L.G.

**Comment by revoxhere** [comment]
@lghustle click this button when you're on Duino-Coin's GitHub. You must've clicked it while being in one of the threads
![image](https://user-images.githubusercontent.com/50244265/142758071-53835435-9d06-4d14-8917-532d3eed8ef6.png)

**Comment by lghustle** [comment]
ATTENTION ADMIN.

REMOVE ME FROM THESE THREADS!!!!!

THe unsubscribe button DOES NOT WORK!!!

I will reply all until removed!  

L.G.

**Comment by vishnoor** [comment]
> This is being worked on as we speak, yesterday I added the kolka ID to the rest api and will implement the correct percentages on the wallet soon. What's your DUCO username?

My DUCO user name is vishnoor
