### ISSUE TITLE
fatal error: eth_phy/phy.h: No such file or directory

### ISSUE THREAD

**Issue by sprokkie** [duino-coin/duino-coin#1117]
Hi,

Any thoughts how to solve this issue?
I try to use a esp32 but get this error all the time while compiling:
D:\Program Files (x86)\Arduino\hardware\espressif\esp32\libraries\WiFi\src\ETH.cpp:22:10: fatal error: eth_phy/phy.h: No such file or directory

**Comment by BastelPichi** [comment]
Seams like the instalation of the board wasnt successfully. Try re-installing the esp32 board.

**Comment by sprokkie** [comment]
how ?

i changed the setting in the preference tab.
i thought that is enough, where do i reinstall the board ?

**Comment by sprokkie** [comment]
@revoxhere  what more info do you need ?

**Comment by PetRatty** [comment]
Sprokkie I don't think you have even downloaded the ESP32 board yet from the comments, 
File->Preferences additional boards manager add : https://dl.espressif.com/dl/package_esp32_index.json

then Tools->Boards->Boards manager...
type esp32 and install
then Tools->Boards and ESP32 Arduino should be there

see how that goes and let me know

**Comment by sprokkie** [comment]
I removed the old version and old manager in preferences, put in the one and updated the boards now it works.
