### ISSUE TITLE
some workers do not disappear in wallet & kolka issue

### ISSUE THREAD

**Issue by Hagbard89** [duino-coin/duino-coin#1123]
i've shut down every worker but 2 of them are still visible (after over 1 hour) in the web wallet an still make valid shares...
![Screenshot (186)_LI](https://user-images.githubusercontent.com/37267036/142913848-93a8f920-c3d8-4dab-9609-c30833db49cb.jpg)

Additionaly i recognized that when i only power on one PI4 as pc miner, the kolka drop is instantly active at 4.4%
![Screenshot (188)_LI](https://user-images.githubusercontent.com/37267036/142913797-a372282c-0a36-4ee6-92ce-2df6292503d6.jpg)

**Comment by Hagbard89** [comment]
today the miners disappeared, but the kolka bug is still present

**Comment by BastelPichi** [comment]
hmmmmmm. The miners not dissapearening should be related to the api. For bove questions, @revoxhere should be able to help you.

**Comment by jklingel1990** [comment]
I’m having the same issue with my pc it is at 32% when it loads. Also the one time I started it they also showed my pi zero running when it was not.

**Comment by jklingel1990** [comment]
Even my aurdino is at 80% and I only have one.

**Comment by Hagbard89** [comment]
is it possible that i got kolka banned? and if so, why?

**Comment by BastelPichi** [comment]
> is it possible that i got kolka banned? and if so, why?

if you got kolka banned, you will see your balance drop. If it stays, you shouldnt. Revox sent this message on the discord yesterday, maybe it will help you.
![grafik](https://user-images.githubusercontent.com/63782569/143480705-533f42a4-44a9-479d-8ac3-4249d6299c4c.png)

**Comment by Hagbard89** [comment]
Today everything is working fine, no kolka drops, ghost miners or anything strange. i think that was a issue after the last kolka update.
