### ISSUE TITLE
Balance Incorrect

### ISSUE THREAD

**Issue by Bandarowski** [duino-coin/duino-coin#1125]
My Account Was verified and Had aprx 2800 Duco. Today my account is Unverified and my balance is 380 Duco.

Please Fix My Account Issue

**Comment by BastelPichi** [comment]
Hey,
Check your email if you got any banned email or so. If you havent broken our tos, write an email to duino.coin@gmail.com. They should be able to help you.

**Comment by Bandarowski** [comment]
> Hey, Check your email if you got any banned email or so. If you havent broken our tos, write an email to [duino.coin@gmail.com](mailto:duino.coin@gmail.com). They should be able to help you.

Last Email From DuinoCoin was long time ago
Your mining rig is now verified ✔️

**Comment by 709mining** [comment]
Same here just yesterday I was verified and today my account is lost, so I try to re-sign in but my account not verified and all of my balance is gone
![Screenshot_20211201-141256_Samsung Internet](https://user-images.githubusercontent.com/95337642/144188631-af3c59f6-3174-4335-bec5-75a349212d22.jpg)


![Screenshot_20211201-141134_Chrome](https://user-images.githubusercontent.com/95337642/144188612-3ce98ada-57cf-4143-9d34-3700218e2be6.jpg)

**Comment by BastelPichi** [comment]
Hey,
send an email to duino.coin@gmail.com. They should be able to help you.
