### ISSUE TITLE
Connection over TOR network

### ISSUE THREAD

**Issue by pcassimans** [duino-coin/duino-coin#1126]
Is it possible to connect the miners over the TOR network by using the sock5 proxy server?

Couldn't find the answer in the Wiki.

**Comment by BastelPichi** [comment]
Using any type of proxy/vpn is against the tos. Tor also counts to that. You will defently get banned if you use tor.

**Comment by pcassimans** [comment]
Sorry but in the whole ToS there is nothing around proxy or vpn. Was just asking. Thx for the information.

**Comment by BastelPichi** [comment]
Sorry, my bad. It has been removed from the tos, so it should be okay :)

**Comment by BastelPichi** [comment]
Of course if youre trying to get better earnings wiot that, that will get you banned.

**Comment by pcassimans** [comment]
It's about privacy, not profitability. Don't worry :-)
