### ISSUE TITLE
Termux Miner

### ISSUE THREAD

**Issue by thinkCreat3** [duino-coin/duino-coin#1127]
Will you add a way to mine Duino-coin on termux?

**Comment by BastelPichi** [comment]
Hey,
You can just use [our android miner](https://github.com/DoctorEenot/DUCOAndroidMiner/releases/latest). You can also mibne in Termux, to do that, just do `https://raw.githubusercontent.com/revoxhere/duino-coin/master/PC_Miner.py` and then `python3 PC_Miner.py` (if you get an error that python isnt foubnd, do `pkg install python` before).

**Comment by BastelPichi** [comment]
Closing for now, if you still have any questions feel free to reopen.
