### ISSUE TITLE
Duino coins got deleted for no reason! (account verified already)

### ISSUE THREAD

**Issue by wenshenwang0416** [duino-coin/duino-coin#1132]
my account was verified back in Sept., few days ago was with +3000 coins.
Today I checked it's all gone, and shows my account is unverified!!??  why?????
I can get into my account now but coins are still gone and it still says unverified.
Please help.
![12](https://user-images.githubusercontent.com/89238111/144010899-386324a8-b9a4-43c5-9e2e-53afbea283c3.png)
![2021-11-30 16_11_20-Duino-Coin _ Error](https://user-images.githubusercontent.com/89238111/144010904-858df617-3278-4182-b267-4f6dfe7cd4d8.png)
![2021-11-30 16_13_01-Duino-Coin _ Web Wallet](https://user-images.githubusercontent.com/89238111/144010907-0c02c68f-c563-439c-9382-e2b63ef2492f.png)

**Comment by BastelPichi** [comment]
Hey,
As you may already done, write an email to duino.coin@gmail.com. They should be able to help you.

**Comment by BastelPichi** [comment]
Oh in the API you can see that you have 4000DUCO, is this already resolved?

**Comment by wenshenwang0416** [comment]
Yes it's all back now. Thanks.

**Comment by wenshenwang0416** [comment]
case closed. thanks for the help.
