### ISSUE TITLE
invalid sytax PC_Miner.py

### ISSUE THREAD

**Issue by qiodaimi** [duino-coin/duino-coin#1133]
Hallo 

I can't run PC_Miner.py on raspberry pi 3? 
Please help

File "PC_Miner.py", line 182
    pretty_print(f"Warning: {response['message']}"
                                                                            ^
SyntaxError: invalid syntax

**Comment by revoxhere** [comment]
Your python is outdated

**Comment by BastelPichi** [comment]
Hello,
As revox already said, your Python is old. Here some steps to fix it:
- Use `python3` instead of `python`
- If that dont works, try to do `sudo apt update` and then `sudo apt install python3.9`
If you encounter any more errors, feel free to write here or join or discord for faster replies.

**Comment by qiodaimi** [comment]
pi@raspberrypi:~/duino-coin $ sudo apt install python3.9
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'postgresql-plpython3-9.5' for regex 'python3.9'
Note, selecting 'postgresql-plpython3-9.6' for regex 'python3.9'
postgresql-plpython3-9.5 is already the newest version (9.5.4-3).
postgresql-plpython3-9.6 is already the newest version (9.6.24-0+deb9u1).
The following packages were automatically installed and are no longer required:
  coinor-libipopt1v5 libmicrodns0 libmumps-seq-4.10.0 libraw15 realpath
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~/duino-coin $ python3 PC_Miner.py
  File "PC_Miner.py", line 182
    pretty_print(f"Warning: {response['message']}"
                                                 ^
SyntaxError: invalid syntax

is there any other way?

still showing syntax error

**Comment by revoxhere** [comment]
You install python3.9 but launch with python3, that does not use the newest version
