### ISSUE TITLE
Kolka % drop can be incorrect

### ISSUE THREAD

**Issue by haxorcitoz** [duino-coin/duino-coin#1134]
I've been experience the issue for several day. As the developer says the kolka drop is starting from the 4th miner but not in my case. I have 12 esp32 miner and the kolka efficiency drop is started from the 1st miner like in the picture attached. What exactly happened here? Why the kolka drop is not like it should? Di i do anything wrong or something else?

![Screenshot_20211130-221815_Chrome](https://user-images.githubusercontent.com/94447147/144065385-e0b2ef0e-bfc5-49ff-a2a1-05861e2aaef2.jpg)

![Screenshot_20211130-221822_Chrome](https://user-images.githubusercontent.com/94447147/144065438-b6323316-68af-4e60-9bd8-58effc4c4ebd.jpg)

![Screenshot_20211130-221836_Chrome](https://user-images.githubusercontent.com/94447147/144065493-987cac73-2e69-4251-9641-cc6f8edd955b.jpg)

![Screenshot_20211130-221847_Chrome](https://user-images.githubusercontent.com/94447147/144065553-fb99292b-0d09-4d95-b9a4-e13e7a7b7d55.jpg)

![Screenshot_20211130-221857_Chrome](https://user-images.githubusercontent.com/94447147/144065633-fce71aa2-f8ac-4669-8fdf-6ba0ef7ca398.jpg)

![Screenshot_20211130-221913_Chrome](https://user-images.githubusercontent.com/94447147/144065673-1f0c4400-5faf-4382-9214-e581993a3a1f.jpg)

**Comment by BastelPichi** [comment]
Hey,
Currently there still some issues. You may want try to stop all of them, wait for them to dissapear and then start them up one by one.

**Comment by haxorcitoz** [comment]
I already try the method as you suggest. I turn off all of my miner and wait for more than 30 minutes. After that i turn on one of them and wait for approximately 10 minutes and check on the duino wallet. Even with only one miner the kolka still dropping. This is the screenshot of my wallet

![Screenshot_20211201-062051_Chrome](https://user-images.githubusercontent.com/94447147/144138062-c5ff2a6d-5abf-4ad4-a5c4-287bc0445d18.jpg)

**Comment by haxorcitoz** [comment]
I repeat the step above and start my RPI4 but still its drop significantly
![Screenshot_20211201-065025_Chrome](https://user-images.githubusercontent.com/94447147/144143273-386d2da4-cc1e-4526-b546-bed7cb38d3e4.jpg)

**Comment by haxorcitoz** [comment]
Today i try to mine only using my rpi4 and this is what happen. The efficiency only 1.15%. It's really strange

![image](https://user-images.githubusercontent.com/94447147/145676427-cb68bff4-3a27-4b76-809e-c17c0fb67825.png)

**Comment by revoxhere** [comment]
Possibly fixed in 3.0
