### ISSUE TITLE
Esp Compilation

### ISSUE THREAD

**Issue by maresob** [duino-coin/duino-coin#1136]
Hi,
Esp8266 
Newest arduino IDE

Compile issue

"'DynamicJsonDocument' was not declared in this scope"

**Comment by BastelPichi** [comment]
Hey,
Can you give some more Information? Are you shure youre using the latest Arduino IDE and Source code?

**Comment by maresob** [comment]
Arduino IDE 1.8.16

Yes im using source code...

More about issue:
espmin:59:3: error: 'DynamicJsonDocument' was not declared in this scope
   59 |   DynamicJsonDocument doc(256);
      |   ^~~~~~~~~~~~~~~~~~~
espmin:60:19: error: 'doc' was not declared in this scope
   60 |   deserializeJson(doc, input);
      |                   ^~~
espmin:60:3: error: 'deserializeJson' was not declared in this scope
   60 |   deserializeJson(doc, input);
      |   ^~~~~~~~~~~~~~~

**Comment by revoxhere** [comment]
Please update your ArduinoJSON library. After that, the code should compile fine.
