### ISSUE TITLE
Wallet not update coin balance value

### ISSUE THREAD

**Issue by haxorcitoz** [duino-coin/duino-coin#1138]
This is screen shot of my wallet that does not update the balance value of duino coin for hours even i constantly mining

At 11.23 am
![Screenshot_20211201-112337_Chrome](https://user-images.githubusercontent.com/94447147/144188731-313045d9-2df9-4d93-9e2b-91619097aa00.jpg)

At 01.43 pm
![Screenshot_20211201-134303_Chrome](https://user-images.githubusercontent.com/94447147/144188811-ff03cfbd-536d-447b-a2a6-b82de223b59a.jpg)

**Comment by BastelPichi** [comment]
Have you tried reloading the Wallet page? This should be related to your site, for me it works fine, and in the api the balance is higher. If you encounter similar problems on PC, please send a screenshot of the console(F12 in most browsers, then click on console).

**Comment by haxorcitoz** [comment]
I reload the page several time but nothing changed then i logout. I leave it until night then login again and the balance update by itself. I dont understand why its happened. My connection is normal, i'm not using proxy or vpn, firewall is on standard settings (no additional settings because i dont really understand about it). I hope its just a bug and already mitigate.
Thank you.
