### ISSUE TITLE
No miners even my devices are online

### ISSUE THREAD

**Issue by FehnrirX** [duino-coin/duino-coin#1140]
i just done cleaning my miners when i turn on, wallet said no miners at all. been waiting for couple minutes, still nothing. decide to read serial, this is happening

```
Connecting to Duino-Coin server...
Loop WDT Failed!
Resetting ESP...
⸮⸮
Connecting to Duino-Coin server...
Connected to the server. Server version: 
Asking for a new job for user: fehnrirX
Job received:   1

Connecting to Duino-Coin server...
Connected to the server. Server version: 
Asking for a new job for user: fehnrirX
Job received:   1
````

am i not allowed or what? or my devices outdated? i use the recent firmware, 2.7.4 for my miners (EPS32 and ESP8266)

**Comment by dodysat** [comment]
as far as I know, SVKO Pool is still down right now
![Screenshot_9](https://user-images.githubusercontent.com/29549201/144361379-d195af1a-649f-4923-b1f8-d67fba4714c1.png)


https://status.duinocoin.com/

**Comment by BastelPichi** [comment]
Do you still have these Problems?

**Comment by revoxhere** [comment]
Solved a few days ago
