### ISSUE TITLE
No wallet connection

### ISSUE THREAD

**Issue by fryswiththat** [duino-coin/duino-coin#1145]
When I try to log in to my wallet I get a malware warning, after allowing the site I get this message: "{"result":["Logged in","*******@******"],"success":true}" Nothing else appears on the page.

**Comment by revoxhere** [comment]
Are you talking about the web wallet? What browser are you using? Do you have any extensions that may interfere with the site?

**Comment by fryswiththat** [comment]
Thank you for responding,

Yes, Web Wallet on Windows 10 PC using Edge Browser. I am using PC Miner and it seems to be functioning, however, when I try to login to Web Wallet I get a white screen with the statement “{"result":["Logged ***@***.***"],"success":true}and nothing else.

I took screenshots of the four pages I get and I’ve attached.

The last one shows a balance in the text, but, I had to go to the server to get that after trying to log on. I’m very new to this, so, I’m not sure about your Extensions question. I have Malwarebytes which I have allowed to proceed from the warning and Windows Defender also.



I would appreciate any help you can give.


Sent from Mail for Windows

________________________________

**Comment by BastelPichi** [comment]
Try to use Chrome or Firefox. I havent heard of anybody having similar issues, maybe you can look in the console if there are any errors(right click-> inspect eolemnt->change to console tab)?

**Comment by fryswiththat** [comment]
Thank you for your response. After thinking about the comment revoxhere mentioned yesterday, I looked into my extensions on Edge and found that Malwarebytes had an extension. After deleting the extension I was able to login in to my wallet on Edge browser. Problem solved!
Also thanks to BastelPichi for the imput.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
