### ISSUE TITLE
Raspberry Pi Pico does not work with the newest Arduino IDE

### ISSUE THREAD

**Issue by kosa6661987** [duino-coin/duino-coin#1146]
**Describe the bug**
Issue with Picopi board mining, after upload code to bard, miner on Raspberry Pi detecting boards on USB, sending job to board but didn't get any respond.

**To Reproduce**
1. No response from Picopi board.

**System (please complete the following information):**
 - OS: Raspberry 
 - Software Avr miner on PC also Rasberry Os
 - Version Lastest

**Comment by JK-Rolling** [comment]
try this https://github.com/revoxhere/duino-coin/issues/996#issuecomment-946277028

**Comment by kosa6661987** [comment]
Upload to board is not issue, just connection with avr miner

**Comment by BastelPichi** [comment]
> Upload to board is not issue, just connection with avr miner

Can you maybe upload an screenshot of teh error?
