### ISSUE TITLE
I can't login my web wallet

### ISSUE THREAD

**Issue by xbb-mcl** [duino-coin/duino-coin#1147]
I can't login my web wallet.I key in the right pwd but it showed I key in the wrong pwd.

**Comment by xbb-mcl** [comment]
When I was creating a new wallet,it showed"You're using a proxy. Please try again"

**Comment by revoxhere** [comment]
Make sure you're not using any VPN services and proxies. If that does not work, try a different network, e.g. mobile data.

**Comment by xbb-mcl** [comment]
Sorry,it didn't work.

**Comment by LDarki** [comment]
Hi, are you still having this problem?
I`ll close this issue
