### ISSUE TITLE
AVR_Miner Wont connect - server Actively Refused Connection

### ISSUE THREAD

**Issue by thetaz001** [duino-coin/duino-coin#1150]
So i have been playing around with Mining DUCO for a couple days now..
am running it on a RPi3 as well as 7 Arduino Unos
ive had the Uno's up for a day, and all the sudden today, im getting error connecting to server
No connection could be made because the target machine actively refused it..
i dont understand why i am blocked or unable to connect can someone please advise..

thanks
Fred

**Comment by ghost** [comment]
now its online again, server down, you can check at https://status.duinocoin.com/ cheers..
its interesting, my esp32 not affected by this server down..
for information i leave avr miner and its start again automatically, so if you see this problem again just leave and forget it hehe ii will comeback normal later..

**Comment by nekomaruh** [comment]
I also have this problem with version 2.75
Error connecting to the server. Retrying in 10s (connection err: [Errno 111] connection Refused)

Version 2.74 is working well, but i have problems with my arduinos, all of a sudden they stop working and i have to restart the program continuously.

**Comment by BastelPichi** [comment]
Hey,
This issue was related to one of the pools going down without signing out of the server properly. The Problem should now be fixed. If you still encounter problems, try to go to https://server.duinocoin.com/getPool. If you dont see any errors there, try to restart your miners.

**Comment by thetaz001** [comment]
> now its online again, server down, you can check at https://status.duinocoin.com/ cheers.. its interesting, my esp32 not affected by this server down.. for information i leave avr miner and its start again automatically, so if you see this problem again just leave and forget it hehe ii will comeback normal later..

THanks for the update, you guys are all correct, it is back now..
funny thing my RPi also did NOT stop mining,, only my Arduino..
thanks for the quick reply all!!
thanks
