### ISSUE TITLE
Attiny85 support?

### ISSUE THREAD

**Issue by ghost** [duino-coin/duino-coin#1151]
Hi, I really enjoy mining projects using this microcontroller, currently I'm using the ATmega32U4 because it doesn't require serial to usb (i love efficiency) and it runs perfectly, when I try to use Attiny85 I can't compile the existing code, is it because it's not compatible? I'm still not too deep in understanding the microcontroller completely. For information, I use the driver and board manager from digistump http://digistump.com/wiki/digispark/tutorials/connecting. On the i2c master slave project https://github.com/ricaun/DuinoCoinI2C there is some information can use Attiny85 as slave but I have no desire to use master-slave i2c duino coin mining. So far I've tried mining on pc, raspberry pi, and esp32 and it works perfectly, thanks to all the developers.

**Comment by revoxhere** [comment]
Attiny 85 doesn't have native serial. Trying to add it by software makes the board not have enough memory for the rest of the code. The only way you can use attinys is by using the i²c setup

**Comment by ghost** [comment]
Wow thanks for the explanation hopefully this information can be useful for others..
