### ISSUE TITLE
Make Duino-Coin I²C an officially supported project

### ISSUE THREAD

**Issue by revoxhere** [duino-coin/duino-coin#1157]
**Describe the solution you'd like**
It may be a good idea to get in touch with @ricaun in the future to make his project officially supported by Duino-Coin and possibly add him to the organization.

**Comment by 45aaa23** [comment]
You can do instructions on how to manually update the version for the time being. and then I just found out about this project, but I can’t try

**Comment by Talentfrei87** [comment]
Hello, I have the following suggestion for the I2C project. You could flash the I2C bootloader from https://github.com/mihaigalos/miniboot on the AVR so that it automatically gets the latest avr miner software via OTA github -> esp -> avr.
