### ISSUE TITLE
Reduce the kolka drop for AVR and ESP mining to 1-2%

### ISSUE THREAD

**Issue by revoxhere** [duino-coin/duino-coin#1159]
**Describe the solution you'd like**
As a lot of avid miners suggested, the kolka drop for the devices this coin is aimed for could be made even lower.

**Comment by admin-kepo** [comment]
strengthen the block hash security, do you think that by strengthening the block defense to go to the main block it is better, if one sha-1 block is easy to complete, why not make 10 or 20 sha-1 blocks in the sequence? while kolka, reduce only half a percent.
