### ISSUE TITLE
Earnings way down

### ISSUE THREAD

**Issue by RLTW96** [duino-coin/duino-coin#1162]
I have noticed that the duco earnings are way down.

I used to see up to 400 duco per day now I am lucky to get 100 per day with most of the day running around 30-60.  

Is there something wrong?

**Comment by SmartDude1568** [comment]
What are you using to mine? (Arduino, PC, etc)

**Comment by Hive89** [comment]
I have the same problem using Arduino I2C miners and raspberry pi as master. about 2 weeks ago I mined 200-300 duct/day now its about 20 per day with the same number of Arduino
