### ISSUE TITLE
PC-Miner Error with Raspberry PI 4B

### ISSUE THREAD

**Issue by desktopminertg** [duino-coin/duino-coin#1165]
**Describe the bug**

pi@TGPI4GB:~/duino-coin $ python3 PC_Miner.py
Traceback (most recent call last):
  File "/home/pi/duino-coin/PC_Miner.py", line 845, in <module>
    Miner.greeting()
  File "/home/pi/duino-coin/PC_Miner.py", line 407, in greeting
    print("\n" + Style.DIM + Fore.YELLOW + Settings.BLOCK + Fore.YELLOW
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2016' in position 11: ordinal not in range(256)

**To Reproduce**
1. Manual installation like description
2. Started like description

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: 2021-10-30-raspios-bullseye-arm64 
 - Software PC Miner
 - Version 2.75

**Additional context**
Reproduce at 2. Raspberry Pie 4B 
The same Issue with 2.7.4 (duino-coin 2.7.4.tar.gz (Source Code)

**Comment by BastelPichi** [comment]
do sudo raspi-config, go to localisation options and change your codec to utf8. Then it should work.
