### ISSUE TITLE
How to close the account

### ISSUE THREAD

**Issue by wenshenwang0416** [duino-coin/duino-coin#1166]
I created a second account to separated ESP devices, which made me cannot wrap the coins due to Alt-account problem. I want to close the second account. How to close it? I sent emails few times but no one reply. Please help.

**Comment by BastelPichi** [comment]
Hmmm. Where have you sent your messages too?

**Comment by wenshenwang0416** [comment]
duino.coin@gmail.com
Sent several emails but no reply.
How can I get help now?  any other email I can contact?
thanks.

**Comment by yura50525** [comment]
Hello i have the same problem and i don't know how to fix that If you know how to fix it, please write the comment cause many people have the same problem

**Comment by yura50525** [comment]
I found the solution: you can use your mobile internet an there will no be that message

**Comment by BastelPichi** [comment]
Hey,
If noone has replied to you, revox dont wants to fix the problem. You cant do anything...

**Comment by tanaka6kenji** [comment]
I have the same issue I have even emailed them asking them to delete the account I am not using.
Then I found that they will not reply to any messages regarding multiple accounts.
I would suggest contacting a lawyer to see what can be done.
I know by law a financial institution dealing with fita or currency must have a way for you to close any account.
