### ISSUE TITLE
Error fetching mining node:local variable 'bg_color' referenced before assignment

### ISSUE THREAD

**Issue by RLTW96** [duino-coin/duino-coin#1167]
Receiving an error when starting up miner:

Error fetching mining node: local variable 'bg_color' referenced before assignment, retrying in 15s

I have reset the boards, re-flashed duino coin code, deleted my settings.cfg file and then did the fresh setup process.  No luck.

**Comment by revoxhere** [comment]
Hello, what's the version you're using?

**Comment by RLTW96** [comment]
version 2.7.4

**Comment by revoxhere** [comment]
What are you running the miner on? Can you try launching from source?

**Comment by RLTW96** [comment]
Running on an iMac using USB hubs to connect the uno boards.  Was working for weeks and just stopped.

**Comment by RLTW96** [comment]
Working now.  Not sure why or what happened.

**Comment by hermanmettler** [comment]
i have the same problem, any solution?

**Comment by edenzul** [comment]
I think the pool server (server.duinocoin.com) unable to response this time.

# curl https://server.duinocoin.com/getPool
{"message":"reduce() of empty sequence with no initial
value","success":false}

**Comment by RLTW96** [comment]
Not sure why, but it resolved itself. I sent a note several weeks back explaining the same.

I did turn off my VPN and it started to work but this is only conjecture.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by francescoproprioio** [comment]
Il gio 20 gen 2022, 16:21 RLTW96 ***@***.***> ha scritto:
