### ISSUE TITLE
Bruteforce and Username enumeration in login page at https://wallet.duinocoin.com

### ISSUE THREAD

**Issue by shriyanss** [duino-coin/duino-coin#1168]
# Bug Report (as described [here](https://server.duinocoin.com/news.html))

# Summary
The login page is vulnerable to bruteforce and user enumeration

# Steps to reproduce
- Go to the [login page](https://wallet.duinocoin.com) (make sure you are running burp suite proxy in background)
- Now enter a wrong username.
- You would get the following error
```
HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Sat, 11 Dec 2021 04:12:29 GMT
Content-Type: application/json
Content-Length: 54
Connection: close
Access-Control-Allow-Origin: *

{"message":"This user doesn't exist","success":false}

```
- This error means that user doesn't exist
- If the error is 
```
HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Sat, 11 Dec 2021 04:15:13 GMT
Content-Type: application/json
Content-Length: 47
Connection: close
Access-Control-Allow-Origin: *

{"message":"Invalid password","success":false}

``` 
- Means the user exists
- Now use the password param to bruteforce the password (make sure to encode it (base-64 then url))

# References
Username enumeration: https://www.rapid7.com/blog/post/2017/06/15/about-user-enumeration/
Password bruteforce: https://en.wikipedia.org/wiki/Brute-force_attack

### My Duco username: shriyanss

**Comment by revoxhere** [comment]
Could you explain it in more detail? Why is that an issue or what's the proposed solution?

**Comment by shriyanss** [comment]
Hi there,
Bruteforce is a type of an attack, where an attacker send multiple of requests to the server for authentication. It is just like you have a login page opened in browser with the victim's username in username field and you constantly entering a password in password field and checking if password is right or not. (Note that it's CLI based)

A video tutorial: https://youtu.be/fHsJAei2ocM
You could skip the "how to perform bruteforce attack" and simply see the cause and solution

# Impact
An attacker can gain unauthorised access to account with wrong password.

# Solution
On the login page, you can simply add a rate limit, means user (malicious one, or attacker, or say as hacker) would be blocked from attempting a log in if he sends 20 request with wrong credentials within a particular time duration, which could be 1 hour or even a day

**Comment by shriyanss** [comment]
It would be better if you would provide an email for security issues (vulnerabilities) or use something that would remain private between reporter and dev team

**Comment by revoxhere** [comment]
If I understand correctly, the bruteforce attempts will likely result in failed attempts, at least for first presumably thousands of requests. Currently each error request increases your ban count by one, and if it reaches a threshold your IP gets temporarily blocked (403). I hope that answers your question

**Comment by shriyanss** [comment]
Yes

**Comment by revoxhere** [comment]
> It would be better if you would provide an email for security issues (vulnerabilities) or use something that would remain private between reporter and dev team

If you have to contact us directly, use the contact form on our page or e-mail us directly at duino.coin@gmail.com, but I think it's much better to have everything clear to public. Closing this issue for now as I think it's been discussed enough, feel free to reopen if needed. Cheers

**Comment by shriyanss** [comment]
> If I understand correctly, the bruteforce attempts will likely result in failed attempts, at least for first presumably thousands of requests. Currently each error request increases your ban count by one, and if it reaches a threshold your IP gets temporarily blocked (403). I hope that answers your question

That's the right solution but you should limit it something low like 20 for login to a particular account or simply add a captcha there.

Reference: https://hackerone.com/reports/1320976
