### ISSUE TITLE
Client side DoS via JS injection

### ISSUE THREAD

**Issue by shriyanss** [duino-coin/duino-coin#1169]
Vulnerability Type: DoS

# ​Steps to reproduce
- Open the app and make a transaction for some duco (I made for 0.001, https://explorer.duinocoin.com/?search=da470b1e7146e2acf6e1959ae31e8bf91eb0c076)
- In the memo section, make sure to add a javascript, the one I added was <script>alert(1)</script>
- Now complete the transaction
- To check the DoS, go to Duco Android App > Transaction and you would see the app closing

# Impact
This could prevent the user from seeing his transaction in DuinoCoin android app

**Comment by BastelPichi** [comment]
Hey,
This is related to the App. The other wallet cut out any part that could be used for such attacks.

**Comment by BastelPichi** [comment]
Sorry, its already done when sending the duco. So this is not really something to consider. Why the app crashes, no idea. Try to go to the proper github repository, and report the bug tehre.
