### ISSUE TITLE
Raspberry Pi Pico disconnects after while of mining

### ISSUE THREAD

**Issue by stehled** [duino-coin/duino-coin#1170]
**Describe the bug**
When I start the AVR miner, AVR threads start and all boards start mining. But after a while, the com port is closed or the Pico gets ton of rejected shares. The AVR miner tries to start the thread again, but it does't do anything.

Error connecting to the AVR! Retrying in 10s (no response from the board: float division by zero, please check the connection, port setting or reset the AVR)

**To Reproduce**
Start AVR miner with Pi Picos
Wait

**Expected behavior**
The com port shouldn't be closed or the thread should be sccessfully started. 

**System (please complete the following information):**
 - OS: Raspbian
- Software AVR Miner
 - Version 2.7.4

**Additional context**
No problem with arduino UNO, only Pi Picos

**Comment by BastelPichi** [comment]
Hey,
The pico is not officially supported. Try to join the discord, someone sjhould be able to help you there.

**Comment by wraith4081** [comment]
Like the Pico rp2040, it's over-engineered board. that it can sometimes shut itself down to avoid self-harm and terminate an existing process. If you're digging with overclocking, try lowering the speed a bit.
