### ISSUE TITLE
QUESTION: python pool executors

### ISSUE THREAD

**Issue by achapkowski** [duino-coin/duino-coin#1172]
I have a general question about the PC Miner.  

1. Is there a way to disable the chatter using print?  It slows down the execution of the code quite a bit over time.
2. The miner uses vanilla threading, but I was wondering if you tested using the ProcessPoolExecutor or the Thread pool?  It might be easier to manage.  
3. Would you get penalized for having multiple python processes performing the mining task vs a single one with multiple threads?

I think the project is awesome and just trying to understand more.

**Comment by BastelPichi** [comment]
Hey,
For the 1st question, you can just comment out the two rejected/accepted lines. For the rest, maybe @revoxhere can help, im not into that stuff.
