### ISSUE TITLE
Raspberry  Pie Picos on Raspberry PI as Host / AVR Miner Error Message

### ISSUE THREAD

**Issue by desktopminertg** [duino-coin/duino-coin#1173]
**Describe the bug**

When i use AVR with the same Picos on Windows it works perfeclty

root@TGPI4GB:/home/pi# cd duino-coin
python3 AVR_Miner.py

21:42:52  net0  Suche nach der schnellsten Verbindung zu dem Server
21:42:55  sys4  AVR mining thread startet  mit DUCO-S1A Algorithmus (/dev/ttyACM4)21:42:55  sys2  AVR mining thread startet  mit DUCO-S1A Algorithmus (/dev/ttyACM2)21:42:55  sys1  AVR mining thread startet  mit DUCO-S1A Algorithmus (/dev/ttyACM1)21:42:55  sys5  AVR mining thread startet  mit DUCO-S1A Algorithmus (/dev/ttyACM5)21:42:55  net0  Verbunden mit dem Haupt-Server (v2.7)21:42:55  sys3  AVR mining thread startet  mit DUCO-S1A Algorithmus (/dev/ttyACM3)

21:42:55  net0  MOTD: You are mining on Bilapool, have fun!
21:42:55  sys0  AVR mining thread startet  mit DUCO-S1A Algorithmus (/dev/ttyACM0)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/duino-coin/AVR_Miner.py", line 875, in mine_avr
    share_print(port_num(com), "reject",
  File "/home/pi/duino-coin/AVR_Miner.py", line 656, in share_print
    print(Fore.WHITE + datetime.now().strftime(Style.DIM + "%H:%M:%S ")
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u26cf' in position 54: ordinal not in range(256)

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: 2021-10-30-raspios-bullseye-arm64
-  AVR Miner 
- Version 2.75
 
![Pico_PI](https://user-images.githubusercontent.com/95868907/146655539-0655b090-3817-4b79-91cf-88473821d59a.JPG)

**Comment by desktopminertg** [comment]
![Pico_W10](https://user-images.githubusercontent.com/95868907/146655862-143f1120-1d34-49fb-8a11-7a4ef097caf2.JPG)

**Comment by BastelPichi** [comment]
You need to change your codec to utf8 or similar.(WIESO HAST DU DEINEN CODEC AUF LATIN1?!)

**Comment by desktopminertg** [comment]
Dank für den tip, aber ich hab das umgestellt gehabt mit rasp config, hab gerade nachgeschaut, war wieder verstellt....

**Comment by desktopminertg** [comment]
hatte es mit sudo raspi-config gemacht gehabt, nun über die Oberfläche direkt und neustart, nun gehts, muss das mal regelmässig kontrollieren

**Comment by BastelPichi** [comment]
Eigentlich sollte sich das nicht selbst verstellen, und wird auch im nächsten release gefixt sein.
