### ISSUE TITLE
Last 3 transactions on Bsc.Ducocoin have failed using The wrap Technique (Sushi Swap).

### ISSUE THREAD

**Issue by rmtucker** [duino-coin/duino-coin#1177]
As stated above all transactions using the sushi swap method seem to be failing.
In fact according to https://polygonscan.com/token/0xaf965beb8c830ae5dc8280d1c7215b8f0acc0cea there have been no successful transactions in nearly 2 days?
I was not sure where to ask about this?
When you press the wrap button it fails to finish the transaction?

**Comment by BastelPichi** [comment]
Hey,
Please use the official Webwallet. The one on bsc.duinocoin.com is known to be broken. Usually the coins are sent anyways, you can check on the duinocoin [explorer](https://explorer.duinocoin.com) by entering your username. For the rest of the questions, @ygboucherk may help you, but hes not online very often.

**Comment by ygboucherk** [comment]
Oh gas tank was empty ! Refilling it :D

**Comment by ygboucherk** [comment]
Pending transactions shall get processed
