### ISSUE TITLE
ESP32 and ESP8266 not fetching pool

### ISSUE THREAD

**Issue by kowi87** [duino-coin/duino-coin#1180]
Hello fellow Duco Team,
Me and my miss are running some ESP32 and ESP8266, but over a week or so, few of them stopped mining. Due to lack of time I had no time to investigate it. Before Christmas I've noticed that none of ours ESPs are mining. Today I plugged one of them to serial monitor and noticed it is not fetching pool.

Bellow is my serial monitor output:
> Fetching pool... 
[HTTP] GET... failed, error: connection refused
Fetching pool... 
[HTTP] GET... failed, error: connection refused
Fetching pool... 
[HTTP] GET... failed, error: connection refused
Fetching pool... 
E (75696) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (75696) task_wdt:  - WiFirec (CPU 0)
E (75696) task_wdt: Tasks currently running:
E (75696) task_wdt: CPU 0: IDLE0
E (75696) task_wdt: CPU 1: loopTask
E (75696) task_wdt: Aborting.
abort() was called at PC 0x4013ced8 on core 0

When I access https://server.duinocoin.com/getPool from any other device's browser I got an output like this:

> {"ip":"176.32.35.94","name":"blyat-pool-1","port":6000,"success":true}

**Comment by kowi87** [comment]
Software update from v.2.7 to the newest one fixed that issue.

**Comment by Josstri** [comment]
Is there a patch for 2.7.3? I'm using the I2C code from Ricaun and it's coming across a similar issue
