### ISSUE TITLE
Error fetching mining node, Connection to server.duinocoin.com timed out

### ISSUE THREAD

**Issue by Juse32** [duino-coin/duino-coin#1182]
**Describe the bug**
Unable to startup miner, was working for days prior. 

Getting the following:
Error fetching mining node: HTTPSConnectionPool(host='server.duinocoin.com', port=443): Max retries exceeded with url: /getPool (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x75c81f10>, 'Connection to server.duinocoin.com timed out. (connect timeout=5)')), retrying in 15s

**To Reproduce**
1. Run, $ pythyon3 PC_Miner.py from the duino-coin dir

**Expected behavior**
Miner to connect to a mining node and start mining

**Screenshots**
![image](https://user-images.githubusercontent.com/38010527/147499715-e4f0759b-b53e-4a6e-a11c-6bd2ba666374.png)

**System (please complete the following information):**
 Raspberry Pi 3 Model B V1.2
 ‖ Official Duino-Coin © Python Miner (2.75) 2019-2021
 ‖ https://github.com/revoxhere/duino-coin
 ‖ CPU: 4x ARMv7 Processor rev 4 (v7l)
 ‖ Developer donation level: 1
 ‖ Algorithm: DUCO-S1 ⚙ Low diff
 ‖ Rig identifier: RaspPi
 ‖ Have a cozy evening, juse32!

**Additional context**
Made sure Pi was up to date, cleared the duino-coin dir and recloned, rebooted the home network, double-checked all requirements were installed, can ping 8.8.8.8 from the device.

I have been unable to access the web wallet for 2-3 days due to what I suspect is an IP ban caused by leaving the lulas dashboard running. This rig was connected prior to the web wallet access issues and after (continuously). It is possible the ban could be a cause for this access issue?

**Comment by Juse32** [comment]
Revox helped address this issue by reallowing my IP.

**Comment by ClaudioLillo** [comment]
I have the same problem now

**Comment by zolag63** [comment]
I also have the same issue.
@revoxhere could you please help?
![image](https://user-images.githubusercontent.com/55257658/148031367-a9e4618e-73a3-4c9b-a638-2987d0d954fc.png)

**Comment by ClaudioLillo** [comment]
In my case, the problem was an internet connection issue. The error message was correct. There was no problem with my IP.

**Comment by zolag63** [comment]
@ClaudioLillo  thank you for the clarification.

this will be something else here.

I was mining and then suddenly today all of my rigs are stoped, expect the browser mining, that is works. but nor the esp32s nor the raspberry

**Comment by zolag63** [comment]
ok , I don't know what is happened, but now it is came back!

MINING AGAIN :D

**Comment by Axoluto** [comment]
Im having the same problem "Error fetching node from poolpicker: connection failed" with only one of the devices i´ve tried, its a D1 mini (clone), NO MATTER THE WAY I PROGRAM IT, TRIED IT ALL ( I THINK).
I cant find any topic in which i can get help to solve it. Im almost at 24 hours trying to solve this with little stops in the middle.
Thanks in advance for any possible help.

**Comment by dvn-jr** [comment]
Same here. It connects over my roommates mobile hotspot but not my own..
