### ISSUE TITLE
STM8S support

### ISSUE THREAD

**Issue by fallen90** [duino-coin/duino-coin#1183]
I've been wondering if it's possible to have support for STM8S boards since STM32 is already supported. Not sure what would be the problem on supporting these boards.

I had tried using the existing STM32 code but had some problems with ArduinoUniqueId, then I had removed the code for it (just returns  some static uniqueId when called) but had ran to issues with compiled code is too large for the 8KB flash, I could have refactored the code to use the existing sha1 implementation that exists on the board, but had some problems coding in SDCC.

**Comment by BBS215** [comment]
Besides the large size of the firmware, there is also a problem with the byte order. AVR and STM32 use little endian, and STM8 - big endian. Take a look here: https://github.com/BBS215/STM8_DUCO_miner

**Comment by LDarki** [comment]
I`ll close this issue
