### ISSUE TITLE
ESP8266 Manual Pool Selection

### ISSUE THREAD

**Issue by KYOCHEN87** [duino-coin/duino-coin#1184]
How to manual select Pool rather then using /getpool as /getpool might give a Pool that is currently down in https://status.duinocoin.com/

**Comment by revoxhere** [comment]
getPool does not select pools that haven't synced in last 60 seconds.

**Comment by KYOCHEN87** [comment]
Possible for me to point my ESP8266 to Beyond Pool or SVKO Pool directly as /getPool return Bilapool/Null/Star Pool which is currently down and getting Rejection share?

**Comment by revoxhere** [comment]
No, please don't hard code any IPs as pool IPs and their ports change from time to time. Bila, star and svko pools are working fine, so check your setup

**Comment by KYOCHEN87** [comment]
i getting BAD,Too many workers share #5 (24201) hashrate: 10.41 kH/s (2.33s) on those pool but no issue when i reboot my device and get into Beyond/SVKO. or is it due to other issue?

My account is verified using 50 x ESP8266.

**Comment by revoxhere** [comment]
Lower your worker count and see if the problem persists.

**Comment by KYOCHEN87** [comment]
Currently troubleshooting using 1 x ESP8266 only. the Rig is currently shut down and found no issue via Up pool in https://status.duinocoin.com/, only having issue for those Pool showing Down.

Is there a maximum miner limit?

**Comment by revoxhere** [comment]
You can have up to 50 workers per IP/account/pool. It's pointless to have more than 20 as the efficiency is less than half

**Comment by KYOCHEN87** [comment]
Thanks, have to continue troubleshooting on the Down Pool using 1 x ESP8266 or Arduino Uno and Nano as they having same behavior using 1 account on Wifi network and Data network thus isolated IP/Router/Network issue.
