### ISSUE TITLE
Contact us link on website leads to a 404

### ISSUE THREAD

**Issue by StickyDigit** [duino-coin/duino-coin#1186]
The contact us link on the duinocoin.com goes to a 404.

To Reproduce: Got to the main website, click "Contact Us", or directly visit https://duinocoin.com/contact

**Comment by Tech1k** [comment]
My apologies, I am currently working on adding spam-prevention to the form's backend. I will let you know here when the form is back which should be today.

**Comment by BastelPichi** [comment]
The form is now back and should be working.
