### ISSUE TITLE
BastelPichi's Faucet is no longer active.

### ISSUE THREAD

**Issue by StickyDigit** [duino-coin/duino-coin#1187]
On the apps page as https://lefaucet.tk/

After checking about the invalid site cert for this faucet, I was lead to understand it has been discontinued.

Suggest remove link.

**Comment by Tech1k** [comment]
I will remove this link as it does seem to be inactive.

@BastelPichi please contact me on Discord if you reactivate your faucet and I'll re-add it!

**Comment by BastelPichi** [comment]
I know, the faucet is dead already quite some time. (||RESPOND TO MY DM TOSHI||)
