### ISSUE TITLE
Auto verification instead of manual

### ISSUE THREAD

**Issue by codeoffun2** [duino-coin/duino-coin#1188]
We could use https://customvision.ai/ or tensorflow to verify accounts instead of manually looking through submissions.
Basically we can make it recognize microcontrollers and perhaps text.
The only problem I can think of is that people can fake the images by taking pictures from google and submitting them

**Comment by BastelPichi** [comment]
Manual Verification goes real quick, as all Discord moderators can verify accounts. Using AI would be a lot of work, and also users could fake images or for example verify the same arduino with different accounts. A human would see something like this.

**Comment by Picolo12** [comment]
ERROR

There was an error sending your request:
No miners running on your account

???????????????????????????

**Comment by primitt** [comment]
> ERROR
> 
> There was an error sending your request: No miners running on your account
> 
> ???????????????????????????

You need to turn on your miners so we can verify they exist and are mining on duino
