### ISSUE TITLE
Can't run pc_miner

### ISSUE THREAD

**Issue by BurnTheWitch13** [duino-coin/duino-coin#1194]
![16411435008264631794786821149529](https://user-images.githubusercontent.com/96991651/147883652-c8c2bfd5-f431-469b-942f-5121ae5a6098.jpg)

Anyone know how to deal with this problem?

**Comment by noobcode73** [comment]
It helped me

Edit the PC_Miner.py file
Change **BLOCK = " | | "**  And replace emojis **PICK** **COG** with characters or spaces in 'class Settings'

 
>     ....
>     BLOCK = " || "
>     PICK = ""
>     COG = " @"
>     if (os.name != "nt"
>         or bool(os.name == "nt"
>                 and os.environ.get("WT_SESSION"))):
>         # Windows' cmd does not support emojis, shame!
>         PICK = " "
>         COG = " @"

In the Translations.json file do the same and remove the copyright icon in the 'banner'

>    ...
>    "banner":"Official Duino-Coin @ Python Miner"
>     ...
>     "report_period":"\n\t\t|| During the last ",
>     ....

and save UTF-8



_OrangePi zero platform_

**Comment by LDarki** [comment]
Solved in [this commit](https://github.com/revoxhere/duino-coin/commit/474261b093684a92a2b4cc8205d41275ffc82da4).
I`ll close this issue
