### ISSUE TITLE
Kolta drop off?

### ISSUE THREAD

**Issue by RobMitt** [duino-coin/duino-coin#1195]
All of my miners are showing a 75.14% earning. Running 5 Arduino Unix hosted and Pi 4.

**Comment by RobMitt** [comment]
Arduino uno. Thanks autocorrect

**Comment by RobMitt** [comment]
I have not rebooted all AVRs and are now running on individual instances. Here are the earning percentages: 100, 88.74, 88.74, 75.14, 75.14, 75.14, 75.14. (82.58%) average. If
I'm understanding Kolta right it should be 100, 100, 100, 100, 96, 94, 92. (96.57% average)?

**Comment by JensL70** [comment]
I noticed something similar, but even more worst - if one of the AVRs reconnects for whatever reason, the drop off seems to gets bigger for it (means getting a lower percentage). Like the lost connection gets into account for a while... so all become the same and drop off value over time.

**Comment by RobMitt** [comment]
Three days later....still running the same as my last comment. No changes or reboots to my rig. @revoxhere

**Comment by RobMitt** [comment]
@revoxhere ok...another update....all AVRs are now showing 88.47% but one that's is at 75.14

**Comment by RobMitt** [comment]
Another update. As if this mornings all miners now show 88.47%. This is an improvement, but I'm still taking about a +10% hit on what the average should be.
