### ISSUE TITLE
Error to Open PC_Miner.py in Raspberry

### ISSUE THREAD

**Issue by SrBombo** [duino-coin/duino-coin#1199]
Hi, I'm triying to open PC_Miner in my Raspberry Pi but is Impossible, always teh same problem

File "PC_Miner.py", line 186
    pretty_print(f"Warning: {response['message']}"
                                                 ^
SyntaxError: invalid syntax

I followed this Steps: 
**sudo apt update
sudo apt install python3 python3-pip git python3-pil python3-pil.imagetk -y # Install dependencies
git clone https://github.com/revoxhere/duino-coin # Clone Duino-Coin repository
cd duino-coin
python3 -m pip install -r requirements.txt**

In fact, I needed to delete the tronpy line from the "requerimets.txt" to finish teh prerequisites, but when I Run the PC Miner I get this error.

**System **
 - OS: Raspbian 9
 - Software PC Miner latest version
 - I tried Python 3.5.3 & 3.7.0

Does anyone know anything about these problems? 
I also followed the same steps on another X86 computer and everything worksrks. 

Thanks!

**Comment by revoxhere** [comment]
Python 3.5 is too old. You need at least Python 3.7. Make sure to launch it like so: `python3.7 PC_Miner.py`

**Comment by SrBombo** [comment]
Hi, 

Thanks for the quickly support. I tried It but the probelms continue, but now in another line:

pi@raspberrypi:~/duino-coin $ python3.7 PC_Miner.py 
Traceback (most recent call last):
  File "PC_Miner.py", line 27, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'


Regards.

**Comment by revoxhere** [comment]
python3.7 -m pip install requests

**Comment by SrBombo** [comment]
Now is working. 

Thaks!
