### ISSUE TITLE
ERROR  There was an error sending your request: No miners running on your account

### ISSUE THREAD

**Issue by Picolo12** [duino-coin/duino-coin#1200]
Verifizierung nicht möglich immer der selbe Fehler : Beim Senden Ihrer Anfrage
ist ein Fehler aufgetreten: Keine Miner, die auf Ihrem Konto ausgeführt werden

Beim Senden Ihrer Anfrage
ist ein Fehler aufgetreten: Keine Miner, die auf Ihrem Konto ausgeführt werden

Beim Senden Ihrer Anfrage
ist ein Fehler aufgetreten: Keine Miner, die auf Ihrem Konto ausgeführt werden

Beim Senden Ihrer Anfrage
ist ein Fehler aufgetreten: Keine Miner, die auf Ihrem Konto ausgeführt werden

 

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.
![Unbenannt](https://user-images.githubusercontent.com/61686639/147976567-0100f246-6a6c-42df-89bd-0532c91a6d60.PNG)

**System Windows und [D1Mini]
**Additional context**

**Comment by revoxhere** [comment]
You need to launch your miners first
