### ISSUE TITLE
Send coins

### ISSUE THREAD

**Issue by Walttinho** [duino-coin/duino-coin#1201]
good night, i have a problem sending my bscDUCO to Metamask.  as a test I managed to send a small amount, but now when I send the following error appears "This address is associated with another account(s)", how should I proceed?

**Comment by BBS215** [comment]
Hello, I checked the wrapping for 200 DUСOs to metamask, and did not find any problems. Transaction completed? Can you find your transaction on bscscan?
https://bscscan.com/token/0xcf572ca0ab84d8ce1652b175e930292e2320785b

**Comment by jarno83** [comment]
Hi, right now bscDUCO wrapper just hangs. It dosen't to the wrapping, something wrong with it.

**Comment by pfwd** [comment]
@revoxhere I'm also getting the same issue.  I've tried to wrap maticDUCO and getting the error in the console
'NO,This address is associated with another account(s): None'
See screenshot
<img width="672" alt="Screenshot 2022-01-05 at 18 58 23" src="https://user-images.githubusercontent.com/126350/148273719-64f0845d-2494-4a19-8546-9a3c0d09e018.png">

**Comment by pfwd** [comment]
It could be down to this https://github.com/revoxhere/duco-rest-api/blob/bc293f15e6a7e7a57b2d666e87398de2b59efa72/app.py#L1559-L1565
Perhaps my account is in a jail (?) or something. I will try again later. 
I recommend having some form of messaging on the frontend to show whats going on here.
