### ISSUE TITLE
adafruit m0 express when compiling w/arduino code

### ISSUE THREAD

**Issue by 3dprinte** [duino-coin/duino-coin#1204]
Arduino: 1.8.19 (Windows 10), Board: "Arduino M0 Pro (Programming Port)"

Sketch uses 31840 bytes (12%) of program storage space. Maximum is 262144 bytes.

Global variables use 3712 bytes (11%) of dynamic memory, leaving 29056 bytes for local variables. Maximum is 32768 bytes.

Open On-Chip Debugger 0.10.0+dev-gf0767a31 (2018-06-11-13:36)

Licensed under GNU GPL v2

For bug reports, read

	http://openocd.org/doc/doxygen/bugs.html

debug_level: 0

none separate

adapter speed: 400 kHz

cortex_m reset_config sysresetreq

Error: unable to find CMSIS-DAP device

Error: No Valid JTAG Interface Configured.

Error: No Valid JTAG Interface Configured.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by JK-Rolling** [comment]
refer link to setup and choose the right board
https://learn.adafruit.com/adafruit-feather-m0-express-designed-for-circuit-python-circuitpython/arduino-ide-setup

**Comment by 3dprinte** [comment]
How do I choose the board ? Tools/boards/adafruitm0or uncommenting something on code?

**Comment by LDarki** [comment]
Hello, are you still having this problem?
If not tell me for close this issue.

**Comment by LDarki** [comment]
No response.
I`ll close this issue
