### ISSUE TITLE
Cannot login to any wallet

### ISSUE THREAD

**Issue by dm-vev** [duino-coin/duino-coin#1207]
**Describe the bug**
I created an account on the web vallet and then turned off the computer. When I turned it on and tried to log in, the site gave me an error (the duino coin icon wobbled and the button became active again), and so on in a loop. Then I remembered that I wrote myself a small code to get my balance (I wanted to make a widget for Linux mints) and lo and behold I was able to log in! How can I log into the web vallet if my data is correct?

**To Reproduce**
1. Go to https://wallet.duinocoin.com/
2. Click onlogin button
3. See login error

**Expected behavior**
Always

**System (please complete the following information):**
 - OS: Linux mint XFCE 21.04
 - Software Web wallet and CLI Wallet/Wallet
 - Version 2.7.5

**Additional context**
Logging into your account through CLI Wallet/Wallet the same is impossible, it will just be eternal loading
Python code of my widget:
```
import datetime
import json
import os
from os import _exit, execl, mkdir
from os import path
import platform
import socket
import sys
import time
from pathlib import Path
from signal import SIGINT, signal
from base64 import b64decode, b64encode
from platform import system as plsystem
from locale import LC_ALL, getdefaultlocale, getlocale, setlocale
from json import load as jsonload

from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
import websocket
from colorama import *

username = "privacy"
password = "privacy"

WS_URI = "ws://server.duinocoin.com:15808"
wss_conn = websocket.create_connection(WS_URI)
SERVER_VER = wss_conn.recv().decode()

def balance():
    try:
        wss_conn.send(bytes(
            "BALA",
            encoding="utf8"))
    except:
        pass
    try:
        balance = round(
            float(wss_conn.recv().decode().rstrip("\n")), 8)
        balanceusd = round(
            float(balance) * float(0.0025), 6)
        balances = [balance,balanceusd]
        return balances
    except:
        pass

def close():
    wss_conn.send(bytes("CLOSE", encoding="utf8"))

wss_conn.send(bytes(
    "LOGI,"
    + str(username)
    + ","
    + str(password)
    + str(",placeholder"),
    encoding="utf8"))
loginFeedback = wss_conn.recv().decode()
print(loginFeedback)

def printf(txt):
    print(Style.BRIGHT + txt)

def reconnect():
    while True:
        try:
            # Try to connect
            wss_conn = websocket.create_connection(WS_URI)
            wss_conn.settimeout(5)
            SERVER_VER = wss_conn.recv().decode().rstrip("\n")

            jsonapi = requests.get(
                "https://raw.githubusercontent.com/"
                + "revoxhere/"
                + "duco-statistics/master/api.json",
                data=None)
            if jsonapi.status_code == 200:
                content = jsonapi.content.decode()
                contentjson = json.loads(content)
                ducofiat = float(contentjson["Duco price"])
            else:
                ducofiat = 0.0025

        except:
            print(Style.RESET_ALL + Fore.RED
                  + "ccts")
            time.sleep(15)
            os.system("python " + __file__)
        else:
            return wss_conn
b = balance()
while True:
    printf("Welcome back, wideputhin!")
    print("Billing:")
    print("- Balance in USD: " + str(b[1]))
    print("- Balance in PTP: "+ str(b[0]) + "(~"+str(b[0]) +"K PT)")
    print("Select action:")
    print("Check miner")
    input("->")
```

**Comment by dm-vev** [comment]
changed for more readability of the code

**Comment by birrozza** [comment]
I have the same problem. I cannot login at my wallet

**Comment by Fred7421** [comment]
Same here.

**Comment by revoxhere** [comment]
Please try now. One of the servers blocked another one xD

**Comment by birrozza** [comment]
Don't work for me. In browser console I have the same error: 
` from origin 'https://wallet.duinocoin.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by dm-vev** [comment]
don't working :(

**Comment by Fred7421** [comment]
I'm back up

**Comment by Fred7421** [comment]
I find it interesting that the more you hash, the less you make.
I'm curious. Using Kolka, where do the remaining shares go? 
Is it a reduction in coins given or shares hit?
Either way, where do they go?

**Comment by dm-vev** [comment]
login is working

**Comment by dm-vev** [comment]
> I find it interesting that the more you hash, the less you make. I'm curious. Using Kolka, where do the remaining shares go? Is it a reduction in coins given or shares hit? Either way, where do they go?

it is possible that the kolka reduces the hash rate depending on your balance. It's not at all clear why this is
