### ISSUE TITLE
AVR mining on Java

### ISSUE THREAD

**Issue by chiffacff** [duino-coin/duino-coin#1209]
Hello. Is it possible to create AVR mining on java? or may be some one have this solution?

**Comment by BBS215** [comment]
The JVM cannot run on 2KB RAM. You can try to rewrite the code for haiku-vm, but in the end it will still be converted to C code and compiled by avr-gcc. Therefore, there is not much sense in this.

**Comment by chiffacff** [comment]
I mean run it on PC, instead of python

**Comment by BBS215** [comment]
I found Java code for android only: https://github.com/DoctorEenot/DUCOAndroidMiner/blob/main/app/src/main/java/com/example/duco_miner/MainActivity.java

**Comment by LDarki** [comment]
Hi, sorry for the late response.
Yes, it is.
But the only code available in java is the Android Miner.

Tell me if i can close this issue.

**Comment by LDarki** [comment]
No response,
i`ll close this issue
