### ISSUE TITLE
Fetching node error

### ISSUE THREAD

**Issue by dm-vev** [duino-coin/duino-coin#1210]
**Describe the bug**
When mining starts, the miner cannot find the node
![image](https://user-images.githubusercontent.com/80632449/148352751-c63145d0-37d8-4967-8c94-5266e37dce68.png)

**To Reproduce**
1. Start mining
2. See error

**Expected behavior**
Always

**Screenshots/photos**
![image](https://user-images.githubusercontent.com/80632449/148352895-9d6cffdf-9071-410a-876e-0925c57141a5.png)

**System (please complete the following information):**
 - OS: Linux mint
 - Software Official PC Miner
 - Version 2.7.5

**Comment by LDarki** [comment]
Hi, Are you still facing this issue?

**Comment by dm-vev** [comment]
No, they were probably just servers. I'm sorry I forgot to close the issue.

**Comment by LDarki** [comment]
No problem, i`ll close it
