### ISSUE TITLE
What is libducohash.so?

### ISSUE THREAD

**Issue by nm17** [duino-coin/duino-coin#1213]
I have found a file named [`libducohash.so`](https://github.com/revoxhere/duino-coin/blob/640701a9d3ce136877b55d15142623f973c2650e/Master_Server/libducohash.so) and I was wondering: What is it's purpose and is it open source or not?

Upon first inspection, it is written in Rust, which is weird, considering there is no rust source code in this repo.

**Comment by revoxhere** [comment]
This is a reminescence of times when the master server was handling practically all clients for mining. It's a rust library that generates the duco jobs, being much faster than the python implementation. I don't have the source for it as it's not even used for a year or so, but the original creatior was HGEpro if you have any more questions.

**Comment by nm17** [comment]
Thanks for the answer
