### ISSUE TITLE
MacOS mining

### ISSUE THREAD

**Issue by bnvill84** [duino-coin/duino-coin#1219]
**Is your feature request related to a problem? Please describe.**
Not able to get the py version of miner to run on Mac with terminal or python

**Describe the solution you'd like**
Add the ability to run a version on mac

**Describe alternatives you've considered**
Running web miner, but that requires to keep the page open and awake

**Additional context**

**Comment by osmolenko** [comment]
@bnvill84 
It's possible to run miner on mac. I use python 3.9 from homebrew.
1. Update python via [Homebrew](https://brew.sh/) with `brew install python`.
2. Download source files from this repo `git clone https://github.com/revoxhere/duino-coin`
3. Open directory `cd duino-coin`
4. Install dependencies `python3 -m pip install -r requirements.txt`
5. Start a miner cli `python3 PC_Miner.py`

**Comment by bnvill84** [comment]
Thank you very much!! worked perfectly
