### ISSUE TITLE
Unable to create a wallet using web browser

### ISSUE THREAD

**Issue by JoshAtticus** [duino-coin/duino-coin#1227]
**Describe the bug**
Using wallet.duinocoin.com doesn't let you sign up for a wallet, it just says loading forever

**To Reproduce**
1. Go to wallet.duinocoin.com
2. Enter details
3. Complete captcha
4. Click create a new wallet
5. Wait for eternity for nothing to happen

**Expected behavior**
I don't know

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: Windows 11
 - Software: Web Wallet (on Firefox Nightly)
 - Version: Firefox Nightly v98.0a1

**Comment by LDarki** [comment]
Hello,
Can you send a picture of the developer tools console?
(F12> Console) - (CTRL + SHIFT + C> Console)
[You can censore what you think thats fine]

I want to see if an error occurs.
Thanks.

**Comment by LDarki** [comment]
No response. i will close this issue.

**Comment by drakor007** [comment]
Hi, I have the same problem. There is my screenshot,

![image](https://user-images.githubusercontent.com/12645375/152696514-7ed10eb4-05c7-4198-aef6-b9625f3da9e4.png)

**Comment by LDarki** [comment]
Please don`t continue closed issues.

And the server is down.

**Comment by JoshAtticus** [comment]
> No response. i will close this issue.

Really sorry! I dropped my phone in water with my 2fa app and had to get it sent in for repair
It seems to just have been a server issue, and I already have a wallet now, thanks for trying to help though
