### ISSUE TITLE
changing the parameters with mining on pc

### ISSUE THREAD

**Issue by test-user-101** [duino-coin/duino-coin#1238]
Hi all,

I am a new member of the duino community, I would like to know how to change the performance of the mining using the CPU mining app , initially I used low specs and thought of changing them later , but it uses the saved specifications every time , is the a command I need to enter to select new parameters , thank in advance.

**Comment by Nelevit** [comment]
Hi,

Setting are stored in Settings.cfg file 
![image](https://user-images.githubusercontent.com/52739692/149725175-e90abf08-f4de-4680-976a-08e1cf003b4d.png)
![image](https://user-images.githubusercontent.com/52739692/149725382-7f3d29e5-d0cc-4458-8fff-ef1668c9e8b8.png)

**Comment by Mifaxav** [comment]
im on the newer version and there is no settings.cfg file. any idea on how to solve this???

**Comment by vishesh0077** [comment]
Mifaxav you can find that files in a folder called Duino-coin PC Miner **3.5**. The version of duino coin will be different for you. And there you can find the settings files.
<img width="960" alt="Screenshot 2023-05-17 090147" src="https://github.com/revoxhere/duino-coin/assets/102781911/281944b3-ab7b-435c-a589-4ebbe8678c96">
