### ISSUE TITLE
Web Wallet not working 

### ISSUE THREAD

**Issue by giobit** [duino-coin/duino-coin#1241]
Unable to login to My Web wallet

**Comment by LDarki** [comment]
Hi,
Can you send more info of that problem?

Web Browser
URL
And ScreenShot of the developers console (F12 > Console) or (Ctrl + Shift + C > Console)

Thanks.

**Comment by Rhoaming** [comment]
Duino coin miner

**Comment by Rhoaming** [comment]
artesroam@mil.com

**Comment by LDarki** [comment]
No response. i will close this issue.
