### ISSUE TITLE
I can't compile the Duino code esp8266 onto the board.

### ISSUE THREAD

**Issue by Ailurophile11** [duino-coin/duino-coin#1245]
At first my code couldn't compile. So I fixed it and uploaded it to the board where it failed. I have installed the firmware for the board. but haven't uploaded yet.
![image](https://user-images.githubusercontent.com/59225749/149610729-0238d20c-1dac-4d09-8a27-2c1f43281106.png)
![image](https://user-images.githubusercontent.com/59225749/149611039-619522f2-0ed0-4871-937f-f0180bedc257.png)
exec: "C:\\Users\\Natth\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\python3\\3.7.2-post1/python3": file does not exist
Error compiling for board Generic ESP8266 Module.

**Comment by benthinker** [comment]
1. Please install [python3](https://www.python.org/downloads/) . 
 1.1 after installation try to run the script again. If still **not** working please start step 2.
2. change windows python's path:
 2.1 Right click on My Computer and click on properties.
 2.2 Click on Advanced System settings.
 2.3 Click on Environment Variable tab.
 2.4 Click on new tab of user variables.
 2.5 Write path in variable name.
 2.6 Copy the path of Python folder.
 2.7 Paste path of Python in variable value.
3. Close Arduino IDE and open it again.

**Comment by Ailurophile11** [comment]
It's the same.
![image](https://user-images.githubusercontent.com/59225749/149620956-92d76074-67ec-4773-bf1c-93ff3080c67c.png)
![image](https://user-images.githubusercontent.com/59225749/149621020-a2b5491a-b168-4a79-a3bf-c8b3e31a50f1.png)

**Comment by LDarki** [comment]
Hi, you are still having this issue?
If not, tell me for close this issue.

**Comment by LDarki** [comment]
No response.
I`ll close this issue
