### ISSUE TITLE
Erorr LINUX

### ISSUE THREAD

**Issue by Jzz0** [duino-coin/duino-coin#1246]
Erorr fetching mining node: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt, retrying in 15 sec
!ERORR IMG](https://user-images.githubusercontent.com/97784399/149617173-00419f89-e7a9-4013-93e2-0b7c5759f481.png)

**Comment by LDarki** [comment]
Hi, you are still having this issue?
If not, tell me for close this issue.
------------------------------------

Maybe /etc/ssl/certs/ca-certificates.crt is not exist.
Try running 
```sudo update-ca-certificates```
to create it.

**Comment by LDarki** [comment]
No response.
I`ll close this issue
