### ISSUE TITLE
WDT timeout

### ISSUE THREAD

**Issue by Daviedz** [duino-coin/duino-coin#1247]
Using the latest Version 3.0 on my ESP8266 and bit difficult to connect to server , i always have WDT timeout..

**Comment by MahardikaAg** [comment]
Using the latest Version 3.0 on my ESP32 and it's a bit difficult to connect to the server,
and also the light does not flash which indicates it is active
please help for this problem

**Comment by LDarki** [comment]
Hi, you are still having this issue?
If not, tell me for close this issue.

**Comment by MahardikaAg** [comment]
very well done
and thank you very much


Pada tanggal Min, 30 Jan 2022 07.47, LDarki ***@***.***>
menulis:

**Comment by LDarki** [comment]
I'll take that as a no, I'll close the issue.

If you still have problems, please make a new issue with the detailed information.

**Comment by MahardikaAg** [comment]
and once again thank you for your attention 🙏😁


Pada tanggal Min, 30 Jan 2022 18.44, LDarki ***@***.***>
menulis:
