### ISSUE TITLE
A lot of connection errors

### ISSUE THREAD

**Issue by a-lang** [duino-coin/duino-coin#1248]
**Describe the bug**
A lots of connection errors when mining even though the network is fine.
![duino-coin-error](https://user-images.githubusercontent.com/11038458/149648806-6b7b1ee4-1949-49e5-b183-7ca1cbc4b872.png)

**System (please complete the following information):**
 - OS: Debian 9
 - Software PC Miner
 - Version 2.7

**Comment by mr1cloud** [comment]
i have a similar problem

**Comment by ghost** [comment]
I have the same problem since tonight and now it doesn't even connect. ![imagen](https://user-images.githubusercontent.com/72511617/149660931-7f845909-e167-4299-99ae-e657c47a07ed.png)

**Comment by revoxhere** [comment]
Are you still facing this issue?

**Comment by LDarki** [comment]
No response, i`ll close this issue
