### ISSUE TITLE
After ENABLE_MQTT compiler error may be wrong libraries etc...

### ISSUE THREAD

**Issue by lyovav** [duino-coin/duino-coin#1252]
```
E:\INSTALL\mining\Duino-Coin_3.0_windows\ESP32_1\ESP32_1.ino: In function 'void setup()':
ESP32_1:829:5: error: 'MqttPublishCode' was not declared in this scope
     MqttPublishCode, "MqttPublishCode", 10000, NULL, 1, &MqttPublishHandle,
     ^~~~~~~~~~~~~~~
E:\INSTALL\mining\Duino-Coin_3.0_windows\ESP32_1\ESP32_1.ino:829:5: note: suggested alternative: 'MqttPublishHandle'
     MqttPublishCode, "MqttPublishCode", 10000, NULL, 1, &MqttPublishHandle,
     ^~~~~~~~~~~~~~~
     MqttPublishHandle
exit status 1
'MqttPublishCode' was not declared in this scope
```

**Comment by ded000** [comment]
i have a similar problem

**Comment by ded000** [comment]
Moved the void MqttPublishCode( void * pvParameters ) block above the void setup() block.
Compiled ok.

**Comment by AdrianITT** [comment]
I have this when I try to verify the code:

C:\Users\adria\OneDrive\Documentos\DuinoCoin\duino-coin-3.0\ESP8266_Code\ESP8266_Code.ino: In function 'void setup()':
C:\Users\adria\OneDrive\Documentos\DuinoCoin\duino-coin-3.0\ESP8266_Code\ESP8266_Code.ino:480:34: warning: 'void {anonymous}::lwdtcb()' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
  480 |   lwdTimer.attach_ms(LWD_TIMEOUT,lwdtcb);
      |                                  ^~~~~~
C:\Users\adria\OneDrive\Documentos\DuinoCoin\duino-coin-3.0\ESP8266_Code\ESP8266_Code.ino:366:22: note: declared here
  366 | void ICACHE_RAM_ATTR lwdtcb(void)
      |                      ^~~~~~
C:\Users\adria\OneDrive\Documentos\DuinoCoin\duino-coin-3.0\ESP8266_Code\ESP8266_Code.ino:480:40: warning: 'void {anonymous}::lwdtcb()' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
  480 |   lwdTimer.attach_ms(LWD_TIMEOUT,lwdtcb);
      |                                        ^
C:\Users\adria\OneDrive\Documentos\DuinoCoin\duino-coin-3.0\ESP8266_Code\ESP8266_Code.ino:366:22: note: declared here
  366 | void ICACHE_RAM_ATTR lwdtcb(void)
      |                      ^~~~~~
C:\Users\adria\OneDrive\Documentos\DuinoCoin\duino-coin-3.0\ESP8266_Code\ESP8266_Code.ino: In function 'void loop()':
C:\Users\adria\OneDrive\Documentos\DuinoCoin\duino-coin-3.0\ESP8266_Code\ESP8266_Code.ino:528:70: warning: 'static String experimental::crypto::SHA1::hash(const String&)' is deprecated [-Wdeprecated-declarations]
  528 |     result = SHA1::hash(last_block_hash + String(duco_numeric_result));
      |                                                                      ^
In file included from C:\Users\adria\OneDrive\Documentos\DuinoCoin\duino-coin-3.0\ESP8266_Code\ESP8266_Code.ino:39:
C:\Users\adria\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/Crypto.h:231:19: note: declared here
  231 |     static String hash(const String &message) __attribute__((deprecated));
      |                   ^~~~
