### ISSUE TITLE
Memory leak in esp32 code for release 3.0

### ISSUE THREAD

**Issue by geneReeves** [duino-coin/duino-coin#1256]
**Describe the bug**
in the 3.0 release there is a memory leak in the ESP32 code at line 641, the code malloc 100 bytes, each time through the loop, I recommend making that a var on the local heap,
 i.e.:
at the beginning of the TaskMining function, place 
unsigned char *hashbuff[128];
then changing line 641 to:
 unsigned char *expectedHashBytes = (unsigned char *)&hashbuff;

enjoy,
Nightrader2k

**Comment by StickyDigit** [comment]
I can confirm that my ESP32 ram was shrinking constantly until it reset.

Yay! Now memory goes up and down a little, instead of just down a lot... so I can also confirm the patch seems to fix it.

Nice one Nightrader2k !!

**Comment by BBS215** [comment]
Sorry to butt in, but unsigned char *hashbuff[128] is 128 pointers to unsigned char elements. Correct like this:
void TaskMining(void *pvParameters) {
unsigned char hashbuff[128];
......
unsigned char *expectedHashBytes = hashbuff;

**Comment by StickyDigit** [comment]
I've tried BBS215's suggestion, and it still works, still with no apparent memory leak.

For me it floated between extremes of roughly 161500 and 164150 bytes free.

Using the attached, ugly and heavily simplified dashboard for easier logging through wget and sed.

[Tinydashboard.txt](https://github.com/revoxhere/duino-coin/files/7890414/Tinydashboard.txt)

**Comment by geneReeves** [comment]
> Sorry to butt in, but unsigned char *hashbuff[128] is 128 pointers to unsigned char elements. Correct like this: void TaskMining(void *pvParameters) { unsigned char hashbuff[128]; ...... unsigned char *expectedHashBytes = hashbuff;

You are correct, it was a typo that I did not notice (even though the code would still work). Good catch!!
