### ISSUE TITLE
Typo Fix in news.html under server.duinocoin.com

### ISSUE THREAD

**Issue by CosmicShreyas** [duino-coin/duino-coin#1257]
Hey Revox i just found a typo related to news.html page the "please" spelling is wrong and i just wanted to inform u that since im banned in duco discord and there is no source code for news.html... pls fix the typo and nice to meet u again Cya!!!
![2022-01-18 19_06_04-Greenshot](https://user-images.githubusercontent.com/97907864/149948294-047ccafb-670f-4911-9feb-5d50f7a4c081.png)

**Comment by LDarki** [comment]
Hi, ty for the notice.

Later will be fixed.

i`ll close this issue
