### ISSUE TITLE
Requesting a discord login/signup for web wallet and a feature to add profile picture in web wallet

### ISSUE THREAD

**Issue by CosmicShreyas** [duino-coin/duino-coin#1258]
Hey Revox could u make webwallet login with discord?? in this manner duino stats also needs a premission called join servers for you 

when someone logins with discord or signups with discord to web wallet then the duino stats would automatically join duino coin discord servers for them!!!

and also i recommend to add a pfp feature in webwallet which means we can set custom photos in webwallet  too!!!
let me know what you think maybe i can help u (if you are not upset with me)

**Comment by LDarki** [comment]
For this topic you can make a suggestion on discord.
I`ll close this issue
