### ISSUE TITLE
OTA firmware update

### ISSUE THREAD

**Issue by bnvill84** [duino-coin/duino-coin#1264]
**Is your feature request related to a problem? Please describe.**
I have multiple ESP32's running duino-coin. There a possibility of OTA or batch OTA to get them all at one time?

**Describe the solution you'd like**
OTA updates, batch updates if this is possible

**Describe alternatives you've considered**
Setting one a server and the rest clients that get updates from the server?

**Comment by BBS215** [comment]
The code for ESP32 supports OTA. To do this, uncomment #define ENABLE_OTA. But keep in mind that enabling OTA support could decrease hashrate (up to 40%).

**Comment by sprokkie** [comment]
does the esp8622 also have 40% hashrate drop?
I noticed that de OTA was enabled by default

**Comment by BBS215** [comment]
No, but I have not tested the OTA function in the ESP8266

**Comment by sprokkie** [comment]
I upgrades my esp8622 to V3  and i noticed that ota was enabled.
