### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kamalmoharana** [duino-coin/duino-coin#1266]
D:\Mine\duino-coin-3.0>python AVR_Miner.py
Traceback (most recent call last):
  File "AVR_Miner.py", line 95, in <module>
    class Settings:
  File "AVR_Miner.py", line 113, in Settings
    and os.environ.get("WT_SESSION"))):
NameError: name 'os' is not defined

While mining with ESP32 board, I'm getting the above error. Please help

**Comment by LDarki** [comment]
Hi, Are you still facing this issue?

Please check if you have the line 
```import os```
in the AVR_Miner.py file

if not just add it on the top of the file
