### ISSUE TITLE
error  compile RIGIDENTIFIER not declared

### ISSUE THREAD

**Issue by ElKoziRRo** [duino-coin/duino-coin#1268]
While compiling get this error with no declared RIGIDIENTIFIER not declared

` // Autogenerate ID if required
  if ( strcmp(RIG_IDENTIFIER, "Auto") == 0 ) {
...
`
it stops here

`
C:\KOPCE\Duino-Coin_3.0_\ESP32_Code\ESP32_Code.ino: In function 'void HandleMqttConnection()':
ESP32_Code:386:42: error: 'RIG_IDENTIFIER' was not declared in this scope
     mqttRigTopic = "duinocoin/" + String(RIG_IDENTIFIER) + "/";
                                          ^
C:\KOPCE\Duino-Coin_3.0_\ESP32_Code\ESP32_Code.ino: In function 'void dashboard()':
ESP32_Code:429:30: error: 'RIG_IDENTIFIER' was not declared in this scope
   s.replace("@@ID@@", String(RIG_IDENTIFIER));
                              ^
C:\KOPCE\Duino-Coin_3.0_\ESP32_Code\ESP32_Code.ino: In function 'void WiFireconnect(void*)':
ESP32_Code:464:44: error: 'RIG_IDENTIFIER' was not declared in this scope
       Serial.println("Rig name: " + String(RIG_IDENTIFIER));
                                            ^
ESP32_Code:527:47: error: 'SSID' was not declared in this scope
       Serial.print("Connecting to: " + String(SSID));
                                               ^
C:\KOPCE\Duino-Coin_3.0_\ESP32_Code\ESP32_Code.ino: In function 'void TaskMining(void*)':
ESP32_Code:613:81: error: 'DUCO_USER' was not declared in this scope
       Serial.println(String(taskCoreName + " asking for a new job for user: " + DUCO_USER));
                                                                                 ^
ESP32_Code:697:84: error: 'RIG_IDENTIFIER' was not declared in this scope
             String(MINER_BANNER) + " " + String(MINER_VER) + MSGDELIMITER + String(RIG_IDENTIFIER) + MSGDELIMITER +
                                                                                    ^
C:\KOPCE\Duino-Coin_3.0_\ESP32_Code\ESP32_Code.ino: In function 'void setup()':
ESP32_Code:749:14: error: 'SSID' was not declared in this scope
   WiFi.begin(SSID, WIFI_PASS);  // Connect to wifi
              ^
ESP32_Code:749:20: error: 'WIFI_PASS' was not declared in this scope
   WiFi.begin(SSID, WIFI_PASS);  // Connect to wifi
                    ^
ESP32_Code:761:15: error: 'RIG_IDENTIFIER' was not declared in this scope
   if ( strcmp(RIG_IDENTIFIER, "Auto") == 0 ) {
               ^
At global scope:
cc1plus.exe: warning: unrecognized command line option '-Wno-frame-address'
Znaleziono wiele bibliotek w "WiFiClient.h"
Wykorzystane: C:\Users\ElKoziRRo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.0\libraries\WiFi
Niewykorzystane: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
'RIG_IDENTIFIER' was not declared in this scope
`

**Comment by ElKoziRRo** [comment]
machine ESP32 Dev-Module

**Comment by LDarki** [comment]
Hello, are you still having this problem?
If not tell me for close this issue.

**Comment by LDarki** [comment]
No response.
I`ll close this issue
