### ISSUE TITLE
libducohasher fail in cargo build on orange pi lite (armbian OS)

### ISSUE THREAD

**Issue by juanximxpx** [duino-coin/duino-coin#1269]
Error in compiling fasthash accelerator.

Following  https://github.com/revoxhere/duino-coin/wiki/How-to-compile-fasthash-accelerations
it fails in this step:
# Compile it:
cargo build --release

building ducohasher, has this error: could not compile 'ducohasher' due the previous error.

usr/bin/ld: cannot find -lpython3.8

![ducohasher](https://user-images.githubusercontent.com/19479908/150192335-caea0b72-f0db-449c-8def-f2522f5de758.jpg)

**Comment by mr1cloud** [comment]
i have same problem, what can i do to run my miner with fusthash?

**Comment by oeiua** [comment]
Hi, try to run
`apt install libpython3-dev`
and then 
`cargo build --release`
Its works for me

**Comment by mr1cloud** [comment]
@oeiua nop, it is not work for me :(

**Comment by juanximxpx** [comment]
> Hi, try to run `apt install libpython3-dev` and then `cargo build --release` Its works for me

Thanks! Now Is working on fasthash
