### ISSUE TITLE
setting the difficulty

### ISSUE THREAD

**Issue by mr1cloud** [duino-coin/duino-coin#1270]
can I set a certain mining difficulty so as not to load my system?

**Comment by francescoproprioio** [comment]
Have no idea sorry

Il gio 20 gen 2022, 18:43 Max ***@***.***> ha scritto:

**Comment by BBS215** [comment]
Difficulty does not affect system load. Difficulty only affects the maximum time to complete jobs. It is set by the pool, depending on the hashrate. To reduce the load, reduce the hashrate.

**Comment by mr1cloud** [comment]
okey, what can i do to reduce hashrate?

**Comment by francescoproprioio** [comment]
Could let miner use alternative wallet such as Swap Wallet: using contract
address of DUINO can create a new coin.

Is just a matter of time: someone will steal all the coins in the web
wallet.
Furthemore to open an account there they want the photos of you miners.

Crazy stupid.

Best regards

Il gio 20 gen 2022, 21:23 Max ***@***.***> ha scritto:

**Comment by BBS215** [comment]
Decrease setting "intensity" in Settings.cfg

**Comment by mr1cloud** [comment]
@BBS215 setting the difficulty in the Settings.cfg does not help me

**Comment by BBS215** [comment]
Not difficulty, intensity.

**Comment by mr1cloud** [comment]
hm, okey, intensity?
