### ISSUE TITLE
Fashhash module not working for Raspberry Pi Model B Rev 2

### ISSUE THREAD

**Issue by kapsolas** [duino-coin/duino-coin#1271]
**Describe the bug**
PC_Miner.py (v3.0) running on Raspberry Pi 3 Rev2(arm6l) is not downloading the fasthash module.
Looking at the code, support for this does exist. 

The error seen is:
 ‖ Official Duino-Coin © Python Miner (3.0) 2019-2021
 ‖ https://github.com/revoxhere/duino-coin
 ‖ CPU: 1x ARMv6-compatible processor rev 7 (v6l)
 ‖ Developer donation level: 1
 ‖ Algorithm: DUCO-S1 ⚙ Low diff
 ‖ Rig identifier: Rasp-Dakri
 ‖ Have a peaceful afternoon, kapsolas!

14:07:31  sys0  Downloading fasthash accelerations module
14:07:35  sys0  Fasthash accelerations are not available for your OS.
		If you wish to compile them for your system, visit:
		https://github.com/revoxhere/duino-coin/wiki/How-to-compile-fasthash-accelerations
		(Libducohash couldn't be loaded: libpython3.9.so.1.0: cannot open shared object file: No such file or directory)

Separately, this error is constantly coming up. Maybe related? Maybe network issues?
14:10:35  net0  Error while mining - most likely a connection error - restarting in 5s. list index out of range

**System (please complete the following information):**
 - OS: Buster
 - Software Raspberry Pi 3 Rev2
 - Version 3.0

**Comment by revoxhere** [comment]
You didin't install the latest version of python (and the dev version of it).

**Comment by kapsolas** [comment]
Great! Thanks for the prompt response I appreciate it.
I should probably move up from buster as well :)

**Comment by francescoproprioio** [comment]
I don't have a Raspberry
Best regards

Il gio 20 gen 2022, 21:32 Dimitrios Kapsalis ***@***.***> ha
scritto:

**Comment by JoshAtticus** [comment]
How do we install the latest version?

**Comment by kapsolas** [comment]
I updated to bullseye from my previous OS version and python updated with it.

**Comment by TechyGuy17** [comment]
I have the same problem with my pi4. Except updating python doesnt help... Anyone got any more tricks up their slieves?

**Comment by JoshAtticus** [comment]
> I have the same problem with my pi4. Except updating python doesnt help... Anyone got any more tricks up their slieves?

I installed Ubuntu on my RPi 4B, and that helped the fasthash accelerations work

**Comment by JoshAtticus** [comment]
> > I have the same problem with my pi4. Except updating python doesnt help... Anyone got any more tricks up their slieves?
> 
> I installed the latest version of Ubuntu Desktop on my RPi 4B, and that helped the fasthash accelerations work

**Comment by TechyGuy17** [comment]
> > > I have the same problem with my pi4. Except updating python doesnt help... Anyone got any more tricks up their slieves?
> > 
> > 
> > I installed the latest version of Ubuntu Desktop on my RPi 4B, and that helped the fasthash accelerations work

Ah okay, solved my issue but no idea how, just redid everything. But there were no issues the first time
