### ISSUE TITLE
issue on mining with usb/avr and i2c/avr

### ISSUE THREAD

**Issue by drdr34m** [duino-coin/duino-coin#1275]
im using avr/i2c with 10 nano's and avr/usb with 10 pico's when i run both of them on my avr/usb getting too many workers even if im using only one pico. When i disconnect my avr/i2c than avr/usb works perfect.
My avr/i2c is connected with esp8266 as master and my avr/usb is connected to my rpi.

**Comment by revoxhere** [comment]
Are you still facing this issue?

**Comment by drdr34m** [comment]
No all works pretty well now

**Comment by LDarki** [comment]
i`ll close this issue. Thanks for the response.
