### ISSUE TITLE
Just enough

### ISSUE THREAD

**Issue by haxorcitoz** [duino-coin/duino-coin#1276]
At first i really excited with this project because it's open new possibility in mining crypto without using expensive device. But today i realize it's just another way to wasting time. No wonder if more problem came out even after update to version 3.0 because the developer itself dont know what he is doing. So please stop tinkering and wasting more time to this what so called "project".
Leave it, there is no future here.

![Screenshot_20220123-205709_Instagram](https://user-images.githubusercontent.com/94447147/150680071-9ae5f154-78a2-45ec-91a5-6d144ec89657.jpg)

**Comment by revoxhere** [comment]
XD

**Comment by haxorcitoz** [comment]
Well i got only XD respons.
I think we all here wants to support you in this so called "project" but when looking at your respons its show that you not serious in the "project".
Me and the other here are supporting you. We test your code, we post the problem, we buy hardware, even buy your coin to support you but after all what iv've got only XD?
Why i talking like this?
Because i serious following this "project". I spent my time to buy hardware, setting rig and even modify the code to make it suitable for my need.
I'm not hoping to get rich from this coin as you said in the website, but i like when the code is running smoothly, i like when the kolka drop following the rule that you make and see the coin is increasing in the wallet. Just as simple as that.
But the respons i got only XD.
Its really dissapointing.
Or just me taking this so seriously??
Well, idk.

**Comment by finnie2006** [comment]
This is just a starter coin to learn crypto, if you want to earn money then just go

**Comment by haxorcitoz** [comment]
I think you dont read all of my comment and even read i think you dont understand what i mean

**Comment by finnie2006** [comment]
Yes, you are whining that the developer is doing everything wrong, and that you think you are not mining enough coins, and if you know better than to make a PR

**Comment by haxorcitoz** [comment]
Just read again my comment and make a careful understanding.
Please read it carefully before judging.

You can see my wallet in the screenshot.
See ho much i have the coin.
If i only care about money, why i wasting my time to mining this coin?
I have money to buy, just buy it.
But why i complain so much today?
Because the attitude.
He is the main developer of this project.
If he doesnt know then where is this project would go?
And the way he answer just like someone who doesnt have any respect.
You are dealing with people from various country around the world and its been the consequences to you that you will be contacted with various persons around the world.
Show some respect

**Comment by revoxhere** [comment]
Yes, you're taking it too seriously. It's clearly stated that, at least for now, it's a for fun project only that I'm focusing on in my limited free time. It gets overwhelming when people reach out to me on private chats for something that's not about me 

> Well i got only XD respons.
> I think we all here wants to support you in this so called "project" but when looking at your respons its show that you not serious in the "project".
> Me and the other here are supporting you. We test your code, we post the problem, we buy hardware, even buy your coin to support you but after all what iv've got only XD?
> Why i talking like this?
> Because i serious following this "project". I spent my time to buy hardware, setting rig and even modify the code to make it suitable for my need.
> I'm not hoping to get rich from this coin as you said in the website, but i like when the code is running smoothly, i like when the kolka drop following the rule that you make and see the coin is increasing in the wallet. Just as simple as that.
> But the respons i got only XD.
> Its really dissapointing.
> Or just me taking this so seriously??
> Well, idk.

**Comment by haxorcitoz** [comment]
Please forgive me revox for bothering you, really sorry for contacting you too much and dont respect your time. But one thing that you must consider. After seeing many many people reporting issue to your duino github page i see some enthusiasm from people who follow your project. Please keep this spirit on by maintaining this project more serious so it can be more excellent in the future.
For people who think i do this only for the money, this is centralized coin wright?
Go ahead take down my account and drawn all of my coin.
There is 140.000 coin in my account.
Take it, it's yours.

Oh one thing reminder for you revox, please take care of the attitude.
Maybe it's not important to you but it's mean a lot for me or maybe for people from another country.

Hope this project will be great in the future.

Yours faithfully, haxorcitoz
