### ISSUE TITLE
Libducohash COULD NOT be loaded... 

### ISSUE THREAD

**Issue by JamesHFredPH** [duino-coin/duino-coin#1280]
I am NOT SURE if this should be under a "Bug Report", but since this is a NEW Install and this issue is coming up it seems reasonable...)

1)  NEW Install of Raspbian OS Buster for a Raspberry Pi 4 on Blank SD Card.
2)  Install the Duco PC_Miner.py v3.x onto the New Install.
3)  Ran the PC_Miner.py without a Config File to create a New Config File.
     (Technically "Settings.cfg" File...)
     
     Ran Using cmdline:  python3 PC_Miner.py

When the PC_Miner.py starts it show this message:

      Fasthash accelerations are not available for your OS.
		If you wish to compile them for your system, visit:
		https://github.com/revoxhere/duino-coin/wiki/How-to-compile-fasthash-accelerations
		(Libducohash couldn't be loaded: libpython3.9.so.1.0: cannot open shared object file: No such file or directory)

Does the Libcudohash REQUIRE Bullseye?

OR

Is there something else I need to install first?

**Comment by revoxhere** [comment]
You didn't install the latest python3-dev package. Just follow what it says, that's what this message is for

**Comment by JamesHFredPH** [comment]
So the way I read that Message it says "I need to Compile" the for My One System?
(Which wasn't the case for the Bullseye Based System, or the Dietpi64 Buster system?)

I will try...

**Comment by JamesHFredPH** [comment]
Thanks for the Quick Response.

That fixed it.

Works Great...

HUGE Improvement on RPi-4.  (Of course, you are are aware of that...)
