### ISSUE TITLE
Launching PC_Miner.py on ARMv7l (Orange Pi PC)

### ISSUE THREAD

**Issue by Rusich1980** [duino-coin/duino-coin#1281]
I can't launching PC_Miner.py on ARMv7l (Orange Pi PC).

For a long time I tried unsuccessfully to run a program on an Orange PC_Miner.py . I kept popping up various Python errors. 
Today I discovered, quite by accident, that my processor on the Orange is x32 ARMv7l. And the file PC_Miner.py designed for the x64 version of ARM. I attach the report from the terminal below.

root@orangepipc:/# ./PC_Miner
bash: ./PC_Miner: cannot execute binary file: Exec format error
root@orangepipc:/# file ./PC_Miner
./PC_Miner: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=2658c04de63e2fdc0fce25e3d835af099253bb9c, for GNU/Linux 2.6.32, stripped
root@orangepipc:/# uname -m
armv7l

My configuration:
 - Orangepipc_2.1.0_ubuntu_xenial_server_linux3.4.113
 - PC_Miner.py
 - 3.0

How do I run this file on my Orange? Is it possible that you will need to cross-compile this file from sources? How to do it correctly?

**Comment by revoxhere** [comment]
As it says in the getting started guide you probably didn't read, you need to launch from source.
