### ISSUE TITLE
Reset password from Web-Wallet

### ISSUE THREAD

**Issue by Rusich1980** [duino-coin/duino-coin#1282]
Hi! I accidentally changed my wallet password somehow. Now I can't log in. Is it possible for administrators to reset the password so that I generate a new one? I am ready to pass all the checks from the admins to confirm my wallet.
![Duco-coin web wallet](https://user-images.githubusercontent.com/96376519/150830702-83f19f47-b94d-42ce-a9ca-6afef3e4786c.PNG)

**Comment by francescoproprioio** [comment]
Do you mean for uplexa android wallet? I don't use it anymore and I can't
answer you.
The password or the seed phrase. In the case of seed phrase the wallet in
lost, you can't recover it.

Il lun 24 gen 2022, 18:10 Rusich1980 ***@***.***> ha scritto:

**Comment by Rusich1980** [comment]
Good evening! I mean the lost password from Duino-Coin Web-Wallet. There are not so many coins in my account, but I would not like to start a new wallet, and lose these coins. Can anyone tell me how to change the password?

**Comment by LDarki** [comment]
Hi, now you can recovery your Private key.

Go to [The Wallet](https://wallet.duinocoin.com/).
And click this button.
![image](https://user-images.githubusercontent.com/51938450/151511724-eee81774-bc0e-4958-ab60-7632f7228520.png)

I hope this helps you.,
