### ISSUE TITLE
ESP unable to connect, PI unable to connect.

### ISSUE THREAD

**Issue by jumper-d-1981** [duino-coin/duino-coin#1315]
Noticed today my two little miners are unable to establish a connection.  Just curious if something changed or went wrong.  To test, I tried fresh code, and redownloaded tools and started from scratch with same outcome.  Verified my network is fine, just wondering.

**Comment by LDarki** [comment]
Hi, We have servers issues now, you can notice it on [Discord](https://discord.gg/SqZRwAse).

**Comment by DreamC2008** [comment]
3:37:55.473 -> Core 0 is waiting for the poolpicker...
23:37:55.751 -> Core 1 is waiting for the poolpicker...
23:37:55.797 -> Poolpicker selected the best mining node: dutch-pool-1
23:38:00.506 -> 
23:38:00.506 -> 
23:38:00.506 -> Core 0 is connecting to the Duino-Coin server...
23:38:00.646 -> Core 0 has connected to the server
23:38:00.739 -> 
23:38:00.739 -> 
23:38:00.739 -> Core 1 is connecting to the Duino-Coin server...
23:38:03.526 -> Core 1 has connected to the server
23:38:18.518 -> Core 0 received server version: v
23:38:19.030 -> Core 0 is not connected - restarting...
23:38:19.030 -> 
23:38:19.030 -> 
23:38:19.030 -> Core 0 is connecting to the Duino-Coin server...
23:38:19.543 -> Core 1 received server version: v
23:38:20.055 -> Core 1 is not connected - restarting...
23:38:20.055 -> 
23:38:20.055 -> 
23:38:20.055 -> Core 1 is connecting to the Duino-Coin server...
23:38:20.103 -> Core 1 has connected to the server
23:38:22.016 -> Core 0 failed to connect
23:38:22.526 -> 
23:38:22.526 -> 
23:38:22.526 -> Core 0 is connecting to the Duino-Coin server...
23:38:23.271 -> Core 0 has connected to the server
What is the reason, no miner connects

**Comment by LDarki** [comment]
Hi, can i close this issue?
Because this problem was solved yesterday.

**Comment by jumper-d-1981** [comment]
absolutely.  You are awesome!



William Dobbins195 Greenwood LaneChloe, WV 25235home: 304-655-7442
cell: 304-532-8803 

    On Friday, January 28, 2022, 04:51:27 PM EST, LDarki ***@***.***> wrote:  
 
 


Hi, can i close this issue?
Because this problem was solved yesterday.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LDarki** [comment]
Ty ❤️
