### ISSUE TITLE
Sent bscDUCO almost a week ago, still not received.

### ISSUE THREAD

**Issue by Osmodia666** [duino-coin/duino-coin#1319]
Hi,
I sent some coins usually to my external Wallet, like I did often. But I am waiting for almost a week now, still no coins arrived.
Did not change anything, worked fine until now.
Address, Recipent, is the same. I did not change anything.

This Transaction was ok:
https://explorer.duinocoin.com/?search=e422077363ecd33322c5686d46d408dfc794d685

The last one not?:
https://explorer.duinocoin.com/?search=c7983cc7fec0fd7246b04ce47bef788d06d19663

**Comment by ygboucherk** [comment]
Sounds like transaction wasnt correctly scanned - checking server/daemon

**Comment by Grantrocks** [comment]
I tried the same thin I had 44 duco sent 30 to my wallet never recieved and just sent 3 and still no recieved. It just says no internal server error.

**Comment by ygboucherk** [comment]
"no internal server error" ? How did you send them ? From DUCO webwallet ?

**Comment by ygboucherk** [comment]
Are u the guy that unwrapped to a BSC address (instead of doing a normal transfer) ? I had to manually cancel your "unwrap" because wrapper loop-tried sending funds for like one whole week !

**Comment by Grantrocks** [comment]
I sent from web wallet using the instructions here. I sent to address bscDUCO and made the message the binance smart chain address and I used metamask.

**Comment by Grantrocks** [comment]
I also used android duco wallet and same thing happened. Made sure that used the right address and used the right duino coin wallet. Both web and arduino wallet throw same error.

**Comment by Grantrocks** [comment]
Sorry looks like I never wrapped it to duco I tried to send via DUCO.

**Comment by javier45689** [comment]
Hello, a week ago I sent 500 DUCO to my metamask account (I sent 500 because it is the minimum from now) But I sent them on 02/13/2022 and on 02/18/2022 they still have not arrived
This is the transaction         https://explorer.duinocoin.com/?search=e11ea24007f12428da2dfe17e5fb98e571d860d6

**Comment by ygboucherk** [comment]
@javier45689 technically fee is also 500 DUCO.
Basically you just paid fee

**Comment by javier45689** [comment]
And when I withdraw my duino again, will I have to pay again, or would the commission already be paid? for the next withdrawals
Thank you

**Comment by ygboucherk** [comment]
It was for this transaction. Best I can do is sending DUCO from my own wallet :D

**Comment by ygboucherk** [comment]
Sent you 500 DUCO - https://explorer.duinocoin.com/?search=d4c36f37bae38ab3c1efc8b26a6cf11f8a0c5ba2

**Comment by ygboucherk** [comment]
Ah btw @javier45689 plz dont say "withdraw my duino".
bscDUCO is a wrap (a bit like binance-pegs on bsc) of DUCO (which is the underlying chain), and only take it as a kind of exchange !

**Comment by Osmodia666** [comment]
Oh, btw I am still waiting for a reply or a Solution for my Issue and where my 1000 DUCO went. 
Any help would be appreciated.

**Comment by ygboucherk** [comment]
@Osmodia666 when did you wrap these 1000 DUCO ?

**Comment by Osmodia666** [comment]
> @Osmodia666 when did you wrap these 1000 DUCO ?

Why should I have wrapped it? I sent it on January 25th. There was no news or announcement that I should wrap it before sending. I sent a few thousand bscDUCO like this already and it worked great. 
The only Announcement which provides info about wrapping and the 500 DUCO Fee, came on Febuary 1st. How should this affect my transaction which I made a week earlier?

**Comment by ygboucherk** [comment]
Ah sry I meant sending (I call it wrapping). Btw please send your DUCO
username (so I can send you these 1k DUCO back)

Le dim. 20 févr. 2022 à 14:34, Osmodia666 ***@***.***> a
écrit :

**Comment by Osmodia666** [comment]
Username is Osmodia.
Thx.

**Comment by LDarki** [comment]
Hi, this is solved?

Tell me if i can close this issue.

**Comment by Osmodia666** [comment]
Sorry, no unfortunately not. I am still waiting for the 1000 Duco.

**Comment by LDarki** [comment]
I'll send you those ducos. and I'll close this issue.
Ty.
