### ISSUE TITLE
ESP8266 (Named HW-628) WDT

### ISSUE THREAD

**Issue by Xordata** [duino-coin/duino-coin#1320]
PCB mark "HW-628"
After running 
<<<Serial log>>>>
Connecting to the Duino-Coin server...
Connected to the server. Server version: 
Asking for a new job for user: xordata
Received a correct job with size of 1 bytes

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (29):
epc1=0x402429cb epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000019 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffac0 end: 3fffffc0 offset: 0190
3ffffc50:  0000004c 4023ed07 00000018 00000000  
3ffffc60:  3ffffc80 40242b07 3ffed8b0 40246d08  
3ffffc70:  40251dee 00000000 0000000b 00000000  
.....
3fffffa0:  3fffdad0 00000000 3ffef0c0 4021373c  
3fffffb0:  feefeffe feefeffe 3ffe85e0 40101021  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

To solve this problem in "void loop() {" modify from 
---------------------------
    if (max_micros_elapsed(micros(), 500000))
      handleSystemEvents();
---------------------------
to
---------------------------
    if (max_micros_elapsed(micros(), 500000))
      handleSystemEvents();
    else
      delay(0); // <- This allow to WDT reset to proceed WIFI events ....
---------------------------

**Comment by revoxhere** [comment]
Can you submit a PR?

**Comment by LDarki** [comment]
Merged.
I`ll close this issue
