### ISSUE TITLE
Why this erorr

### ISSUE THREAD

**Issue by abhinav596** [duino-coin/duino-coin#1321]
![IMG_20220130_140418_1](https://user-images.githubusercontent.com/75115166/151692702-7df3beca-075d-4283-8b0c-c59b72d73971.jpg)
![IMG_20220130_140415](https://user-images.githubusercontent.com/75115166/151692707-58548ef3-eaad-4e2f-a3d0-ea3ebbbe7fa5.jpg)

**Comment by abhinav596** [comment]
@revoxhere @naphob @njsoly @ricardofiorani @ProtoThis

**Comment by LDarki** [comment]
Hi, acording to the [issue 1318](https://github.com/revoxhere/duino-coin/issues/1318) image.
You have too much ping connecting to the server
![image](https://user-images.githubusercontent.com/51938450/151696133-22d62626-dd61-4dc6-95d1-f3efdb7cce03.png)
This is not a easy problem to solve.

The possible reasons are:
```c
- Your firewall blocks the server ip
- You have any proxy or vpn

-------------------
You can try :
- Disabling your firewall or adding a rule for prevent the block.
- Refreshing your dns.

Windows: ipconfig /flushdns

Mac:  lookupd -flushcache
In new versions (10.5 ahead): dscacheutil -flushcache

Linux: /etc/rc.d/init.d/nscd restart
```

**Comment by abhinav596** [comment]
Is this becauce i created a duino account to my sister with same ip if yes can i do anything

**Comment by LDarki** [comment]
This is a connection problem, you have too much ping.

**Comment by abhinav596** [comment]
@LDarki so what can i do for it

**Comment by abhinav596** [comment]
But when i use a vpn i can visithttps://server.duinocoin.com/getPool but when i dont it dosent load

**Comment by LDarki** [comment]
Maybe you´re ip-banned.

try opening the windows cmd (win + r then type cmd and hit enter)
and use this command:
```
tracert server.duinocoin.com
```
wait until finished. 
And when it finish, send me a screenshot of the output (if you can do it on Direct Message, or send it here but censor ips)

**Comment by abhinav596** [comment]
![IMG_20220130_200043](https://user-images.githubusercontent.com/75115166/151704006-dd9efc9d-a795-448a-b5f9-493b5298c1c7.jpg)

**Comment by abhinav596** [comment]
@LDarki 
![IMG_20220130_200321](https://user-images.githubusercontent.com/75115166/151704372-b087fb69-8d67-4132-b369-1036b56c0f4f.jpg)

**Comment by LDarki** [comment]
I think that you´re ip-banned. i´ll remove that msg because anyone can see your ip 😂

**Comment by abhinav596** [comment]
@LDarki  so what can i do for that

**Comment by LDarki** [comment]
If you´re ip-banned i cant do anything.
Send a mail to [duino.coin@gmail.com](mailto:duino.coin@gmail.com)

**Comment by abhinav596** [comment]
What should i send to duino.coin@gmail.com

**Comment by abhinav596** [comment]
@LDarki is this ok
![IMG_20220130_204532](https://user-images.githubusercontent.com/75115166/151705618-ad00e6e9-55e0-4709-ba92-3c327239a4a8.jpg)

**Comment by LDarki** [comment]
Ask if you`re ip-banned.

**Comment by abhinav596** [comment]
What about this
![IMG_20220130_205812](https://user-images.githubusercontent.com/75115166/151706069-557f408f-19ed-49d6-bf16-107680f02a3b.jpg)
