### ISSUE TITLE
Raspberry Pi seem detected has a PC miner

### ISSUE THREAD

**Issue by pierrealexaline** [duino-coin/duino-coin#1336]
Hello there, before all thanx for your work, I think there's a little bug with the 3.0 version, the rpi (model A+, 3 and 4) are always classified has a PC (i know it is) with the difficulty and goal average reduced by the kolka algorithm. It's seem to be not clearly detected has a RPI. When i try to mine with a real PC i have the same performances in DUCO product. Can you confirm it's a bug or not ? many thanks !

**Comment by revoxhere** [comment]
This is the correct behavior. Raspberry Pis are just small PCs.
