### ISSUE TITLE
ESP8266 esp-01 module wont mine

### ISSUE THREAD

**Issue by Grantrocks** [duino-coin/duino-coin#1338]
I keep trying to mine with my esp8266 esp-01 but nothing pops up. I can successfully flash the esp8266 but after i open the serial monitor and it wont show anything. I have the right port and settings set but still nothing. Everything is wired right as i was able to upload the code but it wont do anything.

**Comment by LDarki** [comment]
Hi, you can send me a screenshot of your arduino ide tools tab ?
And if you can, send me the baudrate of the serial console and the Serial.begin code line

**Comment by Grantrocks** [comment]
![Screenshot 2022-02-04 23:01:40](https://user-images.githubusercontent.com/46384149/152627968-951afb88-b99c-4274-a1ea-5200336db150.png)
![Screenshot 2022-02-04 23:04:07](https://user-images.githubusercontent.com/46384149/152628017-32a3d06c-7e91-4d07-8f3b-7849c0a4d806.png)
![Screenshot 2022-02-04 23:05:37](https://user-images.githubusercontent.com/46384149/152628063-b2389843-80d2-4af4-8f27-a32bee2d8a48.png)

Baudrate is 500000

**Comment by Grantrocks** [comment]
wait nvm i had gpio0 connected to ground. sorry

**Comment by LDarki** [comment]
No problem. So i can close this issue ?
