### ISSUE TITLE
New Miner Rewards System

### ISSUE THREAD

**Issue by geneReeves** [duino-coin/duino-coin#1342]
Duco Coin Miner Thread Registration Proposal

    Purpose:
    method to track miner thread counts and
    help prevent cheats (aka fake miners) and 
    improve reward system for future growth.

    As part of user verification, have them 
    choose/enter a miner count for each hard-
    ware type with which they intend to mine
    with. 
    For non-verified users, establish
    some low count limits for each hardware
    type, which should help to encourage 
    users to verify there account/setups.

    Source Code:
    In the Main Server code, have it store
    and manage the user miner counts as part
    of the normal user account data management.

    In the Pool Server code, have it store and
    manage a live miner thread id list with miner thread
    counts per user and hardware type and enforcing
    limits based off info from accounts synced from 
    main server. This miner thread id list can be
    garbage collected every 30 or 60 sec. for any
    miner threads that have not been seen since last
    GC cycle. List can also be cleaned of any thread
    id's when an app owning those id's reconnects.

    In client miner app, have app log into pool 
    server with username and password to link mining
    app to user, then have miner app call registration 
    function for each mining thread it's wanting to 
    start, receiving a unique miner_thread_id for each
    registered thread. Then each thread started will 
    use it's unique id when connecting to the pool 
    server to request mining jobs/return results..

    The miner_thread_id should be dynamically generated
    based off username, miner hardware type and dependent
    upon hardware type, a unique hardware signature and 
    registered thread count for user/type.
    thus helping to prevent fake or hacked miners.    

    This should improve over all network/mining as
    it should eliminate issues with miner apps and
    or rewards earned thus reducing the need to 
    punish the dedicated people that apply there
    hard earned resource to the Duino-Coin world
    with a reward system that cuts rewards based
    on device counts of recommended mining device
    types.

    The Duino-Coin establishment should embrace those
    individuals that wish to devote there time, 
    effort and physical hardware to said establishment 
    instead of punishing them with the convoluted 
    reward system referred to as Kolka, which based
    on the public history, does not appear to be 
    either very effective at stopping fake miners
    or creating happy Duino-Coin miner populations.

    Duino-Coin could easily reach into the IoT
    space, i.e. smart wall switches, smart wall 
    plugs, smart power strips, smart coffee pots,
    wireless temperature/environment sensors, etc
    which could make Duino-Coin one of the most 
    popular in the world. With the sear number of
    homes being built today with fully IoT enable
    devices (lights, fans, window blinds) spread 
    through out. How popular would Duino-Coin be
    if most New Homes came with smart switches/
    plugs/fans/blinds/etc with builtin Duino-Coin
    mining thread.   Duino-Coin would be HUGE.
    But it is my humble opinion, that the use of
    Kolka for the rewards system complete kills
    this future possibility.

    Please consider the above proposal as a first step towards dropping Kolka.

    Thank You,
    Gene Reeves
    02/05/2022

**Comment by revoxhere** [comment]
> first step towards dropping Kolka.
XDD
