### ISSUE TITLE
too many miners, low kolka efficifancy

### ISSUE THREAD

**Issue by MuppetMikey** [duino-coin/duino-coin#1343]
i am getting a red x blinking on my wallet when i float over it , it saays too many miners, low kolka effiacency.. i am completly new to raspberry pi and programing.. is there some way to limit the cores used on the pi3b to fix this error, or whats the solution to the problem, understanding i am like a 5 year old, and need clear instructions..

pi3b runnning the lastest raspian build .. i have 2 of these mining along with a pi4b as well, but i have no issues with the 4b
  other then the error on the wallet showing, the miners seem to be running just fine

**Comment by LDarki** [comment]
Hi, can you tell me your duco username?
I need to see your account.

And maybe you have too much miners active.

**Comment by MuppetMikey** [comment]
MuppetMikeyWallet

**Comment by MuppetMikey** [comment]
i have 3 seperate pi's mining.. total of 12 cores .. 2 pi 3b's and a pi4b

**Comment by LDarki** [comment]
Yeah i can see it, you have too much hashrate.

Because this crypto is not designed to be mined with PC (raspberry count as one)
you can`t get the same profit as some user with 2 arduinos.

And kolka gives a penalty (less reward) when you have too many workers or too much hashrate.

You can ignore that warning (using this button)
![image](https://user-images.githubusercontent.com/51938450/152666524-f4b8fe56-d0ca-4bfd-8238-93cba08673a4.png)
but isn`t the best.

![image](https://user-images.githubusercontent.com/51938450/152666505-525d26ce-523a-40db-95b9-bf8c777bc734.png)

**Comment by MuppetMikey** [comment]
so would shutting down one of the miners improve everything over all?.. i
kind of just stumbled onto doing this, thought i would do some experiments
with the 3 pis i have sitting here. but if its better to run two ill do
that..

**Comment by LDarki** [comment]
You can do whatever you want.

You can see in the next image a table of the kolka penalty
![image](https://user-images.githubusercontent.com/51938450/152666806-440592a0-64bd-400b-8d37-77a69d9750e8.png)

Tell me if i can close this issue.

**Comment by MuppetMikey** [comment]
i know this is kind of a useless coin and mining it is just for fun, but
where do you see this going over all?

**Comment by LDarki** [comment]
Well, this coin isn`t useless, you can use it for learn about crypto and avr.
And in some time we can have a better price.

You can read the [whitepaper](https://github.com/revoxhere/duino-coin/blob/gh-pages/assets/whitepaper.pdf) if you want, there is more info about this crypto. (note that the whitepaper is not updated)

**Comment by MuppetMikey** [comment]
sorry i didnt mean useless,  im learning and thats cool.. ment more the
price of it at this point.. i will read  the whitepaper, thanks for the link

**Comment by LDarki** [comment]
No problem, i`ll close this issue (because i think that now its fine).

If you want tell me and i will re-open the issue.

**Comment by MuppetMikey** [comment]
close it.. appreciate your help..
