### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by MikeGR97** [duino-coin/duino-coin#1353]
Mined through a program on a PC on an unverified account for about 10 minutes. Initially, I did not quite understand whether it needed to be verified. it was only about the device. At the moment, as I understand it, the account is blocked((( I would like to restore access to it ...
Also, I can't open this link https://server.duinocoin.com/verify.html, as well as log into my account and mining on this account has stopped working. I understand that blocking by ip.

**Comment by LDarki** [comment]
Hi, you`re still facing this issue? i need more info.

**Comment by MikeGR97** [comment]
> Hi, you`re still facing this issue? i need more info.

At the moment everything is working. Thank you.

**Comment by LDarki** [comment]
No problem, i`ll close this issue.
