### ISSUE TITLE
unverified account

### ISSUE THREAD

**Issue by psiakrew** [duino-coin/duino-coin#1354]
I don't know what happened, but after some recent problems with your servers, I got an in my web wallet. Although I have verified my account before
 ![ddd](https://user-images.githubusercontent.com/98645719/153625153-e3a79a26-12d3-40d3-a352-32490699f91f.jpg)

**Comment by Grantrocks** [comment]
same here but just re verify.
________________________________
From: psiakrew ***@***.***>
Sent: Friday, February 11, 2022 10:01 AM
To: revoxhere/duino-coin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [revoxhere/duino-coin] unverified account (Issue #1354)


I don't know what happened, but after some recent problems with your servers, I got an in my web wallet. Although I have verified my account before
[ddd]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F98645719%2F153625153-e3a79a26-12d3-40d3-a352-32490699f91f.jpg&data=04%7C01%7C%7C579b247862c343065afa08d9ed77b762%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637801920697768086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=87cHme7IOst8lgy%2B64PlRUgZgco7FY%2BSTxAnMlJnXa4%3D&reserved=0>

**Comment by psiakrew** [comment]
> same here but just re verify.

Why do I have to go through verification again if it's not my fault?

**Comment by Grantrocks** [comment]
maybe just some server error
________________________________

**Comment by birrozza** [comment]
I have the same problem. I redid the verification, I also received the confirmation email, but my account still remains in the unverified state. 
Thanks

**Comment by LDarki** [comment]
Hi, i can`t tell a permanent fix for this guys.
Re-send the verification request.

Maybe its a bug of the bot that we use for the verification.

**Comment by birrozza** [comment]
I re-send  the verification request, but  return ` No user found with that e-mail`
