### ISSUE TITLE
Help-how can I have my PC miner Config Mod on my respberrypi 3

### ISSUE THREAD

**Issue by darrellhendershot** [duino-coin/duino-coin#1381]
Dear All,

Thank you for your help. I do test the miner on my pi zero w. I put the pi zero TF card in a Pi 3 and run my miner.

![image](https://user-images.githubusercontent.com/92722456/155080393-ab439c2e-48f2-4201-8178-2ee559fe33ce.png)

You can refer to the picture, PI3 use only one core of CPU for mining( that's zero's config)

How can I go back to the first step when I start mining I can put how many cores will be used for mining.

Thanks

**Comment by GameOneDev** [comment]
remove folder "Duino-Coin PC Miner"

**Comment by darrellhendershot** [comment]
> remove folder "Duino-Coin PC Miner"

then, download the miner again and re-start?

**Comment by GameOneDev** [comment]
Just remove folder and start PC_Miner(and you must have first setup again)

**Comment by TheArtistPT** [comment]
Basta ir a pasta duino-coin / PCMiner/ e Apagas o ficheiro Config. e ai abres o pcMiner.py e  voltas a por tudo! não te esqueças que quanto mais baixo o hasrate melhor para minerar duino

**Comment by LDarki** [comment]
Hi, i can close this issue?
Looks like its solved.

**Comment by darrellhendershot** [comment]
> Basta ir a pasta duino-coin / PCMiner/ e Apagas o ficheiro Config. e ai abres o pcMiner.py e voltas a por tudo! não te esqueças que quanto mais baixo o hasrate melhor para minerar duino

Just go to the duino-coin / PCMiner/ folder and delete the Config file. And then you open the pcMiner. You'll put it all back on! don't forget that the lower the hashrate the better to mine duino

**Comment by darrellhendershot** [comment]
> Hi, i can close this issue? Looks like its solved.

Yes, thank you for your help, guys!
