### ISSUE TITLE
Can I run my own miner on 8051?

### ISSUE THREAD

**Issue by alan-student** [duino-coin/duino-coin#1382]
Hey Guys,

I am a MCU learner. And I found this fantastic project which is partly based on MCU.
Here is my question. I wonder if it is legal to develop my own code and run it on 8051 MCU to mine the DUCO? 
And do so kind everyone have any wonderful tips for my beginner?

**Comment by LDarki** [comment]
Hi, If you use the correct difficulty there is no problem.

![image](https://user-images.githubusercontent.com/51938450/155604047-c6cf2d6a-b3d6-4773-80ea-7c9da6bb52e9.png)
Tell me if i can close this issue.

**Comment by LDarki** [comment]
No response, i'll close this issue
