### ISSUE TITLE
mainnet

### ISSUE THREAD

**Issue by ra1n08** [duino-coin/duino-coin#1383]
does duino-coin have mainnet
or token 
i want to import DUCO to metamask wallet

**Comment by LDarki** [comment]
Hi, you have the [BSCDuco Wrapper](https://bsc.duinocoin.com).

**Comment by ra1n08** [comment]
how i swap DUCO to bscduco

**Comment by LDarki** [comment]
You can use the Wrap section on the website or do it manually( [Follow this tutorial](https://github.com/revoxhere/duino-coin/wiki/bscDUCO-Tutorial) )
PD: You have 500 ducos of fee doing this, so try to make the transfer of more than 500 ducos

**Comment by ra1n08** [comment]
thanks :>>
