### ISSUE TITLE
The mined with the program DuinoCoinEthernetMiner does not appear on the page https://wallet.duinocoin.com

### ISSUE THREAD

**Issue by roggarmar** [duino-coin/duino-coin#1385]
**Describe the bug**
A clear and concise description of what the bug is:
The mining dos not appear on https://wallet.duinocoin.com

**To Reproduce**
1. Go to program mentioned above
2. I have kept the values of 30 and 31 unchanged because they are suitable for my local network
3. Click on line 34 and put {51.15.127.80} //IP of server.duinocoin.com 
4. Scroll down to line 38 and type "roggarmar" //my username
5.Type en line 39  = "AVR Miner"

**Expected behavior**
 I expected see the mining in the url https://wallet.duinocoin.com in which the mining does appear when the Arduino Mega card is used alone.
The green LED of the RJ45 connector is on steadily and the yellow one is flashing, to the beat of the data traffic.

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.
On the other hand, in the system console, the host has been pinged, verifying that the address assigned in the sketch is correct, but the waiting time expires, without result.
![image](https://user-images.githubusercontent.com/100074575/155516796-7823b0fc-4a88-4248-802b-7e3cf066fee9.png)

**System (please complete the following information):**
 - OS: [Windows 10]
 - Software [DuinoCoinEthernetMiner]
 

**Additional context**

**Comment by LDarki** [comment]
![image](https://user-images.githubusercontent.com/51938450/155612999-85aab7ac-0bdd-4659-bd15-fd9b7593904b.png)

Hi, try with a pool ip instead of the master server one.
For example: 
```
51.159.175.20
```

**Comment by roggarmar** [comment]
The suggested IP (51.159.175.20) is placed on line 38 instead of the server.
When verifying, the errors shown in the attached screenshot appear.
![Captura](https://user-images.githubusercontent.com/100074575/155706940-3e1d68c0-db81-41e1-9a3f-ba999f3e8e85.PNG)

**Comment by LDarki** [comment]
You need to change the port too:

```c
51.159.175.20:6043

byte pool[] = {51,159,175,20};
unsigned short port = 6043;
```

**Comment by roggarmar** [comment]
First of all, thank you very much for the interest and speed of your response.
I have added the line
unsigned short port = 6043;
and the compilation has been successful.
However, it is still not possible to see the mining via ethernet in the wallet.duinocoin where the one carried out by usb and PC is reflected.

**Comment by LDarki** [comment]
First of all, No problem.
In the serial monitor you can see any error ?

Edit: Uncomment the line 8

**Comment by roggarmar** [comment]
Next Monday I will open the serial monitor. In the meantime, I wish you a happy weekend.

**Comment by roggarmar** [comment]
Hi, enabling the serial monitor (uncomment line 8), I get malfunction messages like the one reproduced here

![2](https://user-images.githubusercontent.com/100074575/155897634-08b7b6b2-bb95-406e-8209-8a6124e93a14.PNG)

and also corrects, like the one shown,

![5](https://user-images.githubusercontent.com/100074575/155897653-1d60c9f1-1e1c-4976-ab68-2b8cbc99bc48.PNG)

in a proportion, variable with time, of one and the other. 

In any case, the existence of mining via Ethernet finally appears in the wallet, however with a question mark.

   ![image](https://user-images.githubusercontent.com/100074575/155897945-b4873272-7cdd-4c5e-a6e4-1fd892044529.png)
  
   
   ![image](https://user-images.githubusercontent.com/100074575/155897986-726d6ee6-e72c-4cd3-90e7-1c8c6af61d40.png)


In spite of, a disconcerting fact occurs because, by **blocking the serial monitor again**, **the AVR Ethernet mining PERMANENTLY DISAPPEARS from the wallet page.**

Mining in the wallet is only detected when the serial monitor is disabled and **the provided pool** address is used.
If the IP of the duinocoin master server is used, it does not work in either of the two ways.

**Comment by LDarki** [comment]
Hi, if i'm not mistaken the master server ip doesn't longer work.
Just mine using a pool ip.

Make a issue on [This repostory](https://github.com/Pumafron/DuinoCoinEthernetMiner).

Now appears to be a issue of the miner.

Tell me if i can close this issue.

**Comment by roggarmar** [comment]
This issue can be closed, for my part. Thank you so much for everything.

In any case, in my opinion, the fact that **the program works only when the serial monitor is activated**, would make it advisable to revise it.
I also think that it would be desirable to have a **list of the IPs of the pools to mine DUCOS**, which I do not know where it can be found because it does not appear in the searches I have carried out on the Internet.

**Comment by revoxhere** [comment]
The best pool can be selected with the getPool endpoint. All official miners use it. 
https://server.duinocoin.com/getPool
