### ISSUE TITLE
Windows Zip Flagged as Trojan? 

### ISSUE THREAD

**Issue by S3ntiantai** [duino-coin/duino-coin#1387]
I was going to start mining with some ESP32 i got in the mail a few days ago.
Downloaded the Zip file for Windows after install it flagged the file as a Sever Trojan?

I have Read online that within GitHub this happens, I was hoping to see someone within this Repository to have mentioned having a similar issue, But alas i have not.

Anyone have any idea?  ill post the screenshot I took.

Cheers! 
![Trojan Duino (2)](https://user-images.githubusercontent.com/88412609/155926405-ae9743bf-d7d0-4611-9bd3-b6ec43405274.png)

Windows 10 OS
I had Arduino IDE Open And Spotify

**Comment by LDarki** [comment]
Hi, windows defender detects any miner software as trojan or malware.

**Comment by blazecoding2009** [comment]
Yeah, don't worry, it's not a trogan

**Comment by S3ntiantai** [comment]
word ok i thought so

**Comment by S3ntiantai** [comment]
Thanks
