### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by MechanicApollo** [duino-coin/duino-coin#1389]
Hello, I've been trying to solve this problem for 3 days, can anyone help?

root@chip:~/duino-coin# python3 PC_Miner.py
  File "PC_Miner.py", line 313
    pretty_print(f"Warning: {response['message']}")
                                                 ^
SyntaxError: invalid syntax
root@chip:~/duino-coin#

**Comment by revoxhere** [comment]
You're using python 3.6 or lower. Duino requires 3.7 minimum
