### ISSUE TITLE
Start mining DUCOs automatically on Raspberry boot

### ISSUE THREAD

**Issue by roggarmar** [duino-coin/duino-coin#1401]
The equipment works perfectly but every time the mains fails, it is necessary to **open the terminal, change to the "duino-coin" subdirectory and type "python3 PC_Miner.py"** to launch the official miner.

It would be very interesting if, when the sector returned, **mining would start again** -as happens with the Arduino- without the cumbersome human participation that requires the connection of a mouse and a screen.

Wouldn't it be possible to **incorporate this operation into the Rasp boot**?
I've tried in many different ways (five) but I can't get it due to my poor domain of programming.

(*) The configuration of the Raspberry is done following the procedure indicated in  **https://duinocoin.com/getting-started**.

**Comment by revoxhere** [comment]
This can be achieved with rc.local, bashrc, systemd or other services.
I prefer crontab - see https://dansinclair25.medium.com/duino-coin-mining-on-a-raspberry-pi-180bad964b1b
