### ISSUE TITLE
recent git pull produces error now when running 'python3 PC_Miner.py' on Rpi

### ISSUE THREAD

**Issue by esp220221** [duino-coin/duino-coin#1403]
**Describe the bug**
just ran a git pull on the duino-coin directory.  Updates downloaded and applied.  When attempting to run 'python3 PC_Miner.py' I now receive the following error:  

pi@rpi301:~/duino-coin $ python3 PC_Miner.py
module 'psutil' has no attribute 'Process'

**Comment by revoxhere** [comment]
try `python3 -m pip install --ignore-installed psutil`

**Comment by esp220221** [comment]
Thanks @revoxhere That worked like a champ!!  Appreciate the quick response!!
