### ISSUE TITLE
does not see the library (Crypto.h). please give me a link to download the library

### ISSUE THREAD

**Issue by bog378** [duino-coin/duino-coin#1408]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by revoxhere** [comment]
You didn't provide any info, how are we supposed to help?

**Comment by bog378** [comment]
please help me find and install the library

**Comment by bog378** [comment]
Arduino: 1.8.13 (Windows 7), Плата:"Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"





















ESP8266_Code:37:10: fatal error: Crypto.h: No such file or directory

 #include <Crypto.h>  // experimental SHA1 crypto library

          ^~~~~~~~~~

compilation terminated.

Несколько библиотек найдено для "ArduinoJson.h"

 Используется: C:\Users\User\Documents\Arduino\libraries\ArduinoJson

Не используется: C:\Users\User\Documents\Arduino\libraries\ArduinoJson-6.x

exit status 1

Crypto.h: No such file or directory

Неверная библиотека найдена в C:\Users\User\Documents\Arduino\libraries\avrdude: нет заголовочных файлов (.h), найденных в C:\Users\User\Documents\Arduino\libraries\avrdude



Этот отчёт будет иметь больше информации с
включенной опцией Файл -> Настройки ->
"Показать подробный вывод во время компиляции"

**Comment by revoxhere** [comment]
You're compiling code designed for ESP8266 on an Arduino Mega board. How do you expect it to work?

**Comment by bog378** [comment]
sorry for the unnecessary worry, the mistake is stupid)))

**Comment by bog378** [comment]
Arduino: 1.8.13 (Windows 7), Плата:"LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"





















ESP8266_Code:51:20: error: 'MGTS_GPON_AA0F' was not declared in this scope

   51 | const char* SSID = MGTS_GPON_AA0F;

      |                    ^~~~~~~~~~~~~~

ESP8266_Code:53:24: error: unable to find numeric literal operator 'operator""CUE36A'

   53 | const char* PASSWORD = 77CUE36A;

      |                        ^~~~~~~~

ESP8266_Code:55:24: error: 'Bog' was not declared in this scope; did you mean 'log'?

   55 | const char* USERNAME = Bog;

      |                        ^~~

      |                        log

Несколько библиотек найдено для "ArduinoJson.h"

 Используется: C:\Users\User\Documents\Arduino\libraries\ArduinoJson

Не используется: C:\Users\User\Documents\Arduino\libraries\ArduinoJson-6.x

exit status 1

'MGTS_GPON_AA0F' was not declared in this scope



Этот отчёт будет иметь больше информации с
включенной опцией Файл -> Настройки ->
"Показать подробный вывод во время компиляции"
but there is a new one

**Comment by revoxhere** [comment]
It clearly says that you need to put variables INSIDE the double quotes, not remove them

**Comment by bog378** [comment]
I don't speak English

**Comment by revoxhere** [comment]
That's not something we should be focused on, don't you think? 😄
