### ISSUE TITLE
Delete my account 

### ISSUE THREAD

**Issue by Lanthi** [duino-coin/duino-coin#1410]
**Is your feature request related to a problem? Please describe.**
Hello, I have a problem, I had an account with the username "Lanthi" and it tells me that my account does not exist. I've been talking to LDarki and he says he doesn't know what could have happened.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LDarki** [comment]
Solved in discord. 
I'll close this issue.
