### ISSUE TITLE
Esp8266 can't work 

### ISSUE THREAD

**Issue by darrellhendershot** [duino-coin/duino-coin#1412]
**Describe the bug**
can't connect to pool

**To Reproduce**
I keep trying to mine with my esp8266 CH430G but nothing pops up. 
I can successfully flash the esp8266 but after I open the serial monitor it show me like below picture, can anyone help me solve it,

Thanks

**Expected behavior**
log:

10:41:39.844 -> Duino-Coin 3.1
10:41:39.844 -> Connecting to: GG&LL
10:42:40.345 -> ....
10:45:50.407 -> 
10:45:50.407 -> nSuccessfully connected to WiFi
10:45:50.407 -> Local IP address: 169.254.139.157
10:45:50.407 -> Rig name: ESP001
10:45:50.407 -> 
10:45:50.407 -> Fetching mining node from the poolpicker in 1s
10:45:50.407 -> Error fetching node from poolpicker: connection failed
10:45:51.383 -> Fetching mining node from the poolpicker in 2s
10:45:51.383 -> Error fetching node from poolpicker: connection failed
10:45:53.388 -> Fetching mining node from the poolpicker in 4s
10:45:53.388 -> Error fetching node from poolpicker: connection failed
10:45:57.393 -> Fetching mining node from the poolpicker in 8s
10:45:57.393 -> Error fetching node from poolpicker: connection failed
10:46:05.424 -> Fetching mining node from the poolpicker in 16s
10:46:05.424 -> Error fetching node from poolpicker: connection failed
10:46:21.387 -> Fetching mining node from the poolpicker in 32s
10:46:21.387 -> Error fetching node from poolpicker: connection failed

**Screenshots/photos**
![image](https://user-images.githubusercontent.com/92722456/158645263-2bb70de0-c076-4ee7-9363-b079d9871356.png)

**System (please complete the following information):**
 - OS: [Windows 10]
 - Software [Adrino IED 1.8.57.0]
 - Version [3.1]

**Additional context**

**Comment by darrellhendershot** [comment]
@LDarki @revoxhere  can Boss help me with this issue? Thanks

**Comment by vmo64** [comment]
are your network creds ok?

**Comment by LDarki** [comment]
Hi, are you still facing this issue ?

**Comment by LDarki** [comment]
No Response.
I'll close this issue.

**Comment by darrellhendershot** [comment]
> No Response. I'll close this issue.

yes，still facing it, can't work
