### ISSUE TITLE
Unable to mine on Ubuntu 20.04

### ISSUE THREAD

**Issue by JoshAtticus** [duino-coin/duino-coin#1413]
**Describe the bug**
Mining doesn't work on Ubuntu 20.04

**To Reproduce**
1. Open files
2. Rename PC_Miner to PC_Miner.py (normal PC_Miner doesn't work either)
3. Open directory in terminal
4. Type `python3 PC_Miner.py`

**Expected behavior**
It should show me the setup

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: Ubuntu 20.04.4
 - Software PC Miner
 - Version 3.0

**Additional context**

**Comment by revoxhere** [comment]
You didn't provide any context, how are we supposed to help?

**Comment by darrellhendershot** [comment]
> You didn't provide any context, how are we supposed to help?



> You didn't provide any context, how are we supposed to help?

Hi Boss, can you please check my issue? Thanks!

https://github.com/revoxhere/duino-coin/issues/1412#issue-1171295422

**Comment by darrellhendershot** [comment]
> You didn't provide any context, how are we supposed to help?

Hi Boss, can you please check my issue? Thanks!

https://github.com/revoxhere/duino-coin/issues/1412#issue-1171295422      @revoxhere

**Comment by darrellhendershot** [comment]
> You didn't provide any context, how are we supposed to help?

Hi Boss, can you please check my issue? Thanks! @revoxhere 

https://github.com/revoxhere/duino-coin/issues/1412#issue-1171295422

**Comment by JoshAtticus** [comment]
> You didn't provide any context, how are we supposed to help?

I didn't see that part, I also have no idea what info I need to share

**Comment by JoshAtticus** [comment]
Here is a video of what happens: https://youtu.be/nVfTHccCJ_A

**Comment by JK-Rolling** [comment]
`python3 -m pip install psutil` or use the latest requirements.txt `python3 -m pip install -r requirements.txt`. get it from https://github.com/revoxhere/duino-coin/blob/master/requirements.txt

**Comment by JoshAtticus** [comment]
This happens

joshatticus@joshatticus-laptop:~$ python3 -m pip install psutil
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/psutil/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/psutil/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/psutil/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/psutil/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/psutil/
Could not fetch URL https://pypi.org/simple/psutil/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/psutil/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))) - skipping
ERROR: Could not find a version that satisfies the requirement psutil (from versions: none)
ERROR: No matching distribution found for psutil

I will try on my home network instead when I get home

**Comment by JoshAtticus** [comment]
> This happens
> 
> joshatticus@joshatticus-laptop:~$ python3 -m pip install psutil WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/psutil/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/psutil/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/psutil/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/psutil/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/psutil/ Could not fetch URL https://pypi.org/simple/psutil/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/psutil/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))) - skipping ERROR: Could not find a version that satisfies the requirement psutil (from versions: none) ERROR: No matching distribution found for psutil
> 
> I will try on my home network instead when I get home

The error has been fixed, and I can now mine on my laptop, thanks to @JK-Rolling for helping.
