### ISSUE TITLE
'latin-1 codec can't encode character '\u2016' in position 11: ordinal not in range(256)

### ISSUE THREAD

**Issue by identd113** [duino-coin/duino-coin#1415]
**Describe the bug**
After going through the config setup, the following stack is seen:

`pi@pi:~/duino-coin $ python3 PC_Miner.py 
The Miner is up to date
Traceback (most recent call last):
  File "/home/pi/duino-coin/PC_Miner.py", line 1224, in <module>
    Miner.greeting()
  File "/home/pi/duino-coin/PC_Miner.py", line 679, in greeting
    print("\n" + Style.DIM + Fore.YELLOW + Settings.BLOCK + Fore.YELLOW
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2016' in position 11: ordinal not in range(256)`

**To Reproduce**
Download, via the raspi instructions
Config setup works
When we go to start mining, error is seen

**Expected behavior**
I would expect to follow the instructions, and have a miner up and running

**Screenshots/photos**

**System (please complete the following information):**
 - OS: Linux pi 5.10.103-v8+ #1530 SMP PREEMPT Tue Mar 8 13:06:35 GMT 2022 aarch64 GNU/Linux
 - Software PC_Miner.py
 - Version 3? (Nost up to date)

**Additional context**
I had this working for a while, but reimaged by pi, and have been stuck since.

`pi@pi:~/duino-coin $ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=en_US`

**Comment by LDarki** [comment]
Try deleting the config folder and run the miner again.

**Comment by identd113** [comment]
I have deleted the  ~/duino-coin folder, and reinstalled, and have the same issue

**Comment by identd113** [comment]
In line 679 seems to have a unicode character that is kicking a fuss.  \u2016, which is "Double Vertical Line", or ‖

**Comment by LDarki** [comment]
Oh yeah that issue.

I'll make a commit.
Try with [this fix](https://github.com/revoxhere/duino-coin/commit/ed805679810867de4e586f7393bad722ce373c97).

**Comment by identd113** [comment]
Any idea why my system is identifying it self with a Latin char set

**Comment by identd113** [comment]
Now...

23:14:05  sys0  Using fasthash hashing accelerations
Error checking mining key: option values must be strings
Traceback (most recent call last):
  File "/home/pi/duino-coin/PC_Miner.py", line 1236, in <module>
    Donate.start(int(user_settings["donate"]))
  File "/home/pi/duino-coin/PC_Miner.py", line 452, in start
    pretty_print(get_string('thanks_donation').replace("\n", "\n\t\t"),
  File "/home/pi/duino-coin/PC_Miner.py", line 543, in pretty_print
    print(Fore.WHITE + datetime.now().strftime(Style.DIM + "%H:%M:%S ")
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 83-84: ordinal not in range(256)

**Comment by identd113** [comment]
I resolved this by setting the following:
export PYTHONIOENCODING=utf8
I believe this only persists in that terminal session

**Comment by LDarki** [comment]
This is a issue with the encoding.

The last error is a issue of the mining key.
But i need to know the characters of the string for fixing it.

Tell me if i can close this issue.

**Comment by identd113** [comment]
Issue still exists, but I have a workaround in place

**Comment by LDarki** [comment]
Try adding this line 
sys.stdout.reconfigure(encoding='utf-8')
after the import sys line

**Comment by identd113** [comment]
As a note, the mining string is null(return when asked)
