### ISSUE TITLE
No return of staking deposit

### ISSUE THREAD

**Issue by Lanthi** [duino-coin/duino-coin#1420]
**Is your feature request related to a problem? Please describe.**
I have not received my 1000 ducos staking deposit, which I made on 03/07/2022 at 00:55:49. Transaction https://explorer.duinocoin.com/?search=bce36434681d03c92c0b4cd27555c796c7506c67
My account was affected with corrupted server files a week ago. 

**Describe the solution you'd like**
Deposit refund xD

**Describe alternatives you've considered**
Leave them in deposit 14 days

**Additional context**
When I receive it, I will deposit all my ducos :p

**Comment by Mariusz696** [comment]
I have the same problem

https://explorer.duinocoin.com/?search=07679c41d267b68f457a0e02c2baa8abe00227be
