### ISSUE TITLE
Segmentation fault after compiling fasthash accelerations

### ISSUE THREAD

**Issue by madmax1970** [duino-coin/duino-coin#1424]
On a fresh RPI 4 install, I followed the instructions on installing the fasthash accelerations:

https://github.com/revoxhere/duino-coin/wiki/How-to-compile-fasthash-accelerations 

I encountered no errors, except for the latin-1 errors which I fixed with adding 

sys.stdout.reconfigure(encoding='utf-8')

before the import sys line in PC_Miner.py

However, it came with another error which I can't figure out:

 â Official Duino-Coin Â© Python Miner (3.0) 2019-2021
 â https://github.com/revoxhere/duino-coin
 â CPU: 1x ARMv7 Processor rev 3 (v7l)
 â Developer donation level: 0
 â Algorithm: DUCO-S1 â Low diff
 â Rig identifier: madmaxrpifast
 â Have a wonderful morning,

**Segmentation fault**

**Comment by LDarki** [comment]
Hi, you're still facing this issue ?
