### ISSUE TITLE
Closed COM port in AVR Miner

### ISSUE THREAD

**Issue by Sukwolite** [duino-coin/duino-coin#1425]
**Describe the bug**
When starting the miner writes Closed COM port

**Screenshots/photos**
![Снимок экрана (95)](https://user-images.githubusercontent.com/102432040/160269002-8845def1-8880-4810-b393-f3dfda8969cd.png)
r-images.githubusercontent.com/102432040/160252465-869fcaa6-72cb-4965-8485-591053765e0a.png)

**System (please comple
te the following information):**
 - OS:  Windows
 - Software: AVR Miner
 - Version: 3.0
 - Printed circuit board: NodeMCU-32s

**Comment by randevry** [comment]
Maybe this will help somehow
![Снимок экрана (95)](https://user-images.githubusercontent.com/102432040/160268977-556ead8a-e7cc-401e-b3b4-cfba4d5993b8.png)

**Comment by revoxhere** [comment]
You said you're using a NodeMCU board. They have wifi capabilities and run standalone, there's no need for the AVR miner. Just make sure you're using the correct code

**Comment by Sukwolite** [comment]
> Вы сказали, что используете плату NodeMCU. Они имеют возможности Wi-Fi и работают автономно, майнер AVR не нужен. Просто убедитесь, что вы используете правильный код

Thank you!

**Comment by Gab-26** [comment]
Good day, NANO 3 Atmega168 not working 
![Untitled](https://user-images.githubusercontent.com/109011009/178130392-1efde453-d6fd-49a1-8576-88e44945510f.png)

**Comment by Gab-26** [comment]
Good day! NANO v3 Atmega168, can it be in duco mining

![Untitled](https://user-images.githubusercontent.com/109011009/178130722-e02748f9-9b7a-4224-b11d-bcf3604e41bb.png)

**Comment by Gab-26** [comment]
Good day! not working NANO v3 Atmega168, can it be used in duco mining?

![Untitled](https://user-images.githubusercontent.com/109011009/178130895-e4c6b36b-bfd2-458c-8aa2-0e11201d4bc5.png)

**Comment by GerardoNevarez** [comment]
open a different issue or ask on Discord, it is a terrible practice to add comments to a totally unrelated, closed issue.
