### ISSUE TITLE
Exposing the user's password in plain text

### ISSUE THREAD

**Issue by Leonaldt** [duino-coin/duino-coin#1426]
When I click on the send coins button, fill in all the information and confirm, the endpoint (https://server.duinocoin.com/transaction/?username=USER-NAME&password=PASSWORD-EXPOSE&recipient=bscDUCO&amount=14&memo=WALLET) which is called in this action shows the user's password in plain text. This is a very serious bug and needs to be fixed soon!

**Comment by Leonaldt** [comment]
I just tested here and the problem still persists @revoxhere

**Comment by Leonaldt** [comment]
This happens when I transfer bscDUCO to Metamask

**Comment by Leonaldt** [comment]
I want to know how this could be happening, and I only see one reason, the user's password is not being encrypted before saving to the bank, or the password is being saved in plain text or with a two-way encryption, which is very bad for both cases.

**Comment by Leonaldt** [comment]
Don't get me wrong, I'm a developer and I just want to help improve the project.

**Comment by KaffinPX** [comment]
They dont care about project i think.

**Comment by LDarki** [comment]
Hi, if you want implement a fix for this.

**Comment by Leonaldt** [comment]
Yes I can, I just need to clone the master branch project and submeter the fix right?

**Comment by Leonaldt** [comment]
This is my first experience with an open source project

**Comment by Leonaldt** [comment]
In this case, it is enough for the password to be encrypted using one-way encryption and to compare the hash of the password in data base with the password to be able to send coins, but another way is to release this endpoint without asking for a password, it is an authentication token when the person login into the wallet and then sends this token in the request and the api validates the token and releases the transaction without manipulating the user's password.
