### ISSUE TITLE
Duco transfer to Metamask is coming back

### ISSUE THREAD

**Issue by Leonaldt** [duino-coin/duino-coin#1427]
When I try to send coins to metamask, the balance sent, however soon after it is returned to my wallet.
![Screenshot from 2022-03-27 20-46-59](https://user-images.githubusercontent.com/32653110/160309029-ac919fd8-7e39-41ee-af7a-002be542988b.png)

**Comment by LDarki** [comment]
Hi, for bscDUCO you have a fee of 500 ducos, if you send less you get a refund.
If you send exactly 500 ducos you don't receive anything.
