### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thinkCreat3** [duino-coin/duino-coin#1428]
‖ Official Duino-Coin © Python Miner (3.1) 2019-2022                                                ‖ https://github.com/revoxhere/duino-coin         ‖ CPU: 2x Intel(R) Xeon(R) CPU @ 2.20GHz          ‖ Developer donation level: 1                     ‖ Algorithm: DUCO-S1 ⚙ Medium diff                ‖ Have a wonderful morning, one_two_tree!                                                          02:29:28  sys0  Downloading fasthash accelerations module                                           02:29:30  sys0  Fasthash accelerations are not available for your OS.                                               If you wish to compile them for your system, visit:                                                 https://github.com/revoxhere/duino-coin/wiki/How-to-compile-fasthash-accelerations                  (Libducohash couldn't be loaded: libpython3.8.so.1.0: cannot open shared object file: No such file or directory)                      Config saved! Launching the miner                 Traceback (most recent call last):                  File "PC_Miner.py", line 1242, in <module>          Donate.load(int(user_settings["donate"]))       File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__                                  raise KeyError(key)                           KeyError: 'donate'

~/duino-coin# python3 PC_Miner.py                 The Miner is up to date                           Traceback (most recent call last):                  File "PC_Miner.py", line 1232, in <module>          Miner.greeting()                                File "PC_Miner.py", line 671, in greeting           if user_settings["start_diff"] == "LOW":        File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__                                  raise KeyError(key)                           KeyError: 'start_diff'

**Comment by Jakobi304** [comment]
Had the same problem on Raspberry Pi. Compiling fasthash solved it for me. But the AVR_Miner is still not working

**Comment by LDarki** [comment]
Hi guys, you're still facing this issue ?

**Comment by SykikXO** [comment]
I am facing the same issue. Plz help
