### ISSUE TITLE
Convert DUCO to USD

### ISSUE THREAD

**Issue by realrecordzLab** [duino-coin/duino-coin#1433]
I'm mining DUCO but I'm not able to understand a simple thing: how I can withdraw them? I want to convert them into usd but I'm unable to find a valid solution. Can anyone explain to me what is thebest approach and the best exchange website?

**Comment by LDarki** [comment]
Hi, you can use the oct-trading channel in [our discord](https://discord.gg/Q2WPkNe4) if you want trade DUCO for FIAT.

Or you can wrap them into [bscDUCO](https://github.com/revoxhere/duino-coin/wiki/bscDUCO-Tutorial) or [wDUCO](https://github.com/revoxhere/duino-coin/wiki/wDUCO-tutorial) and swap them for other currency like BUSD  (Binance USD).
