### ISSUE TITLE
High Difficulty

### ISSUE THREAD

**Issue by MashiatIliastheeditor** [duino-coin/duino-coin#1434]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by LDarki** [comment]
????

**Comment by BastelPichi** [comment]
Hello,
Can you describe what your problem is or close the issue?
