### ISSUE TITLE
account stopped earnign awards

### ISSUE THREAD

**Issue by RobMitt** [duino-coin/duino-coin#1435]
it seems that my account stopped earning awards some time ago.  To make matter worse it appears that I am still mining but not getting rewarded at all for it.  I have requested verification twice since December. Still shows unverified.  I just attempted a third verification and it says no user exist
<img width="605" alt="Screen Shot 2022-04-05 at 6 19 00 PM" src="https://user-images.githubusercontent.com/95778903/161860254-b7273260-295e-47bd-82fc-98764b5e4fd2.png">
s with that email.  Please advise.

**Comment by LDarki** [comment]
Hi, can you send your wallet username ?

**Comment by RobMitt** [comment]
Hi Darki, 

Waller Username RobMitt

I restarted my miners yesterday and it appears that they are earning.  But for I don't know how many weeks I was mining with no rewards. Probable since late January.

**Comment by LDarki** [comment]
Hi, right now you're earning ducos.

You can't send a new verify request ?
Send me the verification picture and i'll verify you :)

**Comment by RobMitt** [comment]
Now that I restarted miners I can see that, 

Am I out of luck for the time I've been mining with no rewards?

Verify requests keep getting rejected.  Here is the picture"

**Comment by LDarki** [comment]
I mean, send me the picture of your miners with your username in paper.
So i can verify you manually.

**Comment by RobMitt** [comment]
Her it is...I replied through email on that last one so the pic didn't go through.  

![tempImage42c10i](https://user-images.githubusercontent.com/95778903/161953686-194ee8c6-97e8-4b2c-8d5c-aa6973e4aad3.gif)

**Comment by RobMitt** [comment]
Verification came though, Thank you!

**Comment by LDarki** [comment]
You're welcome, Tell me if i can close this issue ❤️

**Comment by RobMitt** [comment]
The only thing left is the question of not receiving rewards even though all miners have been running at 100%.   Is there any record of shares mined vs. rewards given?

**Comment by LDarki** [comment]
![image](https://user-images.githubusercontent.com/51938450/162037955-773f3fca-2a97-41f2-ab7b-1a12eca5fb0d.png)
I see that you're earning ducos.

Maybe the Daily Profit is bugged.

**Comment by RobMitt** [comment]
I only started earning yesterday after I rebooted my rig.   I had a good 6+ weeks without earning but erveyhtign a runing, mining hashes at 100%

**Comment by LDarki** [comment]
Ok that's weird, i'll give you some ducos.
Edit: 
Sorry about that.
[Transaction ID](https://explorer.duinocoin.com/?search=2b9879cb8b18ea35b503a0e01c6cb967e31f1bf5)
Tell me if i can close this issue ❤️

**Comment by RobMitt** [comment]
Ok, thank for all the help!  I think we can close this out.

**Comment by RobMitt** [comment]
‌

Confirm your subscription

[Yes, I want to subscribe](https://manage.kmail-lists.com/subscriptions/subscribed?opt=da28ea6eeecad027fce67b9888897bb4)

If you didn't subscribe to this list or you're not sure why you received this email, you can delete it. You will not be subscribed if you don't click on the link above.

 

If you have any questions, you can reply to this email.

**Comment by RobMitt** [comment]
‌

Confirm your subscription

[Yes, I want to subscribe](https://manage.kmail-lists.com/subscriptions/subscribed?opt=29b2a741449dcebee46e8ca26de34a10)

If you didn't subscribe to this list or you're not sure why you received this email, you can delete it. You will not be subscribed if you don't click on the link above.

 

If you have any questions, you can reply to this email.

**Comment by RobMitt** [comment]
‌

Confirm your subscription

[Yes, I want to subscribe](https://manage.kmail-lists.com/subscriptions/subscribed?opt=82bd7ee2d5ced37864d449c6aa40dfb0)

If you didn't subscribe to this list or you're not sure why you received this email, you can delete it. You will not be subscribed if you don't click on the link above.

 

If you have any questions, you can reply to this email.

**Comment by RobMitt** [comment]
‌

Confirm your subscription

[Yes, I want to subscribe](https://manage.kmail-lists.com/subscriptions/subscribed?opt=f9b71bf8773b730c08d1a1a35850c5dc)

If you didn't subscribe to this list or you're not sure why you received this email, you can delete it. You will not be subscribed if you don't click on the link above.

 

If you have any questions, you can reply to this email.
