### ISSUE TITLE
verification error

### ISSUE THREAD

**Issue by sufii112233sufii** [duino-coin/duino-coin#1436]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sufii112233sufii** [comment]
verification error

**Comment by sufii112233sufii** [comment]
![Uploading Screenshot (1).png…]()

**Comment by BastelPichi** [comment]
Hello,
The screenshot somehow isnt uploaded. Could you try again?
