### ISSUE TITLE
PC Miner Difficulty

### ISSUE THREAD

**Issue by MashiatIliastheeditor** [duino-coin/duino-coin#1442]
Everytime saying that incorrect difficulty in PC miner

**Comment by LDarki** [comment]
Hi, you're still facing this issue?

Can you post more info ? At least i need the hashrate and the difficulty that you're using.

**Comment by MashiatIliastheeditor** [comment]
Yes I'm still facing this problem. My hashrate is 1 to 2 mh/s per thread and I'm using Medium difficulty

**Comment by MashiatIliastheeditor** [comment]
Amm It's fixed Thanks

**Comment by MashiatIliastheeditor** [comment]
f
