### ISSUE TITLE
serial monitor issue

### ISSUE THREAD

**Issue by stefanobettipro** [duino-coin/duino-coin#1443]
Hi, I need some help to play the code on ESP 32 Wrover B. As you can see the upload seem to went good but at the end I was non able to connect the serial monitor to the ESP property...

  
![image](https://user-images.githubusercontent.com/73939631/163133107-6a63b432-d653-4e96-a10e-4af42e5e8b7c.png)

> Lo sketch usa 1043877 byte (79%) dello spazio disponibile per i programmi. Il massimo è 1310720 byte.
>   Le variabili globali usano 45596 byte (13%) di memoria dinamica, lasciando altri 282084 byte liberi per le variabili locali. Il massimo è 327680 byte.
>   esptool.py v3.3
>   Serial port COM11
>   Connecting......
>   Chip is ESP32-D0WD (revision 1)
>   Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
>   Crystal is 40MHz
>   MAC: 84:0d:8e:d4:14:ac
>   Uploading stub...
>   Running stub...
>   Stub running...
>   Changing baud rate to 512000
>   Changed.
>   Configuring flash size...
>   Flash will be erased from 0x0000e000 to 0x0000ffff...
>   Flash will be erased from 0x00001000 to 0x00005fff...
>   Flash will be erased from 0x00010000 to 0x00110fff...
>   Flash will be erased from 0x00008000 to 0x00008fff...
>   Compressed 8192 bytes to 47...
>   Writing at 0x0000e000... (100 %)
>   Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 659.7 kbit/s)...
>   Hash of data verified.
>   Compressed 18560 bytes to 12759...
>   Writing at 0x00001000... (100 %)
>   Wrote 18560 bytes (12759 compressed) at 0x00001000 in 0.6 seconds (effective 254.5 kbit/s)...
>   Hash of data verified.
>   Compressed 1049648 bytes to 672896...
>   Writing at 0x00010000... (2 %)
>   Writing at 0x0001c6a9... (4 %)
>   Writing at 0x00027b28... (7 %)
>   Writing at 0x000333fa... (9 %)
>   Writing at 0x0003ea9d... (11 %)
>   Writing at 0x000447a6... (14 %)
>   Writing at 0x0004a606... (16 %)
>   Writing at 0x0005063f... (19 %)
>   Writing at 0x00055be1... (21 %)
>   Writing at 0x0005abc9... (23 %)
>   Writing at 0x0005ff9f... (26 %)
>   Writing at 0x00065733... (28 %)
>   Writing at 0x0006aad9... (30 %)
>   Writing at 0x0006fc86... (33 %)
>   Writing at 0x00075100... (35 %)
>   Writing at 0x0007a3e2... (38 %)
>   Writing at 0x0007f62a... (40 %)
>   Writing at 0x00084a81... (42 %)
>   Writing at 0x00089fbc... (45 %)
>   Writing at 0x0008fdfb... (47 %)
>   Writing at 0x000962a2... (50 %)
>   Writing at 0x0009bfa6... (52 %)
>   Writing at 0x000a11f0... (54 %)
>   Writing at 0x000a6dee... (57 %)
>   Writing at 0x000ac393... (59 %)
>   Writing at 0x000b1797... (61 %)
>   Writing at 0x000b6bdc... (64 %)
>   Writing at 0x000bbe04... (66 %)
>   Writing at 0x000c11dd... (69 %)
>   Writing at 0x000c669d... (71 %)
>   Writing at 0x000cbd2e... (73 %)
>   Writing at 0x000d15aa... (76 %)
>   Writing at 0x000d7413... (78 %)
>   Writing at 0x000dce59... (80 %)
>   Writing at 0x000e5be7... (83 %)
>   Writing at 0x000eecad... (85 %)
>   Writing at 0x000f411d... (88 %)
>   Writing at 0x000f9a83... (90 %)
>   Writing at 0x000ff0b6... (92 %)
>   Writing at 0x00104e90... (95 %)
>   Writing at 0x0010a19e... (97 %)
>   Writing at 0x0010fdae... (100 %)
>   Wrote 1049648 bytes (672896 compressed) at 0x00010000 in 15.9 seconds (effective 529.8 kbit/s)...
>   Hash of data verified.
>   Compressed 3072 bytes to 128...
>   Writing at 0x00008000... (100 %)
>   Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.1 seconds (effective 396.5 kbit/s)...
>   Hash of data verified.
>   
>   Leaving...
>   Hard resetting via RTS pin...

**Comment by LDarki** [comment]
Hi, sorry for the late response.
What do you mean with "i was not able to connect the serial monitor to the ESP property... "

You see some error, or maybe you see dots ?
Can you send more info ?.

**Comment by stefanobettipro** [comment]
Hi, LDarki, thank you for your response, in the meantime I was able to solve the problem by myselfe sympli reinstalling the Arduino IDE, someting whas wrong with the monitor itself (the window did not appear al all).

**Comment by stefanobettipro** [comment]
thank you anyway

s.
