### ISSUE TITLE
No miners detected

### ISSUE THREAD

**Issue by stefanobettipro** [duino-coin/duino-coin#1445]
Hi, I'm an absolute beginner and I was able two days ago to start the miner in my ESP32 and it run until then, I believe, but as you can see from the image the web wallet did not recognize any miners... is ther any trick I did not understand from the guide?

![image](https://user-images.githubusercontent.com/73939631/163348876-70f6b0d1-0dae-4245-a67b-2f362bf58d29.png)

**Comment by MashiatIliastheeditor** [comment]
yes i'm also facing this problem

**Comment by revoxhere** [comment]
Make sure you entered a correct mining key in your miners

**Comment by MashiatIliastheeditor** [comment]
I'm 100% sure that I have gave correct mining key

**Comment by eagle275** [comment]
I had a similar problem - when creating the account I chose to leave mining-key empty .. Which then lead to errors using the current AVR_miner.py - after several tries and at my wits end I simply set a mining-key in the wallet and entered that mining-key when asked by AVR and PC miners and it works

**Comment by mkursadulusoy** [comment]
Try writing None to your mining key
