### ISSUE TITLE
ESP8266 not mining

### ISSUE THREAD

**Issue by manicz** [duino-coin/duino-coin#1446]
![image](https://user-images.githubusercontent.com/84632569/163682330-24829860-ddfd-4bc3-a38c-f0d09e2354df.png)

WHAT happended to this??

**Comment by manicz** [comment]
i just changed the baud rate to 500000

**Comment by achirawi** [comment]
คือ อะไรครับ ตรงๆ เลย ผม ไม่เข้าใจครับ

NOVA MACHINE ,MVS VISION

Achirawit Rhenpatoom
89/14 Moo 3, Suan Phrik Subdistrict, Phra Nakhon Si Ayutthaya District,
Ayutthaya Province  Phra Nakhon Si Ayutthaya 13000
Design & Fabrication of
• -Tumkeys Projects for Automation
• -Automation Systems
•  -Electrical Circuit & Control Panel
• -PLC programming
• -Original Machine Party Precision Jig & Flaturg
•  SENSORS VISION
MEASUREMENT & MICROSCOPES Direct Sales Fast

ในวันที่ ส. 16 เม.ย. 2022 23:02 manicz ***@***.***> เขียนว่า:
