### ISSUE TITLE
duco_api

### ISSUE THREAD

**Issue by IlyaDudelzak** [duino-coin/duino-coin#1471]
I tried using duco_api, but when I run the test program from readme.md, I got an error that the duco_api.api_actions function was not found. What i will do?

**Comment by LDarki** [comment]
Hi, 
![image](https://user-images.githubusercontent.com/51938450/163831399-ca13c48b-e56d-46b5-a6f5-767a03802779.png)

Try using the [pyduinocoin LIB](https://github.com/BackrndSource/pyduinocoin).

**Comment by IlyaDudelzak** [comment]
Thanks.
