### ISSUE TITLE
Not working RP PICO MINNING

### ISSUE THREAD

**Issue by legendar999** [duino-coin/duino-coin#1473]
HI, i get a new pack of raspberry pi's, but unfortunatly i cant mine on them DUINOcoins... I dont know. I'm working by tutorial from YT, but this don't work. So: i started uploading a code on rp pico but the system is typing: something went wrong. Please help me if you can.

PS:
I am using offitial files arduino_code.ino from duino coin.... but it doesent work. Also with my 6 other RP PICO's

#pico #picoMining #error #raspberryPi

![Screenshot_6](https://user-images.githubusercontent.com/78644457/164108078-f9ed1f65-c219-489a-9902-490c5663a5fb.png)

**Comment by LDarki** [comment]
Hi, Check that you have the correct port selected.

**Comment by eagle275** [comment]
Check also that you selected the correct Board - right above the port in the Tools menu

**Comment by LDarki** [comment]
Hi, you're still facing this issue?

**Comment by LDarki** [comment]
No response, i'll close this issue.
