### ISSUE TITLE
Modified Hashrate Detected 

### ISSUE THREAD

**Issue by MashiatIliastheeditor** [duino-coin/duino-coin#1478]
I'm mining with my PC using 3.18 miner it's saying that Kolka 2 Modified Hashrate Detected 
![Screenshot (21)](https://user-images.githubusercontent.com/102611340/164614558-8b7d8ecc-66e2-4b1f-bb85-92a40bf6156c.png)

**Comment by eagle275** [comment]
See that as well on my Raspberry Pi 4 using fasthashing  and on my Raspberry Pi 3 /w fasthashing as well .. 
Surprisingly on the Pi 3 it seems to be allowed , while on the Pi 4 I see "Earnings [(Kolka eff. drop)] 26.21%" which is kinda annoying

**Comment by LDarki** [comment]
Hi, you're still facing this issue?

**Comment by eagle275** [comment]
I still see those messages on my Raspberry Pi4 and Raspberry Pi3 - both run the fasthash lib

**Comment by LDarki** [comment]
Hi, sorry for the late response,
If you're still facing this issue then try mining without fasthash

**Comment by LDarki** [comment]
No response, i'll close this issue

**Comment by Crilum** [comment]
I still get the `Rejected (Kolka 2: modified hashrate detected)` error, on a Pi 3 and a Pi 2, _with_ fasthashing enabled...
