### ISSUE TITLE
Kolka calculation counts miners wrong

### ISSUE THREAD

**Issue by eagle275** [duino-coin/duino-coin#1480]
**Describe the bug**
When I look at the wallet section showing my miners, I see the 4 Pico's running over AVR miner correctly running from 100% down to 88,47 % but my PC miners are strange. I run a Pi4 with 4 threads but 1 miner which should receive 100% - and a pi 3 runing 4 threads which should go to 80% according to the list .. instead the Pi4 gets listed with 64% and the Pi3 with 51% .. so no pc miner is running at 100% efficiency .... 
**To Reproduce**
Just have 4 AVR  threads and 2 PC miners running 4 threads each to one account

**Expected behavior**
First pc miner should be counted 100%, second with 80% according to Kolka list in documentation

**System (please complete the following information):**
 - Raspberry PiOS 
 - AVR Miner, PC Miner
 - current 3.0 (.18)
 -

**Comment by LDarki** [comment]
Because every thread count as 1 miner.

**Comment by eagle275** [comment]
After the recent corrections as described in the news feed, my numbers look way better .. thanks @devs
