### ISSUE TITLE
Bug in Kolka algorytm

### ISSUE THREAD

**Issue by pierrealexaline** [duino-coin/duino-coin#1482]
Hello there, i think there is a big mistake, Bug ? with the kolka algo....I noticed that since a few days, when i look on the wallet side, i can see that :

**Official AVR Miner 3.0 | 28,3 Gh/S | 100%**                                                                                                                   

It's very strange, it's a arduino nano with 28,3 GH/s it's seem enormous just for one nano ??? what do you think about that ??
You can see that on my account : Euskalminer. My ring is composed by :

- 8x nano
- 1Xmega
- 8X esp32 (variable)
- 8x esp8266 (variable)

nano and mega are connected to internet via raspberry pi .....if you need more info please tell me.

**Comment by revoxhere** [comment]
Doesn't look like account "Euskalminer" exists

**Comment by pierrealexaline** [comment]
....I think it does....but it's indicated as non verified (i posted photo with identification on a paper 3 or 4 times without response).... i' indicated to you that i've beginned with 3 account, but i've seen that it is not authorised, i've posted a message about that in the discussion fil, here : https://github.com/revoxhere/duino-coin/discussions/1351 ....my account was verified,....and since a few weeks it's appears that's not ! ...

**Comment by pierrealexaline** [comment]
For proof of what i said : i've made a pull request with french translation with the name of the account "Euskalminer" here :
https://github.com/revoxhere/duino-coin/blob/master/Resources/CLI_Wallet_langs.json
thx for your response and your work !

**Comment by pierrealexaline** [comment]
....for the issue or bug detected....look at the image bellow :
![Capture d’écran_2022-04-25_19-18-50](https://user-images.githubusercontent.com/43777037/165140716-257f5a95-4d77-4a10-a327-da5bed3862e8.png)
 This is a Arduino nano, same has the 3 others !

**Comment by revoxhere** [comment]
Try enabling the mining key, it's possible it's someone else's miner.

**Comment by pierrealexaline** [comment]
ok ....the key is set ....the miners are mining with normal H rate ! perfect ...thx ... Last thing ...how to verify my account ?
![IMG_20220425_195519](https://user-images.githubusercontent.com/43777037/165147475-44d251fe-8b6d-4cad-8076-3bd9f32fc962.jpg)
I've just some esp to relaunch, see the description at the beginning of the discussion....thx
