### ISSUE TITLE
I can't mine with ESP8266

### ISSUE THREAD

**Issue by MashiatIliastheeditor** [duino-coin/duino-coin#1486]
I have uploaded ESP8266 code in my esp board in serial monitor i get some flipped question makes and nothing

**Comment by LDarki** [comment]
Hi, you see some dots in the serial monitor ?  maybe your wifi data is wrong

**Comment by Trickster-git** [comment]
try this terminal 
https://www.compuphase.com/software_termite.htm

**Comment by LDarki** [comment]
Hi, you're still facing this issue?

**Comment by LDarki** [comment]
No response, i'll close this issue.
