### ISSUE TITLE
AVR_miner

### ISSUE THREAD

**Issue by prychortle** [duino-coin/duino-coin#1488]
For some reason, I can't access it as AVR_Miner doesn't work on windows. It keeps getting blocked, what should I do?

**Comment by LDarki** [comment]
Hi, you tried disabling windows defender ?

**Comment by prychortle** [comment]
I can't find it?

**Comment by LDarki** [comment]
Press the windows key and type "Windows Security"
Select the Windows Security app from the search results, go to Virus & threat protection, and under Virus & threat protection settings select Manage settings.
Switch Real-time protection to Off.

**Comment by LDarki** [comment]
Hi, you're still facing this issue?

**Comment by Mercedes-li** [comment]
![unknown](https://user-images.githubusercontent.com/56230475/166703510-32d7e628-4e6c-48c7-832d-1fcd2506cb3a.png)
I get errors like this
