### ISSUE TITLE
what is Duino IOT

### ISSUE THREAD

**Issue by ra1n08** [duino-coin/duino-coin#1489]
i see 1 tab on my dashboard duino-coin this is duino iot and how i use this ?

**Comment by LDarki** [comment]
Hi, Duino IOT allows you to use a temperature (and humidity) sensor with the esp8266 (or esp32) and see it on the web wallet.
![image](https://user-images.githubusercontent.com/51938450/165985080-7baff988-c15b-4069-9fb3-8e34a1bffaae.png)

**Comment by revoxhere** [comment]
It's woth noting that the features for Duino IoT will be expanded to provide more value options in the upcoming week

**Comment by ra1n08** [comment]
thanks @revoxhere for answer :))
