### ISSUE TITLE
No ESP8266-ESP-01 Miner on Web Wallet

### ISSUE THREAD

**Issue by Alabaca** [duino-coin/duino-coin#1494]
I set up this morning an ESP-01, and after all this time there's no miner on the Web Wallet.
All seems to be working fine:

![ESP8266](https://user-images.githubusercontent.com/104778761/166256438-88a60f4c-0bc3-47ce-ac8b-267c5cb40f92.jpg)
![Web Wallet](https://user-images.githubusercontent.com/104778761/166256485-eac18396-afab-4efe-9b38-8f9635ce502f.jpg)

It is normal ???

**Comment by revoxhere** [comment]
Have you entered your mining key to the esp code? If not, why aren't you following the wallet instructions? what's hard there?

**Comment by Alabaca** [comment]
> Have you entered your mining key to the esp code? If not, why aren't you following the wallet instructions? what's hard there?

According to the instructions, there's no need to enter mining key for ESP:
![image](https://user-images.githubusercontent.com/104778761/166258878-ed9a0eec-040d-43f8-90d0-8243de3cea02.png)

I had just fulfill those variables on the code:

![image](https://user-images.githubusercontent.com/104778761/166259268-694e2f9e-e3ef-403e-ba24-c5528c34f19d.png)

**Comment by revoxhere** [comment]
Looks like the instructions are outdated. I'd have updated them, but I always need to wait for a different person to update the website as I don't have access to it. Anyway, what would be the point of not requiring the mining key when it's for security?
Wallet explains that in the setup window.
![image](https://user-images.githubusercontent.com/50244265/166259607-ae00cc28-c2c2-46ba-a2ac-cdd23a2d42a7.png)
