### ISSUE TITLE
Shield DHT11 with ESP8266 ESP-01 Not Reading Sensors

### ISSUE THREAD

**Issue by Alabaca** [duino-coin/duino-coin#1498]
I have just upload the new ESP8266 release, and activate the DHT since I'm using a Shield DHT11 with a ESP-01.
![image](https://user-images.githubusercontent.com/104778761/166746026-73f8bc09-7899-47f1-abf7-75937f1a55ef.png)

My code is like this:
#ifdef USE_DHT
  
  float temp = 0.0;
  float hum = 0.0;
  float temp_weight = 0.9; // 1 for absolute new value, 0-1 for smoothing the new reading with previous value
  float temp_min_value = 10.0;
  float temp_max_value = 40.0;
  float hum_weight = 0.9; // 1 for absolute new value, 0-1 for smoothing the new reading with previous value
  float hum_min_value = 0.1;
  float hum_max_value = 100.0;
    
  // Install "DHT sensor library" if you get an error
  #include <DHT.h>
  // Change D3 to the pin you've connected your sensor to
  #define DHTPIN 2
  // Set DHT11 or DHT22 accordingly
  #define DHTTYPE DHT11
  DHT dht(DHTPIN, DHTTYPE);
#endif

Have no errors compiling and uploading, but the results came Zero from the sensors
![Captura de ecrã 2022-05-04 175708](https://user-images.githubusercontent.com/104778761/166746368-c6d1cc09-77e7-4cf5-a71d-936d6dcd16a3.jpg)
![Captura de ecrã 2022-05-04 175740](https://user-images.githubusercontent.com/104778761/166746377-4b7b4aed-850e-47b9-a9c8-b64df40c7cd4.jpg)

Running a simple skecth using the same configuration on the DHT I can have readings
 
![Captura de ecrã 2022-05-04 180032](https://user-images.githubusercontent.com/104778761/166746645-f6ddbcad-9beb-4b45-a8df-4858138a0553.jpg)

Can this be something related with the code, or some parameters extra for this hardware?

**Comment by revoxhere** [comment]
Reading with a value of 0 may mean there's a connection issue between the ESP and DHT. Check your wiring and pin configuration (maybe 2 should be changed to D2?) I don't really know how the pins are mapped on a basic ESP8266-01 module

**Comment by Alabaca** [comment]
This code works fine, and the hardware is the same. The PIN mapped looks equal to yours...

[ESP8266_DHT11_Web.txt](https://github.com/revoxhere/duino-coin/files/8625641/ESP8266_DHT11_Web.txt)

**Comment by ghost** [comment]
It happens to me too, but I have a NodeMCU and my DHT11 is connected to D4

**Comment by ghost** [comment]
> Reading with a value of 0 may mean there's a connection issue between the ESP and DHT. Check your wiring and pin configuration (maybe 2 should be changed to D2?) I don't really know how the pins are mapped on a basic ESP8266-01 module

I don't think it's a wiring or configuration problem, there has to be something wrong with the code or the server, because I didn't change the wirings from the previous ones

**Comment by lyovav** [comment]
Hi all. I'm not very strong in programming but the output is next

 #ifdef USE_DHT
    float newTemp = dht.readTemperature();
    float newHum = dht.readHumidity();
//    if ((temp >= temp_min_value) && (temp <= temp_max_value)) {
//      if ((newTemp >= temp_min_value) && (newTemp <= temp_max_value)) {
//        temp = temp_weight * newTemp + (1.0f - temp_weight) * temp; // keep weighted measurement value
 //    } else {
        **temp = newTemp; // keep current temp**
 //    }
//    } // else - keep newTemp as is

 //   if ((hum >= hum_min_value) && (hum <= hum_max_value)) {
//     if ((newHum >= hum_min_value) && (newHum <= hum_max_value)) {
//        hum = hum_weight * newHum + (1.0f - hum_weight) * hum; // keep weighted measurement value
//     } else {
        **hum = newHum; // keep current hum**
//      }
//    } // else - keep newHum as is
  #endif


![22](https://user-images.githubusercontent.com/3407229/167256571-c2a3398b-ec48-44b5-a3ec-ef7773ea3217.jpg)
 #define DHTPIN 4 (gpio4 - sda)
  // Set DHT11 or DHT22 accordingly
  #define DHTTYPE DHT22
![photo_2022-05-07_16-34-49](https://user-images.githubusercontent.com/3407229/167256736-010ee08b-4eba-40ce-b27b-882ae58ce24c.jpg)

**Comment by ghost** [comment]
> 

Thanks! This was a very simple fix to be honest 😄

**Comment by LDarki** [comment]
Hi, try using the latest code, in theory it's fixed now.
Tell me if i can close this issue.

❤️

**Comment by lyovav** [comment]
> Hi, try using the latest code, in theory it's fixed now. Tell me if i can close this issue.
> 
> ❤️

Hi. Seems to be working fine.

**Comment by Alabaca** [comment]
Hi,
it really is working now:
![image](https://user-images.githubusercontent.com/104778761/168262880-b555dd91-c8f9-45cf-a7a9-696eeb110d98.png)

But to be honest this ESP performs really slow with the DHT11 module, with very slow mining performance that don´t even appear on the wallet...
Since is the first version of the ESP8266, I will assume that it does not have the power to do both things at the same time, and use it without the DHT11.

Thanks for the effort, and at least it contributes to make some improvements on the code.

For me you can close the issue.
