### ISSUE TITLE
Ability to Stake Coins more than once

### ISSUE THREAD

**Issue by cikaldev** [duino-coin/duino-coin#1505]
**Is your feature request related to a problem? Please describe.**
Halo maintainer, thank you for this great project. but i really miss one feature here, Ability to Stake Coins more than one time.

**Describe the solution you'd like**
`none`

**Describe alternatives you've considered**
`none`

**Additional context**
Stake Coins is great feature here, we can freeze Amount of coins for several time (21 days in this project). But this feature limited to only one time Stake,

**Comment by revoxhere** [comment]
This is intended behavior.
