### ISSUE TITLE
low profit avr, raspberry as host

### ISSUE THREAD

**Issue by NoNameNoCry** [duino-coin/duino-coin#1507]
**Describe the bug**
1 piece avr gets 10-13 ducos
4 pcs avr gets more than 30 ducos
esp 8266 gets 6 ducos.
real reward per day 15 ducos

**To Reproduce**
connect 4 pc arduino nano from usb to raspberry pi
run python3 AVR_Miner.py

**Expected behavior**
Problems with production began after 05/13/2022.

**Screenshots/photos**
![1](https://user-images.githubusercontent.com/104968373/169871595-cb328898-82e9-4d35-85a9-2eda8380f4e9.JPG)
![2](https://user-images.githubusercontent.com/104968373/169871912-a3925ee5-89ec-49aa-8f23-65b1b0e810f5.JPG)
![3](https://user-images.githubusercontent.com/104968373/169872289-42b682ff-326e-45cf-8c8d-1ce45afafe1f.JPG)

**System (please complete the following information):**
 - OS: raspberry pi os lite (32 bite) (Realeased 2022-04-04)
 - Software [e.g. AVR Miner] last version 3.18

**Comment by Grantrocks** [comment]
might be your ping. 600ms is quite high

**Comment by NoNameNoCry** [comment]
@revoxhere Hi. Do you know what the matter?
only avr

![image](https://user-images.githubusercontent.com/104968373/170092067-7f5ce89b-4282-4883-86cf-fb4add97b361.png)

**Comment by Grantrocks** [comment]
try to restart them

**Comment by NoNameNoCry** [comment]
Does not help.  reboot is configured once a day.

**Comment by Grantrocks** [comment]
How are you connecting all of them?

**Comment by Grantrocks** [comment]
Try using one of the 2 usb3.0 ports on the pi.

**Comment by NoNameNoCry** [comment]
Usb hub.
this worked fine until the specified date.  the problem is not mine.  at the moment, production is jumping.  this is not normal

**Comment by Grantrocks** [comment]
So the amount you are earning is jumping all over?

**Comment by NoNameNoCry** [comment]
Yes. Screen up

**Comment by NoNameNoCry** [comment]
![image](https://user-images.githubusercontent.com/104968373/170538039-9567e92e-e5d0-4d21-890c-6564ba64617d.png)
![image](https://user-images.githubusercontent.com/104968373/170538254-7a4dfd0f-c96b-448f-b4db-1c98dc455952.png)
![image](https://user-images.githubusercontent.com/104968373/170540141-57e98d4d-3bd5-43ec-8094-8ef4c53b65ce.png)

**Comment by NoNameNoCry** [comment]
you're right. It's about high ping. How to fix it?)

**Comment by NoNameNoCry** [comment]
![image](https://user-images.githubusercontent.com/104968373/170878743-34212bbe-0fcb-48e6-a436-97d56efa8009.png)
when I configured the ssh authorization key, the ping decreased.
how it works?

**Comment by NoNameNoCry** [comment]
Oh, no
My problem it's not resolved.

**Comment by NoNameNoCry** [comment]
@revoxhere Hi. you can open this issue?)
My problem it's not resolved.

![image](https://user-images.githubusercontent.com/104968373/190904610-7cbd9233-7321-4de0-b09f-80bcf7bc4669.png)

**Comment by revoxhere** [comment]
You're not using official miners.

**Comment by NoNameNoCry** [comment]
@revoxhere  official miners or not official miners
why ping wery hight?)

![image](https://user-images.githubusercontent.com/104968373/190904992-d7269755-4ee8-4498-8340-3f5b478876cf.png)
