### ISSUE TITLE
Multi wifi 

### ISSUE THREAD

**Issue by Cowlcc** [duino-coin/duino-coin#1509]
Is it possible to get a feature for multiple wifi connections feature. So if one wifi connection drops out the esp board will connection to the next wfi ssid available 

I

**Comment by mkursadulusoy** [comment]
Hello. 

As an answer to your question Yes it is possible to write couple wifis but i think tis is not suits for the most people they wont do this.

Also i want to say This is not an issue. Tis is a suggestion. Maybe you can open a topic in discussions.

**Comment by Cowlcc** [comment]
hi
i added some code and i am now able to use multiple wifi connections..

if one drops out the miner will then look for the next connection in the list

thanks anyway
