### ISSUE TITLE
AVR-Miner Rasp. Picos, Raspberry 4 as host

### ISSUE THREAD

**Issue by desktopminertg** [duino-coin/duino-coin#1513]
**Describe the bug**
i upgraded to V3.18, AVR Miner on Raspberry with Pico (Arduino, also new). 
Before the update and with V3 i dont have any rejects. I dont know what to change. Also many Connection errors. 

The mined DC is less then the half as it was with V3

**Screenshots/photos**
![Screenshot 2022-05-31 101924](https://user-images.githubusercontent.com/95868907/171354768-eae6643d-9269-4dff-92df-864de4dcad03.jpg)

**System (please complete the following information):**
 - OS: Raspberry 
 - Software AVR-Miner 
 - Version 3.18

**Comment by k1l0kn4113r** [comment]
Change `#pragma GCC optimize ("-Ofast")` to ` #pragma GCC optimize ("-O0")`

**Comment by desktopminertg** [comment]
> #pragma

ok and where to change it?

**Comment by LDarki** [comment]
Line 18 of the arduino code, 
![image](https://user-images.githubusercontent.com/51938450/171448498-4a50b40c-0ad4-4fb3-a441-3431e64872a2.png)

**Comment by desktopminertg** [comment]
i change it but still the same
![Screenshot 2022-06-01 203413](https://user-images.githubusercontent.com/95868907/171477500-8266dcf7-ea34-4e09-8981-5489ada9f31e.jpg)
