### ISSUE TITLE
Error message: "You're using multiple accounts"

### ISSUE THREAD

**Issue by asboldyrev** [duino-coin/duino-coin#1516]
**Describe the bug**
When I try to exchange coins I get the message: "You're using multiple accounts: dgmasster asboldyrev, this is not allowed". But I don't know any dgmasster. And I don’t know why it is somehow connected with my account (asboldyrev).

**To Reproduce**
1. Go to wallet.duinocoin.com
2. Click on "DUCO Exchange"
3. Select "NANO"
4. Click on "Continue to details"
5. Click on "Continue to swap"
6. Input username, password, my NANO wallet address, email
7. Click on "Swap"
8. See error

**Expected behavior**
I expected that, as usual, there would be a exchange.

**Screenshots/photos**
![2022-06-06 14-16-55](https://user-images.githubusercontent.com/15995789/172119918-34e231e9-b62f-4004-999a-67b7a4a9427c.png)

**System (please complete the following information):**
 - OS: Linux Mint
 - Software: AVR Miner, ESP32 Miner
 - Version: 3.18

**Additional context**
The NANO wallet I tried to transfer to is my personal one and coins have been sent to it several times before without any problems.
The same is observed in the application for Android.

**Comment by myTyou** [comment]
![Screenshot_20220610-110247](https://user-images.githubusercontent.com/107249137/173037266-17617acf-a95f-4ccb-9c79-19faca92ec42.png)
 Same problem.
