### ISSUE TITLE
request duino miner for openwrt routers

### ISSUE THREAD

**Issue by zain141** [duino-coin/duino-coin#1517]
i have many wifi routers on which i installed custom openwrt firmware and then i tried to mine duino coin( using unofficial mininal-cpu-miner) on it and after 10 or 7 min it complete a job and after that again silent, i think i cant handle even low difficulty.
so im requesting t release a official miner for openwrt which can able to mine on that low power cpu.
thanks...

**Comment by BastelPichi** [comment]
Hello,
Have you checked out: [this](https://github.com/BastelPichi/MineCryptoOnWifiRouter)?
Let me know if it worked, or create a issue over there.
