### ISSUE TITLE
DUCO Exchange breaks on float numbers

### ISSUE THREAD

**Issue by Crilum** [duino-coin/duino-coin#1518]
**Describe the bug**
Using DUCO Exchange (selling 0.4 DUCO for Likecoin), I get error `Error: Invalid literal for int with base 10: '0.4'`.
**To Reproduce**
1. Sell a float amount (like 0.4) of DUCO for another currency
2. See error

**Expected behavior**
I expected no error.
**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.
![brokenDUCOExchange](https://user-images.githubusercontent.com/91354257/172209272-8eb79741-4af8-4ead-a653-7cf6044733ee.png)

**System (please complete the following information):**
 - OS: Raspberry Pi OS 11
 - Software: exchange.duinocoin.com (Chromium)
 - Version: N/A

**Comment by revoxhere** [comment]
Float amounts are not really allowed, sorry it's not clear. I'll adjust the error message

**Comment by Crilum** [comment]
Now I get a new error, selling 1 DUCO:
![brokenDUCOExchange2](https://user-images.githubusercontent.com/91354257/172210997-3a0301cf-4db4-4ba3-a14d-29bba5367931.png)
