### ISSUE TITLE
Duino IOT from RPi

### ISSUE THREAD

**Issue by seadolphine0** [duino-coin/duino-coin#1519]
Hello,

I would like to begin by thanking you for this great project. Cryptocurrency has always been like rocket science for me, and this project allows me to learn more while having fun. Thank you.

I have 4 arduinos (Mega, Due and 2 adapted Mega644P) connected to a RaspberryPi as host. A TMP100 temperature sensor is connected to the RPi, and I can read the temperature from the RPi directly by SSHing to it and run a script.

My question: is it possible to send the temperature reading to my wallet?

Thanks
Sandra

**Comment by LDarki** [comment]
Hi, actually you can't do it in a Official way,
You can modify the AVR_Miner code for that but i don't recommend to do it.

You can make the suggestion in [our Discord](https://discord.gg/kvBkccy) and maybe we will implement it in a new version :)

**Comment by seadolphine0** [comment]
> Hi, actually you can't do it in a Official way, You can modify the AVR_Miner code for that but i don't recommend to do it.
> 
> You can make the suggestion in [our Discord](https://discord.gg/kvBkccy) and maybe we will implement it in a new version :)

OK, thanks.
Will post it on Discord.
