### ISSUE TITLE
Add the ability to toggle usage of onboard LEDs on Raspberry Pi.

### ISSUE THREAD

**Issue by DarkWolf2244** [duino-coin/duino-coin#1522]
**Is your feature request related to a problem? Please describe.**
Right now, the official PC Miner just takes control of the onboard Power and ACT LEDs on a Raspberry Pi. While it's useful, I think it would be nice to be able to turn that off, maybe through a command switch. The LEDs turn off when there's a short circuit, and I'd like to be able to know if that happens.

**Describe the solution you'd like**
A method to toggle onboard LEDs' usage to display when a hash succeeds. It could be through a simple `--noLED` switch in the command line or a (Y/n) question on setup.

**Describe alternatives you've considered**
Apart from editing it out of the program myself, there's no way to toggle it at all.

**Additional context**
None.

**Comment by revoxhere** [comment]
New config line (raspi_leds) added in the latest release. change it from `y` to `n`.
