### ISSUE TITLE
API auth returns capcha error 

### ISSUE THREAD

**Issue by jisus-17** [duino-coin/duino-coin#1524]
**Describe the bug**

URL - https://server.duinocoin.com/auth/<username>?password=<password>=&captcha=<reCaptcha_v2>
all the data is correct and the reCapcha code is valid, but i soon as i make the call it returns {"message":"Wrong captcha score", "success":false}
**To Reproduce**
1. Use this url replacing the diferent data with your username and password
2. Go to https://www.google.com/recaptcha/admin crerate new site token using V2 and reCapcha for android
4. Generate a new capcha token in the android app
5. make the api call using the returned token from username capcha test

**Expected behavior**
{"message":"Wrong captcha score", "success":false}

**Screenshots/photos**
![IMG_20220627_214722](https://user-images.githubusercontent.com/77003452/176024650-faae2367-212a-4500-86f8-368474f8ae51.jpg)
![IMG_20220627_214826](https://user-images.githubusercontent.com/77003452/176024664-b275d0e8-1043-4e85-a553-8339e9598ce8.jpg)

**System (please complete the following information):**
 - OS: Android
 - Software: API rest + Google reCapcha v2 on custom android client

**Comment by revoxhere** [comment]
You'd need to use the public & private key we have on the webwallet. The issue is also submitted in the wrong repository.
