### ISSUE TITLE
Network friendly names 

### ISSUE THREAD

**Issue by tbillion** [duino-coin/duino-coin#1535]
i have been changing this section of the code each time i update, i think it should be part of the original code but i dont know how to do a pull request. 

this is the original code 
`void SetupWifi() {
  Serial.println("Connecting to: " + String(SSID));
  WiFi.mode(WIFI_STA); // Setup ESP in client mode
  WiFi.setSleepMode(WIFI_NONE_SLEEP);
  WiFi.begin(SSID, PASSWORD);`

this is my change :

`void SetupWifi() {
  Serial.println("Connecting to: " + String(SSID));
  WiFi.mode(WIFI_STA); // Setup ESP in client mode
  WiFi.setSleepMode(WIFI_NONE_SLEEP);
  WiFi.hostname(newHostName.c_str());
  WiFi.begin(SSID, PASSWORD);`

this allows the device to be seen easily on the network. 

the beginning code is also modified
`  // Change the part in brackets if you want to set a custom miner name (use Auto to autogenerate, None for no name)
  const char *RIG_IDENTIFIER =  "Your rig ID";
  String newHostName =          "your rig id for network purposes";`

i have tried to use the constant char rig id but you get a type mismatch and im not sure how to convert but it would be more streamline to just use the rig id.

this is in the esp8266 code . but i am sure it applies to the esp32 code as well

**Comment by GerardoNevarez** [comment]
what is the problem with hostname and rigid being the same?  it already works like that on my Asus router.

Bonjour/zero-conf works as well,  rigid.local

**Comment by tbillion** [comment]
Not the case as I've seen on multiple networks the rig I'd is for duco
purposes and the other is the hostname given to network appliances when
they query the device . Without this line you get a generic response like
"esp8266-36547"
