### ISSUE TITLE
RPI 3B LED error

### ISSUE THREAD

**Issue by Darksplat** [duino-coin/duino-coin#1543]
HI

I have recently downloaded 3.2 and have the following error

`pi@raspberrypi:~/libducohash $ python3 PC_Miner.py
A new version is available, you want to update miner (Y/n) ? y
09:28:55  sys0  The miner is outdated. Updating....
09:28:55  sys0  Config saved! Launching the miner
09:28:55  sys0  Saving update to: /home/pi/libducohash/PC_Miner_3.2.py
107% [###########################################################] 0.03 MB  1742.0 KB/s09:28:55  sys0  Download complete

 ‖ Official Duino-Coin © Python Miner (3.2) 2019-2022
 ‖ https://github.com/revoxhere/duino-coin
 ‖ CPU: 4x ARMv7 Processor rev 4 (v7l)
 ‖ Developer donation level: 1
 ‖ Algorithm: DUCO-S1 ⚙ Low diff
 ‖ Config file: Duino-Coin PC Miner 3.2/Settings.cfg
 ‖ Have a wonderful morning, darksplat!

09:28:58  sys0  Using fasthash hashing accelerations
Traceback (most recent call last):
  File "/home/pi/libducohash/./PC_Miner_3.2.py", line 1299, in <module>
    if user_settings["raspi_leds"] == "y":
  File "/usr/lib/python3.9/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'raspi_leds'
`

I am running RPI OS 32bit on a RPI3B with libducohash I have no problems with AVR_Miner, I have to comment out the lines to make this work 

Cheers

**Comment by LDarki** [comment]
Hi, you need to delete the Duino Coin PC Miner 3.2 folder and restart the miner, this happens  because the last version of the miner has a new setting that the old config file doesn't has
