### ISSUE TITLE
Should I use coin Magi API for my Duino-coin ?

### ISSUE THREAD

**Issue by Destore2023** [duino-coin/duino-coin#1545]
![image](https://user-images.githubusercontent.com/46444977/182545399-6d31a164-4212-4dc3-921c-a831c6002fd9.png)
 I  want my mini screen to look like this.

should I use this API?  

https://magi.duinocoin.com/api.html
![image](https://user-images.githubusercontent.com/46444977/182545689-b7e60ff0-7478-4d73-af0b-6d2477b8a8fb.png)

**Comment by revoxhere** [comment]
If you want to display magi stats you can proceed with the magi rest api.
