### ISSUE TITLE
error w avr miner

### ISSUE THREAD

**Issue by greymesa** [duino-coin/duino-coin#1547]
**Describe the bug**
when attempting to run the avr miner on my raspi 4 i receive this error:
```
Traceback (most recent call last):
  File "AVR_Miner.py", line 490, in <module>
    lang_file = jsonload(lang_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 265 column 9 (char 18019)
pi@grey
```

**To Reproduce**
1. Go to 'terminal'
2. Click on 'python3 AVR_Miner.py'
3. Scroll down to 'the error'

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: Raspian
 - Software AVR Miner
 - Version 3.18

**Additional context**

**Comment by LDarki** [comment]
Hi, go to the Duino-Coin AVR Miner 3.2 folder then modify Translations.json:

![image](https://user-images.githubusercontent.com/51938450/183071037-59ee9cd4-55c9-44da-a698-ac0900530f5b.png)

There's a missing comma
