### ISSUE TITLE
Cant upload ESP8266_Code

### ISSUE THREAD

**Issue by Michal-Dudcenko** [duino-coin/duino-coin#1557]
Cant upload ESP8266_Code

I click upload and it show :

compilation terminated.
exit status 1
TypeConversion.h: No such file or directory

 - OS: [Windows 10]
 - Software [Arduino 1.8.19]
 - Version [1.8.19]

**Comment by Michal-Dudcenko** [comment]
I have the same problem with BearSSL

**Comment by revoxhere** [comment]
Show the full error.

**Comment by Michal-Dudcenko** [comment]
ok

**Comment by Michal-Dudcenko** [comment]
![image](https://user-images.githubusercontent.com/87039655/187482384-4f6f9faa-007f-4fdb-96a5-1ec3f6bde10a.png)
It's all

**Comment by revoxhere** [comment]
Please try again with the newest code
