### ISSUE TITLE
ESP32 S2 2.0.1 library error

### ISSUE THREAD

**Issue by CarlsonDataCenter** [duino-coin/duino-coin#1562]
My ESP32 S2 has been getting a 2.0.1 library error for arduino ide in the wallet. I had originally library 2.0.4 but I downgraded it to 2.0.1 and reinstalled the code but I’m still getting an error. It might have to do with the fact that my ESP32 is an ESP32 S2 but if the error could be fixed that would be helpful.
![1372746E-5484-4FEC-9DFB-11D644EDE108](https://user-images.githubusercontent.com/113611201/190417742-42badaf6-c01f-45fb-ab62-f1d19b0b3570.jpeg)

**Comment by revoxhere** [comment]
Your miners don't show us as double threaded, are you selecting the right board?

**Comment by revoxhere** [comment]
Nevermind, looks like the S2 is just a single core.
