### ISSUE TITLE
Waiting For the poolpicker 

### ISSUE THREAD

**Issue by Andre-cmd-rgb** [duino-coin/duino-coin#1566]
I’m mining on ESP32 but when I look at the serial terminal I see: core 0 waiting for the poolpicker, core 1 waiting for the poolpicker.
Can you please help me

**Comment by Trickster-git** [comment]
I have same trouble. 
08:56:21.772 -> Core 0 is waiting for the poolpicker...
08:56:25.923 -> Core 1 is waiting for the poolpicker...
