### ISSUE TITLE
warning: `ducohasher` (lib) generated 1 warning

### ISSUE THREAD

**Issue by alyaparan** [duino-coin/duino-coin#1577]
Compiling ducohasher v0.1.0 (/root/libducohash)
warning: method `DUCOS1` should have a snake case name
  --> src/lib.rs:18:12
   |
18 |     pub fn DUCOS1(&mut self, expected_hash: &[u8], diff: u128, eff: u64) -> u128 {
   |            ^^^^^^ help: convert the identifier to snake case: `ducos1`
   |
   = note: `#[warn(non_snake_case)]` on by default

warning: `ducohasher` (lib) generated 1 warning
    Finished release [optimized] target(s) in 24.15s

**Comment by revoxhere** [comment]
This is not an issue.
