### ISSUE TITLE
Stopped working PC_Miner on rpi 3.33

### ISSUE THREAD

**Issue by sshymchuk** [duino-coin/duino-coin#1578]
**Describe the bug**
Fresh installation or update generates an error after execution.

**To Reproduce**
1. `python3 PC_Miner.py`
Output/Error: `'tag_name'`

**Expected behavior**
Normal work.

**Screenshots/photos**
![image](https://user-images.githubusercontent.com/13236337/198993728-28af9539-6e3e-4fde-822f-da67eb46e822.png)

**System (please complete the following information):**
 - OS: Raspbian
 - Software PC_Miner
 - Version 3.33

**Additional context**
No.

**Comment by revoxhere** [comment]
Delete the old config file.

**Comment by sshymchuk** [comment]
There are no config files for new installation. There is only 1 file `Translations.json` in `'Duino-Coin PC Miner 3.33'` folder.

**Comment by revoxhere** [comment]
I don't know who but someone added an exit in the update function. Re-pull and try again now.

**Comment by sshymchuk** [comment]
Thanks. It works.
