### ISSUE TITLE
https://github.com/revoxhere/duino-coin/issues/832 */

### ISSUE THREAD

**Issue by sowildhuri** [duino-coin/duino-coin#1596]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by sowildhuri** [comment]
https://github.com/revoxhere/duino-coin/issues/832 */

**Comment by minercat** [comment]
""esp code giving error esp8266 nodemcu board.""

In file included from C:\Users\mehme\Downloads\ESP_Code\MiningJob.h:14,
                 from C:\Users\mehme\Downloads\ESP_Code\ESP_Code.ino:51:
C:\Users\mehme\Downloads\ESP_Code\Settings.h:66:21: warning: 'hashrate' initialized and declared 'extern'
   66 | extern unsigned int hashrate = "0";
      |                     ^~~~~~~~
C:\Users\mehme\Downloads\ESP_Code\Settings.h:66:32: error: invalid conversion from 'const char*' to 'unsigned int' [-fpermissive]
   66 | extern unsigned int hashrate = "0";
      |                                ^~~
      |                                |
      |                                const char*
C:\Users\mehme\Downloads\ESP_Code\Settings.h:67:21: warning: 'difficulty' initialized and declared 'extern'
   67 | extern unsigned int difficulty = "0";
      |                     ^~~~~~~~~~
C:\Users\mehme\Downloads\ESP_Code\Settings.h:67:34: error: invalid conversion from 'const char*' to 'unsigned int' [-fpermissive]
   67 | extern unsigned int difficulty = "0";
      |                                  ^~~
      |                                  |
      |                                  const char*
C:\Users\mehme\Downloads\ESP_Code\Settings.h:68:22: warning: 'share_count' initialized and declared 'extern'
   68 | extern unsigned long share_count = "0";
      |                      ^~~~~~~~~~~
C:\Users\mehme\Downloads\ESP_Code\Settings.h:68:36: error: invalid conversion from 'const char*' to 'long unsigned int' [-fpermissive]
   68 | extern unsigned long share_count = "0";
      |                                    ^~~
      |                                    |
      |                                    const char*
C:\Users\mehme\Downloads\ESP_Code\Settings.h:69:15: warning: 'node_id' initialized and declared 'extern'
   69 | extern String node_id = "";
      |               ^~~~~~~
C:\Users\mehme\Downloads\ESP_Code\Settings.h:70:15: warning: 'WALLET_ID' initialized and declared 'extern'
   70 | extern String WALLET_ID = "";
      |               ^~~~~~~~~
Multiple libraries were found for "Ticker.h"
  Used: C:\Users\mehme\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\Ticker
  Not used: C:\Users\mehme\OneDrive\Belgeler\Arduino\libraries\Ticker
exit status 1

Compilation error: invalid conversion from 'const char*' to 'unsigned int' [-fpermissive]

**Comment by mehmetacikgozz** [comment]
""esp code giving error esp8266 nodemcu board.""

In file included from C:\Users\****Downloads\ESP_Code\MiningJob.h:14,
                 from C:\Users\****\Downloads\ESP_Code\ESP_Code.ino:51:
C:\Users\****\Downloads\ESP_Code\Settings.h:66:21: warning: 'hashrate' initialized and declared 'extern'
   66 | extern unsigned int hashrate = "0";
      |                     ^~~~~~~~
C:\Users\****\Downloads\ESP_Code\Settings.h:66:32: error: invalid conversion from 'const char*' to 'unsigned int' [-fpermissive]
   66 | extern unsigned int hashrate = "0";
      |                                ^~~
      |                                |
      |                                const char*
C:\Users\****\Downloads\ESP_Code\Settings.h:67:21: warning: 'difficulty' initialized and declared 'extern'
   67 | extern unsigned int difficulty = "0";
      |                     ^~~~~~~~~~
C:\Users\****\Downloads\ESP_Code\Settings.h:67:34: error: invalid conversion from 'const char*' to 'unsigned int' [-fpermissive]
   67 | extern unsigned int difficulty = "0";
      |                                  ^~~
      |                                  |
      |                                  const char*
C:\Users\****\Downloads\ESP_Code\Settings.h:68:22: warning: 'share_count' initialized and declared 'extern'
   68 | extern unsigned long share_count = "0";
      |                      ^~~~~~~~~~~
C:\Users\****\Downloads\ESP_Code\Settings.h:68:36: error: invalid conversion from 'const char*' to 'long unsigned int' [-fpermissive]
   68 | extern unsigned long share_count = "0";
      |                                    ^~~
      |                                    |
      |                                    const char*
C:\Users\****\Downloads\ESP_Code\Settings.h:69:15: warning: 'node_id' initialized and declared 'extern'
   69 | extern String node_id = "";
      |               ^~~~~~~
C:\Users\****\Downloads\ESP_Code\Settings.h:70:15: warning: 'WALLET_ID' initialized and declared 'extern'
   70 | extern String WALLET_ID = "";
      |               ^~~~~~~~~
Multiple libraries were found for "Ticker.h"
  Used: C:\Users\****\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\Ticker
  Not used: C:\Users\****\OneDrive\Belgeler\Arduino\libraries\Ticker
exit status 1

Compilation error: invalid conversion from 'const char*' to 'unsigned int' [-fpermissive]
