### ISSUE TITLE
choose a certain pourcent on the avr miner

### ISSUE THREAD

**Issue by ProjectQuantumofficial** [duino-coin/duino-coin#1599]
Hey,
can you add an option in the avr miner where you can choose the pourcent of power that you use on the board.
Because if you use too much the arduino that can happen : https://fr.wikipedia.org/wiki/%C3%89lectromigration

**Comment by revoxhere** [comment]
Percent of power? How would you even want to achieve that? A NOP instruction uses pretty much the same CPU power as any other one, except the time. 
Also I can't read french
