### ISSUE TITLE
ESP32 C3 and S3 2.0.1 library error

### ISSUE THREAD

**Issue by Lysnyt** [duino-coin/duino-coin#1600]
Im getting a 2.0.1 library error in my wallet and the hashrate fluctuating around 25kh/s. It is doing so nevertheless if i use 2.0.1 library or not (the board is correct).
Problem is that duino coin system can´t determine which version of ESP32 is used. Which is interesting, as ESP32-C3 is supported from 2.0.0 library and it is known, that is single core (Single-core 32-bit CPU, up to 160 MHz). 
Next problem is with the ESP32-S3, which is suported only from early 2.0.3-RC1 library ( https://github.com/espressif/arduino-esp32/releases ), so using the 2.0.1 library is impossible. ESP32-S3 is dualcore (Dual-core Xtensa LX7 CPU, up to 240 MHz) as first ESP32. So it should have double the hashrate as S2 version.

![esp32](https://user-images.githubusercontent.com/97849848/211708659-644f7130-1985-49a7-8ceb-929b4adba966.png)

Could you please make the support for these new boards ? Thank You in advance :)

**Comment by revoxhere** [comment]
I don't own this board, if you're willing to sponsor one I can work on it

**Comment by Lysnyt** [comment]
Hi Robert,

Which one ? C3 or S3 ?
But no problem, just give me your address, I can buy you one from
aliexpress ;)

Best regards,
Ed

st 11. 1. 2023 o 6:34 Robert Piotrowski ***@***.***>
napísal(a):
