### ISSUE TITLE
Raspberry Pi Pico W Standalone Support

### ISSUE THREAD

**Issue by HEJOK254** [duino-coin/duino-coin#1605]
I'd like to use my pico w to mine without having to leave my pc running, however it's currently not possible because the mining software is ran on the pc. But since the pico w already has wifi, nothing but the pico is necessary to use it.

What i think could be done for it to mine by itself, is adding support for the wifi chip and adding the wifi ssid and password as a variable you have to change when you set the program up before uploading it to the device. Alternatively, a "first boot setup" could be used to save all the variables on the pico requiring the user to use the pc mining program once to set the config.

Additionally, there could be a "OnLog" method or something similar that would allow the user to easily modify the code to add support for any displays the might want to use to see the log.

**Comment by revoxhere** [comment]
You'll need to write the code for it.
