### ISSUE TITLE
[VIRUS] PC_Miner.exe (v3.4) getting detected as a virus/malware/trojan by Windows Defender and VirusTotal gives 17/71 poisitve virus test

### ISSUE THREAD

**Issue by 3Domse3** [duino-coin/duino-coin#1613]
Here the link to the VirusTotal result: https://www.virustotal.com/gui/file/7bff9b7a8377b17f13c84e01c4e212c43c9f95b1d7ff49d193307bf002fdf07f?nocache=1

Does someone know why and whether the software is secure or not?
I know many malware scanners flag cryptominers as a virus even if they just do what they should - mine crypto...

**Comment by revoxhere** [comment]
Please learn to read.
![image](https://user-images.githubusercontent.com/50244265/218324688-db2a0867-21ab-4711-a461-131508bafed6.png)

**Comment by 3Domse3** [comment]
@revoxhere 
sry. Missed that completely :(
