### ISSUE TITLE
Add graphs for DUCO amount, hashrate and est. daily profit to show the time progression in detail

### ISSUE THREAD

**Issue by 3Domse3** [duino-coin/duino-coin#1614]
I'd love to see graphs for the current DUCO amount in my account, my hashrate and est. daily profit to get more insight in my mining performance and see what bottlenecks my mining.
If possible also hashrate and reward graphs for each miner individually :)

**Comment by BastelPichi** [comment]
You can get more statistics via the various sites and softwares out there ([https://duinocoin.com/apps](https://duinocoin.com/apps) for some).

You can also build your own via the [duinocoin rest api](https://github.com/revoxhere/duco-rest-api).
