### ISSUE TITLE
Incorrect board recognition

### ISSUE THREAD

**Issue by Vishal-09-00** [duino-coin/duino-coin#1617]
**Describe the bug**
When starting the AVR Miner on Pico board using the Raspberry Pi 4B as host, in the initial configuration state, the board is incorrectly recognized as ESP8266 instead of AVR.

**To Reproduce**
execute python3 AVR_Miner.py in the console

**Expected behavior**
I expect the board to be recognized as AVR type.

**Screenshots/photos**
![Error](https://user-images.githubusercontent.com/75847766/219586936-fa4fcdbe-c80d-4ff3-b357-7890cf74bb21.png)

**System (please complete the following information):**
 - OS: Debian bullseye
 - Software: AVR Miner
 - Version: 2.4

**Comment by revoxhere** [comment]
This is correct behavior.

**Comment by mrlunk** [comment]
It says: 'assigned starting difficulty: ESP8266'
Wich means your pico gets that difficulty setting as a starting point.
It does not say your board is recognised as a ESP8266
You can see how your setup is recognised in the web wallet at: https://wallet.duinocoin.com/ 

Greetz,
MrLunk
