### ISSUE TITLE
Arduino uno Wi-Fi rev3

### ISSUE THREAD

**Issue by jakethepython** [duino-coin/duino-coin#1632]
Added Wi-Fi support for arduino uno Wi-Fi rev3.
This board is self hostable with onboard Wi-Fi.

it is a black board with dip switches and Wi-Fi.

**Comment by jakethepython** [comment]
I didn’t know where to ask or suggest this, so I did it here.

**Comment by revoxhere** [comment]
If you're willing to send me one, I can work on it. Otherwise you'll need to write the code and create a PR yourself.

**Comment by jakethepython** [comment]
Hey revox, the pancake rate keeps switching to bch, or ubeswap. 

Upon looking into those they created a different currency. 
Is the coin income rate still the same for those coins even though they cost most than duco?

I’m curious because I’m mining them According to the rate

**Comment by jakethepython** [comment]
![Uploading 2F99FEAA-37C2-4E0E-98EE-C422AFCB4F7E.png…]()
