### ISSUE TITLE
issue during sketch verification and upload process (IDE)

### ISSUE THREAD

**Issue by jakethepython** [duino-coin/duino-coin#1633]
C:\Users\Admin\AppData\Local\Temp\Temp1_duino-coin-master.zip\duino-coin-master\Arduino_Code\Arduino_Code.ino:31:10: fatal error: uniqueID.h: No such file or directory
 #include "uniqueID.h"
          ^~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: uniqueID.h: No such file or directory

**Comment by revoxhere** [comment]
You're not following the getting started guides.
