### ISSUE TITLE
Miners Don't show up in dashboard

### ISSUE THREAD

**Issue by vishesh0077** [duino-coin/duino-coin#1651]
**Miners Don't show up in dashboard**
While I was mining on my arduino and esp8266 and till yesterday it was working fine but today I was mining and it did not show up in wallet dashboard in 'YOUR MINERS'. sometimes i can see my arduino and esp but in just 1 or 2 minutes it disappears. When it appears my DUCO increases and in a minute the miners disappear and my DUCO becomes 2.69003834681 and the DUCO is mentioned is where i stopped mining yesterday and today it started to do like this. Im new to this community so please help me.

**Expected behavior**
What is expected is appear as normal. what i mean is to show my miners as normal. Like hashrate name and accuracy

**Screenshots/photos**

<img width="960" alt="Screenshot 2023-05-19 120450" src="https://github.com/revoxhere/duino-coin/assets/102781911/32146bac-efc4-4029-b0b9-4caaa6225b9f">

**System**
 - OS: Windows 11
 - Software [AVR MINER]
 - Version 3.5

**Comment by vishesh0077** [comment]
I thank @revoxhere for a wonderful job. The problem is with the server and @revoxhere fixed it.  

Thank you

**Comment by glosbee** [comment]
i cant connect to my wallet account anymore
