### ISSUE TITLE
duino-coin on arch linux 

### ISSUE THREAD

**Issue by umikali222** [duino-coin/duino-coin#1658]
I've tried running duino-coin on arch Linux, and it seemed to have issues, because arch Linux doesn't use pip, instead, you install all the packages using pacman like so: `sudo pacman -S python-xyz`, where xyz is the package name. I was getting a weird error message, that would tell me that pip doesn't work on arch Linux, and to use the command referenced above.

1. get arch Linux, (I tried it on bare metal)
2. install git, python, and python-pip
3. clone duino-coin using git
4. run the duino-coin PC miner with python

**Expected behavior**
the PC miner software, should run the pacman command, to install the libraries, when it detects, that it's running on arch Linux.

**System (please complete the following information):**
 - OS: arch Linux 6.4.2-arch1-1
 - Software PC miner
 - Version newest? idk how to check which on is it.

btw I fixed the problem, by running Ubuntu in a docker container, and running duino-coin there.

**Comment by revoxhere** [comment]
We do not say we support arachne Linux anywhere. If you know how to fix your problem - just do it and submit a PR. Closing as unrelated

**Comment by umikali222** [comment]
what does arachne have to do with this?
