### ISSUE TITLE
Esp8266 loop WDT failed

### ISSUE THREAD

**Issue by spy1345a** [duino-coin/duino-coin#1659]
in serial moniter 
it shows connecting to duico
and after some time it failes the wdt
HELP and sed iam using the 2.7.4 vertion in ide

**Comment by spy1345a** [comment]
> in serial moniter it shows connecting to duico and after some time it failes the wdt HELP and sed iam using the 2.7.4 vertion in ide
10:37:58.948 -> 3ffffb70:  3ffef2a4 3fff0694 3fff0694 4021cc63  
10:37:58.948 -> 3ffffb80:  3ffef2dc 3fff0694 00000000 4021d0c2  
10:37:58.948 -> 3ffffb90:  3ffef5f8 00000000 00000020 4010032c  
10:37:58.948 -> 3ffffba0:  3fff0668 3ffef2a4 3fff0568 3ffef5f8  
10:37:58.948 -> 3ffffbb0:  3ffef2a4 3ffef2dc 3ffef5ec 40224448  
10:37:58.948 -> 3ffffbc0:  00000014 3fff0564 000000ff 00000000  
10:37:58.948 -> 3ffffbd0:  3fff0694 3ffef6ec 3ffe9671 00000008  
10:37:58.948 -> 3ffffbe0:  40256536 3ffeccb8 3ffef954 3fff0694  
10:37:58.948 -> 3ffffbf0:  3fff0694 3ffef2b0 3ffef2a4 4022451c  
10:37:58.948 -> 3ffffc00:  3ffe0000 00000000 00000000 4021d975  
10:37:58.948 -> 3ffffc10:  3fff06d8 3ffef2a4 3fff0568 40225fc4  
10:37:58.948 -> 3ffffc20:  3ffef2a4 00000000 00000000 40226f93  
10:37:58.948 -> 3ffffc3

**Comment by revoxhere** [comment]
This is not even the latest version

**Comment by Tech1k** [comment]
@spy1345a please use the latest version which is 3.5 at this time (https://github.com/revoxhere/duino-coin/releases/tag/3.5) and let me know if it works.

**Comment by Tech1k** [comment]
Here is a link to the updated (v3.5) ESP8266 ino file: https://github.com/revoxhere/duino-coin/blob/3.5/ESP8266_Code/ESP8266_Code.ino

**Comment by Vishal-09-00** [comment]
> @spy1345a please use the latest version which is 3.5 at this time (https://github.com/revoxhere/duino-coin/releases/tag/3.5) and let me know if it works.

it's not working

**Comment by Tech1k** [comment]
> it's not working

Assuming you're using v3.5, what error are you getting?

**Comment by Vishal-09-00** [comment]
> > it's not working
> 
> Assuming you're using v3.5, what error are you getting?

yes using v3.5 and getting this
<img width="612" alt="Error" src="https://github.com/revoxhere/duino-coin/assets/75847766/b7d00e81-634f-4f33-a398-d97a682005d0">

**Comment by spy1345a** [comment]
Yes,after your support i tried the 3.5 it still didn't work
I just uninstalled and installed everything ide and library etc 
And still won't work
I am using a nodemcu esp8266
And yes now i am using the new mining audino script

**Comment by Vishal-09-00** [comment]
> Yes,after your support i tried the 3.5 it still didn't work
> I just uninstalled and installed everything ide and library etc 
> And still won't work
> I am using a nodemcu esp8266
> And yes now i am using the new mining audino script 

Yeah same here
Are you also getting the same error like I have mentioned in the picture above?

**Comment by spy1345a** [comment]
14:42:11.795 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
14:42:11.795 -> 
14:42:11.795 -> Exception (9):
14:42:11.795 -> epc1=0x40105d94 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000003 depc=0x00000000
14:42:11.795 -> 
14:42:11.795 -> >>>stack>>>
14:42:11.795 -> 
14:42:11.795 -> ctx: sys
14:42:11.795 -> sp: 3fffed10 end: 3fffffb0 offset: 0150
14:42:11.795 -> 3fffee60:  40105fc5 01075ed4 3ffeef7c 00000000

**Comment by Vishal-09-00** [comment]
The issue is still not resolved.

**Comment by spy1345a** [comment]
> 14:42:11.795 -> --------------- CUT HERE FOR EXCEPTION DECODER --------------- 14:42:11.795 -> 14:42:11.795 -> Exception (9): 14:42:11.795 -> epc1=0x40105d94 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000003 depc=0x00000000 14:42:11.795 -> 14:42:11.795 -> >>>stack>>> 14:42:11.795 -> 14:42:11.795 -> ctx: sys 14:42:11.795 -> sp: 3fffed10 end: 3fffffb0 offset: 0150 14:42:11.795 -> 3fffee60: 40105fc5 01075ed4 3ffeef7c 00000000

ya with every thing new still i cant mine with esp8266

**Comment by Seelenkind** [comment]
> in serial moniter it shows connecting to duico and after some time it failes the wdt HELP and sed iam using the 2.7.4 vertion in ide

Where did you get version 2.7.4?
The latest current version of the Arduino IDE is 2.2.1
[https://www.arduino.cc/en/software](https://www.arduino.cc/en/software)

**Comment by Seelenkind** [comment]
Try to integrate the stable ESP8266 board manager link
http://arduino.esp8266.com/stable/package_esp8266com_index.json

**Comment by alex5456** [comment]
I used Esp-01S and had same problem. I flashed latest mining script version (3.5) from page "Get started". On some Esp-01s boards the error "Loop WDT Failed!" occurs often, but less often on some boards. Here is my Serial output:

> 05:38:02.909 -> 
> 05:38:02.909 -> 
> 05:38:02.909 -> Successfully connected to WiFi
> 05:38:02.909 -> Local IP address: 192.168.0.106
> 05:38:02.909 -> Rig name: Esp-01S
> 05:38:02.909 -> 
> 05:38:02.909 -> Fetching mining node from the poolpicker in 1s
> 05:38:05.068 -> Poolpicker selected the best mining node: iowa-pool-2
> 05:38:05.284 -> 
> 05:38:05.284 -> 
> 05:38:05.284 -> Connecting to the Duino-Coin server...
> 05:38:45.067 -> Loop WDT Failed!
> 05:38:45.067 -> Restarting ESP...
> 05:38:45.565 -> �x���x�������xx��x�������������x�������������x���x����������x����xx��������x�x��xx���x������x�������������xx���������x�x��x��x�x��x������x��������������������������������������������������������������������������
> 05:38:45.656 -> Duino-Coin 3.5
> 05:38:45.656 -> Connecting to: Tenda_DB4DB0
> 05:38:50.746 -> 
> 05:38:50.746 -> 
> 05:38:50.746 -> Successfully connected to WiFi
> 05:38:50.746 -> Local IP address: 192.168.0.106
> 05:38:50.746 -> Rig name: Esp-01S
> 05:38:50.746 -> 
> 05:38:50.746 -> Fetching mining node from the poolpicker in 1s
> 05:38:52.957 -> Poolpicker selected the best mining node: iowa-pool-2
> 05:38:53.142 -> 
> 05:38:53.142 -> 
> 05:38:53.142 -> Connecting to the Duino-Coin server...
> 05:38:53.547 -> Connected to the server. Server version: 3.0
> 05:38:53.860 -> Asking for a new job for user: flora1324
> 05:39:23.538 -> Received job with size of 
> 05:39:23.538 -> 
> 05:39:23.538 -> User exception (panic/abort/assert)
> 05:39:23.538 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
> 05:39:23.538 -> 
> 05:39:23.538 -> Panic ESP8266_Code_v3.5-flora1324.ino:589 uint8_t* hexStringToUint8Array(const String&, uint8_t*, uint32_t): Assertion 'hexString.length() >= arrayLength * 2' failed.
> 05:39:23.538 -> 
> 05:39:23.538 -> >>>stack>>>
> 05:39:23.538 -> 
> 05:39:23.538 -> ctx: cont
> 05:39:23.538 -> sp: 3ffffd60 end: 3fffffd0 offset: 0010
> 05:39:23.538 -> 3ffffd70:  00000000 3ffe8a50 3ffeed10 402035c2  
> 05:39:23.538 -> 3ffffd80:  00000000 001a001f 00000000 00000000  
> 05:39:23.538 -> 3ffffd90:  00000000 00000000 00000000 3ffe8fad  
> 05:39:23.571 -> 3ffffda0:  00000000 402103e4 00000020 40100ca4  
> 05:39:23.571 -> 3ffffdb0:  00000000 00000000 00000004 4020b507  
> 05:39:23.571 -> 3ffffdc0:  00000000 3ffe8fa9 00000003 402103e4  
> 05:39:23.571 -> 3ffffdd0:  3ffe8fa9 3fff0434 00000000 00000002  
> 05:39:23.571 -> 3ffffde0:  3ffe8fb2 4020f731 00000000 001a001f  
> 05:39:23.571 -> 3ffffdf0:  00000000 00000000 00000003 4020b507  
> 05:39:23.571 -> 3ffffe00:  40105fc5 0023e5e3 3ffeef6c 00000000  
> 05:39:23.571 -> 3ffffe10:  3ffee6e0 3ffeef6c 3ffe85e0 3ffeef6c  
> 05:39:23.571 -> 3ffffe20:  00000000 00001d8a 70a3d70a 00222812  
> 05:39:23.571 -> 3ffffe30:  00001d58 3ffeef6c 00000032 00000032  
> 05:39:23.571 -> 3ffffe40:  00000001 00000032 00001d58 4020b901  
> 05:39:23.571 -> 3ffffe50:  00000000 32333161 00000000 00000000  
> 05:39:23.571 -> 3ffffe60:  3fff03ee 00000000 3ffeeb8c 3fff0474  
> 05:39:23.571 -> 3ffffe70:  00000001 00001d58 00000032 4020c1c8  
> 05:39:23.571 -> 3ffffe80:  00000000 0021002f 00000000 402030f0  
> 05:39:23.571 -> 3ffffe90:  40100200 00000000 0018001f 00000000  
> 05:39:23.571 -> 3ffffea0:  00000000 4e363632 00000000 00000000  
> 05:39:23.571 -> 3ffffeb0:  0017001f 00000000 00000000 000e000f  
> 05:39:23.571 -> 3ffffec0:  00000000 00000000 000d000f 00000000  
> 05:39:23.571 -> 3ffffed0:  feefeffe 00000000 00000000 0011001f  
> 05:39:23.571 -> 3ffffee0:  00000000 00000000 00000000 00000000  
> 05:39:23.571 -> 3ffffef0:  ffffffff feefef01 00000000 feef000a  
> 05:39:23.571 -> 3fffff00:  00000000 feefeffe 00000000 00000000  
> 05:39:23.571 -> 3fffff10:  00000000 feefeffe 00000000 00000000  
> 05:39:23.571 -> 3fffff20:  00000000 00000000 3fff0444 3fff04b4  
> 05:39:23.571 -> 3fffff30:  00000000 3ffefe04 3fff04a4 3fff0444  
> 05:39:23.571 -> 3fffff40:  feefef20 feefeffe 00000000 0089008f  
> 05:39:23.571 -> 3fffff50:  00000000 00000000 0089008f 00000000  
> 05:39:23.571 -> 3fffff60:  00000000 0024002f 00000000 00000000  
> 05:39:23.604 -> 3fffff70:  0089008f 00000000 feefeffe feefeffe  
> 05:39:23.604 -> 3fffff80:  3fff03e2 3ffeedf8 3ffeeba4 feefeffe  
> 05:39:23.604 -> 3fffff90:  3ffefe04 feefeffe feefeffe feefeffe  
> 05:39:23.604 -> 3fffffa0:  feefeffe feefeffe feefeffe 3ffeef94  
> 05:39:23.604 -> 3fffffb0:  3fffdad0 00000000 3ffeef68 4020b9ac  
> 05:39:23.604 -> 3fffffc0:  feefeffe feefeffe 3fffdab0 40101105  
> 05:39:23.604 -> <<<stack<<<
> 05:39:23.604 -> 
> 05:39:23.604 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
> 05:39:23.604 -> �x���x������xx��x������������x�������������x���x����������x����xx����������x��xx���x������x��������x���xx��������x�x��x����x��x������x��������������������������������������������������������������������������
> 05:39:23.692 -> Duino-Coin 3.5
> 05:39:23.692 -> Connecting to: Tenda_DB4DB0
> 05:39:28.724 -> 
> 05:39:28.724 -> 
> 05:39:28.724 -> Successfully connected to WiFi
> 05:39:28.724 -> Local IP address: 192.168.0.106
> 05:39:28.724 -> Rig name: Esp-01S
> 05:39:28.724 -> 
> 05:39:28.724 -> Fetching mining node from the poolpicker in 1s
> 05:39:30.531 -> Poolpicker selected the best mining node: iowa-pool-1
> 05:39:30.703 -> 
> 05:39:30.703 -> 
> 05:39:30.703 -> Connecting to the Duino-Coin server...
> 05:39:31.107 -> Connected to the server. Server version: 3.0
> 05:39:31.417 -> Asking for a new job for user: flora1324
> 05:39:31.634 -> Received job with size of 3f7a0ba6da506130a728c2b15c03429a4a91fe6b,3ce38df0698c03b59d5fd91aa74ec7672d45343d,3500
> 05:39:31.634 -> Parsed job: 3f7a0ba6da506130a728c2b15c03429a4a91fe6b 3ce38df0698c03b59d5fd91aa74ec7672d45343d 350001
> 05:40:10.502 -> Loop WDT Failed!
> 05:40:10.502 -> Restarting ESP...
> 05:40:11.002 -> �x���x�������xx��x������������x�������������x���x����������x����xx��������x�x��xx���x������x��������x���xx��������x�x��x��x�x��x������x��������������������������������������������������������������������������
> 05:40:11.124 -> Duino-Coin 3.5
> 05:40:11.124 -> Connecting to: Tenda_DB4DB0
> 05:40:16.145 -> 
> 05:40:16.145 -> 
> 05:40:16.145 -> Successfully connected to WiFi
> 05:40:16.145 -> Local IP address: 192.168.0.106
> 05:40:16.145 -> Rig name: Esp-01S
> 05:40:16.145 -> 
> 05:40:16.145 -> Fetching mining node from the poolpicker in 1s
> 05:40:17.932 -> Poolpicker selected the best mining node: coffee-pool-1
> 05:40:18.105 -> 
> 05:40:18.105 -> 
> 05:40:18.105 -> Connecting to the Duino-Coin server...
> 05:40:18.277 -> Connected to the server. Server version: 3.0
> 05:40:18.605 -> Asking for a new job for user: flora1324
> 05:40:18.651 -> Received job with size of 181cae25e313c8aced9b3ae3f977a96922c85948,5ce6e4d1f854b516e21e3a2eb596aa6628ec4875,3500
> 05:40:18.651 -> Parsed job: 181cae25e313c8aced9b3ae3f977a96922c85948 5ce6e4d1f854b516e21e3a2eb596aa6628ec4875 350001

**Comment by alex5456** [comment]
I tried to mine, but get "Loop WDT failed" error. Try 3.33 version of miner. It works perfect on all my boards, but 3.5 have errors
