### ISSUE TITLE
Unable to register on the web wallet

### ISSUE THREAD

**Issue by Singleboardcomputer** [duino-coin/duino-coin#1670]
**Describe the bug**
Unable to register through the web wallet with any device and proper internet

**To Reproduce**
1. Go to register
2. Fill details
3. Click create wallet

**Expected behavior**
Whenever you register it says couldn't connect to servers.

**Comment by revoxhere** [comment]
This "bug report" tells us absolutely nothing. 
Most likely it's something on your side blocking our server.
