### ISSUE TITLE
New User faucet - Wrong captcha score

### ISSUE THREAD

**Issue by Veldkornet** [duino-coin/duino-coin#1672]
**Describe the bug**
After entering my username in the "[New User Faucet](https://server.duinocoin.com/faucet.html)", I receive the error "_Wrong captcha score_", although no captchas appear.....

**To Reproduce**
1. Go to [New User Faucet](https://server.duinocoin.com/faucet.html)
2. Enter username
3. click "Claim your reward"

**Expected behavior**
You receive the 5 DUCO for new users

**Screenshots/photos**
![image](https://github.com/revoxhere/duino-coin/assets/10297361/24b15a42-3c80-407e-84a0-16ce4d6a7fbc)

**System (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by revoxhere** [comment]
Fixed
