### ISSUE TITLE
Wemos TTGO ESP8266 0.91 - not work no WiFI connection

### ISSUE THREAD

**Issue by ds2k5** [duino-coin/duino-coin#1678]
Using a Wemos TTGO ESP8266 0.91,
did set: WiFi SSID & Password + duinocoin username and Miner Key in the file: ESP8266_Code.ino

**To Reproduce**
1. Open Arduino 1.8.19
2. open File: ESP8266_Code.ino
3. Select Board: NodeMCU 0.9
4. Click to Upload

**Expected behavior**

That the esp8266 did connect to my WiFi
But there is no esp8266 connected.

**System (please complete the following information):**
 - OS: Debian Linux
 - Software duino-coin
 - Version 3.5

**Additional context**
```

Build options changed, rebuilding all
Archiving built core (caching) in: /tmp/arduino_cache_481461/core/core_esp8266_esp8266_nodemcu_xtal_80,vt_flash,exception_disabled,stacksmash_disabled,ssl_all,mmu_3232,non32xfer_fast,eesz_4M2M,ip_lm2f,dbg_Disabled,lvl_None____,wipe_none,baud_115200_47807693afab82418ebd0211e7b7327a.a
. Variables and constants in RAM (global, static), used 30692 / 80192 bytes (38%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ DATA     1504     initialized variables
╠══ RODATA   2580     constants       
╚══ BSS      26608    zeroed variables
. Instruction RAM (IRAM_ATTR, ICACHE_RAM_ATTR), used 61348 / 65536 bytes (93%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ ICACHE   32768    reserved space for flash instruction cache
╚══ IRAM     28580    code in IRAM    
. Code in flash (default, ICACHE_FLASH_ATTR), used 405592 / 1048576 bytes (38%)
║   SEGMENT  BYTES    DESCRIPTION
╚══ IROM     405592   code in flash   
esptool.py v3.0
Serial port /dev/ttyUSB0
Connecting........_
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 68:c6:3a:xx:xx:xx
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 442416 bytes to 324033...
Writing at 0x00000000... (5 %)
Writing at 0x00004000... (10 %)
Writing at 0x00008000... (15 %)
Writing at 0x0000c000... (20 %)
Writing at 0x00010000... (25 %)
Writing at 0x00014000... (30 %)
Writing at 0x00018000... (35 %)
Writing at 0x0001c000... (40 %)
Writing at 0x00020000... (45 %)
Writing at 0x00024000... (50 %)
Writing at 0x00028000... (55 %)
Writing at 0x0002c000... (60 %)
Writing at 0x00030000... (65 %)
Writing at 0x00034000... (70 %)
Writing at 0x00038000... (75 %)
Writing at 0x0003c000... (80 %)
Writing at 0x00040000... (85 %)
Writing at 0x00044000... (90 %)
Writing at 0x00048000... (95 %)
Writing at 0x0004c000... (100 %)
Wrote 442416 bytes (324033 compressed) at 0x00000000 in 28.5 seconds (effective 124.3 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

```

**Comment by revoxhere** [comment]
You need to check the serial monitor. This doesn't show anything useful.

**Comment by ds2k5** [comment]
@revoxhere

hi thanks for your help

can not see something readable.... only strange signs

tryed all options:  Both LN & CR, No Line Ed. , newline, Carriage return

![Screenshot_2023-09-21_12-18-16](https://github.com/revoxhere/duino-coin/assets/11292286/eb3d8756-8ed5-4e67-a5b8-c67c79b62676)

tryed speed from 1200 up to 9600 to 115200

![Screenshot_2023-09-21_12-21-51](https://github.com/revoxhere/duino-coin/assets/11292286/728b2a0f-480b-4ac9-b2a7-2b546a492a09)




what did I wrong ?

**Comment by revoxhere** [comment]
You haven't followed the getting started guides. If you did that, you'd know why you're seeing garbage

**Comment by ds2k5** [comment]
thanks

did select another board typ:  LOLON(Wemos) D1 mini lite

Looks like it works - but in serial console can not see some....
