### ISSUE TITLE
[ESP32] Support default hashrate for arduino-esp32@2.0.7 and higher

### ISSUE THREAD

**Issue by reinos** [duino-coin/duino-coin#1679]
It seems that the current Official miner for ESP32 needs at least `arduino-esp32@2.0.6` or higher. 

However, if I used the latest version of `arduino-esp32`, which is `2.0.13` (https://github.com/espressif/arduino-esp32/releases) the hashrate is much lower (20Kh/s) than the hashrate on version 2.0.6.

Im not sure what happend and why the change affect the hashrate. But is it possible to support newer versions of  https://github.com/espressif/arduino-esp32/ and keeping the average hash rate on 40Kh/s?

**Comment by revoxhere** [comment]
The getting started guides clearly say to use 2.0.1 and I'm not sure what this issue is trying to say?

**Comment by reinos** [comment]
Perhaps I should rephrase my question :-)

Why should we stick to version 2.0.1? What is the reason we can't use a higher version?

**Comment by revoxhere** [comment]
If you use a newer version the hash rate is much lower. It's something the Espressif foundation changed in the newer versions that makes SHA1 functions less efficient and not something we can change.

**Comment by revoxhere** [comment]
Of course, if you want you can use a different version, but don't be surprised the performance is poor
