### ISSUE TITLE
FQBN: esp8266:esp8266:generic

### ISSUE THREAD

**Issue by alyaparan** [duino-coin/duino-coin#1685]
FQBN: esp8266:esp8266:generic
Using board 'generic' from platform in folder: C:\Users\alikp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2
Using core 'esp8266' from platform in folder: C:\Users\alikp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2

"C:\\Users\\alikp\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\python3\\3.7.2-post1/python3" -I "C:\\Users\\alikp\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2/tools/mkbuildoptglobals.py" "C:\\Program Files\\Arduino IDE\\resources\\app\\lib\\backend\\resources" 10607 "C:\\Users\\alikp\\AppData\\Local\\Temp\\arduino\\sketches\\09D9037E17A77D643A195D118E3D3DA0" "C:\\Users\\alikp\\AppData\\Local\\Temp\\arduino\\sketches\\09D9037E17A77D643A195D118E3D3DA0/core/build.opt" "C:\\Users\\alikp\\OneDrive\\Документы\\duino-coin-master\\ESP8266_Code/ESP8266_Code.ino.globals.h" "C:\\Users\\alikp\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2\\cores\\esp8266/CommonHFile.h"
default_encoding:       cp1252
Assume aggressive 'core.a' caching enabled.
Note: optional global include file 'C:\Users\alikp\OneDrive\\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b\duino-coin-master\ESP8266_Code\ESP8266_Code.ino.globals.h' does not exist.
  Read more at https://arduino-esp8266.readthedocs.io/en/latest/faq/a06-global-build-options.html

*** Traceback (most recent call last):
  File "C:\Users\alikp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 824, in <module>
    rc = main()
  File "C:\Users\alikp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 819, in main
    handle_error(0)   # commit print buffer
  File "C:\Users\alikp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 274, in handle_error
    print(msg_print_buf, file=fd, end='', flush=True)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 137-145: character maps to <undefined>

exit status 1

Compilation error: exit status 1

**Comment by revoxhere** [comment]
Unrelated
