### ISSUE TITLE
Compilation error: ArduinoJson.h: No such file or directory

### ISSUE THREAD

**Issue by alyaparan** [duino-coin/duino-coin#1686]
C:\Users\alikp\Downloads\ESP8266_Code\ESP8266_Code.ino:28:10: fatal error: ArduinoJson.h: No such file or directory
   28 | #include <ArduinoJson.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: ArduinoJson.h: No such file or directory

**Comment by matteocrippa** [comment]
@alyaparan check step 4 here https://duinocoin.com/getting-started.html
