### ISSUE TITLE
BAN donation?

### ISSUE THREAD

**Issue by PSLLSP** [duino-coin/duino-coin#1691]
[FAQ](https://github.com/revoxhere/duino-coin/wiki/FAQ) has a question **[Q: Can we list a low fee coin like banano or raven?](https://github.com/revoxhere/duino-coin/wiki/FAQ#q-can-we-list-a-low-fee-coin-like-banano-or-raven)**

[Donate](https://duinocoin.com/donate) page has no option to donate [BAN](https://banano.cc/) coins...

1000 BAN for liquidity is about 5 USD, it should not be a real problem. BAN can be get from [Nanswap](https://nanswap.com/), they support many coins, including XNO, BTC, DOGE, RVN, BCH, XMR, LTC. DUCO is not in their list... ;-)

Other question is why anyone wants swap BAN for DUCO.

And other question is why many [DUCO exchange](https://exchange.duinocoin.com/) pairs show "no liquidity". Does it meat that such pair cannot be swapped? Many of them have this status, example, DUCO-RVN has no liquidity. Others have "low liquidity" or "medium liquidity", I have no idea what it means, how many DUCO can be swapped in "low liquidity" condition...

I am just curios. From my point of view, it is easier to get few BAN coins (join [F@H project](https://foldingathome.org/?lng=en) with [BAN team](https://bananominer.com/)) than DUCO coins and BAN can be swapped for other crypto coins (at Nanswap).

**Comment by Jonny11bonk** [comment]
In this case, make a discussion thread instead of an Issue or use any of the contact forms available on the https://duinocoin.com/contact.html
