### ISSUE TITLE
Transactions export to CSV

### ISSUE THREAD

**Issue by PSLLSP** [duino-coin/duino-coin#1696]
Could be transactions exported to CSV? I wanted to check details about one of older transaction and I cannot find it. I see only newer transactions. [Web wallet](https://wallet.duinocoin.com/) interface is the best, it shows the longest list of transactions but it is limited to 20 transactions, that is the maximum.

I tried to use [REST API](https://github.com/revoxhere/duco-rest-api), `/user_transactions/<username>` but that one return only 5 most recent transactions.

[DuinoCoin wallet for Android](https://play.google.com/store/apps/details?id=com.protothis.duinocoin) is limited to 10 transactions.

[DuinoCoin block explorer](https://explorer.duinocoin.com/) is limited to 5 transactions.

Do I miss something? Where can I find older transactions, like my first transaction?

---

I cannot find REST-API call to check status of a block. I can see only 5 last mined blocks in the block explorer, the last one is several hours old, it is block [36b41467b533b3150c496c98caebbb483d54a990](https://explorer.duinocoin.com/?search=36b41467b533b3150c496c98caebbb483d54a990)

When I ask for coins from faucet, I receive them immediately, without new block was mined! What a magic!!

I am in series doubt that there is any blockchain behind DuinoCoin, just a simple database that holds several last transactions and balances for wallets, several randomly generated blocks. There is no way to find the first block ever mined or my first transaction with DUCO, probably transaction from faucet for new users...

Other warning detail is that I cannot browse blocks in block explorer (block by block), I cannot see "previous" or the "next" block. Blocks do not list of transactions those they hold, transactions do not refer blocks...

---

And even that "simple database" crashes several times a week, API server is down, again. Block explorer shows "Please, wait"... :-(

```
$ date -u
Mon 13 Nov 14:36:17 UTC 2023

$ ping -c1 server.duinocoin.com
PING server.duinocoin.com (51.15.127.80) 56(84) bytes of data.

--- server.duinocoin.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

Android application "Duino-Coin Companion" cannot handle "server down situation" and crashes...

UPDATE, host `server.duinocoin.com` ignores ping requests, so that test was not valid. Server is up again and I cannot ping it...

**Comment by revoxhere** [comment]
This is a for fun coin. you haven't even visited the main website which states that clearly. There is no blockchain and it's not said anywhere that there is. Closing

**Comment by revoxhere** [comment]
To view more transactions, you can use a tool like https://duco.pcgeek.pl or just append ?limit=<number> to your /user_transactions request, e.g.: https://server.duinocoin.com/user_transactions/revox?limit=500
