### ISSUE TITLE
Arduino_Code.ino cannot be compiled on UNIX like OS

### ISSUE THREAD

**Issue by PSLLSP** [duino-coin/duino-coin#1697]
duino-coin-3.5

Arduino code: `duino-coin-3.5/Arduino_Code/Arduino_Code.ino`

The bug: File `duino-coin-3.5/Arduino_Code/duco_hash.h` tries to include `arduino.h`, no such file exists.

The correct name of the header file is `Arduino.h`... I assume you test on Windows, so there is no difference between `arduino.h` and `Arduino.h` but UNIX type systems are filename case sensitive and these are two distinct files...

The bug:
```
$ grep include duino-coin-3.5/Arduino_Code/duco_hash.h 
#include <arduino.h>
```

The fix:
```
$ grep include duino-coin-3.5/Arduino_Code/duco_hash.h 
#include <Arduino.h>
```

**Comment by reinos** [comment]
In `master` it seems to be correct --> https://github.com/revoxhere/duino-coin/blob/master/Arduino_Code/duco_hash.h#L3

Otherwise, you can try to make a PR if needed.

**Comment by revoxhere** [comment]
@reinos thanks for your input. Indeed seems to be fixed in master, but it's not present in the latest release afaik which will be created soon.
