### ISSUE TITLE
Duino Coin API server is not stable

### ISSUE THREAD

**Issue by PSLLSP** [duino-coin/duino-coin#1698]
I build new miner with Arduino board. I want to test it but miner cannot be configured, I receive connection timeout:

```
Enter your Duino-Coin username: censored
21:14:41  sys0  Error loading the configfile (Duino-Coin AVR Miner 3.5/Miner_config.cfg). Try removing it and re-running configuration. Exiting in 10s (HTTPSConnectionPool(host='server.duinocoin.com', port=443): Max retries exceeded with url: /users/censored (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f79159971c0>, 'Connection to server.duinocoin.com timed out. (connect timeout=15)')))
```

This is just another incident with Duino Coin API, just in a few days. This coin is centralized, and it relies on official infrastructure, that is centralized. Such infrastructure has to be stable and robust but it is not, it is source of trouble, again and again...

```
$ date -u; nc -v server.duinocoin.com 443
Mon 13 Nov 20:41:03 UTC 2023
nc: connect to server.duinocoin.com port 443 (tcp) failed: Connection timed out

$ host server.duinocoin.com
server.duinocoin.com has address 51.15.127.80
```

This page shows, how many incidents were there during the last week, [Duino-Coin API status](https://status.duinocoin.com/history/duino-coin-api)

---

I tried to build ESP8285 miner. It doesn't need configuration with Duino Coin API, configuration is "hardcoded" in the code. My new miner can connect to WiFi but it cannot mine, it cannot fetch jobs from server (information visible in console):

```
Successfully connected to WiFi
Local IP address: 192.168.232.133
Rig name: ESP01

Fetching mining node from the poolpicker in 1s
Error fetching node from poolpicker: connection failed
Fetching mining node from the poolpicker in 2s
Error fetching node from poolpicker: connection failed
Fetching mining node from the poolpicker in 4s
...
``` 

It is interesting that miners those were connected yesterday are still reporting that they are mining. Maybe those just report accepted shares to the console but are not mining in the real. I cannot verify that, I cannot login to my [wallet](https://wallet.duinocoin.com) :-(

---

Webminer cannot be started, it depends on `server.duinocoin.com` [Duino Coin WebMiner](https://server.duinocoin.com/webminer.html) :-(

**Comment by reinos** [comment]
Possible network issues. Please check the discord channel https://discord.gg/kvBkccy in such case. Do not create issues here with such questions.

**Comment by PSLLSP** [comment]
API server is down several times a day and there is an evidence for that. It is critical part of infrastructure. When API server is down, miners cannot connect, wallet cannot connect, etc. That is a real issue with infrastructure...

I think that part of this issue is design of API, it was designed for failure, it doesn't scale well. Calls like `/transactions`, `/miners` or `/balances` create heave load to API server and lot of traffic. I am not sure but there are some signs that  back-end is powered by `SQLite`. I like SQLite but it was not designed for such usage...

Wallet and explorer pages trigger API calls to API server like crazy, when user opens wallet or explorer on several computers, maybe even smart phone, and than it can easily reach limit 60 requests per minute and user is banned. Several users behind NAT can easily reach API limit and their shared IP public address is banned...

API server is open source, there is a repository at `github`. But it is useless because there is no way to clone database; that DB is central and cannot be shared for security reasons. There is a limit of 60 API requests for minute, it will take years to clone DB in this way...

API cannot be called from VPN servers, it blocks servers located in datacentres. Maybe that it makes sense to block miners in "the cloud" but what is a reason to block wallet running in AWS? (AWS Workspace is just a desktop PC running in the cloud...) Even blocking miners located in datacenter doesn't make sense. This coin is worthless, just a toy without future, and running miners in the cloud is an expensive hobby. Why to block these?? It doesn't make sense to pay for miners in the cloud  to mine DUCO...
