### ISSUE TITLE
webwallet and server.duinocoin.com down .. how do I connect now?

### ISSUE THREAD

**Issue by eagle275** [duino-coin/duino-coin#1699]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by reinos** [comment]
Please check or ask such questions on the Discord channel --> https://discord.gg/kvBkccy

**Comment by revoxhere** [comment]
Your IP was most likely temp IP-banned. Contact us if you're still facing this issue. closing for now
