### ISSUE TITLE
esp32 DEV kit V1 Hashrate 12kh/s max 

### ISSUE THREAD

**Issue by wk-Pr** [duino-coin/duino-coin#1719]
I have a problem with the esp32 dev kit v1 in hashrate
It only gives 8KH/s or 10KH/s and the maximum is 12KH/s for CORE
Is it natural?
And is the yellow sign next to the HASHRATE on the site, also natural? If not, what is the solution to the problem?
I would appreciate your help, thank you

![hashrate1](https://github.com/revoxhere/duino-coin/assets/121831645/1346ed06-67d1-41d4-9644-a19473e9bf1c)
![hashrate2](https://github.com/revoxhere/duino-coin/assets/121831645/7e9ccae0-c7e2-4fa6-814f-f6b319bff270)

**Comment by lucassobralofc** [comment]
hi, no problem about that, He only makes the sum of core 1 with 2, no problems about it


Happy mining

**Comment by wk-Pr** [comment]
Thanks for the help
But I have a question, what does this yellow mark mean to the HASHRATE indicator in the picture I shared that there is a problem with HASHRATE, right?
Because here in the picture that shows the information on the page of DOUINO-COIN
Shows that the ESP32 should be 40 - 42KH/S
And I get 10KH/S in each CORE
So it only gives 20KH/S HASHRATE, is there a problem with me? Or how did I transfer the code to ESP32 DEV KIT V1?
I would appreciate it if you could help me, thanks

**Comment by wk-Pr** [comment]
Thanks for the help
But I have a question, what does this yellow mark mean to the HASHRATE indicator in the picture I shared that there is a problem with HASHRATE, right?
Because here in the picture that shows the information on the page of DOUINO-COIN
Shows that the ESP32 should be 40 - 42KH/S
And I get 10KH/S in each CORE
So it only gives 20KH/S HASHRATE, is there a problem with me? Or how did I transfer the code to ESP32 DEV KIT V1?
I would appreciate it if you could help me, thanks
