### ISSUE TITLE
Banned for a single question

### ISSUE THREAD

**Issue by spytaspund** [duino-coin/duino-coin#1722]
**Describe the bug**
Recently I was looking for help on an official Duino-Coin discord server where I shared my issue with community that DUCO server is being geoblocked in russia. Some guys replied me that server is definitely geoblocked. It would seem that the issue has been resolved, but on the next day I see that I am banned on discord server and my wallet is banned too. I wrote with all due respect, did not sanctify and even more so did not promote my political views, but I was banned. **It would be nice if I will be unbanned**, because I was not breaking any rules, or if not, **I want to know why am I banned** (I hope not because I was born in a random country).

**Comment by revoxhere** [comment]
Can you provide your username?

**Comment by spytaspund** [comment]
spytaspund, old name was spytaspund#1430

**Comment by revoxhere** [comment]
Unbanned.

**Comment by spytaspund** [comment]
Thank you so much! Sorry for misunderstanding, username of wallet was SPYT.
