### ISSUE TITLE
You are using multiple accounts (web wallet)

### ISSUE THREAD

**Issue by ASX320** [duino-coin/duino-coin#1728]
### Discussed in https://github.com/revoxhere/duino-coin/discussions/1727

<div type='discussions-op-text'>

<sup>Originally posted by **ASX320** December 31, 2023</sup>
Hi, I've met an issue with DuinoCoin wallet on the web (https://wallet.duinocoin.com). I can't perform any kind of operations with coins. I've made a screenshot:

![Screenshot 2023-12-31 at 5 03 04 PM](https://github.com/revoxhere/duino-coin/assets/96183740/b7072877-1053-4278-bd8c-5cd63059518e)

The listed accounts **do not belong to me**, my is k050506koch. If someone knows how to resolve this issue, help please</div>

**Comment by Jonny11bonk** [comment]
Please, don't spam discussions and issues. Use the e-mail [duino.coin@gmail.com](mailto:duino.coin@gmail.com) or the form at https://duinocoin.com/contact.html to get in contact.

**Comment by ASX320** [comment]
Sure, I'll fill a form, thanks. Should I close the issue?

**Comment by Jonny11bonk** [comment]
> Sure, I'll fill a form, thanks. Should I close the issue?

Yes, that would be good. Just make sure to include all the details regarding your issue.

**Comment by ASX320** [comment]
Included and submitted, thanks for your guidance. Happy New Year!
