### ISSUE TITLE
esp32 Devkitc V4 - ESP32-D0WD-V3 (revision v3.1) - V4 will not run

### ISSUE THREAD

**Issue by ds2k5** [duino-coin/duino-coin#1734]
esp32 Devkitc V4 flashed the Version 4 to - but will not run

**To Reproduce**
1. open Arduino 1.8.19
2. Select Board: ESP32 Dev Module
3. open the File: duino-coin/ESP_Code/ESP_Code.ino
4. Edit the file: Settings.h and set Wifi SSID, Wifi Password, DUCO_USER, MINER_KEY, RIG_IDENTIFIER -> Save
5. Compile and Upload to ESP32
6. Disconnect USB
7. Connect USB
8. Open Serial Monitor
     see this:  
```


RT@S⸮⸮⸮#Z⸮⸮⸮0cP⸮⸮É	⸮⸮
⸮⸮U⸮⸮⸮&g⸮⸮⸮
U⸮b⸮`⸮u⸮8⸮⸮ʪ⸮⸮⸮g腤װ⸮⸮:qGV
A(⸮⸮L*j⸮BDU⸮)Aī⸮⸮ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
⸮R⸮Ku⸮⸮&[ρxT⸮⸮u⸮JEL⸮%⸮E⸮⸮6t⸮⸮|u⸮G⸮W⸮⸮U⸮⸮⸮⸮⸮
⸮⸮⸮
```

**Expected behavior**
That the ESP32 boot an do Wifi connect

![board](https://github.com/revoxhere/duino-coin/assets/11292286/f6c40c18-7b63-4a6c-8681-c411f15402ac)

![messages](https://github.com/revoxhere/duino-coin/assets/11292286/52cdbfc5-ec98-4030-9822-b5e675fd2f4c)

![messages2](https://github.com/revoxhere/duino-coin/assets/11292286/6dad1178-ec61-42f6-8a4b-711a5205c112)

**System (please complete the following information):**
 - OS: Linux
 - Software: ESP_Code
 - Version: 4.0

**Comment by revoxhere** [comment]
Did you follow the getting started guides?

**Comment by ds2k5** [comment]
@revoxhere  did flashed Version 3.5 in the past this works

**Comment by revoxhere** [comment]
Yes, but the old versions require an old library version (2.0.1) and for 4.0 you should use the newest one as stated in the guides.

**Comment by revoxhere** [comment]
What's more, you have 40 MHz clock mode set. I don't know why you even changed it - WiFi will not work with such a low clock speed

**Comment by ds2k5** [comment]
the libs are updated

![libs](https://github.com/revoxhere/duino-coin/assets/11292286/ca53cda7-0f05-4718-8f25-79f05163514e)

**Comment by revoxhere** [comment]
Set the cpu frequency to anormal clock mode that allows WiFi. Also erase flash if you'll face further issues

**Comment by ds2k5** [comment]
>Set the cpu frequency to anormal clock mode that allows WiFi. Also erase flash if you'll face further issues

esptool.py --port /dev/ttyUSB0 erase_flash

![settings](https://github.com/revoxhere/duino-coin/assets/11292286/b90b8a53-ff46-4555-a63d-6ab9a7e2424b)

![serial_mointor](https://github.com/revoxhere/duino-coin/assets/11292286/3cc61e1d-318d-4488-b26a-f6461ae4945f)

did not see at: https://wallet.duinocoin.com/

**Comment by Pendralum** [comment]
same probleme for esp32c3 
![Screenshot_1](https://github.com/revoxhere/duino-coin/assets/99128535/3072499d-fac1-4032-b209-37787687438b)

**Comment by revoxhere** [comment]
I don't know then. It works for me and others

**Comment by ds2k5** [comment]
>I don't know then. It works for me and others

ok thanks for your help
