### ISSUE TITLE
Webserver (Dashboard) / OTA not working on ESP32

### ISSUE THREAD

**Issue by dl1lmh** [duino-coin/duino-coin#1737]
The dashboard and the OTA update do not work in both cases since the update V4.0.
With V3.9 it works perfectly.

Ping and mining work perfectly.

The dashboard and the OTA get the error “Connection Timeout”

I guess that
`server.handleClient();`
and the OTA handler are not executed.

Hardware:
ESP32-WROOM-32
connected via WLAN

OLIMEX POE board
ESP32-WROOM-32E
connected via WLAN or LAN (see pull request #1735)

Browser for Dashboard:
- Firefox & Edge on Win11
- Mobile Devices Android & Apple

Software OTA:
- VisualStudio with Platformio (up to date) - normally i use this for development
- ArduinoIDE (up to date)

**Comment by revoxhere** [comment]
I'm pretty sure it worked pretty well both on ESP8266, 32s2 and 32 boards when I was creating the 4.0 code for it. Are you sure you're connecting to the correct IP address?

**Comment by dl1lmh** [comment]
I will test it again this evening with your original software and give feedback.  But I'm very sure because I tested on several ESP...

**Comment by joseguia** [comment]
Same on the 4 adafruit huzzah32 feathers I tested on. The same symptoms as the OP. Mine and ping work. But that's all I get , using latest versions of arduino and update v4

**Comment by revoxhere** [comment]
Fixed in 4.2/4.3
