### ISSUE TITLE
ESP32 DCv4.0 Brownout Detection with newest Libs

### ISSUE THREAD

**Issue by Skillertheking** [duino-coin/duino-coin#1741]
Wemos D1 Mini ESP32 

Arduino IDE 2.2.1
Libs:
Boards ESP32 v2.0.14
ArduinoJson v7.0.0
TridentTD_EasyFreeRT v1.9

Compiling all Okey, no errors 

Serial Monitor:
"Duino-Coin 4.0
Connecting to: ***SSID***

Brownout detector was triggered"

### **When i Install a older ESP32 Board Lib like 2.0.1 - 2.0.9**

and the esp have in Dashboard 42kH/s per Core, 2 Core together ~84kH/s  
that's uplausible, isn't it? from 3.5 to 4.0 double the hashrate?

under this condition have the ming machine no solid connection to the Dashboard it is sometimes there and sometimes gone. v3.5 was solid stable connection!

With 2.0.10 - 2.0.14 is only Brownout Detection, no full booting into Programmode

**Comment by revoxhere** [comment]
Closing as it's unrelated to the code. Burnout detector means underperforming power supply.

**Comment by Skillertheking** [comment]
sorry but @revoxhere  did you read what i wrote ? i only have a brownout with the latest esp32 board libs!

same power connection. 
same usb port and cable when flashing with lib 2.0.9 everything works and with lib 2.0.10 or above nothing works ?

**Comment by revoxhere** [comment]
This is not the esp32 support. If you're saying it's dependent on the used library version for you, then it's not anything on duino coin side
