### ISSUE TITLE
Discord Ban 

### ISSUE THREAD

**Issue by limefocus** [duino-coin/duino-coin#1753]
### Issue Summary
I have been banned from the Duino Coin Discord server and have attempted to contact the team through email and the contact form on the website. Unfortunately, I have not received any response. This issue is to seek assistance and resolution regarding my Discord ban.

### Discord Username
My Discord username is changcaizhang_87072.

### Email Address
I used the email address electrowirelab@gmail.com to contact Duino Coin.

### Requested Action
I am seeking a review of my Discord ban or clarification on the reason for the ban.

### Contact Information
Please contact me using my discord username, email or here itself
### Discord Ban Appeal (if applicable)
If there is an official procedure for a ban appeal, I am willing to follow it.

**Comment by rawnullbyte** [comment]
Their staff sucks, got banned to lmao

**Comment by catdroutx** [comment]
banned too lmao. The owner is polish and he sold an ESP board with 20 USD shipping (to sweden from poland)

**Comment by rawnullbyte** [comment]
> banned too lmao. The owner is polish and he sold an ESP board with 20 USD shipping (to sweden from poland)

ye lol

**Comment by revoxhere** [comment]
> > banned too lmao. The owner is polish and he sold an ESP board with 20 USD shipping (to sweden from poland)
> 
> ye lol

This behavior will not be tolerated. What does this have to do with this repository?
