### ISSUE TITLE
AVR_Miner.py asks for configuration again after executing with the absolute path specified

### ISSUE THREAD

**Issue by boson-higgs** [duino-coin/duino-coin#1759]
**Describe the bug**
I would like to add AVR_Miner in systemd but AVR_Miner.py asks for configuration again when I speciify the absolute path of AVR_Miner.py.

**To Reproduce**
1. Execute the AVR_Miner.py with absolute path (python3 /path/duino-coin/AVR_Miner.py)

**Expected behavior**
Not asking about new configuration when the same file AVR_Miner.py has been executed in past (this behavior works when executing python3 AVR_Miner.py after cd /path/duino-coin).

**System (please complete the following information):**
 - OS: Linux Raspbian
 - Software AVR_Miner.py
 - Version 3.5 and 4.0

**Comment by OrtegaUS1** [comment]
it does this on raspberry pi too. i think?   i tried to make it an destop app it does not work

**Comment by revoxhere** [comment]
This is not a Duino-Coin issue. By providing a different path, you're effectively starting the app from a different place. One solution to this may be to store the config in a predetermined location, but that raises compatibility issues and more hassle for users to find it whenever they want to edit it manually.
