### ISSUE TITLE
Raspberry pi   New IOT feature: ip , user and customizable config from web wallet

### ISSUE THREAD

**Issue by OrtegaUS1** [duino-coin/duino-coin#1760]
I have a idea for future update for iot data on raspberry pi
Ip address Added in IOT(What ip is the Raspberry pi on)
what current user on the raspberry pi is mining
and Change config from the web wallet?

Sorry if this sounds dumb

**Comment by revoxhere** [comment]
Exposing your IP address on the internet is not the best idea. You can do it however by simply adding this data to the miner you're using. See https://github.com/revoxhere/duino-coin/wiki/Duino's-take-on-the-Internet-of-Things
