### ISSUE TITLE
Android app link doesnt work

### ISSUE THREAD

**Issue by KorryKatti** [duino-coin/duino-coin#1764]
**Describe the bug**
The link for the android app at https://duinocoin.com/getting-started.html which leads to google play store does not provide an app, it has probably been removed from there

**To Reproduce**
1. Go to https://duinocoin.com/getting-started.html
2. Click on 'View on Google Play'
3. See error

**Expected behavior**

**Screenshots/photos**
An actual application on google play

**System (please complete the following information):**
 - OS: Android
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**
Would be better to link an apk file

**Comment by Jonny11bonk** [comment]
I suppose you're talking about the com.fatorius.duinocoinminer. It looks like it's private and not available to the public as I can access the app's page.

**Comment by KorryKatti** [comment]
yeah i am talking about it,would be better to update the link
