### ISSUE TITLE
Add libducohash.tar.gz to the repository

### ISSUE THREAD

**Issue by sinuso** [duino-coin/duino-coin#1774]
I am following these [instructions ](https://github.com/revoxhere/duino-coin/wiki/How-to-compile-fasthash-accelerations)but the libducohash.tar.gz download link is blocked.

Is it possible to add it to the [Resources](https://github.com/revoxhere/duino-coin/tree/master/Resources) or [Tools](https://github.com/revoxhere/duino-coin/tree/master/Tools)?
I know it's temporary, but at least we can continue messing around and preparing devices.

Thanks and congratulations for the project.

**Comment by revoxhere** [comment]
Available in https://github.com/profpandaa/compatible-libducohash
