### ISSUE TITLE
Multiple accounts on same IP.

### ISSUE THREAD

**Issue by kizeren** [duino-coin/duino-coin#1788]
Being rejected for multiple accounts registered on same network.

On 7/4/23 I recieved 3 warning while sleeping.  Suspicious behavior.  Logged into website to see what was happening.  System says I recieved 5 warnings.  Then on 10/14/23 out of the blue my verification that was sent into on  10/19/21 has now been rejected.  Then 11 days later another email stating verification has been rejected. For alt account.  I had no clue what then meant.  I checked the email and seen a noticed about securing with mining token. Set up one and went back to mining.  Got verified on 10/27/23.   Only to get 3 morening warnings ( system said 5, still waiting on total of 4 warnings that has not been sent yet and all done while asleep.  ) for invalid or inappropriate stats.  These errors made no sense.  I only had a few miners and none matched what was being reported.  Same time I reflashed all miners watched the dashboard for wrong miner information.  None has shown up yet!  Tried to verify on dec 13, even sent multiple emails to no eval.  Finally got a reject notice on jan 17 only after I started asking questions in discord and on facebook.
Tried to verify 4 more times all stating alt accounts.  No, still same account on same ip since 2021.  Finally JPx13 messaged me on discord.  Wanted to know which IP address was mine. The one with many or then one with only my account on it.  Mine was the single ip with just my account.  He said my account was registered with two IP - must of had a VPN.   Never had a VPN while mining duincoin.

Had one in 2017 and didn't like it.  But either way almost a year into this and no closer to resolving.  Steps were taken to fix any problems that arose.  Still not seeing any extra miners and bad stats on dashboard.

Now what realy lights the fire. I see many who had similar if not same issues fixed in a few minutes and backing mining the same day.
So again for the record:

VPN: No never still not using one.
IP: same IP since I moved here in 2018 - never changed.
ACCOUNT: Same account, never made a new one.
WRONG MINER: Fixed last year.  Never came back.

**Comment by revoxhere** [comment]
Can you provide your username so that someone from the administration can check on this?

**Comment by misterpk-thailand** [comment]
I have quite the same problem, I applied to verify more new miners, but they replied me ....

Your verification request was not accepted. We're just letting you know that your mining rig verification has been rejected. The reason for this is that you have multiple accounts registered on the same network. This is not allowed by the terms of service you agreed to comply with during registration. Sorry, but we do not help cheaters.Verification rejected by admin: bononek

Come on man!! I have the only one account : misterpk

**Comment by Jonny11bonk** [comment]
> I have quite the same problem, I applied to verify more new miners, but they replied me ....
> 
> Your verification request was not accepted. We're just letting you know that your mining rig verification has been rejected. The reason for this is that you have multiple accounts registered on the same network. This is not allowed by the terms of service you agreed to comply with during registration. Sorry, but we do not help cheaters.Verification rejected by admin: bononek
> 
> Come on man!! I have the only one account : misterpk

Try logging in now. Clear your cookies and cache before that. Sadly, we can't do anything about the dynamic IPs.

**Comment by misterpk-thailand** [comment]
> > I have quite the same problem, I applied to verify more new miners, but they replied me ....
> > Your verification request was not accepted. We're just letting you know that your mining rig verification has been rejected. The reason for this is that you have multiple accounts registered on the same network. This is not allowed by the terms of service you agreed to comply with during registration. Sorry, but we do not help cheaters.Verification rejected by admin: bononek
> > Come on man!! I have the only one account : misterpk
> 
> Try logging in now. Clear your cookies and cache before that. Sadly, we can't do anything about the dynamic IPs.

It returns back to normal now, many thanks bro.

**Comment by kizeren** [comment]
> Can you provide your username so that someone from the administration can check on this?

Same name, "kizeren"

**Comment by Jonny11bonk** [comment]
> > Can you provide your username so that someone from the administration can check on this?
> 
> Same name, "kizeren"

You're using a VPN which is not allowed and resulted in your account getting flagged as an alt along with the others.

**Comment by kizeren** [comment]
> > > Can you provide your username so that someone from the administration can check on this?
> > 
> > 
> > Same name, "kizeren"
> 
> You're using a VPN which is not allowed and resulted in your account getting flagged as an alt along with the others.

*facepalm*  Guess you didn't read the original issue.  Instead of guessing or vomiting out the same old thing over and over, why not investigate a bit.  As stated orignally there was a vpn back in 2017.  Hell I have even bought a new firewall appliance just for this.  A new desktop...... There ARE NO VPNS!!!!

**Comment by Jonny11bonk** [comment]
So you're telling me that datacenter IP addresses are commonly found in
every household?

Používateľ Shaun Mcbride ***@***.***> sobota 22. júna 2024
napísal:

**Comment by kizeren** [comment]
> So you're telling me that datacenter IP addresses are commonly found in every household? Používateľ Shaun Mcbride ***@***.***> sobota 22. júna 2024 napísal:
> […](#)
> Can you provide your username so that someone from the administration can check on this? Same name, "kizeren" You're using a VPN which is not allowed and resulted in your account getting flagged as an alt along with the others. *facepalm* Guess you didn't read the original issue. Instead of guessing or vomiting out the same old thing over and over, why not investigate a bit. As stated orignally there was a vpn back in 2017. Hell I have even bought a new firewall appliance just for this. A new desktop...... There ARE NO VPNS!!!! — Reply to this email directly, view it on GitHub <[#1788 (comment)](https://github.com/revoxhere/duino-coin/issues/1788#issuecomment-2184185291)>, or unsubscribe < You are receiving this because you commented.Message ID: ***@***.***>

omg really?  I contacted via github to report this problem.  Normally projects would love to help figure this out instead of spewing this crap.  Apparently not this project.

Have you check timestamps of when this happened?  Do you even log that information?  Do the logs show as of today vpn being used? Since this problem started 2023 there have been zero vpn's in use.  I am minging right now and nothing has changed the problem came about accept for the addition of the mining key being enabled.  I can gurantee my works are coming from 68.119.x.x.  For a project that wants to explorer and learn, this one sure doesn't...

Now if you all would like to stop splling the same garbage and would like to really put some brains into it and figure out why your system is showing vpn when in fact its not.  Feel free to.  I'll give you my undivided attention in doing so.

**Comment by Jonny11bonk** [comment]
> > So you're telling me that datacenter IP addresses are commonly found in every household? Používateľ Shaun Mcbride _**@**_._**> sobota 22. júna 2024 napísal:
> > […](#)
> > Can you provide your username so that someone from the administration can check on this? Same name, "kizeren" You're using a VPN which is not allowed and resulted in your account getting flagged as an alt along with the others. _facepalm_ Guess you didn't read the original issue. Instead of guessing or vomiting out the same old thing over and over, why not investigate a bit. As stated orignally there was a vpn back in 2017. Hell I have even bought a new firewall appliance just for this. A new desktop...... There ARE NO VPNS!!!! — Reply to this email directly, view it on GitHub <[#1788 (comment)](https://github.com/revoxhere/duino-coin/issues/1788#issuecomment-2184185291)>, or unsubscribe < You are receiving this because you commented.Message ID: _**@**_.**_>
> 
> omg really? I contacted via github to report this problem. Normally projects would love to help figure this out instead of spewing this crap. Apparently not this project.
> 
> Have you check timestamps of when this happened? Do you even log that information? Do the logs show as of today vpn being used? Since this problem started 2023 there have been zero vpn's in use. I am minging right now and nothing has changed the problem came about accept for the addition of the mining key being enabled. I can gurantee my works are coming from 68.119.x.x. For a project that wants to explorer and learn, this one sure doesn't...
> 
> Now if you all would like to stop splling the same garbage and would like to really put some brains into it and figure out why your system is showing vpn when in fact its not. Feel free to. I'll give you my undivided attention in doing so.

Your problem should be fixed by now. We rely on IP databases which report us the usage type and other useful information in recognizing the VPNs. It seems like must've used TunnelBear (to be more precise, _Oy Creanova Hosting Solutions Ltd._) at some point as that's the IP origin which was being reported before. All these information regarding the IPs are publicly available via free websites.

**Comment by revoxhere** [comment]
I'm not seeing any issues for your account anymore so I'll close this issue
