### ISSUE TITLE
Once all boards are plugged out and both programs are closed the PC enforces the set local group policy for all users

### ISSUE THREAD

**Issue by adrian2793** [duino-coin/duino-coin#1795]
**Describe the bug**

Once all boards are plugged out and the program is closed the PC enforces the set local group policy for all users [ I set them but only applied them to one user. Once happend it was applied to all users ] I am sure it was your software because I didn‘t changed anything and I had set the local group policy a few weeks ago and it worker until today ] Also I only opened your miners and chrome to run two web miners

**To Reproduce**

1. Open the PC miner

2. Plug in the boards

3. Open the AVR miner

4. Plug them out

5. Close the AVR miner

6. Close the PC miner

**Expected behavior**

None

**Screenshots/photos**

I needed to reset my PC so I got none :(

**System:**
 - OS: Windows 10
 - Software AVR miner
 - Version Latest

**Additional context**

I had to reset my PC because of that. The only programs I had ran your both miner programs and closed both [ first the AVR one and then the PC miner ]

**Comment by revoxhere** [comment]
What? None of the duino softwares use any group policies or anything like that.

**Comment by adrian2793** [comment]
> What? None of the duino softwares use any group policies or anything like that.

I don‘t know. Once I closed the program the group policies were applied to all my users and I needed to reset my PC then.

**Comment by adrian2793** [comment]
Before I closed the AVR miner it gave me the error that it couldn‘t connect to them [ Because I plugged them out ]

**Comment by revoxhere** [comment]
Well, I can tell you this is not the cause. You're already on GitHub so you can check the source codes and see there's no ingerention in any system calls.

**Comment by adrian2793** [comment]
> Well, I can tell you this is not the cause. You're already on GitHub so you can check the source codes and see there's no ingerention in any system calls.

You are using python to run the code, right?
