### ISSUE TITLE
Mining all coins implementation

### ISSUE THREAD

**Issue by ArakelTheDragon** [duino-coin/duino-coin#1805]
Hi!

I would really like to use the nodeMCU mining for my project, but I don't have the opportunity to develop the code. Can I please request the following:

1. The NodeMCU mines as normally, but it has the option to swap the duino coin for other coins and sent this to a web3 or other wallet. Of course the payouts will be at a certain amount.
2. The feature can be implemented with the pancake swap API or another method, we understand the end price will be lower than swapping manually, to cover the process

I can give this example with uniswap
[code]
function swapExactTokensForTokens(
    uint amountIn,
    uint amountOutMin,
    address[] calldata path,
    address to,
    uint deadline
)
[/code]

Source:
https://stackoverflow.com/questions/67049492/pancakeswap-api-swaping-bnb-with-binance-smart-chains-api

**Comment by revoxhere** [comment]
Wtf? This is an issue tracekr not a request concert

**Comment by ArakelTheDragon** [comment]
Sorry if the new feature is inappropriate, have a nice day!
