### ISSUE TITLE
Release 4.2

### ISSUE THREAD

**Issue by mzakiab** [duino-coin/duino-coin#1809]
under ESP_Code.ino tab, under line 554 i add:

```
lcd.init();       // tambah sendiri
lcd.backlight();  // tambah sendiri
```

when i want to use LCD 16x2 as a display

**Comment by revoxhere** [comment]
Cool and why did you open an issue for this?

**Comment by mzakiab** [comment]
i don't know how to do that... this is my first time write comment in github

**Comment by revoxhere** [comment]
If you want to improve something, send a pull request
