### ISSUE TITLE
Version 4.2 did not run - Version 4.0 runs on my esk8266 LOLIN D1 mini clone

### ISSUE THREAD

**Issue by ds2k5** [duino-coin/duino-coin#1813]
**Describe the bug**

Downloaded the Code Version 4.2
wanna install it to my esp8266 Device

**To Reproduce**
1. git clone https://github.com/revoxhere/duino-coin
2. run arduino ide
3. Open the files from ESP_Code
4. Set Parameters in Settings.h
5. run compile

device did not connect to wifi
so did not see it at: https://wallet.duinocoin.com/

How to fix this ?

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: Linux
 - Software Arduino IDE
 - Version 1.8.19

**Additional context**

**Comment by revoxhere** [comment]
This is a possible bug, I'll take a look at it. From what I see it works on some routers while it doesn't on other

**Comment by ds2k5** [comment]
@revoxhere  

thanks for your help

can I help with some information, trace ?

**Comment by revoxhere** [comment]
Can you check whether removing the line WiFi.disconnect(true); makes any difference?

**Comment by ds2k5** [comment]
>Can you check whether removing the line WiFi.disconnect(true); makes any difference?

![Screenshot_2024-08-18_21-29-26](https://github.com/user-attachments/assets/20988764-cc6f-4097-9037-d0ad4e9c5472)

Looks like it is connected to WiFi but did not see the Device at: https://wallet.duinocoin.com/

**Comment by revoxhere** [comment]
What does the serial monitor say?

**Comment by ds2k5** [comment]
>What does the serial monitor say?

![grafik](https://github.com/user-attachments/assets/08f59555-df5f-4289-b4de-6d1dd002af1b)

**Comment by revoxhere** [comment]
You're not following the getting started guides. Baudrate should be set to 500000

**Comment by ds2k5** [comment]
can only set 57600

![grafik](https://github.com/user-attachments/assets/819172ee-f3f4-40d7-8fc5-95bdb60837f7)

can I change here to 57600 ?
![grafik](https://github.com/user-attachments/assets/2ad4c182-6156-4cd6-9bfd-d8fcfa91e61a)

**Comment by revoxhere** [comment]
Sure

**Comment by ds2k5** [comment]
![grafik](https://github.com/user-attachments/assets/073de926-ef58-46e3-8b00-082f497fb36f)

same if  WiFi.disconnect(true) is enabled

**Comment by revoxhere** [comment]
Ok. I'll try to make some changes

**Comment by ds2k5** [comment]
>Ok. I'll try to make some changes

thanks

**Comment by revoxhere** [comment]
Can you pull the latest code and check whether that has changed anything?

**Comment by ds2k5** [comment]
yes thank you so much ! it works with Version 4.3 now!

have a nice Evening!

**Comment by revoxhere** [comment]
That's great to hear. I'll close this issue for now

**Comment by ds2k5** [comment]
got a lot of double devices in the list now at https://wallet.duinocoin.com/

and the hash rate is still fluctuating

Will check tomorrow an report again

thanks for all

**Comment by ds2k5** [comment]
@revoxhere 

Hello,
still the same
Double entrys

![Screenshot_2024-08-19_08-56-41](https://github.com/user-attachments/assets/2dda13af-4a1a-4008-9955-a9454450c051)


a few Seconds later:
![grafik](https://github.com/user-attachments/assets/ce67eeb3-274b-42ba-b093-d46083fdb987)

It should be:  F0 until F6

At my router I can see 7 Devices
