### ISSUE TITLE
Duino code not working after version 3.9 and above on ESP32-C3

### ISSUE THREAD

**Issue by Lysnyt** [duino-coin/duino-coin#1815]
**Describe the bug**
After applying code 3.9 and above, miner does not work anymore on ESP32-C3 , keeps on loop with error

**To Reproduce**
not connecting to wifi, after serial print a get error loop
1R	�ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x8 (TG1WDT_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380080
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0x1058
load:0x403cc710,len:0x8a8
load:0x403ce710,len:0x2fa0
entry 0x403cc710
v@�ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x8 (TG1WDT_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380082
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0x1058
load:0x403cc710,len:0x8a8
load:0x403ce710,len:0x2fa0
entry 0x403cc710

**Expected behavior**
Code 4, 4.1, 4.2 working without problem on ESP32, ESP32-S3, ESP8266

**Screenshots/photos**
see attached screen
![error loop](https://github.com/user-attachments/assets/10bb8f5a-b94b-4cd9-b5bb-02a12e77580f)

**System (please complete the following information):**
 - OS: WIN11 Pro
 - Software: Duino-Coin_4.2_windows
 - Version 4.2

**Comment by revoxhere** [comment]
Use the latest code from master branch. I tested it on C3

**Comment by Lysnyt** [comment]
Yep, the code from master branch is working, thanks.
In wallet gui is showing as 
Official ESP32-S2 Miner 4.3

**Comment by revoxhere** [comment]
Sounds about right, currently the code reports as S2 for single core ESP32 variants
