### ISSUE TITLE
Hello the wallet is not login

### ISSUE THREAD

**Issue by ghost** [duino-coin/duino-coin#1831]
I'm trying to access my account and check my duco but I get a captcha error even though the button to solve the captcha doesn't even appear. The computer has windows and google chrome so it shouldn't give any problems. Does anyone know how to solve this?
![image](https://github.com/user-attachments/assets/0e0c2173-7165-4947-a7d0-5105f2312857)

**Comment by Jomossey** [comment]
@DUINO-MINER Have you tried refreshing the page or clearing your browser cache? Sometimes that helps with weird issues like captcha not loading.

**Comment by ghost** [comment]
It be solved

**Comment by ghost** [comment]
Solved
