### ISSUE TITLE
You are using multiple Accounts Issue

### ISSUE THREAD

**Issue by makerpro299** [duino-coin/duino-coin#1835]
Hi, 
Wenn I try to stake my coins or Swap my Coins, I always get the Issue, that I am using multiple Accounts, but I don't. There has already been a Request for Fix here on Github but it was 10 Month ago and nothing happened. I can't really do anything with my coins, this leaves my account "broken". I am not using VPN, Private Relay or Proxy. I'm on MacOs 15.0.1 using Safari. 
Thanks!
<img width="675" alt="Bildschirmfoto 2024-10-07 um 16 24 11" src="https://github.com/user-attachments/assets/b1f2313d-ab5f-449c-8c62-a4c2e9556819">

**Comment by profpandaa** [comment]
What's your DUCO username? I'll take a look at it.

**Comment by makerpro299** [comment]
Thank you, my username is minersmines

**Comment by profpandaa** [comment]
Your account has been marked due to you using iCloud Private Relay. I've unlinked your account, however, refrain from using any VPN (or the like) in the future.

**Comment by makerpro299** [comment]
Okay, thank you.

**Comment by makerpro299** [comment]
![image](https://github.com/user-attachments/assets/5c4931bf-3328-40a7-91d2-61787c586d79)

I still have the issue without using vpn or any like that. Could it also be that these accounts and me use the same provider?

**Comment by profpandaa** [comment]
You accessed the DUCO service via the iCloud Private Relay again.

**Comment by makerpro299** [comment]
Okay, sorry. Can you maybe reset it one more time and I will not access via private relay anymore. Thank you.

**Comment by makerpro299** [comment]
I also messed things up a bit, I created a second account because I wanted to start from new cause I was a little upset with these problems. But now I have the error message saying there is minersmines and minersmines2
Problem is I can't login in minersmines2 and delete the account.

**Comment by profpandaa** [comment]
As far as I can see, there's no user with that name.

**Comment by makerpro299** [comment]
Yeah, I got an error creating that account, but it still shows up when I'm trying to do a transaction.

**Comment by makerpro299** [comment]
![image](https://github.com/user-attachments/assets/3925b8a3-25e7-4469-8321-5143257169a4)

**Comment by profpandaa** [comment]
Mind trying again?

**Comment by makerpro299** [comment]
I will try when I am back home, but thanks for all the help so far.

**Comment by makerpro299** [comment]
I have tried it, but I am connected to US-Network. It works now, hopefully it will also work in Germany.

**Comment by lucassobralofc** [comment]
hello, you are using some kind of vpn, or mobile data, that’s strange…


lucassobralofc, official duinocoin helper (aka as Szefito)

**Comment by makerpro299** [comment]
I don't know, I have used iCloud private relay before. But now I don't use it anymore. IDK but I sometimes access the website via my iPhone using mobile data but with disabled iCloud Private Relay.

**Comment by lucassobralofc** [comment]
> minersmines

i see twice, and is all free in my system, try twice (no vpn plz)
cya!

**Comment by makerpro299** [comment]
Thank you, Latenz it has been working. I think it is solved, thank you so much.

**Comment by brooksr0** [comment]
I have the same issue You're using multiple accounts: Sap0174 Sap01742 Snicks1134 brooksr I am brooksr and i dont own theese other accounts
