### ISSUE TITLE
ESP32 is mining for a diffrent username NOT set in settings.h

### ISSUE THREAD

**Issue by wolfieboy09** [duino-coin/duino-coin#1836]
**Describe the bug**
I have the username set to my wallet, and in the ESP32, it is reporting to wallet "username". My wallet username is not "username." I went to my wallet, and it said no miners detected.

**To Reproduce**
I don't know how this happened. I just turned on captive portal

**Expected behavior**
For it to be getting from my wallet

**Screenshots/photos**
![image](https://github.com/user-attachments/assets/ee20b3dc-adc5-4288-a4be-a76ad776608a)

**System (please complete the following information):**
 - OS: Windows 11
 - Software Duinocoin ESP32 Miner
 - Version 4.3

**Additional context**
N/A

**Comment by wolfieboy09** [comment]
I fixed it by just reconfiguring it by the captive portal. No clue how that worked

**Comment by revoxhere** [comment]
If you have enabled the captive portal, then the string input in the code does not matter. What you input in the captive portal however, does. I'm happy to see you have managed to resolve it on your own though.
