### ISSUE TITLE
Bump libducohasher to 0.1.1

### ISSUE THREAD

**Issue by profpandaa** [duino-coin/duino-coin#1837]
I've updated (and optimized) the code for libducohasher. The SHA1 dependency was updated (the name changed from 'sha1' to 'sha1_smol'; iirc 'sha1' is now in the hands of rust-crypto).

The hashrate increased from 8.8 - 8.9 MH/s to 10.6 - 11 MH/s on one thread on my machine. 
The binary size will probably be marginally larger. However, when compiled with '--release', the binary takes up roughly 0.5 MB on my machine.

This change doesn't feature any breaking changes. The methods still have the same name and there's currently a miner running on my machine with the updated library.

**Comment by revoxhere** [comment]
Hey panda. I appreciate your work. Just to confirm, the repo you're referring to is compatible-libducohash?

**Comment by profpandaa** [comment]
Yes, exactly. The other one is (currently) outdated and contains breaking changes.

**Comment by seanganteng** [comment]
Hey how to compile you fasthash?

**Comment by profpandaa** [comment]
Try to keep off-topic conversations out of these issues.

I updated the readme, so just follow the one (1) step and you'll be good to go.

**Comment by revoxhere** [comment]
Hello panda.
I've updated the codebase on our server to your libducohash version.
The only thing left to do would be to create precompiles binaries for some commonly used architectures. For now the precompiles binaries are still the previous version before your edits.
Closing as it's done.
Thanks for your input!

**Comment by profpandaa** [comment]
Will do in the following days 👍
