### ISSUE TITLE
Server feedback typo.

### ISSUE THREAD

**Issue by kyngs** [duino-coin/duino-coin#24]
When you send funds to someone successfully, server responds with "Successfully transfered funds!" however, there is a typo in that sentence, the correct sentence is: "Successfully transferred funds!".

**Comment by kyngs** [comment]
I've wanted to fix it, however it looks like the server file is not on git anymore.

**Comment by revoxhere** [comment]
It is, but on branch useful-tools. But it's not up-to-date as server probably had some small changes since the time it was uploaded to git

**Comment by kyngs** [comment]
Yep, it is 12 days old.

**Comment by revoxhere** [comment]
Fixed
