### ISSUE TITLE
neither 1.6 nore 1.5 windows versions will install, and neither will the wallet files included with either

### ISSUE THREAD

**Issue by Pensive** [duino-coin/duino-coin#27]
Wallet gives me a script error, windows install window just vanishes and doesnt do anything.

Windows 10 fully updated

**Comment by kyngs** [comment]
Run it in command prompt and give us the exact error please.

**Comment by Pensive** [comment]
It's OK - I did that already - it does not work through a VPN :)

**Comment by Pensive** [comment]
Thanks - issue resolved - user stupidity :D
