### ISSUE TITLE
Compiling error with Arduino Code

### ISSUE THREAD

**Issue by jilliby4** [duino-coin/duino-coin#28]
When I try to load the Arduino Code I get the following error in the Arduino IDE software

In file included from sketch\backend.cpp:21:0:
sketch\sha1/sha1.c: In function 'sha1_hasher_gethash(sha1_hasher_s*)':
sketch\sha1/hash.c:165:5: warning: iteration 5 invokes undefined behavior [-Waggressive-loop-optimizations]
   a = hasher->state.words[i];
   ~~^~~~~~~~~~~~~~~~~~~~~~~~
sketch\sha1/hash.c:162:15: note: within this loop
  for(i = 0; i < 8; i++)
             ~~^~~
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\main.cpp: In function 'main':
sketch\sha1/hash.c:165:5: warning: iteration 5 invokes undefined behavior [-Waggressive-loop-optimizations]
   a = hasher->state.words[i];
     ^
sketch\sha1/hash.c:162:15: note: within this loop
  for(i = 0; i < 8; i++)
               ^
C:\Users\Andrew\AppData\Local\Temp\ccVCoxFU.ltrans0.ltrans.o: In function `write':
sketch/sha256.cpp:41: undefined reference to `sha256_hasher_putc(sha256_hasher_s*, unsigned char)'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Uno.

Please help

**Comment by revoxhere** [comment]
Thanks for submitting an issue.
Maybe @JoyBed will be able to help solve this for the future.
For now I'd recommend trying out Arduino Code from [Release 1.5](https://github.com/revoxhere/duino-coin/releases/tag/1.5) and see if it compiles

**Comment by jilliby4** [comment]
Thank you I will give it a try after work.

**Comment by jilliby4** [comment]
I have got 1.5 working for now thanks.

Can I have more than 1 arduino working at the same time? If so how do I include it on the miner?

**Comment by Bilaboz** [comment]
You can start the Arduino miner multiple times (in different directories)

**Comment by jilliby4** [comment]
Thanks I will give it a try

**Comment by JoyBed** [comment]
I gave the 1.6 some error corrections but its on @Revox to make them on
github. The question is if you are using the Linux or Windows version?

Dňa po 21. 9. 2020 o 1:36 jilliby4 <notifications@github.com> napísala(a):

**Comment by jilliby4** [comment]
Sorry I should have mentioned that I am on the Windows version

**Comment by revoxhere** [comment]
1.6 release has been updated by JoyBed, please re-download it and try compiling the code again

**Comment by jilliby4** [comment]
The new 1.6 is working now. Thank you all for your help.
