### ISSUE TITLE
Wallet does not seem to work on Windows and Linux

### ISSUE THREAD

**Issue by theAkito** [duino-coin/duino-coin#292]
Greetings,

first of all: thank you for the coin I was always waiting for. Great job!

I tried to open `Wallet.exe` in Windows 10 and `Wallet` on the newest stable NixOS, but neither do seem to work on their respective target systems. Since these are release builds, the exceptions disappear quickly and nothing is really said, besides that a file cannot be found.

I did not find any dependency requirement for the pre-built binaries, so I expect them to work out of the box.

Are there dependencies missing or are the builds not working for different reasons?

Thank you.

**Comment by revoxhere** [comment]
Hello, please use the 1.9 release for now because the 1.9.5 was compiled wrong and it has issues with launching. We will fix that in the upcoming version.

**Comment by theAkito** [comment]
Thanks. It seems to open now on Windows, but when I try to register, it tells me that my e-mail address is invalid. The validator should be probably a bit more lose. Does the service require an e-mail validation, by sending a verification e-mail? If yes, the e-mail addresses entered into the wallet do not need validation, except maybe for the `@` symbol...

**Comment by revoxhere** [comment]
I will look into that, for now, I'm closing this thread
