### ISSUE TITLE
Doesn't work on Raspberry

### ISSUE THREAD

**Issue by Maggi80** [duino-coin/duino-coin#297]
Hi Comunity,

i tried to run duino-coin on a RPI3 without success.
It says you don'T need python anymore but with the command: ./PC-Miner i get the following massage.
`-bash: ./PC_Miner: Permission denied`

So i gave permisson to the directory and files and got a new Massage.

`-bash: ./PC_Miner: cannot execute binary file: Exec format error`

Any Idea?

**Comment by kaiiwaii** [comment]
If it isn't solved early, use the source, the .py file.

**Comment by revoxhere** [comment]
`sudo chmod 777 PC_Miner && ./PC_Miner`

**Comment by revoxhere** [comment]
Oh, I just noticed, you're trying to run it on Raspberry Pi but the releases are for x86-64bit systems (not arm). You have to lanch the miner from the source code.
