### ISSUE TITLE
1.8 tft to show hashrate and balance

### ISSUE THREAD

**Issue by fellowmean5** [duino-coin/duino-coin#319]
Hello, i have a 1.8 tft spi oled display(128x160) st7735. Is it possible to show my hashrate of all miners and my balance?
Thanks!

**Comment by revoxhere** [comment]
Everything is possible with enough dedication, maybe you could just read miner data from the json api (http://51.15.127.80/api.json), balance from balance json api (http://51.15.127.80/balances.json) and display parts that interest you on the screen.

**Comment by fellowmean5** [comment]
Thanks
