### ISSUE TITLE
Encryption of the Server 🔐

### ISSUE THREAD

**Issue by nobodyinperson** [duino-coin/duino-coin#320]
Hi,

Nice project, this Duino-Coin. 👏

However, I wonder why the server and API over at http://51.15.127.80/ is unencrypted and doesn't use HTTPS? 🔐

This is the only thing that makes using Duino-Coin rather uncomfortable. 😕

Apart from Arduinos, all other devices (ESPs, Raspberry Pis and Desktops of course) support HTTPS. But Arduinos don't connect to the server directly, so that shouldn't be a problem.

So why is the server not encrypted? 🤷 (no offense, I'm just curious)

Cheers,

Yann

**Comment by revoxhere** [comment]
I don't know how to setup HTTPS. I've tried a few times but there always were problems. Also the websockets would have to be moved to wss to work on https.

**Comment by nobodyinperson** [comment]
I see. It is pretty easy to add HTTPS to a webserver like NGINX or Flask even. But you seem to use the raw sockets, I have never used those.

**Comment by hgecode** [comment]
I think the server uses Apache

**Comment by BastelPichi** [comment]
I already got revox to isntall certbot, but somehow domain redirects are not working for that server....

**Comment by BastelPichi** [comment]
There we Go: https://server.duinocoin.com
