### ISSUE TITLE
How does the „Kolka” System work?

### ISSUE THREAD

**Issue by nobodyinperson** [duino-coin/duino-coin#321]
I wonder how the Kolka system works.

Apart from the information that it seems to be [a town in Latvia](https://en.wikipedia.org/wiki/Kolka,_Latvia) and [this image](https://github.com/revoxhere/duino-coin/blob/master/Resources/kolkasystem.png) this doesn't seem to be documented anywhere.

How does it work? What's the exact formula behind it to calculate the reward?

**Comment by revoxhere** [comment]
I'll be documenting it soon, for now I haven't even finished deveolping it fully.

**Comment by nobodyinperson** [comment]
It seems the magic happens around [here](https://github.com/revoxhere/duino-coin/blob/useful-tools/Server.py#L949).

**Comment by NETLIFYHOSTINGAHMD** [comment]
wtf

**Comment by ghost** [comment]
ah yes ahmed

**Comment by ghost** [comment]
> wtf

i second this

**Comment by NETLIFYHOSTINGAHMD** [comment]
_BrandeilotAlgorithmsCompany_

**Comment by revoxhere** [comment]
Documented in the whitepaper: https://github.com/revoxhere/duino-coin/blob/gh-pages/assets/whitepaper.pdf
