### ISSUE TITLE
Open Source Server and API software

### ISSUE THREAD

**Issue by nobodyinperson** [duino-coin/duino-coin#322]
To make Duino Coin a **real** open source project, it would be necessary to also open source the server and API software. Maybe I missed it, but it doesn't seem to be available anywhere.

This would also answer #321 and make #320 easier as people could help. 

Really nice project BTW!

**Comment by revoxhere** [comment]
Server is open source, just in a separate brach to not make the master one even more bloated. https://github.com/revoxhere/duino-coin/blob/useful-tools/Server.py

**Comment by nobodyinperson** [comment]
Ah cool, I didn't see that. Thank you very much.
