### ISSUE TITLE
Using DuinoCoin for Timestamping ⏲️

### ISSUE THREAD

**Issue by nobodyinperson** [duino-coin/duino-coin#323]
There are services like https://originstamp.com or https://opentimestamps.org/ that offer [blockchain timestamping](https://sebastiaans.blog/why-timestamp-content-blockchain/) (basically putting a hash of a file into one or more blockchains as a matter of proving the file existed at a certain time).

Pretty much all of these services have one big problem: They can only timestamp documents so fast. For example, the fastest OriginStamp can do using Aion is 10 minutes. OpenTimestamps is around 10 hours AFAIK.

With DuinoCoins instant transactions, this would be a huge advantage and would make bulk timestamping of rather fast things (like git commits for example) viable.

The only thing the blockchain needs to provide is a means of putting some information into a transaction. With Bitcoin, that information can be a recieving address generated from the hash of the file(s) to timestamp. 

Would that work with DuinoCoin? Is it possible to somehow ”attach” information to a transaction? Or is everything just username-based? There are certainly hashes involved, but is it possible to control that hash to some degree?

This would be a super awesome usecase for DuinoCoin!

**Comment by revoxhere** [comment]
I was thinking of adding messages, even a simple memo message to the transactions and it won't be a hard task. I'll work on it and try to add it in the upcoming release.

**Comment by nobodyinperson** [comment]
But this message must be part of the tamper-proof blockchain somehow. It must be included in the proof-of-work, so maybe the message should be part of the SHA1 hash to find. The miners would then need to find `number` so that  `sha1(oldhash + number + message) == newhash`, if I understand it correctly.

**Comment by revoxhere** [comment]
Hmm. We'll see, I'm not sure if it'd be easy to add it to the PoW too

**Comment by nobodyinperson** [comment]
If it's not in the PoW, then it can't be used for timestamping.

**Comment by profpandaa** [comment]
Instead of sha1(oldhash + number + message) you could use sha1(oldhash + message + number) thus allowing to just make this a serversided update. And by forcing to have a small duco fee (idc how big it'd be, like if you're bulk timestamping, 2-3 ducos; if it's only a few maybe 5-10?) while that fee would be treated as a donation to the project itself you could create an artificial transaction to which you could attach your message/timestamp. (this is due to low transaction activity on duco rn)

**Comment by nobodyinperson** [comment]
Bulk timestamping doesn't introduce a longer `message`, you can use a Merkle Tree to condense your file hashes into one [like OriginStamp does](https://docs.originstamp.com/guide/originstamp.html#merkle-tree).

I'd recommend making the fee dependant on the length of the `message` as the miners need to process this bit of data more and it takes more processing time. Maybe the `message` could have an upper limit of 140 characters or so.

The timestamping with DUCO is just a nice side-effect of beeig able to add a comment to any transaction. The timestamping transaction itself could be made to the project itself (just because you need a transaction to put it into the blockchain) or to any other account.

This would require only very minimal changes in the system.

**Comment by nobodyinperson** [comment]
I wrongly assumed that DuinoCoin was blockchain-based (#325). Without a blockchain, timestamping with DuinoCoin does not make sense. Adding messages to transactions might still be a nice addition though, but that's rather something for a separate issue, then.
