### ISSUE TITLE
Downloading the DuinoCoin Blockchain 📥

### ISSUE THREAD

**Issue by nobodyinperson** [duino-coin/duino-coin#325]
Is it possible to download the DuinoCoin blockchain for inspection and verification?

This is a vital part of building trust into the system, that anyone can verify its integrity.

**Comment by ghost** [comment]
Duinocoin does not have a blockchain, it's centralized

**Comment by nobodyinperson** [comment]
Wait, being centralized doesn't conflict with it having a blockchain, right?

**Comment by nobodyinperson** [comment]
Well if it's not blockchain-based, then #323 doesn't make sense. I'd need to look into the server sources but surely @revoxhere can confirm whether DuinoCoin is blockchain-based or not.

**Comment by ghost** [comment]
how about you calm down for a sec

**Comment by profpandaa** [comment]
> Well if it's not blockchain-based, then #323 doesn't make sense. I'd need to look into the server sources but surely @revoxhere can confirm whether DuinoCoin is blockchain-based or not.

It's currently not blockchain-based, because there aren't enough transactions for the whole thing to work. The miners are currently just mining random hashes based on the prev hash

**Comment by nobodyinperson** [comment]
Alright, thanks for the clarification, I wondered what transactions all the miners were confirming. But now it makes sense.
