### ISSUE TITLE
Serial port didn't working on Raspberry PI

### ISSUE THREAD

**Issue by yan4ikyt** [duino-coin/duino-coin#351]
When rasp connect to Arduino, programm try to start mining thread, but programm reboots.
![Screenshot_20210404-213551_VNC Viewer](https://user-images.githubusercontent.com/59663838/113518267-dcaa2e80-958d-11eb-9507-d4ff8bb6999e.jpg)

**Comment by revoxhere** [comment]
I will investigate on my Pi in a moment

**Comment by yan4ikyt** [comment]
Ok

**Comment by revoxhere** [comment]
I've checked on my mini raspberry pi 3 laptop, and indeed there's something wrong when running AVR miner, as the response from arduino looks more or less like this: `b'*\xd5\xa2\xa2\xcaD\xc2:d\xd1\x9a\x8a\x92*\x81\x99\xf0\xc2\xa2\x12\xc5\x1a\xc2"\xe5\x8a*\xcd*\xd9"\xcd\x12\xd1\xca\xa2\xaa\x82\xfa'`. I will investigate further now.

**Comment by revoxhere** [comment]
Looks like the latest source code is more or less working, although not very stable. I will try to do something about it some time later.
![Screenshot_20210404_211956](https://user-images.githubusercontent.com/50244265/113519321-bd120680-958b-11eb-921f-d6950db124c3.png)

**Comment by yan4ikyt** [comment]
Ok thanks)

**Comment by revoxhere** [comment]
Welcome again, I've managed to fix the AVR mining on Raspberry pi mining - make sure you're using the [latest AVR Miner](https://github.com/revoxhere/duino-coin/blob/master/AVR_Miner.py) &  [new Arduino Code](https://github.com/revoxhere/duino-coin/tree/master/Arduino_Code). I'm closing this issue, if you'll still have any problems - reopen it.
![Screenshot_20210406_135942](https://user-images.githubusercontent.com/50244265/113707759-ab8e4300-96e0-11eb-85ae-e9f15e713c08.png)
