### ISSUE TITLE
Error Connecting to Server

### ISSUE THREAD

**Issue by luvtofish** [duino-coin/duino-coin#352]
While running AVR_Miner.py on Linux node connected to Arduino UNO. Has been working fine until today.

**Comment by ghost** [comment]
Try to use the v2.4. It should work.

**Comment by luvtofish** [comment]
I’m using it now, still not connecting.

**Comment by luvtofish** [comment]
![image](https://user-images.githubusercontent.com/20867664/113610173-600d6380-9612-11eb-8536-cc810e331332.png)

**Comment by revoxhere** [comment]
Hello, if you have python 3 installed, use the latest [AVR miner](https://github.com/revoxhere/duino-coin/blob/master/AVR_Miner.py) and burn the newest [Arduino code](https://github.com/revoxhere/duino-coin/tree/master/Arduino_Code) to your board, then it should wok.

**Comment by luvtofish** [comment]
Just re-installed from git clone of code. Still getting network errors and also had a python error on the import socket line. It didn't like the "close" on line #9. Here a screen shot of the errors. 
![image](https://user-images.githubusercontent.com/20867664/113723454-fc894180-96b6-11eb-94d8-40fbbd7bf7e3.png)

I removed "close" from line #9 to get it to run:
![image](https://user-images.githubusercontent.com/20867664/113723825-58ec6100-96b7-11eb-8e7c-4612bf81a69f.png)

**Comment by revoxhere** [comment]
Indeed that close isn't needed - I removed it from the code.
About the list index out of range - your arduino isn't submitting what it should.
Hard to say where the problem lies, maybe debug output will show more info

**Comment by luvtofish** [comment]
How to I turn on debug output?

**Comment by revoxhere** [comment]
Edit Miner_config.ini file and set `debug = y`

**Comment by luvtofish** [comment]
I found that line in the code. Thanks!

**Comment by luvtofish** [comment]
I've enabled debug but the output to screen is exactly the same. I'm not seeing any log file that would provide more detail?

UPDATE: I was setting debug in the wrong place. I've since corrected that and am getting the following output:
![image](https://user-images.githubusercontent.com/20867664/113729497-af0fd300-96bc-11eb-9ac9-85975e6e6fe2.png)

**Comment by luvtofish** [comment]
I should probably mention, I'm not running the precompiled binaries as my CENTOS 8 system does not have the required GLIBC2.29 lib. I'm executing the the AVR_Miner.py file from the command line using "python3 AVR_Miner.py".

**Comment by revoxhere** [comment]
It should work nonetheless, there's just something wrong when reading data from the arduino

**Comment by luvtofish** [comment]
I just moved the arduino from my centos 8 box over to my PC running windows. It's working under v2.3 on Windows. Switched back to centos 8 box and is now working again under v2.3. Is not working under v2.4 under Centos 8.

**Comment by revoxhere** [comment]
I will look into that more, some guy said that changing programmer in arduino IDE while burning the arduino code helped.

**Comment by revoxhere** [comment]
Should be fixed in release 2.4
