### ISSUE TITLE
Compile Using windows 10

### ISSUE THREAD

**Issue by PipeDeveloper** [duino-coin/duino-coin#353]
Hello

I have some issues by runnign PC_Miner on python in windows 10.

I have installed the latest version of python.

After run this command to install dependencies.
py -m pip install -r requirements.txt

It gives this error on my command line:
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-temuy_va\\cytoolz_c4849adb3bdc405bbb9f1bb25db50937\\setup.py'"'"'; __file__='"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-temuy_va\\cytoolz_c4849adb3bdc405bbb9f1bb25db50937\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Felipe Rojas Verasay\AppData\Local\Temp\pip-record-4_csc3at\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\Include\cytoolz'
         cwd: C:\Users\Felipe Rojas Verasay\AppData\Local\Temp\pip-install-temuy_va\cytoolz_c4849adb3bdc405bbb9f1bb25db50937\
    Complete output (50 lines):
    ALERT: Cython not installed.  Building without Cython.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.9\cytoolz
    creating build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.9\cytoolz
    creating build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.9\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    **error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/**
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-temuy_va\\cytoolz_c4849adb3bdc405bbb9f1bb25db50937\\setup.py'"'"'; __file__='"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-temuy_va\\cytoolz_c4849adb3bdc405bbb9f1bb25db50937\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Felipe Rojas Verasay\AppData\Local\Temp\pip-record-4_csc3at\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\Include\cytoolz' Check the logs for full command output.

I have download visual studios tools C++ but the issue persist

**Comment by PipeDeveloper** [comment]
python -m pip install tronpy

This install is doing the error

Also xxhash

**Comment by PipeDeveloper** [comment]
I have installed visual studios tools with C++ 2015 and now there is a new error

-packages (from httpcore==0.12.*->httpx<0.17.0,>=0.16.1->tronpy->-r requirements.txt (line 6)) (0.12.0)
Using legacy 'setup.py install' for cytoolz, since package 'wheel' is not installed.
Using legacy 'setup.py install' for parsimonious, since package 'wheel' is not installed.
Installing collected packages: cytoolz, parsimonious, httpcore, eth-utils, pycryptodome, httpx, eth-abi, tronpy
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-_uy_ibd2\\cytoolz_82249075e18441a7873ab28b62225d81\\setup.py'"'"'; __file__='"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-_uy_ibd2\\cytoolz_82249075e18441a7873ab28b62225d81\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Felipe Rojas Verasay\AppData\Local\Temp\pip-record-elwqtulz\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\Include\cytoolz'
         cwd: C:\Users\Felipe Rojas Verasay\AppData\Local\Temp\pip-install-_uy_ibd2\cytoolz_82249075e18441a7873ab28b62225d81\
    Complete output (56 lines):
    ALERT: Cython not installed.  Building without Cython.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.9\cytoolz
    creating build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.9\cytoolz
    creating build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.9\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\cytoolz
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\include -IC:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt /Tccytoolz/dicttoolz.c /Fobuild\temp.win-amd64-3.9\Release\cytoolz/dicttoolz.obj
    dicttoolz.c
    C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\include\pyconfig.h(200): fatal error C1083: No se puede abrir el archivo incluir: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-_uy_ibd2\\cytoolz_82249075e18441a7873ab28b62225d81\\setup.py'"'"'; __file__='"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-_uy_ibd2\\cytoolz_82249075e18441a7873ab28b62225d81\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Felipe Rojas Verasay\AppData\Local\Temp\pip-record-elwqtulz\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\Include\cytoolz' Check the logs for full command output.

C:\Users\Felipe Rojas Verasay\Desktop\duino-coin-master>

**Comment by revoxhere** [comment]
This tronpy stuff is only needed if you intend on using ~~voidDUCO~~ wDUCO wrapper. You should be able to get the software working by just launching it - it should install needed dependencies automatically.

**Comment by Bilaboz** [comment]
Can you try to install `cython` and try again

**Comment by PipeDeveloper** [comment]
@Bilaboz done installed cython, but the error persist.

Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-487lerzk\\cytoolz_79513a57c2274428b4369cf74d295e15\\setup.py'"'"'; __file__='"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-487lerzk\\cytoolz_79513a57c2274428b4369cf74d295e15\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Felipe Rojas Verasay\AppData\Local\Temp\pip-record-pd7fq1er\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\Include\cytoolz'
         cwd: C:\Users\Felipe Rojas Verasay\AppData\Local\Temp\pip-install-487lerzk\cytoolz_79513a57c2274428b4369cf74d295e15\
    Complete output (60 lines):
    [1/5] Cythonizing cytoolz/utils.pyx
    [2/5] Cythonizing cytoolz/dicttoolz.pyx
    [3/5] Cythonizing cytoolz/functoolz.pyx
    [4/5] Cythonizing cytoolz/itertoolz.pyx
    [5/5] Cythonizing cytoolz/recipes.pyx
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.9\cytoolz
    creating build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.9\cytoolz
    creating build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.9\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\cytoolz
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\include -IC:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt /Tccytoolz/dicttoolz.c /Fobuild\temp.win-amd64-3.9\Release\cytoolz/dicttoolz.obj
    dicttoolz.c
    C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\include\pyconfig.h(200): fatal error C1083: No se puede abrir el archivo incluir: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-487lerzk\\cytoolz_79513a57c2274428b4369cf74d295e15\\setup.py'"'"'; __file__='"'"'C:\\Users\\Felipe Rojas Verasay\\AppData\\Local\\Temp\\pip-install-487lerzk\\cytoolz_79513a57c2274428b4369cf74d295e15\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Felipe Rojas Verasay\AppData\Local\Temp\pip-record-pd7fq1er\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Felipe Rojas Verasay\AppData\Local\Programs\Python\Python39\Include\cytoolz' Check the logs for full command output.

**Comment by PipeDeveloper** [comment]
@revoxhere if i run PC_miner.py actually nothing happen, it just output this

C:\Users\Felipe Rojas Verasay\Desktop\duino-coin-master>python PC_Miner.py
09:11:57 Xxhash is not installed. Continuing without xxhash support.
Traceback (most recent call last):
  File "C:\Users\Felipe Rojas Verasay\Desktop\duino-coin-master\PC_Miner.py", line 1181, in <module>
    title(getString("duco_python_miner") + str(minerVersion) + ")")
  File "C:\Users\Felipe Rojas Verasay\Desktop\duino-coin-master\PC_Miner.py", line 186, in title
    system("title " + title)
TypeError: system() takes 0 positional arguments but 1 was given

**Comment by revoxhere** [comment]
Download the latest code. It should be fixed in it. I forgot to change windows-related import.

**Comment by PipeDeveloper** [comment]
working! thank you very much
