### ISSUE TITLE
Web wallet not opening in my mobile..

### ISSUE THREAD

**Issue by Saikatsaha1996** [duino-coin/duino-coin#356]

**Comment by revoxhere** [comment]
Can you provide some more information?

**Comment by Saikatsaha1996** [comment]
> Can you provide some more information?
After clicking register ... Not respond anything pc and my mobile also...
I want to register my new account but I am unable to register .... 

![Screenshot_2021-04-10-16-07-44-761_com whatsapp](https://user-images.githubusercontent.com/72664192/114266974-fa0c4c00-9a16-11eb-8ec0-2610c7d17f7b.jpg)

**Comment by revoxhere** [comment]
Your browser either blocks connection to the server or doesn't support websockets or entirely javascript. Use the desktop wallet.

**Comment by Saikatsaha1996** [comment]
![Screenshot_2021-04-10-18-07-58-022_com termux](https://user-images.githubusercontent.com/72664192/114270077-0f3da680-9a28-11eb-93da-5ac8186a0f44.jpg)
And now showing this problem ☹️
