### ISSUE TITLE
some suggestions with love!

### ISSUE THREAD

**Issue by suifengtec** [duino-coin/duino-coin#363]
it's a cool project, some suggestions: 

1. domain ext from com to io or org; 
2. push main site and wallet site frontend codes and i18n package to github; 
3. avoid to use uncommon words on any UI.

**Comment by revoxhere** [comment]
1. Write to @Tech1k as he is hosting the duinocoin.com website
2. What is i18n? Web wallet, web miner codes are available [here](https://github.com/revoxhere/playground) and the main site is on the [gh-pages branch](https://github.com/revoxhere/duino-coin/tree/gh-pages). Everything is open-source - don't worry.
3. What do you specifically mean by uncommon words?

**Comment by suifengtec** [comment]
@revoxhere i18n=internationalization

**Comment by revoxhere** [comment]
I still don't know what do you mean

**Comment by suifengtec** [comment]
let more people play it with their mother tongue or mother language.

**Comment by revoxhere** [comment]
About the websites - I don't know how to make a translation system for the web so I won't be able to work on that. About the python apps like wallet or the miners - the translations are available here:
* https://github.com/revoxhere/duino-coin/blob/master/Resources/PC_Miner_langs.json
* https://github.com/revoxhere/duino-coin/blob/master/Resources/AVR_Miner_langs.json
* https://github.com/revoxhere/duino-coin/blob/master/Resources/Wallet_langs.json
