### ISSUE TITLE
Cannot register (CLI Wallet, GUI Wallet & Website)

### ISSUE THREAD

**Issue by charles-marceau** [duino-coin/duino-coin#364]
I'm trying to register but it seems there is an error with the server. I tried using all 3 methods to create an account but they all failed when submiting to the websocket. Here are the error messages:

### CLI_Wallet.py
`Traceback (most recent call last):
  File "/home/username/duino-coin-2.3/CLI_Wallet.py", line 406, in <module>
    s.send(bytes(
BrokenPipeError: [Errno 32] Broken pipe`

### Wallet.py
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/username/duino-coin-2.3/Wallet.py", line 430, in _registerprotocol
    message=response[1])
IndexError: list index out of range
```

### Website
There is not any output on the website. However, the websocket does not respond after sending the register request.

**Comment by suifengtec** [comment]
try more times via GUI wallet.

**Comment by charles-marceau** [comment]
Thank you but I keep trying and there is no change. Same error message. I'll just wait I'm in no rush. Maybe its a server-side bug.

**Comment by revoxhere** [comment]
Try now.

**Comment by charles-marceau** [comment]
It tried with CLI_Wallet.py and got the same error. I then tried with the website and it worked first time. Thank you!

**Comment by TusharChillal** [comment]
Hey i want to create a wallet but i am unable to create please help me.

**Comment by Dragonfyre11** [comment]
I have tried the gui wallet and the web wallet. GUI says Error registering user Please use the web wallet. Wallet.duino.com. I tried the web wallet first and when you type all your info in and verify your human, it just hangs there forever. I tried with multiple devices, multiple networks, multiple different usernames and passwords and email address. Just hangs. Please help!
