### ISSUE TITLE
wallets(PC & CLI versions) may need their own config files instead of hardcode i18n info.

### ISSUE THREAD

**Issue by suifengtec** [duino-coin/duino-coin#366]
wallets(PC & CLI versions) may need their own config files instead of hardcode i18n info.

PC_Wallet has none config file :

![pc_wallet](https://i.imgur.com/qN8UnDJ.jpg)

PC_Miner has its own config file and working fine:

![pc_miner](https://i.imgur.com/uDKcbUJ.jpg)

**Comment by revoxhere** [comment]
It has a config inside the .db file, I will try to make a language selector for it later though

**Comment by Bilaboz** [comment]
You can now select the language in the configuration file
