### ISSUE TITLE
Issues with ESP8266 and ESP32

### ISSUE THREAD

**Issue by Bruce17** [duino-coin/duino-coin#367]
Hi,
I installed the latest version on a ESP8266 and ESP32 and both have trouble to connect to the backend server. Is it down at the moment?

ESP8266
```
Duino-Coin ESP8266 Miner v2.4
Connecting to: <SSID>
.
Connected to WiFi!
Local IP address: <IP>

Connecting to Duino-Coin server...
Connection failed.
Resetting ESP...

 ets Jan  8 2013,rst cause:2, boot mode:(3,1)
[core dump and restart]
```

ESP 32
```
Duino-Coin ESP32 Miner v2.3
Connecting to: <SSID>
.....
Connected to WiFi!
Local IP address: <IP>

CORE1 Connecting to Duino-Coin server...
[E][WiFiClient.cpp:288] setSocketOption(): 1006 : 9
[E][WiFiClient.cpp:258] connect(): socket error on fd 54, errno: 104, "Connection reset by peer"
CORE1 is connected: 0

[core dump and restart]
```

**Comment by revoxhere** [comment]
I've just checked on my ESP8266 running the 2.4 code and it seems to work fine.

**Comment by Bruce17** [comment]
Ok seems to work now. Maybe a status page for the backend service is an idea similar to e.g. [GitHub's status page](https://www.githubstatus.com/)?

**Comment by revoxhere** [comment]
I'll think about it later, but these problems aren't often and there's a status checker on the discord
