### ISSUE TITLE
Web wallet doesn't show miners

### ISSUE THREAD

**Issue by endre90** [duino-coin/duino-coin#371]
Hi,

web wallet shows "no miners detected". 
Should this show my named rigs and their hash rates?

Best,
Endre

**Comment by revoxhere** [comment]
Yes, something's wrong - looks like the wrong IP was put for the API in the latest update. I'll try to do something about it

**Comment by Bruce17** [comment]
The wallet runs on an HTTPS domain and tries to load `http://51.15.127.80/api.json` from a HTTP domain. Chrome throws "mixed content" and CORS errors. Either set proper CORS headers or serve the files from the same domain.

**Comment by LDarki** [comment]
Fixed on commit https://github.com/revoxhere/playground/commit/a4327a3162b7a39e1256c4809ad8846d13f81231
Please wait for the update

**Comment by revoxhere** [comment]
Fixed now
