### ISSUE TITLE
PC Wallet does not show ESTIMATED PROFIT sometime

### ISSUE THREAD

**Issue by suifengtec** [duino-coin/duino-coin#372]
PC Wallet does not show ESTIMATED PROFIT sometime.

![pc wallet](https://i.imgur.com/0xEIiIW.jpeg)

**Comment by suifengtec** [comment]
@revoxhere oops! why delete the README_zh_CN.md ...

**Comment by LDarki** [comment]
The estimated profit is calculated when you receive 2 different money values, therefore if they make a transfer it will give you a different estimated profit, anyway, it is calculated by your client so until you have a different money value it will not come out

**Comment by LDarki** [comment]
Pd: If there is an error, it will not show you the estimated profit

**Comment by revoxhere** [comment]
Latest source code version should have already fixed that, I'll be releasing 2.4 soon as binaries

**Comment by revoxhere** [comment]
Should be fixed in 2.4
