### ISSUE TITLE
AVR Miner doesn't work on Raspberry

### ISSUE THREAD

**Issue by MaxiDoet** [duino-coin/duino-coin#373]
I connected an arduino uno to my raspberry pi and ran avr_miner.py but it keeps saying:

![image](https://user-images.githubusercontent.com/38401902/114568798-bdd62700-9c74-11eb-886b-95012032c4c6.png)

Btw. ignore the 'debug' message i tried to fix it myself. 

On my desktop pc (windows) it works.
uploadavrminer.py works too (on the pi)

Note: The rx led flashes frequently (every 3secs) on the arduino

My Specs:
Raspberry Pi 4B 8GB
Raspbian OS 32bit

**Comment by revoxhere** [comment]
Have you uploaded the 2.4 Arduino code to your board?

**Comment by MaxiDoet** [comment]
what do you mean? I cloned duino-coin and then executed upload.....py. Its weird cause i've already worked with PySerial and it worked even on the pi

Edit: Ah do you mean the release version. I only see 2.3 and some beta branches

**Comment by revoxhere** [comment]
The upload script has the outdated arduino code compiled, @hgecode will need to work on that. Please upload the newest Arduino Code using Arduino IDE for now and then it should work

**Comment by MaxiDoet** [comment]
ah ok i'll try that

Edit: You mean the hex file is older right?

**Comment by revoxhere** [comment]
Yes

**Comment by MaxiDoet** [comment]
How can i get 2.4?

**Comment by revoxhere** [comment]
https://github.com/revoxhere/duino-coin/tree/master/Arduino_Code

**Comment by MaxiDoet** [comment]
Ok now it works thank you😀

![image](https://user-images.githubusercontent.com/38401902/114670917-ca559080-9d03-11eb-990d-5763e826440d.png)
