### ISSUE TITLE
BAD TOO MANY CONNECTIONS for one connected miner

### ISSUE THREAD

**Issue by Bruce17** [duino-coin/duino-coin#374]
Hi,
yesterday I started up 5 ESP as miners which I had lying around. Today I noticed almost none was mining anymore, only one. In the [api](http://51.15.127.80/api.json) overview page I can see only one miner connected. If I connect a second one I receive the error `TOO MANY CONNECTIONS` which is either caused by [Server.py#L979](https://github.com/revoxhere/duino-coin/blob/useful-tools/Server.py#L979) or [Server.py#L988](https://github.com/revoxhere/duino-coin/blob/useful-tools/Server.py#L988).

To me it seems that hanging clients or not properly disconnected clients are not removed from the internal counter (code [Server.py#L2418:L2432](https://github.com/revoxhere/duino-coin/blob/useful-tools/Server.py#L2418:L2432).

Maybe some similar code to https://github.com/revoxhere/duino-coin/blob/useful-tools/Server.py#L2436 is required to do a final cleanup or check in intervals if no user data exists anymore e.g. `COUNT( minerapi[x]["User"] == "foo" ) == 0` (dummy code).

Even restarting my router to force a IP refresh did no help. Therefore I assume the code at [Server.py#L2426:L2432](https://github.com/revoxhere/duino-coin/blob/useful-tools/Server.py#L2426:L2432) is not finaly triggered and results in `workers[username] > 0` for zero actual connected clients.

I also tried to connect to Discord to see if anyone else has that issue, but it shows me some weird french error message 🤷‍♂️:
![image](https://user-images.githubusercontent.com/5036995/114580130-e2370100-9c7e-11eb-93c6-01cff82f92ff.png)

**Comment by revoxhere** [comment]
The decementers are triggered, but only after either the connection is properly closed or the connection times out. I'm not sure what to do about it.
About the Discord - someone forgot to disable raidmode. I'm not on the server currently so I can't disable it.

**Comment by Bilaboz** [comment]
Raidmode has been disabled

**Comment by Bruce17** [comment]
@revoxhere I think there was on break in the last exception which caused the thread to stop before cleaning up everything

**Comment by revoxhere** [comment]
Possible. But I think your PR and some of my changes solved it now

**Comment by Bruce17** [comment]
I noticed that there a two more places where a counter reset is missing and might cause issue if a connection is broken.

**Comment by nigeljohnson73** [comment]
With this being closed, that would mean it's fixed? I'm running 2.5.5 on my ESP32 miners, and I'm still getting the error after some network issues on my broadband. It's been several hours so is there a way to manually clear it? When I query the server statistics, it says I only have 4 active miners... Even if that the 4 ESP32 chips, that's 8 connections... well under 50.
