### ISSUE TITLE
Problems creating account for wallet creation

### ISSUE THREAD

**Issue by techbytesrn** [duino-coin/duino-coin#377]
The registration page for creating a wallet account appears to be having a problem.
I have tried several different user names and a variety of passwords to create a wallet account.
I have also tried mixed case, all lower case, mixed case with special characters.
I went to the link https://wallet.duinocoin.com/ which then redirects to a non-ssl link.
After clicking the register button, I only see a "Proxy server online" message at the bottom of the window after a few seconds.
unable to create an account at this point.

**Comment by LDarki** [comment]
Please try using 
https://wallet.duinocoin.com/register

**Comment by techbytesrn** [comment]
Tried the link.  I filled in the information and click on register.
nothing happens.

Ron

**Comment by Bilaboz** [comment]
We're currently experiencing a bug with registration, we're working on it

About the non ssl links, changes have been made https://github.com/revoxhere/playground/commit/ca870430d4a8f85bc449ad12f47e5650044f8251 and will take effect soon

**Comment by techbytesrn** [comment]
Thanks for update.
Will try again later.

Ron

**Comment by revoxhere** [comment]
Should be fixed now.

**Comment by techbytesrn** [comment]
Thanks for helping with this.
i have created an account without any issue.
Will be able to proceed with creating several videos for my Youtube channel
showing how to mine Duino.

Ron

**Comment by Akhmadihin** [comment]
I cannot create account, i press button 'register' and they write 'You're using multiple accounts: stromz Akhmadihin Artzr Akhmadishin rar artur artar qetuo Fritz AAAA aaaa brtur akhmadishin Uno wasd ARTUR aRTUR Artur1511 Artur151112, this is not allowed Please try again' i'll try this and they write it again

**Comment by lucassobralofc** [comment]
> I cannot create account, i press button 'register' and they write 'You're using multiple accounts: stromz Akhmadihin Artzr Akhmadishin rar artur artar qetuo Fritz AAAA aaaa brtur akhmadishin Uno wasd ARTUR aRTUR Artur1511 Artur151112, this is not allowed Please try again' i'll try this and they write it again

@Akhmadihin ,
It seems that you're encountering an issue with creating an account due to the presence of multiple accounts associated with your name. According to our terms, the use of multiple accounts is not permitted. I recommend joining our [Discord server](https://duinocoin.com/discord) to discuss this issue further and gain more clarity on the matter.

Thank you for your understanding.
