### ISSUE TITLE
error creating account or login in CLI_Wallet

### ISSUE THREAD

**Issue by ghost** [duino-coin/duino-coin#379]
The error “list index out of range” arises if you access both sector
under line 366
Enter your password: 
Traceback (most recent call last):
  File "CLI_Wallet.py", line 366, in <module>
    + str(loginFeedback[1]))
IndexError: list index out of range

**Comment by BastelPichi** [comment]
Try to use a stronger Password(Big letters, small letters, special signes(!"§$etc.),numbers)

**Comment by BastelPichi** [comment]
And/Or use a different wallet

**Comment by BastelPichi** [comment]
Does it work now?

**Comment by ghost** [comment]
It's working but not smooth still persist alot connection error

Cannot connect to the server. It is probably under maintenance or temporarily down.
Retrying in 15 seconds.
