### ISSUE TITLE
arduino-DuinoCoin Library

### ISSUE THREAD

**Issue by ricaun** [duino-coin/duino-coin#381]
Hello @revoxhere 

I decided to create a library to make the Arduino code more clear and easy to maintain.

* https://github.com/ricaun/arduino-DuinoCoin

The current version only works with Arduino_Code V2.4

The idea is to add the ESP8266, ESP32, and other microcontrollers in one library to make the `ducos1a` more simple.

See yaa!

**Comment by revoxhere** [comment]
Damn, interesting idea of making it like this :) Maybe we will integrate it

**Comment by JoyBed** [comment]
This looks freakin interesting! The lib can be used as multiarchitecture as you said. So it can run on Arduinos with AVR, ARM(like the Due), STM32, ESP8266, ESP32.... Maybe in the future I will add more microcontrollers but I dont have any other bought.

**Comment by ricaun** [comment]
> 
> 
> This looks freakin interesting! The lib can be used as multiarchitecture as you said. So it can run on Arduinos with AVR, ARM(like the Due), STM32, ESP8266, ESP32.... Maybe in the future I will add more microcontrollers but I dont have any other bought.

That's the ideia to make possible to add more `Arduinos` boards, I update and add a simple code to the Esp8266, and gonna finish the Esp32 support.

* https://github.com/ricaun/arduino-DuinoCoin/tree/main/examples/ESP8266_Code

I don't know if the system is unstable but sometimes I hard to validate the code.

**Comment by revoxhere** [comment]
@joaquinbvw is working on a similar library that we will probably officially use. I'll let you know if you'll be able to help with it

**Comment by revoxhere** [comment]
We may reach out later, for now - closing
