### ISSUE TITLE
Miner keeps stopping

### ISSUE THREAD

**Issue by MaxiDoet** [duino-coin/duino-coin#382]
My miner always stopps after a few hours or only mines on one avr/cpu thread

My Specs:
Raspberry Pi 3b (it also happens on windows or the pi 4)
Raspbian OS Lite 32bit

**Comment by revoxhere** [comment]
possibly fixed in https://github.com/revoxhere/duino-coin/commit/b8cfc5a7b5bfbabb62aed4112e454e340230762a
