### ISSUE TITLE
Miners lose connection and don't reconnect

### ISSUE THREAD

**Issue by endre90** [duino-coin/duino-coin#384]
Hi,

I prepared several machines to mine and I have been doing so for a few days. 
No matter which algorithm I use or what type the machine it is, all of them lose connection at one point and stop mining. 
No machine was able to mine for longer than 8 hours without me having to restart the miner.
I start mining on all machines, go to sleep, and in the morning none of them mine because they lost connection at one point. 
I can solve this for myself using a combination of ssh, screen and crontab, in order to restart the Miners every hour.
However, it would be nice to have a more robust reconnection procedure that is inbuilt.
Does anybody else have this issue?

Best,
Endre

**Comment by revoxhere** [comment]
Hey, we know of this issue and we're working on it. Please stay tuned for updates.

**Comment by revoxhere** [comment]
Should be fixed in release 2.4
