### ISSUE TITLE
Error loading Python lib '/tmp/_MEIBa354u/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIBa354u/libpython3.8.so.1.0)

### ISSUE THREAD

**Issue by ste-t** [duino-coin/duino-coin#386]
When I try to start PC_Miner on debian buster it says **Error loading Python lib '/tmp/_MEIBa354u/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIBa354u/libpython3.8.so.1.0)**

**Comment by revoxhere** [comment]
Are you using non 64 bit OS?

**Comment by tezano** [comment]
same here. 64 bit OS

**Comment by tezano** [comment]
same here, im using vps and im not sure its 32/64bit OS

**Comment by revoxhere** [comment]
Can you guys provide more info about your systems?

**Comment by tezano** [comment]
what u need ?

**Comment by BastelPichi** [comment]
Try to install the latest version with "sudo apt-get install r-base-core"

**Comment by tezano** [comment]
not working bro

**Comment by BastelPichi** [comment]
Do you use the python file or the executable?

**Comment by tezano** [comment]
./PC_Miner

thats the command im using

**Comment by BastelPichi** [comment]
What happenens when you run the source code version?

**Comment by tezano** [comment]
what u mean bro ? i dont understand

**Comment by BastelPichi** [comment]
> what u mean bro ? i dont understand

Download the source code from the releases, unzip it and run: python3 PC_Miner.py ...

**Comment by ste-t** [comment]
> Are you using non 64 bit OS?

Hi (sorry for the inactivity), these are my system informations:

OS: Debian GNU/Linux 10 (buster) x86_64 
Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) 
Kernel: 4.19.0-14-amd64 
Packages: 763 (dpkg) 
Shell: bash 5.0.3 
Terminal: /dev/pts/0 
CPU: AMD EPYC 7282 16- (4) @ 2.794GHz 
GPU: VMware SVGA II Adapter 
Memory: 5263MiB / 7978MiB

It's a VPS: tezano's got the same problem with a VPS, so maybe it has something to do with virtualization

**Comment by revoxhere** [comment]
Launch the softwares from the source code, looks like it's a different architecture.
