### ISSUE TITLE
mining err: list index out of range after 1 hour of mining

### ISSUE THREAD

**Issue by upttiunej** [duino-coin/duino-coin#388]
01:42:28  net0  Error while mining - most likely a connection error - restarting in 5s. **(mining err: list index out of range)**
01:42:43  net2  Error retrieving data from GitHub! Retrying in 10s. (git err: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /revoxhere/duino-coin/gh-pages/serverip.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75bda690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
**_..... 2 HAOURS LATER_**
03:26:23  net0  Error retrieving data from GitHub! Retrying in 10s. (git err: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /revoxhere/duino-coin/gh-pages/serverip.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75c4a070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))

**Comment by revoxhere** [comment]
Failed to establish a new connection: [Errno -3] Temporary failure in name resolution means something on your side is blocking acces to github.

**Comment by upttiunej** [comment]
yep. fix it after rebooting my router.
