### ISSUE TITLE
AVR Miner error

### ISSUE THREAD

**Issue by 0jk6** [duino-coin/duino-coin#389]
This is the error I got when I ran avr_miner.py file.

```Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\python\duino-coin\AVR_Miner.py", line 867, in AVRMine
    raise Exception("Empty data")
Exception: Empty data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jaych\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\jaych\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\python\duino-coin\AVR_Miner.py", line 884, in AVRMine
    comConn = connectToAVR(com)
  File "D:\python\duino-coin\AVR_Miner.py", line 258, in connectToAVR
    comConn = serial.Serial(
  File "C:\Users\jaych\AppData\Local\Programs\Python\Python38\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\jaych\AppData\Local\Programs\Python\Python38\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\jaych\AppData\Local\Programs\Python\Python38\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM4': PermissionError(13, 'Access is denied.', None, 5)```

How do I fix it?

![Here is the screenshot](https://user-images.githubusercontent.com/58852543/115038195-eb2d0a00-9eec-11eb-9e56-6e4f98714636.PNG)

**Comment by revoxhere** [comment]
Try running the miner as an administrator, looks like windows isn't allowing the access

**Comment by 0jk6** [comment]
I tried that way too and it didn't work.

**Comment by BastelPichi** [comment]
> I tried that way too and it didn't work.

A) run the .exe or B) make shure python is added to your path

**Comment by 0jk6** [comment]
@BastelPichi  Wow it did not work!!! How did I get those Traceback and Exception Handling errors if I don't have python in my path? There's something odd with either the code or my board. 

Hey, @revoxhere I don't have much experience with AVR boards, I previously used it to program an AT89S52 microcontroller using SPI. Will re-burning the bootloader onto my board fix the issue?

**Comment by BastelPichi** [comment]
>     raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
> serial.serialutil.SerialException: could not open port 'COM4': PermissionError(13, 'Access is denied.', None, 5)```
There different errors. This one means most likely that theres a different application using the board like the serial monitor...

**Comment by 0jk6** [comment]
@BastelPichi Yes, the very first thought in my head was about the serial monitor reading the COM4 port. I quit the Arduino application then disabled and enabled the COM4 port from the device manager and ran the avr_miner.py, but still, I got the same error. I followed a couple of StackOverflow answers and they didn't work too. It gave me the same error again and again.

**Comment by BastelPichi** [comment]
> @BastelPichi Yes, the very first thought in my head was about the serial monitor reading the COM4 port. I quit the Arduino application then disabled and enabled the COM4 port from the device manager and ran the avr_miner.py, but still, I got the same error. I followed a couple of StackOverflow answers and they didn't work too. It gave me the same error again and again.

Did you run it via cmd or jusz doubleclick?

**Comment by 0jk6** [comment]
I ran it using ```python3 avr_miner.py``` in the command line. What's the difference in running it via double click. As the program is in a loop sending and receiving bytes using sockets, the command line won't close even if we double click. Are you trying to solve the issue or trying to ask me all the unnecessary stuff?

**Comment by revoxhere** [comment]
Hello, while Pichi's tips may not be relevant to this problem, I'm not sure what else to suggest too. Some guy said that re-flashing the code helped.

**Comment by 0jk6** [comment]
@revoxhere ah, thanks! will try that.

**Comment by 0jk6** [comment]
hey @revoxhere It worked after re-burning the bootloader onto the chip.
