### ISSUE TITLE
AVR Miner getting error with COM3 port

### ISSUE THREAD

**Issue by techbytesrn** [duino-coin/duino-coin#391]
Trying to troubleshoot by moving to another USB port.  How to I get the software to go through a reconfiguration process so I can move it to another USB port?  

Looking for info online.  Didnt find any information online with this information.
Tried to get on the discord server but got an error about discord being unable to accept the invite.

**Comment by revoxhere** [comment]
You can remove the configuration file (AVRMiner_2.4_resources/Miner_config.ini) or edit it manually

**Comment by techbytesrn** [comment]
Thanks for the reply.
Still ended up having the same error after recreating the config file
(which had a .cfg in my case).
Here is what I was seeing on the screen -
14:49:51  usb3  Arduino is taking longer than expected, sending it a new
job  (errorCounter > 5: Empty data)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "AVR_Miner.py", line 867, in AVRMine
Exception: Empty data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "threading.py", line 892, in run
  File "AVR_Miner.py", line 884, in AVRMine
  File "AVR_Miner.py", line 258, in connectToAVR
  File "serial\serialwin32.py", line 33, in __init__
  File "serial\serialutil.py", line 244, in __init__
  File "serial\serialwin32.py", line 64, in open
serial.serialutil.SerialException: could not open port 'COM3':
PermissionError(13, 'Access is denied.', None, 5)

I when made sure all of the windows updates were applied.
I also applied the latest bios updates.
Still had the problem.

As a last ditch effort, I decided to re-upload the arduino code to the R3.
That fixed the problem.
I am new to the Arduino family, so having the figure out the
troubleshooting process.

Thought I would pass this on in case you could use it in a troubleshooting
FAQ on your site.

Thanks,
Ron
