### ISSUE TITLE
Low success rate?

### ISSUE THREAD

**Issue by endre90** [duino-coin/duino-coin#396]
Hi,

the new release seems to have solved the re-connection error, miners are working on several machines for > 24 hours.
However, it seems like the success rate has dropped. Let's take 3 machines as an example. After mining for 24 hours, there were more failed attempts than solved instances. Machine 1 has dropped to 45% success rate, machine 2 to 37% and machine 3 to 31%.

The reasons are the following:
    1. Error connecting to the server. Retrying in 10s (net err: timed out)
    2. Error while mining - most likely a connection error - restarting in 5s. (mining err: list index out of range)
    3. ✗ Rejected
    4. Error while mining - most likely a connection error - restarting in 5s. (mining err: [Errno 32] Broken pipe)
    5. Error connecting to the server. Retrying in 10s (net err: [Errno 111] Connection refused)
    6. Error while mining - most likely a connection error - restarting in 5s. (mining err: [Errno 104] Connection reset by peer)
    7. Error while mining - most likely a connection error - restarting in 5s. (mining err: timed out)
    
The most common reasons are 2, 3 and 5. Is such a low success rate expected or is something else happening?

Best Regards,
Endre

**Comment by revoxhere** [comment]
Most of them are caused by internal server errors which I'm slowly fixing, just wait :P
