### ISSUE TITLE
✗ Rejected

### ISSUE THREAD

**Issue by endre90** [duino-coin/duino-coin#397]
Hi,

for the last 1 hour, the success rate is 0% on all machines. 
Here is an example from one machine, all results are incorrect: 

✗ Rejected 2/703 (0%) ∙ 18.94s ∙ 0.89 MH/s @ diff 118090 ∙ ping 21ms

Why does this happen?

Best,
Endre

**Comment by endre90** [comment]
Solved it by increasing the difficulty to NET.

**Comment by revoxhere** [comment]
Ah, I know - Kolka V3 isn't fully implemented and instead of moving miner to the right diff it just rejects its shares. I will fix that soon.
