### ISSUE TITLE
More Errors in AVR Miner...

### ISSUE THREAD

**Issue by ArduinoMiner** [duino-coin/duino-coin#398]
Fourtunataly more errors have appeared...
![IMG_20210417_180545](https://user-images.githubusercontent.com/82709754/115120163-d2f6d280-9f60-11eb-863c-84c6b01839b6.jpg)
![IMG_20210417_183415](https://user-images.githubusercontent.com/82709754/115120239-4ef11a80-9f61-11eb-8886-249b45db6d38.jpg)

**Comment by revoxhere** [comment]
Looks like a board connection issue, I'm not sure what to suggest in that case

**Comment by revoxhere** [comment]
Latest AVR miner fix should restart the board after this error, release version of this will be pushed soon.
