### ISSUE TITLE
new account can not be registered  ,it says conecting to proxy .

### ISSUE THREAD

**Issue by badbabil** [duino-coin/duino-coin#399]
I'm a new user and I couldn't register a new account I tried with  the web browser from different devices, still not happening .

**Comment by badbabil** [comment]
I live in India, is it the reason why there is an error creating a new account? ,
I tried the user name and password with a combination of capital letters, small letters, and symbols ... help to fix that

**Comment by revoxhere** [comment]
Try now. it should work

**Comment by badbabil** [comment]
thank you so much. it really did worked
