### ISSUE TITLE
Unable to Register

### ISSUE THREAD

**Issue by gam3t3chelectronicshobbyhouse** [duino-coin/duino-coin#4]
Attempting to run the wallet setup both on linux, pc and they both freeze up. I have to force quit it each time.  It allows me to create user name and password but locks on the register button. Will try on another computer in a bit but wanted to see if this was common   one is a windows 7 pc and the other is a raspi 4 with buster on it (which I would prefer to get working).

**Comment by gam3t3chelectronicshobbyhouse** [comment]
Managed to get this off linux.    tkinter is working as it should so not sure. 

> Connected to the server
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "Wallet.py", line 70, in FSSignup
    Signup()
  File "Wallet.py", line 23, in Signup
    window.destroy()
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2062, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed

>

**Comment by gam3t3chelectronicshobbyhouse** [comment]
and a new one. 

> Connected to the server
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "Wallet.py", line 56, in FSSignup
    s.send(bytes("REGI,"+username+","+password, encoding='utf8')) #send register request to server
BrokenPipeError: [Errno 32] Broken pipe

>

**Comment by gam3t3chelectronicshobbyhouse** [comment]
attempted on win7 win10 raspbian and ubuntu  same issue on all 4 devices.

**Comment by revoxhere** [comment]
Hello! 
Thanks for submitting bug report! 
I have no idea how this bug passed through. Sorry for that.
**I'm in process of fixing it right now.** There will be a new release (Alpha 6.1) which will include fix for this problem. Stay tuned, should be released in the next few hours!

**Comment by gam3t3chelectronicshobbyhouse** [comment]
Awesome Thanks @revoxhere love the idea of this project keep it up

**Comment by revoxhere** [comment]
Fixed in [Alpha 6.1](https://github.com/revoxhere/duino-coin/releases/tag/alpha-6.1). Check if it's working now.

**Comment by gam3t3chelectronicshobbyhouse** [comment]
register is working but showing a issue with the login now looks like previous registrations went through in the lockup tho.    waiting to see if it populates some fun.

**Comment by revoxhere** [comment]
Ok, good to hear. Yes - previous registrations all went in but wallet wasn't receiving a signal that registration was successfull.

**Comment by gam3t3chelectronicshobbyhouse** [comment]
Just tried creating a new one and it registered fine but still issues with the login  no output as of yet on it to see whats up.  Will post as soon as I find something.

**Comment by revoxhere** [comment]
Tried restarting the wallet? I'll have to rewrite wallet-server communication it seems.

**Comment by gam3t3chelectronicshobbyhouse** [comment]
that did the trick restarting it after registering worked. looks like I am in lol

**Comment by revoxhere** [comment]
Good. At least something works. Sorry for all this inconvenience. I'll look more at the wallet at the weekend.
