### ISSUE TITLE
Connection aborted, ConnectionResetError(10054)

### ISSUE THREAD

**Issue by ericddm** [duino-coin/duino-coin#400]
I, and my friends  encountered a connection error.
It happens frequently and we can’t mine normally.
![0418](https://user-images.githubusercontent.com/20798114/115144148-a1275e00-a07d-11eb-9aa4-21c9a59638b8.png)

**Comment by revoxhere** [comment]
I think this may be caused by too many GitHub requests from the miner to request the pool IP, I will try to do something about it, for now I can suggest restarting your router when this happens.

**Comment by ericddm** [comment]
thanks my man, it seems to work now
