### ISSUE TITLE
Cannot connect to the server CLI wallet.

### ISSUE THREAD

**Issue by eoghanriley** [duino-coin/duino-coin#403]
Whenever I load or reload the CLI wallet it says "Cannot connect to the server. It is probably under maintenance or temporarily down. Retrying in 15 seconds"

**Comment by revoxhere** [comment]
Are you sure nothing is blocking the wallet from accessing the server?

**Comment by eoghanriley** [comment]
Yes because it works after a few minutes.

**Comment by revoxhere** [comment]
My guess is you're opening too many connections to the server

**Comment by eoghanriley** [comment]
Ok thx
