### ISSUE TITLE
Server swamped?

### ISSUE THREAD

**Issue by endre90** [duino-coin/duino-coin#404]
Hi,

I haven't been able to mine a single block in the last 30 hours on due to:
Error connecting to the server. Retrying in 10s (net err: [Errno 110] Connection timed out)

Also, I can't seem to open my web wallet, it always get's stuck at connecting.
Moreover, opening the duino explorer page is rarely possible.

Server swamped?

Best Regards,
Endre

**Comment by revoxhere** [comment]
Should be working now

**Comment by endre90** [comment]
Hi,

unfortunately there is no change, at least for me. 
I don't know if anybody else has these issues.
I didn't do any mining for the last 36 hours.

I made sure to reboot all machines and check my internet connection,
but all I get when I start the miner is error 110.
I even tried making a new account, but I have the same issue.

Any ideas?

Best,
Endre
