### ISSUE TITLE
Mining problem

### ISSUE THREAD

**Issue by jimtsi** [duino-coin/duino-coin#406]
Hello i have a problem and i cant mine ( i am using a raspberry pi 400) 
The issue is shown in this photo 
![175118294_271703597935776_4139187347220947692_n](https://user-images.githubusercontent.com/76746171/115259148-4acc2500-a13a-11eb-9cae-b8883ad9ba88.jpg)

I cant find any solution yet

**Comment by BastelPichi** [comment]
Set debug to y in the miner config file and send the output here.

**Comment by jimtsi** [comment]
> Set debug to y in the miner config file and send the output here.

Does the program auto write the debug output??
Or you want me to send you the text I receive ??
(I have to say that when running the script in a python compiler I had no issues . Everything worked fine , only in the terminal is have this issue )

**Comment by ghost** [comment]
![Screenshot from 2021-04-20 10-21-58](https://user-images.githubusercontent.com/82426224/115328152-b5c13e80-a1c2-11eb-99d9-fa29b47c444b.png)


![Screenshot from 2021-04-20 10-23-43](https://user-images.githubusercontent.com/82426224/115328215-cffb1c80-a1c2-11eb-866c-aceda5ccaf43.png)

**Comment by BastelPichi** [comment]
It seems like this is because of your high ping. Maybe try to run it via the hotspot of your phone...

**Comment by jimtsi** [comment]
> Set debug to y in the miner config file and send the output here.

![Screenshot from 2021-04-20 15-56-16](https://user-images.githubusercontent.com/76746171/115399809-3eef6a00-a1f1-11eb-90b1-ebd12cbd0b6c.png)
![Screenshot from 2021-04-20 15-56-30](https://user-images.githubusercontent.com/76746171/115399817-41ea5a80-a1f1-11eb-8f1f-3b6e36cdcf0c.png)
this is what i get in the terminal
In the python compiler everything runs

**Comment by revoxhere** [comment]
Looks like locale decoding issue, maybe you can change the encoding to utf-8 manually somwhere?

**Comment by BastelPichi** [comment]
> In the python compiler everything runs

What compiler? Link?

**Comment by jimtsi** [comment]
> > In the python compiler everything runs
> 
> What compiler? Link?

No i use Thonny Python IDE i like its simplicity for quick debugging (I know thats not a reason for using it but i tried it some time ago and i got stuck to it )

**Comment by jimtsi** [comment]
> Looks like locale decoding issue, maybe you can change the encoding to utf-8 manually somwhere?

I thought so myself and i manually installed evey utf-8  for testing , i did not find a solution .
I started this thread cause i thought that if i had this problem maybe someone had it also and found a solution to it .
I will keep trying tonight and if i find anything i will post it here for anyone else that might have the same problem 
I like your project and your thoughts behind it , thats why i am still trying to solve my problem ....

**Comment by BastelPichi** [comment]
For all other pcs than raspberry pi use the executable

**Comment by iarapu** [comment]
To fix the issue you need to run this command before starting the mining script:

```
export PYTHONUTF8=1
```

**Comment by BastelPichi** [comment]
Does it work with that command?

**Comment by jimtsi** [comment]
Just got home from work 
I tried it seems to work fine 
Thanks for the help
