### ISSUE TITLE
Error when install requirements on ubuntu 18.04

### ISSUE THREAD

**Issue by iCesenberk** [duino-coin/duino-coin#409]
python3 -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting py-cpuinfo
  Using cached py_cpuinfo-8.0.0-py3-none-any.whl
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.18.4)
Collecting pyserial
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting pypresence
  Using cached pypresence-4.2.0-py2.py3-none-any.whl (11 kB)
Collecting tronpy
  Using cached tronpy-0.2.6-py3-none-any.whl (34 kB)
Collecting cryptography
  Using cached cryptography-3.4.7-cp36-abi3-manylinux2014_aarch64.whl (3.1 MB)
Collecting cffi>=1.12
  Using cached cffi-1.14.5-cp36-cp36m-manylinux2014_aarch64.whl (206 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting base58<3.0.0,>=2.0.0
  Using cached base58-2.1.0-py3-none-any.whl (5.6 kB)
Collecting httpx<0.17.0,>=0.16.1
  Using cached httpx-0.16.1-py3-none-any.whl (65 kB)
Collecting eth_abi<3.0.0,>=2.1.1
  Using cached eth_abi-2.1.1-py3-none-any.whl (27 kB)
Collecting pycryptodome<4.0.0,>=3.9.7
  Using cached pycryptodome-3.10.1-cp35-abi3-manylinux2014_aarch64.whl (1.5 MB)
Collecting ecdsa<0.16,>=0.15
  Using cached ecdsa-0.15-py2.py3-none-any.whl (100 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (2018.1.18)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (2.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (1.22)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from ecdsa<0.16,>=0.15->tronpy->-r requirements.txt (line 6)) (1.11.0)
Collecting eth-typing<3.0.0,>=2.0.0
  Using cached eth_typing-2.2.2-py3-none-any.whl (6.2 kB)
Collecting eth-utils<2.0.0,>=1.2.0
  Using cached eth_utils-1.10.0-py3-none-any.whl (24 kB)
Collecting parsimonious<0.9.0,>=0.8.0
  Using cached parsimonious-0.8.1-py3-none-any.whl
Collecting eth-hash<0.4.0,>=0.3.1
  Using cached eth_hash-0.3.1-py3-none-any.whl (8.9 kB)
Collecting cytoolz<1.0.0,>=0.10.1
  Using cached cytoolz-0.11.0.tar.gz (477 kB)
Collecting toolz>=0.8.0
  Using cached toolz-0.11.1-py3-none-any.whl (55 kB)
Collecting sniffio
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting httpcore==0.12.*
  Using cached httpcore-0.12.3-py3-none-any.whl (55 kB)
Collecting rfc3986[idna2008]<2,>=1.3
  Using cached rfc3986-1.4.0-py2.py3-none-any.whl (31 kB)
Collecting h11==0.*
  Using cached h11-0.12.0-py3-none-any.whl (54 kB)
Collecting contextvars>=2.1
  Using cached contextvars-2.4-py3-none-any.whl
Collecting immutables>=0.9
  Using cached immutables-0.15.tar.gz (44 kB)
Building wheels for collected packages: cytoolz, immutables
  Building wheel for cytoolz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dw0mw9i2/cytoolz_74a84bfea33d4a7e97faeaf17e336870/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dw0mw9i2/cytoolz_74a84bfea33d4a7e97faeaf17e336870/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-h5y5b4by
       cwd: /tmp/pip-install-dw0mw9i2/cytoolz_74a84bfea33d4a7e97faeaf17e336870/
  Complete output (61 lines):
  [1/5] Cythonizing cytoolz/utils.pyx
  [2/5] Cythonizing cytoolz/dicttoolz.pyx
  [3/5] Cythonizing cytoolz/functoolz.pyx
  [4/5] Cythonizing cytoolz/itertoolz.pyx
  [5/5] Cythonizing cytoolz/recipes.pyx
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.6
  creating build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/utils_test.py -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/compatibility.py -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/_version.py -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/_signatures.py -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/__init__.py -> build/lib.linux-aarch64-3.6/cytoolz
  creating build/lib.linux-aarch64-3.6/cytoolz/curried
  copying cytoolz/curried/operator.py -> build/lib.linux-aarch64-3.6/cytoolz/curried
  copying cytoolz/curried/exceptions.py -> build/lib.linux-aarch64-3.6/cytoolz/curried
  copying cytoolz/curried/__init__.py -> build/lib.linux-aarch64-3.6/cytoolz/curried
  copying cytoolz/utils.pyx -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/recipes.pyx -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/itertoolz.pyx -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/functoolz.pyx -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/dicttoolz.pyx -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/utils.pxd -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/recipes.pxd -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/itertoolz.pxd -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/functoolz.pxd -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/dicttoolz.pxd -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/cpython.pxd -> build/lib.linux-aarch64-3.6/cytoolz
  copying cytoolz/__init__.pxd -> build/lib.linux-aarch64-3.6/cytoolz
  creating build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_utils.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_tlz.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_signatures.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_serialization.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_recipes.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_none_safe.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_functoolz.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_doctests.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_docstrings.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_curried.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/test_compatibility.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-aarch64-3.6/cytoolz/tests
  running build_ext
  building 'cytoolz.dicttoolz' extension
  creating build/temp.linux-aarch64-3.6
  creating build/temp.linux-aarch64-3.6/cytoolz
  aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c cytoolz/dicttoolz.c -o build/temp.linux-aarch64-3.6/cytoolz/dicttoolz.o
  cytoolz/dicttoolz.c:19:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cytoolz
  Running setup.py clean for cytoolz
  Building wheel for immutables (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dw0mw9i2/immutables_7654d2f9744f4cb1ab8c26da01132491/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dw0mw9i2/immutables_7654d2f9744f4cb1ab8c26da01132491/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dv2kvpm5
       cwd: /tmp/pip-install-dw0mw9i2/immutables_7654d2f9744f4cb1ab8c26da01132491/
  Complete output (34 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.6
  creating build/lib.linux-aarch64-3.6/immutables
  copying immutables/map.py -> build/lib.linux-aarch64-3.6/immutables
  copying immutables/_version.py -> build/lib.linux-aarch64-3.6/immutables
  copying immutables/_testutils.py -> build/lib.linux-aarch64-3.6/immutables
  copying immutables/__init__.py -> build/lib.linux-aarch64-3.6/immutables
  running egg_info
  writing immutables.egg-info/PKG-INFO
  writing dependency_links to immutables.egg-info/dependency_links.txt
  writing requirements to immutables.egg-info/requires.txt
  writing top-level names to immutables.egg-info/top_level.txt
  reading manifest file 'immutables.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'immutables.egg-info/SOURCES.txt'
  copying immutables/_map.c -> build/lib.linux-aarch64-3.6/immutables
  copying immutables/_map.h -> build/lib.linux-aarch64-3.6/immutables
  copying immutables/_map.pyi -> build/lib.linux-aarch64-3.6/immutables
  copying immutables/py.typed -> build/lib.linux-aarch64-3.6/immutables
  copying immutables/pythoncapi_compat.h -> build/lib.linux-aarch64-3.6/immutables
  running build_ext
  building 'immutables._map' extension
  creating build/temp.linux-aarch64-3.6
  creating build/temp.linux-aarch64-3.6/immutables
  aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNDEBUG=1 -I/usr/include/python3.6m -c immutables/_map.c -o build/temp.linux-aarch64-3.6/immutables/_map.o -O2 -std=c99 -fsigned-char -Wall -Wsign-compare -Wconversion
  In file included from immutables/_map.c:2:0:
  immutables/pythoncapi_compat.h:19:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for immutables
  Running setup.py clean for immutables
Failed to build cytoolz immutables
Installing collected packages: immutables, toolz, contextvars, sniffio, rfc3986, h11, eth-typing, eth-hash, cytoolz, pycparser, parsimonious, httpcore, eth-utils, requests, pycryptodome, httpx, eth-abi, ecdsa, cffi, base58, tronpy, pyserial, pypresence, py-cpuinfo, cryptography, colorama
    Running setup.py install for immutables ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dw0mw9i2/immutables_7654d2f9744f4cb1ab8c26da01132491/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dw0mw9i2/immutables_7654d2f9744f4cb1ab8c26da01132491/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yiopk5tj/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/icesenberk/.local/include/python3.6m/immutables
         cwd: /tmp/pip-install-dw0mw9i2/immutables_7654d2f9744f4cb1ab8c26da01132491/
    Complete output (34 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.6
    creating build/lib.linux-aarch64-3.6/immutables
    copying immutables/map.py -> build/lib.linux-aarch64-3.6/immutables
    copying immutables/_version.py -> build/lib.linux-aarch64-3.6/immutables
    copying immutables/_testutils.py -> build/lib.linux-aarch64-3.6/immutables
    copying immutables/__init__.py -> build/lib.linux-aarch64-3.6/immutables
    running egg_info
    writing immutables.egg-info/PKG-INFO
    writing dependency_links to immutables.egg-info/dependency_links.txt
    writing requirements to immutables.egg-info/requires.txt
    writing top-level names to immutables.egg-info/top_level.txt
    reading manifest file 'immutables.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'immutables.egg-info/SOURCES.txt'
    copying immutables/_map.c -> build/lib.linux-aarch64-3.6/immutables
    copying immutables/_map.h -> build/lib.linux-aarch64-3.6/immutables
    copying immutables/_map.pyi -> build/lib.linux-aarch64-3.6/immutables
    copying immutables/py.typed -> build/lib.linux-aarch64-3.6/immutables
    copying immutables/pythoncapi_compat.h -> build/lib.linux-aarch64-3.6/immutables
    running build_ext
    building 'immutables._map' extension
    creating build/temp.linux-aarch64-3.6
    creating build/temp.linux-aarch64-3.6/immutables
    aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNDEBUG=1 -I/usr/include/python3.6m -c immutables/_map.c -o build/temp.linux-aarch64-3.6/immutables/_map.o -O2 -std=c99 -fsigned-char -Wall -Wsign-compare -Wconversion
    In file included from immutables/_map.c:2:0:
    immutables/pythoncapi_compat.h:19:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dw0mw9i2/immutables_7654d2f9744f4cb1ab8c26da01132491/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dw0mw9i2/immutables_7654d2f9744f4cb1ab8c26da01132491/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yiopk5tj/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/icesenberk/.local/include/python3.6m/immutables Check the logs for full command output.

**Comment by revoxhere** [comment]
you can skip installing tronpy if you dont intend on using the wDUCO wrapper

**Comment by iCesenberk** [comment]
Well, i skip installing tronpy now i got this error when try to run pc miner

> $ python3 PC_Miner.py
> Traceback (most recent call last):
>   File "PC_Miner.py", line 146, in <module>
>     if locale.startswith("es"):
> AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by revoxhere** [comment]
Re-clone the repo and it should work
