### ISSUE TITLE
Improve server response with `\n`.

### ISSUE THREAD

**Issue by ricaun** [duino-coin/duino-coin#410]
Sometimes when my esp8266 connects to the server the client does not receive the version. And when the client requests a JOB the client receives something like this:

`2.47e3cb5a854019db3c42c1a4f4a1a00dcf6069b1c 
3b9398b594d89582c495e141e4bf4dc7b4b7a811 6`

I suggest to the server to send always a new line at the end of each request/response, like this is easier to filter these responses and make share the JOB request is in one line. 

I belive the `feedback` have the same problem, I somethime receive `GOODb5337c15c40d3751e7bda9158ef0ffcc5cb45a5b 1d6bb0e34fce945d1b73c3deb22d0e7e83169b35 6` and this aways causes the JOB to unsucsses.

See yaa!

**Comment by revoxhere** [comment]
Yes, we're slowly adding the newline endings to all the responses, but not all software is ready for it yet, currently the job is already sent with \n's

**Comment by ricaun** [comment]
> 
> 
> Yes, we're slowly adding the newline endings to all the responses, but not all software is ready for it yet, currently the job is already sent with \n's

Great! I'm using this to mitigate some character o the `hash`.

``` C
if (hash.length() > 40)
{
  hash = hash.substring(hash.length()-40);
}
```

Works perfectly when the hash has 40 chars.

**Comment by ricaun** [comment]
Hello, the response version still does not have the `\n`.

The server sends 3 bytes only... The `2.4` should have `\n` on the end.

😆

**Comment by revoxhere** [comment]
Yes, I know that, but I'm not sure if all the softwares were made to ignore \n where needed, I (or someone else) needs to check them and later update them, only then we'll fully add the \n. But knowing that the ver is always 3 bytes it's not a huge deal.
