### ISSUE TITLE
CLI Wallet registration problem

### ISSUE THREAD

**Issue by Hisha** [duino-coin/duino-coin#411]
Trying to get started and downloaded onto a Raspberry Pi running Ubuntu 20.04. I select option 2 to register and after entering all the info I get the following:

Traceback (most recent call last):
  File "CLI_Wallet.py", line 407, in <module>
    s.send(bytes(
BrokenPipeError: [Errno 32] Broken pipe

**Comment by IDontModLobbies** [comment]
Same issue for me on raspberry pi 4 8gb on raspberry pi os (32-bit)

**Comment by BastelPichi** [comment]
Just dont use the cli wallet. Nobody really needs it and i dont know why there so many people using it. Just use the webwallet.

**Comment by IDontModLobbies** [comment]
> Just dont use the cli wallet. Nobody really needs it and i dont know why there so many people using it. Just use the webwallet.

I got everything working last night and this is no longer an issue. I think the servers were down as my email verification wasn't going through upon registration.

**Comment by BastelPichi** [comment]
> > Just dont use the cli wallet. Nobody really needs it and i dont know why there so many people using it. Just use the webwallet.
> 
> I got everything working last night and this is no longer an issue. I think the servers were down as my email verification wasn't going through upon registration.

It normally also gives errors if you password isnt strong enough...

**Comment by IDontModLobbies** [comment]
> > > Just dont use the cli wallet. Nobody really needs it and i dont know why there so many people using it. Just use the webwallet.
> > 
> > 
> > I got everything working last night and this is no longer an issue. I think the servers were down as my email verification wasn't going through upon registration.
> 
> It normally also gives errors if you password isnt strong enough...

My web browser (MS Edge) recommended I change my password. Is it possible on the web browser?

**Comment by BastelPichi** [comment]
> > > > Just dont use the cli wallet. Nobody really needs it and i dont know why there so many people using it. Just use the webwallet.
> > > 
> > > 
> > > I got everything working last night and this is no longer an issue. I think the servers were down as my email verification wasn't going through upon registration.
> > 
> > 
> > It normally also gives errors if you password isnt strong enough...
> 
> My web browser (MS Edge) recommended I change my password. Is it possible on the web browser?

1. Dont use edge, 2. nope. Use one of the desktop wallets. Why did it recomend tto chnage the passwd? Dataleak?
