### ISSUE TITLE
Error while mining - most likely a connection error - restarting in 5s. (mining err: list index out of range)

### ISSUE THREAD

**Issue by schwaenchen** [duino-coin/duino-coin#415]
Hello

I'm mining on Windows and Linux with the official v2.4 miner. 
I have a lot of "Error while mining" messages on both systems, i rebootet both my cable modem and my router,
but the error is still there even after the reboot of the modem/router and restarting the miner's.

Is this error coming from "server" / "network" / "miner"  ?

Best regards,
schwaenchen

![image](https://user-images.githubusercontent.com/79098898/115748355-603d8b00-a396-11eb-87d8-00d46f15a007.png)

**Comment by revoxhere** [comment]
Please try again now

**Comment by BastelPichi** [comment]
Does it work now?

**Comment by revoxhere** [comment]
Should be fixed in 2.4.5. Closing
