### ISSUE TITLE
Debug output in " elif osname == "posix":" maybe an copy/paste error?

### ISSUE THREAD

**Issue by schwaenchen** [duino-coin/duino-coin#416]
Hello

i'm wondering if in PC_Miner.py and AVR_Miner.py the debug output under

  elif osname == "posix":

is a copy/paste error from the same "nt" section:

![image](https://user-images.githubusercontent.com/79098898/115751513-8c0e4000-a399-11eb-8d83-e3ac11fb3311.png)

8-)

Best regards,
schwaenchen

**Comment by revoxhere** [comment]
You can correct it, just didn't notice it
