### ISSUE TITLE
User names and passwords transmitted in plain text over unencrypted TCP connection.

### ISSUE THREAD

**Issue by statusbits** [duino-coin/duino-coin#417]
Server commands 'REGI' and 'LOGI' transmit user names and passwords in plain text over unencrypted TCP connection. It's 2021. Seriously? :-O

**Comment by Lulaschkas** [comment]
Hi!
The webwallet is using a secured websocket connection over SSL. The address for it is: wss://server.duinocoin.com:15808
Miners are not connecting over this address but if you are logging in/registering over the webwallet, there is no problem.
I hope I could help

**Comment by kerneltask** [comment]
CLI_Wallet.py does use an unecrypted socket connection and sends the pasword in clear text though.

```
        s = socket.socket()
        . . . 
        s.send(bytes(
            "LOGI,"
            + str(username)
            + ","
            + str(password)
            + str(",placeholder"),
            encoding="utf8"))
```

**Comment by revoxhere** [comment]
You can use the webwallet if you are scared or using the CLI one.

**Comment by Bilaboz** [comment]
Offical wallets now use a secure connection
https://github.com/revoxhere/duino-coin/commit/e2b4a994b2236f3f80af1530c8c7f544028f49f7
https://github.com/revoxhere/duino-coin/commit/92d8c87db033df48def80f06af40cff59b0e19c9
