### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by IDontModLobbies** [duino-coin/duino-coin#419]
Import Error: cannot import name "ImageTk" from "PIL" (/user/lib/python3/dist-packages/PIL/_+init__.py)

On raspberry pi 4 8gb

**Comment by revoxhere** [comment]
sudo apt-get install python3-pil python3-pil.imagetk

**Comment by IDontModLobbies** [comment]
Works! However, "Error sending verification email" after account registration.

**Comment by jhonnystene** [comment]
I'm having the same "error sending verification email" issue.

**Comment by IDontModLobbies** [comment]
> I'm having the same "error sending verification email" issue.

working for me now, just tested it

**Comment by jhonnystene** [comment]
Same here, I think it was just a server issue since it restarted a few minutes ago.
