### ISSUE TITLE
No led after update V2.4

### ISSUE THREAD

**Issue by infinexx** [duino-coin/duino-coin#420]
Hello,
I did update 2.4 but after update none of my ESP8266 have blinking leds. They are mining but look dead. I tryed the 340 and 2102 versions.

**Comment by revoxhere** [comment]
Can you try this code https://github.com/revoxhere/duino-coin/blob/master/ESP8266_Code/ESP8266_Code.ino

**Comment by BastelPichi** [comment]
>  I did update 2.4 but after update none of my ESP8266 have blinking leds. They are mining but look dead. I tryed the 340 and 2102 versions.

Did you set the right led while uploading?

**Comment by infinexx** [comment]
Sorry for late reply but it works. Multi thx.

**Comment by BastelPichi** [comment]
> Sorry for late reply but it works. Multi thx.

What was the problem?

**Comment by infinexx** [comment]
I don't know but when i flash with the new code from Revox it works great.
Before when i was uploading i see the flash and also i see in monitor the mining but zero leds. Now after upgrade everything works great again.
