### ISSUE TITLE
Duino Coin

### ISSUE THREAD

**Issue by Hammerh3ad** [duino-coin/duino-coin#427]
can't get registered for Duino-Coin Web Wallet fill out form and it simply hangs on raspberry Pi 3 b+. Followed instructions on Duino site.

**Comment by BastelPichi** [comment]
> can't get registered for Duino-Coin Web Wallet fill out form and it simply hangs on raspberry Pi 3 b+. Followed instructions on Duino site.

Use a stronger password. With that it should work. If your password isnt strong enough, (at the time) you get no error. Just nothing. If you use a stronger password, it should work.
