### ISSUE TITLE
AVR_Miner Parsing Error

### ISSUE THREAD

**Issue by dansinclair25** [duino-coin/duino-coin#433]
I've found an issue with the AVR miner, but I don't know how to fix it.

 I occassionally get a parsing error when decoding the response from the server after posting a job. If I break it down and log the output of `feedback` in [AVR_Miner.py](https://github.com/revoxhere/duino-coin/blob/2e9be3537a61d140638e69de383b44920bfc5d89/AVR_Miner.py#L977) in the exception block I can see that feedback is `GOOD` (which is… well… good!). But I don't understand why this triggers the exception. `rstrip()` doesn't trigger the exception if there's no new line char at the end of the string it's stripping. Is it something to do with the buffer size maybe?!

**Comment by YeahNotSewerSide** [comment]
Variable feedback was set to GOOD from previous packet, so when you get an error, var feedback is not changed, so you are getting nothing from server and seeing that feedback is GOOD, copying response from Discord.

**Comment by revoxhere** [comment]
Try the latest 2.4.5 miner, using switch instead of recv might've fixed it (@joaquinbvw improvement)

**Comment by dansinclair25** [comment]
Looks like that's been fixed in 2.4.5
