### ISSUE TITLE
WebWallet daily profit calculation

### ISSUE THREAD

**Issue by dansinclair25** [duino-coin/duino-coin#439]
I am well aware that I don't understand the ins and outs of the web wallet, and I definitely don't fully understand JS, but I don't think the calculation is correct for the Daily Profit. Currently the func it
```
const ProfitCalculator = () => {
    let prev_bal = curr_bal;
    curr_bal = balance;
    let daily = (((curr_bal - prev_bal) * 12) * 60) * 24;
    profitcheck++;
    if ((curr_bal - prev_bal) > 0 && profitcheck > 1) {
        document.getElementById("estimatedprofit").innerHTML = daily.toFixed(2) + " ᕲ";
        document.getElementById("estimatedprofitusd").innerHTML = "≈$" + (daily * ducoUsdPrice).toFixed(2);
    }
};
```
But I don't understand the calculation for the `daily` variable is. Should you not track the time between each call to get the balances and use that in the equation? The way I understand it, it should be
```
seconds_in_day = 24 * 60 * 60 
number_of_balance_calls_in_day = seconds_in_day / (cur_time - prev_time)
daily_profit = number_of_balance_calls_in_day * (cur_balance - prev_balance)
```

**Comment by revoxhere** [comment]
The function is run every 5 seconds, that is enough. Desktop wallet uses the same principle
```JS
window.setInterval(() => {
    ProfitCalculator();
}, 5000);
```
