### ISSUE TITLE
Higher hash rates, lower daily profits

### ISSUE THREAD

**Issue by justcallmekoko** [duino-coin/duino-coin#450]
I have noticed the higher my hash rates, the lower my projected daily profit.

These are my two different setups

### AVR Mining
I have installed the AVR mining firmware on an Arduino Uno and an Arduino Leonardo. Both are being used by the AVR_Miner.exe as seen in this picture...
![avr_mining](https://user-images.githubusercontent.com/25190487/116611396-4f47c900-a904-11eb-8f69-c96c48d1d315.PNG)

The combined hash rates of the two microcontrollers will be anywhere between 330H/s - 340H/s and the projected daily profit will be anwhere between 20 DUCO and 40 DUCO.

### Raspberry Pi Mining
I am of course using the PC_Miner.py on the raspberry pi 4b 8gb. It is mining on 4 threads, efficiency is 96, and diff is LOW. The resulting hash rate from a single Pi is 1.31MH/s but the projected daily profit will be anywhere between 7 DUCO and 12 DUCO as seen in the picture here...
![pi_mining](https://user-images.githubusercontent.com/25190487/116612076-19efab00-a905-11eb-98ad-b75763cb8268.PNG)

I noticed the same thing when mining with an ESP32. I was hitting about 13KH/s but the projected daily profits were about the same as the Pi miner. For some reason, the two AVR microcontrollers have higher daily profit projections with SIGNIFICANTLY lower hash rates.

Can someone explain how that happens?

**Comment by revoxhere** [comment]
Yes, having big hashrate is not the point in duino coin, as stated in the white paper. There are other coins that Raspberry Pi can mine, but none for Arduino. The ESP is a tricky topic, on one hand it's more powerful but also it doesn't require a host device like Arduino, thus the lower profits.

**Comment by justcallmekoko** [comment]
Interesting. I will have to re-read the white paper. Thanks for the response.
So would this mean having more and more AVR microcontrollers would not necessarily translate to a higher daily profit?

**Comment by revoxhere** [comment]
It would, although every miner earns a bit less than the previous one. It's a complicated topic and more detailed documentation for it is in the works.

**Comment by justcallmekoko** [comment]
Understood. I will be sure to read it when it becomes available. I will be fully transparent though...
The reason I ask is because I am designing a DUCO dedicated miner for the memes. I am not trying to undermine the project but rather kind of poke fun at the rest of the mining environment.

Miners and GPUs are out of stock or over priced so it becomes a pain in the ass for anyone who wants to mine of course. I decided to design a PCB to work like one of those Antminer USB miners. It has 4 ATmega32u4s on it and it takes up one USB port.

Like I said before, I am just poking fun. I don't mean for this to be a get-rich-quick thing and I am not trying to shit all over your project here.

But if you are interested, here are a couple pictures of the 3D model from easyeda...

(ignore the female headers. They are supposed to be castellated through holes)

![](https://cdn.discordapp.com/attachments/805120351860031518/837055742807769178/unknown.png)

![](https://cdn.discordapp.com/attachments/805120351860031518/837055814207406171/unknown.png)

**Comment by revoxhere** [comment]
Interesting idea

**Comment by joaquinbvw** [comment]
That board looks great! Are you planning on split the jobs so each ATmega has one part of it? I have tried to do that with the ESP32 and it wasn't worth it, but I had to mess with the RTOS too, I think if you do it with different microcontrollers like this could work.

**Comment by justcallmekoko** [comment]
@joaquinbvw I am planning on splitting the jobs. The chip angled at a 45 degree is a USB hub IC which should allow the PC to recognize all four A32u4s separately.

**Comment by BastelPichi** [comment]
> Understood. I will be sure to read it when it becomes available. I will be fully transparent though...
> The reason I ask is because I am designing a DUCO dedicated miner for the memes. I am not trying to undermine the project but rather kind of poke fun at the rest of the mining environment.
> 
> Miners and GPUs are out of stock or over priced so it becomes a pain in the ass for anyone who wants to mine of course. I decided to design a PCB to work like one of those Antminer USB miners. It has 4 ATmega32u4s on it and it takes up one USB port.
> 
> Like I said before, I am just poking fun. I don't mean for this to be a get-rich-quick thing and I am not trying to shit all over your project here.
> 
> But if you are interested, here are a couple pictures of the 3D model from easyeda...
> 
> (ignore the female headers. They are supposed to be castellated through holes)
> 
> ![](https://camo.githubusercontent.com/99f3b1eb91f5e21ef1c68c3cee798caad9892f4758b0fe75cf0f38c076e1c7ff/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3830353132303335313836303033313531382f3833373035353734323830373736393137382f756e6b6e6f776e2e706e67)
> 
> ![](https://camo.githubusercontent.com/71ce7da3dbd32ee681aec02f3375b5ac176817164f834bf06e2dd6994aa0c8b8/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3830353132303335313836303033313531382f3833373035353831343230373430363137312f756e6b6e6f776e2e706e67)

Cool! Daniel Jovar(a crypto youtube) already made such a board, and ordered it, but just with one atmega. So cool idea!

**Comment by ricaun** [comment]
> 
> 
> @joaquinbvw I am planning on splitting the jobs. The chip angled at a 45 degree is a USB hub IC which should allow the PC to recognize all four A32u4s separately.

Nice! I'm thinking to use a Esp8266 as a master and some atme328p as a slave using I2C.

**Comment by joaquinbvw** [comment]
> > @joaquinbvw I am planning on splitting the jobs. The chip angled at a 45 degree is a USB hub IC which should allow the PC to recognize all four A32u4s separately.
> 
> Nice! I'm thinking to use a Esp8266 as a master and some atme328p as a slave using I2C.

Great! I have seen someone on Discord trying to do that. You should also consider using SPI, I have seen some examples on the web using the Atmega as SPI slave, I don't know if you can use I2C as slave though.

**Comment by justcallmekoko** [comment]
> > > @joaquinbvw I am planning on splitting the jobs. The chip angled at a 45 degree is a USB hub IC which should allow the PC to recognize all four A32u4s separately.
> > 
> > 
> > Nice! I'm thinking to use a Esp8266 as a master and some atme328p as a slave using I2C.
> 
> Great! I have seen someone on Discord trying to do that. You should also consider using SPI, I have seen some examples on the web using the Atmega as SPI slave, I don't know if you can use I2C as slave though.

You can use atmega328p as I2C slave. I do that [here](https://github.com/justcallmekoko/MarauderCentauri/blob/main/i2c_keyboard/i2c_keyboard.ino) for that exact microcontroller.

**Comment by joaquinbvw** [comment]
> > > > @joaquinbvw I am planning on splitting the jobs. The chip angled at a 45 degree is a USB hub IC which should allow the PC to recognize all four A32u4s separately.
> > > 
> > > 
> > > Nice! I'm thinking to use a Esp8266 as a master and some atme328p as a slave using I2C.
> > 
> > 
> > Great! I have seen someone on Discord trying to do that. You should also consider using SPI, I have seen some examples on the web using the Atmega as SPI slave, I don't know if you can use I2C as slave though.
> 
> You can use atmega328p as I2C slave. I do that [here](https://github.com/justcallmekoko/MarauderCentauri/blob/main/i2c_keyboard/i2c_keyboard.ino) for that exact microcontroller.

Oh nice! Then I2C it's the best option, just two traces for all of them. Just be careful with the pull up resistors, I had some issues in the past with those.

**Comment by ricaun** [comment]
> 
> 
> > > > > @joaquinbvw I am planning on splitting the jobs. The chip angled at a 45 degree is a USB hub IC which should allow the PC to recognize all four A32u4s separately.
> > > > 
> > > > 
> > > > Nice! I'm thinking to use a Esp8266 as a master and some atme328p as a slave using I2C.
> > > 
> > > 
> > > Great! I have seen someone on Discord trying to do that. You should also consider using SPI, I have seen some examples on the web using the Atmega as SPI slave, I don't know if you can use I2C as slave though.
> > 
> > 
> > You can use atmega328p as I2C slave. I do that [here](https://github.com/justcallmekoko/MarauderCentauri/blob/main/i2c_keyboard/i2c_keyboard.ino) for that exact microcontroller.
> 
> Oh nice! Then I2C it's the best option, just two traces for all of them. Just be careful with the pull up resistors, I had some issues in the past with those.

I'm trying to create something and discover the Wire Library has a really annoying 32 bytes max buffer...

[The Wire library implementation uses a 32 byte buffer, therefore any communication should be within this limit. Exceeding bytes in a single transmission will just be dropped.
](https://www.arduino.cc/en/reference/wire)

**Comment by kickshawprogrammer** [comment]
32 bytes? In my project, I reduced the serial buffer size from 64 bytes to 4 bytes. I only have 512 of memory to work with (ATTiny85) and allocating 64 of them for a temporary buffer was troublesome...  have a look at my attiny85 miner code to see how I handle it.
