### ISSUE TITLE
Where did my coins go?

### ISSUE THREAD

**Issue by gkozin** [duino-coin/duino-coin#454]
So yesterday I checked my balance and it was around 60 Ducos. Today? It's 46.559383! There's no in our out transactions recorded. So where did the coins go? Where can I see your blockchain? How come the mining rewards are not tracked in the transaction log?

**Comment by kaiiwaii** [comment]
There were problems with the database. Don't worry, send your username and the amount here and revox will refund them

**Comment by gkozin** [comment]
What exactly do you mean by the "problems with the database"? The blockchain is supposed to be immutable. That's of course IF THERE IS a blockchain. Is there?

**Comment by kaiiwaii** [comment]
There is a hashchain, read the wiki and the whitepaper

**Comment by gkozin** [comment]
Your whitepaper is mostly marketing bee-es and your [wiki](https://github.com/revoxhere/duino-coin/wiki) says nothing at all:

`The Wiki is still an early work in progress, please check later if something isn't finished yet - or, even better, contribute yourself!`

You do call Duco-Coin a "cryptocurrency" in your whitepaper though. That implies that all transactions, icluding mining rewards must be recodred on the blockchain. Where can I see the history of mining rewards?

**Comment by Bilaboz** [comment]
I think he meant read the FAQ https://github.com/revoxhere/duino-coin/wiki/FAQ
You can see the transactions and the mined blocks on the explorer https://explorer.duinocoin.com

**Comment by gkozin** [comment]
So, let me get this strait. Based on you FAQ, there's no real blockchain. What you describe as a "hashchain" does not protect transactions ledger from tampering. The mining rewards are not recorded on the transaction ledger at all, you just directly modify account balances in your user database table. You can also directly modify user account balances at will using server CLI commands  "add", "subtract" and "set". And what about "jail"? What the heck is that for? Dude, get real. This is NOT a cryptocurrency. This is a gross misrepresentation bordering on fraud. You should really be ashamed of yourself.

**Comment by Bilaboz** [comment]
> you just directly modify account balances in your user database table

I should quote revox about this "I can't believe I have to say it everytime a similar situation happens, but Duco will stay centralized - there's no other (easy!) way to make it mineable on low power devices. 
You don't like that? Sorry, find something else, even though we're the first crypto that enables mining on so many hardware configurations."

> And what about "jail"?

Jail was made to softban users trying to abuse the system by trying to mine on the wrong difficulty

> This is a gross misrepresentation bordering on fraud. You should really be ashamed of yourself.

Wow. The goal of duino isn't to earn money, it's a fun project that allows people to learn programming and crypto related stuff. If you search for a decentralized cryptocurrency and to make money, there is thousands of coins that will satisfy you

**Comment by gkozin** [comment]
This is definitely not about money - your coin is worthless anyway, particulrly because you and your friends can make yourself instant "billionaires" just by typing "add revox 1000000000" at the command prompt :-\

I was interested in this project from the technical point of view because you claimed it to be a "centralezed cryptocurrency" but it turned out to be a "fakechain", not a blockchain. 

I don't mind you and your friends experimenting with technology, but at no point you should mislead your users by comparing your coin to Ripple. 
There should be a full disclosure that this is a "digital currency", not a cryptocurrency, but somehow I doubt you even know the difference. What a joke!

Anyway, good luck with your toy coin :-D

**Comment by TheDevMinerTV** [comment]
I'd go as far as to say, feel free to discuss this on the Discord server.

No, this is not me trying to educate you, I just want to understand your good reasoning without exploding this GitHub issue. :)

**Comment by gkozin** [comment]
@TheDevMinerTV, Nah, I've already wasted too much time on this. Got better things to do :)
But for waht it's worth, I thought there really was a bug that resluted in unexplained account balance change until I realized that it's not really a blockchain-based crypto, whether centralized or not. Over and out! (Sorry for all the noise :)
