### ISSUE TITLE
Auto-start PC_Miner.py on Raspberry Pi

### ISSUE THREAD

**Issue by TheLion** [duino-coin/duino-coin#461]
Hi,

I have been trying to get PC_Miner.py to start on startup by using the @reboot in crontab, but that doesn't seem to work. It does run some parts (checking and installing requirements) of the script, but the actual miner doesn't seem to start.

Also tried starting it through rc.local and that does start it, but 4 times ;-)

Is there a (better) way to start the miner automatically at reboot?

**Comment by dansinclair25** [comment]
@TheLion try following the steps in [this post](https://dansinclair25.medium.com/duino-coin-mining-on-a-raspberry-pi-180bad964b1b).

**Comment by TheLion** [comment]
Gee. Didn't find/see this one yet. 

Thanks!
