### ISSUE TITLE
question about certain files

### ISSUE THREAD

**Issue by tarbear123** [duino-coin/duino-coin#462]
if i move esp8266 + hash to the arduino folder, do i need the arduino-code in there too?

**Comment by kickshawprogrammer** [comment]
I’m not sure what you’re trying to accomplish here but the Arduino and ESP are two different architectures. ESP supports wifi with proper libraries whereas Arduino does not so they require two separate code bases. IE: not interchangeable - so Yes, the Arduino code would still be required if using an Arduino board

**Comment by kickshawprogrammer** [comment]
On the other hand, if your board is an arduino mega 2560 (clone) with wifi, then no. You won’t have to have the Arduino code and the esp code will work. I have such a board and can help you get the esp side up and running if you need help
