### ISSUE TITLE
Arduino ID issues

### ISSUE THREAD

**Issue by MPM1107** [duino-coin/duino-coin#463]
One of my Arduino UNOs triggers DUCOID error messages in the AVR miner console.
(Possible incorrect chipID! This will cause problems with the future release of Kolka security system)

After adding a print statement into the code to see what its ID is, it shows this: DUCOID89534951485189
It seems like the ID is shorter than it should be. Is this an error in the arduino firmware?

**Comment by revoxhere** [comment]
It should be okay, It's probably using a different chip than the 328p - I need to make a exception for these. Nothing to worry about.

**Comment by MPM1107** [comment]
It's because the last 2 bytes of the ID are integers smaller than 10, so the DUCOID string is shorter than it should be.
Doing something like this should fix it I think:
```
// Grab Arduino chip ID
for (size_t i = 0; i < 8; i++) {
  if (UniqueID[i] < 10) {
    IDstring += "0";
  }
  IDstring += UniqueID[i];
}
```

**Comment by revoxhere** [comment]
Added your suggestion to the code

**Comment by ricaun** [comment]
Using Hexa on the uniqueID should be better?

```
String UniqueIDHexa()
{
  String id = "";
  char buff[4];
  for (size_t i = 0; i < 8; i++)
  {
    sprintf(buff, "%02X", (uint8_t) UniqueID[i]);
    id += buff;
  }
  return id;
}
```

Like this always return 16 chars.

**Comment by revoxhere** [comment]
Nice idea, since it's not (yet) used for anything I'm open to changes, and maybe the hex will be better

**Comment by revoxhere** [comment]
Fixed with the newest codes
