### ISSUE TITLE
ican't register web wallet & wallet cli 

### ISSUE THREAD

**Issue by anon2334** [duino-coin/duino-coin#467]
![image](https://user-images.githubusercontent.com/68531183/117109257-a08b0900-ad99-11eb-8988-bbc32b1e5db6.png)

**Comment by revoxhere** [comment]
What does the GUI/CLI one say?

**Comment by anon2334** [comment]
both

**Comment by anon2334** [comment]
iran ip blocked ?

**Comment by revoxhere** [comment]
GUI & CLI one will tell you the cause of rejection. I can't tell you anything from a single screenshot

**Comment by anon2334** [comment]
![image](https://user-images.githubusercontent.com/68531183/117109965-b0571d00-ad9a-11eb-86dc-c076fa2c011b.png)

**Comment by revoxhere** [comment]
Can you try the GUI one?

**Comment by anon2334** [comment]
GUI not work 
![image](https://user-images.githubusercontent.com/68531183/117112168-e9dd5780-ad9d-11eb-834b-cd5ab699e878.png)

**Comment by revoxhere** [comment]
I'm not sure what's the cause. Maybe someone else will help here.

**Comment by morsine** [comment]
> iran ip blocked ?

As an Iranian I can confirm that Iran's IPs are blocked, they use AWS, so... use a VPN.

**Comment by kaiiwaii** [comment]
The server is not on AWS

**Comment by revoxhere** [comment]
We are not using AWS

**Comment by morsine** [comment]
Even if your servers are not running on AWS, it passes trough them at some point which it blocks the traffic from the previously mentioned country.
```
PING wallet.duinocoin.com (34.233.38.119) 56(84) bytes of data.
64 bytes from ec2-34-233-38-119.compute-1.amazonaws.com (34.233.38.119): icmp_seq=1 ttl=46 time=234 ms
```
Edit: The server in which the author has issues with, **is hosted on the AWS**:
https://www.whatismyip.com/34.233.38.119/

**Comment by revoxhere** [comment]
I think there's nothing I can do about it unfortunately. Also I didn't knew about this whole aws thing

**Comment by morsine** [comment]
> I think there's nothing I can do about it unfortunately. Also I didn't knew about this whole aws thing

Yes, Nothing can be done. The author should use a VPN.
