### ISSUE TITLE
Typo  in duinocoin.com

### ISSUE THREAD

**Issue by ghost** [duino-coin/duino-coin#482]
In technical specifications section of duinocoin.com there is typo "fom" instead of "from"

![IMG_20210509_190251](https://user-images.githubusercontent.com/68266667/117574152-6010ef80-b0f9-11eb-9808-f4ed1c683ba2.jpg)

I can fix this just tag me the website source code

**Comment by revoxhere** [comment]
You can find the source code for websites [here](https://github.com/revoxhere/duino-coin/tree/gh-pages)

**Comment by BastelPichi** [comment]
> In technical specifications section of duinocoin.com there is typo "fom" instead of "from"
> 
> ![IMG_20210509_190251](https://user-images.githubusercontent.com/68266667/117574152-6010ef80-b0f9-11eb-9808-f4ed1c683ba2.jpg)
> 
> I can fix this just tag me the website source code

Fixed.

**Comment by BastelPichi** [comment]
Just gonna take a minute til github.pages updates

**Comment by revoxhere** [comment]
Kristian hosts the site so it will take even longer :smile:

**Comment by BastelPichi** [comment]
> Kristian hosts the site so it will take even longer 😄

I thought it would be ghpages, as the brsnch is called like that

**Comment by revoxhere** [comment]
It was hosted on the gh-pages before Kristian said he will host them

**Comment by BastelPichi** [comment]
> It was hosted on the gh-pages before Kristian said he will host them

Then we can remove the "histed by github pages" from the footrr....
