### ISSUE TITLE
In the "Getting Started" page the "Download the latest release" section should point to the latest release ...

### ISSUE THREAD

**Issue by cregist** [duino-coin/duino-coin#484]
nfm

**Comment by BastelPichi** [comment]
> nfm

It does

**Comment by cregist** [comment]
If you click the link it goes to the latest. 2.4.5

But the text says 
Assets
Duino-Coib-2.2_linux.zip

etc.

**Comment by BastelPichi** [comment]
> If you click the link it goes to the latest. 2.4.5
> 
> But the text says
> Assets
> Duino-Coib-2.2_linux.zip
> 
> etc.

Thats just the pic, i can change that, but since our webmaster dont updates that often, it will take 2 weeks, til its public on the website.
