### ISSUE TITLE
ESP8266 (ESP - 01s) issue

### ISSUE THREAD

**Issue by ghost** [duino-coin/duino-coin#486]
I have been using esp 01s to mine duco or duino coin for a few days now, but whenever i check on the monitoring app on android, i could not see it mining after a day. i can only my esp32 mining on the app.

it would be great to add a code that resets the microcontroller at least 1 per day to prevent it from interrupting the mining.

**Comment by BastelPichi** [comment]
> I have been using esp 01s to mine duco or duino coin for a few days now, but whenever i check on the monitoring app on android, i could not see it mining after a day. i can only my esp32 mining on the app.
> 
> it would be great to add a code that resets the microcontroller at least 1 per day to prevent it from interrupting the mining.

Theyre currently working on that, and (i think) they already implelented that, but the problem (i think) was that they would freeze after time and no software could reset them...

**Comment by ghost** [comment]
it is possible to reset them using codes after a certain period of time. by connecting the IO pin to the RST pin and sending a voltage to it. I want to try and add thay code to it, but i don't want to mess with the codes that was already made for the device and don't know where to put it.

so after a few hours IO pin would be set to LOW to reset the device.

This may or may not be feasible depending on the device.

**Comment by MPM1107** [comment]
Please don't connect random IO pins to RST just to reset the ESP, that makes absolutely no sense. All of this can be done in software. My first guess is that the hashing loop is causing issues because it takes too long and causes issues with the backlog of background tasks. yield() should be used every so often while hashing to keep critical background networking tasks working.

What would be helpful is the serial output of the ESP before it crashes. If it's actually a hard crash it should spit out some info about what happened. If there's no output then we have a bigger problem...

**Comment by kickshawprogrammer** [comment]
I am not having this issue at all. Mine have been running for days now. Are you running the latest version?

**Comment by ghost** [comment]
i didn't connect any, i just thought it would be a good feature to have for when the miner stopped mining without you knowing. having this feature would help one  monitor the miner less than what is needed.

yes i am running version 2.4

also it seems to work fine as of now. i will check tomorrow if the issue still persist.

**Comment by ghost** [comment]
i have been observing it these past few days and monitored the android app returned data.

i am using the latest release 2.4 for esp 01s

and 2.3 for the esp32 (the code is still 2.3 for some reason, but it came from the 2.4.5 release)

For  ESP-01s

1. the ESP-01s stopped working at some point (maybe because the mcu getting too hot due to its size and design)

2. i let the mcu rest for a few seconds to let it cool down, then restarted it and it is working and it worked for a few hours (the next day when i checked my earnings, only the esp32 is mining)

3. i just repeat this cool down restart and mine sequence from time to time. (maybe it is the device's problem and not the code)

i probably need to put a heatsink on it to dissipate the heat and not let the mcu overheat.


For the ESP 32

1. i was previously using the 2.3 version before the 2.4.5 release but after a few days the mining stopped completely and my earnings stopped increasing

2. i updated it to the latest one from the 2.4.5 folder but the one on the android app says that the miner is using ver 2.3

3. yesterday the mining stopped and i had to restart it and after restarting it, it works again.

i am still monitoring if my earning would stop and which device would stop first

though the android app could get some improvements it is irritating when you are looking at which miners are currently working but after opening the app the miner's list is empty and when it did show up it only last for a few seconds.

it would be great if the list stays the same and would just refresh without clearing the list and add a timer

 (ex. 
miner_1                          4.84 kH/s
core 1 ver 2.3      diff 2000, 10/10
last activity 50 seconds ago
)

this would also help in debugging, this would help users see if their miners stopped working, which and when.

**Comment by primitt** [comment]
> i have been observing it these past few days and monitored the android app returned data.
> 
> i am using the latest release 2.4 for esp 01s
> 
> and 2.3 for the esp32 (the code is still 2.3 for some reason, but it came from the 2.4.5 release)
> 
> For ESP-01s
> 
> 1. the ESP-01s stopped working at some point (maybe because the mcu getting too hot due to its size and design)
> 2. i let the mcu rest for a few seconds to let it cool down, then restarted it and it is working and it worked for a few hours (the next day when i checked my earnings, only the esp32 is mining)
> 3. i just repeat this cool down restart and mine sequence from time to time. (maybe it is the device's problem and not the code)
> 
> i probably need to put a heatsink on it to dissipate the heat and not let the mcu overheat.
> 
> For the ESP 32
> 
> 1. i was previously using the 2.3 version before the 2.4.5 release but after a few days the mining stopped completely and my earnings stopped increasing
> 2. i updated it to the latest one from the 2.4.5 folder but the one on the android app says that the miner is using ver 2.3
> 3. yesterday the mining stopped and i had to restart it and after restarting it, it works again.
> 
> i am still monitoring if my earning would stop and which device would stop first
> 
> though the android app could get some improvements it is irritating when you are looking at which miners are currently working but after opening the app the miner's list is empty and when it did show up it only last for a few seconds.
> 
> it would be great if the list stays the same and would just refresh without clearing the list and add a timer
> 
> (ex.
> miner_1 4.84 kH/s
> core 1 ver 2.3 diff 2000, 10/10
> last activity 50 seconds ago
> )
> 
> this would also help in debugging, this would help users see if their miners stopped working, which and when.

Which version are you running? 2.4 or 2.4.5

**Comment by primitt** [comment]
I see now nvm

**Comment by ghost** [comment]
I have tried re uploading all of the sketches today for the esp32 and esp01s.

The esp01s seems to work fine now without shutting down. version 2.4.6 as indicated by the web wallet.

the esp32's hash rate became 10 -11  kH/s in each core for the 2 cores. version 2.3 as indicated by the web wallet.

**Comment by ghost** [comment]
my esp01s and esp32 miners seems to be stable now and had not stopped mining after a day like it did in the past
