### ISSUE TITLE
Is there a way to add new mining devices when the script has already run once?

### ISSUE THREAD

**Issue by StachRedeker** [duino-coin/duino-coin#487]
I have been playing around with Duino Coin for the past two days now, and I am really enjoying it.
Currently, I am using a Raspberry Pi 4 as a host, and two Arduino Nanos as miners.
Everything is working perfectly fine, however I am not able to add more Arduino miners, because if I run `AVR_Miner.py` (again), the program skips the 'configuration phase' and straight up starts mining.

![it straight up starts mining](https://i.imgur.com/noM2Auy.png)

My go to solution up until now was just to delete the folder and download the GitHub repo again, but I feel like there should be an easier way. Is there any?

Whatever the answer may be: keep up the good work!

**Comment by revoxhere** [comment]
You can remove the Miner_config.cfg file in the AVRMiner_v2.45_resources folder to re-run the config tool again or edit the file yourself and specify the boards there, separated by commas: `avrport = /dev/ttyUSB0,/dev/ttyUSB1,etc..`

**Comment by StachRedeker** [comment]
Thanks a lot!
