### ISSUE TITLE
error found Crypto.h library not found.

### ISSUE THREAD

**Issue by upendrasvkm** [duino-coin/duino-coin#490]

**Comment by BastelPichi** [comment]
Install via library manager.

**Comment by upendrasvkm** [comment]
i am not finding library can you send link of this library.

**Comment by BastelPichi** [comment]
> i am not finding library can you send link of this library.

Sorry, you just need to unzip the whole folder, then there should be no problem. If you just unzip the .ino file it wont work.

**Comment by upendrasvkm** [comment]
unzip whole folder but not work.

**Comment by BastelPichi** [comment]
> unzip whole folder but not work.

Then put the crypto.h file into your librarys folder.

**Comment by upendrasvkm** [comment]
GOT error -'experimental' has not been declared

**Comment by revoxhere** [comment]
Update your esp8266 core to the newest version

**Comment by upendrasvkm** [comment]
got error - hard resetting via rts pin

**Comment by revoxhere** [comment]
That's not an error, it means code was uploaded to your board.

**Comment by upendrasvkm** [comment]
But my hotspot not onnected yet

**Comment by revoxhere** [comment]
Make sure you've entered the correct wifi credentials in the code

**Comment by upendrasvkm** [comment]
Enter correct wifi credentials

**Comment by upendrasvkm** [comment]
thank you founder.
