### ISSUE TITLE
Raspberrypi 4 mining- console and wallet hash rate is not matching

### ISSUE THREAD

**Issue by bentech4u** [duino-coin/duino-coin#491]
HI

Thanks for this wonderful crypto idea,

i have started mining from my laptop and Raspberrypi

in Laptop, console is showing 2.56 MH/s but in wallet it is reporting only 323 KH/s

Raspberry pi 4 ( 4gb), in console 341 MH/s But in wallet, only 85 KH/s

both of them are mining contunisully from last 3 days till now only 12 coins.

please help me, i was planning to add more RPI.

regards,
Ben

**Comment by revoxhere** [comment]
Hey, make sure you're using the correct username on the miners (usernames are case sensitive), but since you said they are mining, it should work. Miners get listed in the API after 5 successful shares, so maybe they were having issues when you checked

**Comment by bentech4u** [comment]
HI

thanks for the response,

yes the username is correct and that's the reason i can able to monitor these two rigs from https://wallet.duinocoin.com/. Total hashrate: 2.50 MH/s is what showing in web wallet.

since last two days it is working, and from my previous question to this response i got 1 coin (2 hours interval).

**Comment by BastelPichi** [comment]
> Raspberry pi 4 ( 4gb), in console 341 MH/s But in wallet, only 85 KH/s

Arduinos are better....

**Comment by bentech4u** [comment]
To start from Ardunio, we need PC right?

i started something with ESP32,
