### ISSUE TITLE
Minimizing the computation range

### ISSUE THREAD

**Issue by PvtSec** [duino-coin/duino-coin#497]
The computation loop can be made to start from a bit higher number, so a slight increment may favor.

**Comment by revoxhere** [comment]
Can you elaborate?

**Comment by PvtSec** [comment]
> Can you elaborate?

# Correct me if I'm wrong
The sha1 hash is calculated from 0 right in the for loop on each thread?
So most submitted shares seems to be of higher value. So the for loop can be made to start the iteration from higher values.

**Comment by YeahNotSewerSide** [comment]
Yes it can, but the number is random in the range [0,difficulty*100], so can occur situation, when result is 0

**Comment by PvtSec** [comment]
What about creating a dictionary or something for the same base hash and different targets, so that the share can be submitted without the need to loop all over again?

**Comment by YeahNotSewerSide** [comment]
base hash always different, is it not?

**Comment by revoxhere** [comment]
Base hash is different for every share

**Comment by PvtSec** [comment]
for received job

**Comment by PvtSec** [comment]
```
2.4
JOB,username,NET
bd9e5c0315335a7677a522b6b1eea9b5e682279e, d29cb5d614b35f73b0a969de40843a62a849d717, 235947
1,1,TEST_SHARE
BAD
JOB,username,NET
bd9e5c0315335a7677a522b6b1eea9b5e682279e, 8072817647b516ff5d9488f75114258087ff7268, 393025
```


bd9e5c0315335a7677a522b6b1eea9b5e682279e  ---> this remains same for some moment, so ... just thinking

**Comment by revoxhere** [comment]
This is not expected, I'll fix it later today
