### ISSUE TITLE
About the officially tested devices

### ISSUE THREAD

**Issue by joaquinbvw** [duino-coin/duino-coin#498]
Hi! I have a question about the officially tested devices table on the Readme file. Are those hashrate values view from the server perspective or on the client side? I ask because I'm running the PC miner on an Odroid XU4 board (8 cores) and I see 1MH/s on each core, but on the web wallet I see a little bit more than 1MH/s for all together. I guess it has something to do with the latency, ping time and all that but I want to know just to update the table.

**Comment by revoxhere** [comment]
I was using the client-side values

**Comment by BastelPichi** [comment]
> Hi! I have a question about the officially tested devices table on the Readme file. Are those hashrate values view from the server perspective or on the client side? I ask because I'm running the PC miner on an Odroid XU4 board (8 cores) and I see 1MH/s on each core, but on the web wallet I see a little bit more than 1MH/s for all together. I guess it has something to do with the latency, ping time and all that but I want to know just to update the table.

Its a bug. The pc miner shows the total hashrate, not the hashrate per core.

**Comment by joaquinbvw** [comment]
> > Hi! I have a question about the officially tested devices table on the Readme file. Are those hashrate values view from the server perspective or on the client side? I ask because I'm running the PC miner on an Odroid XU4 board (8 cores) and I see 1MH/s on each core, but on the web wallet I see a little bit more than 1MH/s for all together. I guess it has something to do with the latency, ping time and all that but I want to know just to update the table.
> 
> Its a bug. The pc miner shows the total hashrate, not the hashrate per core.

Oh good to know. Thanks! Will update the table then.

**Comment by joaquinbvw** [comment]
By the way, the Raspberry Pi Zero power consumption seems a little bit off... I don't have any but I believe should be higher. I believe that is the idle power consumption but running DUCO should be higher, just something to take into account.

**Comment by revoxhere** [comment]
I also don't have a pi zero, and you may be right that it's the idle consumption. I will look for more data to update it
