### ISSUE TITLE
Windows defender and console official miner

### ISSUE THREAD

**Issue by BoyNG** [duino-coin/duino-coin#502]
Deffender says - wacapew.c!ml on checking PC_Miner.exe
Whats is that?

**Comment by kaiiwaii** [comment]
False positive (pyinstaller thing)

**Comment by BastelPichi** [comment]
> Deffender says - wacapew.c!ml on checking PC_Miner.exe
> Whats is that?

its a false positive. If youre annoyed by that, follow these steps from the readme:
If you are on Windows, download Python 3, then our [repository](https://github.com/revoxhere/duino-coin/releases), extract it and open the folder in command prompt. In CMD, type:

py -m pip install -r requirements.txt


After doing this, you are good to go with launching the software (e.g. python3 PC_Miner.py OR py PC_Miner.py).

**Comment by BastelPichi** [comment]
PS: you would need a code signing cerificate to get rid of that. And they arent cheap.
