### ISSUE TITLE
NODEMCU upload error

### ISSUE THREAD

**Issue by s1ashtv** [duino-coin/duino-coin#504]
![ssss](https://user-images.githubusercontent.com/36398850/118209374-b3d15f00-b492-11eb-95ff-6a17ee0af885.PNG)
im having this error when i upload the esp8266 code into my nodemcu despite it is readable in the IDE,. is there like a driver that is needed to be installed before uploading the code?. Thanks in advance for the answers

**Comment by ghost** [comment]
if it's esp8266, does it use a ch340g chip? and if yes, do you have that driver installed in your computer?

**Comment by s1ashtv** [comment]
yes it is already installed, got the driver from the arduino forums

**Comment by revoxhere** [comment]
This is not an error related to us, but maybe something from this will help: 
* https://forum.arduino.cc/t/esp-8266-timed-out-waiting-for-packet-header/597634/8 
* https://www.reddit.com/r/esp8266/comments/d1z42x/cant_upload_to_esp8266_esptoolfatalerror_timed/
* https://randomnerdtutorials.com/solved-failed-to-connect-to-esp32-timed-out-waiting-for-packet-header/

**Comment by s1ashtv** [comment]
ill take a look at it, hope they works, thanks @revoxhere

**Comment by D4NS4M** [comment]
I know that error mostly from esp01/s.
But if it's a NODEMCU u can hold the flash button pressed, while you connect it to the USB.
That way it stays in flash mode till reset

**Comment by s1ashtv** [comment]
> I know that error mostly from esp01/s.
> But if it's a NODEMCU u can hold the flash button pressed, while you connect it to the USB.
> That way it stays in flash mode till reset

tried that already and the output is still the same

**Comment by BastelPichi** [comment]
> that already and the output is still same

Just upload it via arduino ide. That script is not working for me too, maybe i can fix it.

**Comment by s1ashtv** [comment]
> > that already and the output is still same
> 
> Just upload it via arduino ide. That script is not working for me too, maybe i can fix it.

uploaded it on the arduino ide and that the image above the post is the error im getting upon uploading the code

**Comment by xscode** [comment]
My Nano's have the same .....-----.... thing and I have to press a button on the board to enable it to write

**Comment by uiisse** [comment]
try this: 
1) press FLASH button until "uploading the code" appears in Arduino IDE, then release it.
2) if it doesn't work, immediately try to compile/upload again
