### ISSUE TITLE
Wss ip

### ISSUE THREAD

**Issue by VatsaDev** [duino-coin/duino-coin#510]
hi, i noticed that the webminer ip is on ws://, could it pleasse be set to wss://, so both http and https can use it, for https web mining?

thanks, vatsadev

**Comment by LDarki** [comment]
Read the [Socket APi](https://github.com/revoxhere/duino-coin/tree/useful-tools#socket-api) before open a issue like this please.

```
wss://51.15.127.80:15808
ws://51.15.127.80:14808

--

tcp://51.15.127.80:2811
```

**Comment by VatsaDev** [comment]
woah, that was fast!

thanks

**Comment by LDarki** [comment]
No problem, sorry for the "rudeness", I'm not good at these things
