### ISSUE TITLE
ESP32-CAM stuck in Scanning Wifi loop

### ISSUE THREAD

**Issue by modfiles** [duino-coin/duino-coin#516]
my ESP32-CAM, aside from OTA that is not working, it is also stuck in Scanning Wifi The only working version is the last update from Lulaschkas https://github.com/revoxhere/duino-coin/commit/fce2be95cb7e61d1bb385141db971f8086645f87#diff-048cbce4cf0e813c4d4b37b217ced9fab44415fb62e93078b5bfd73c62564339
![Capture](https://user-images.githubusercontent.com/11314888/118386351-6d723080-b649-11eb-91a1-f236e483abe0.JPG)

btw, my network is hidden and no security

**Comment by MPM1107** [comment]
There's a known issue with the ESP32 being unable to connect to hidden wifi networks on channel 13. Do you happen to have your network on channel 13 in addition to it being hidden?

**Comment by joaquinbvw** [comment]
> my ESP32-CAM, aside from OTA that is not working, it is also stuck in Scanning Wifi The only working version is the last update from Lulaschkas [fce2be9#diff-048cbce4cf0e813c4d4b37b217ced9fab44415fb62e93078b5bfd73c62564339](https://github.com/revoxhere/duino-coin/commit/fce2be95cb7e61d1bb385141db971f8086645f87#diff-048cbce4cf0e813c4d4b37b217ced9fab44415fb62e93078b5bfd73c62564339)
> ![Capture](https://user-images.githubusercontent.com/11314888/118386351-6d723080-b649-11eb-91a1-f236e483abe0.JPG)
> 
> btw, my network is hidden and no security

Ok. If your network is hidden then it will never get out of that loop. That part of the code is to list all the networks available and close to your ESP32 so you can see if your network is there and it has a strong signal. I can make another option to remove that part in case any user don't want it or if they have a hidden network like yours. I'll work on that.

**Comment by joaquinbvw** [comment]
By the way, take a look into this issues on the Espressif repository:

https://github.com/khoih-prog/ESP_WiFiManager/issues/53
https://github.com/espressif/arduino-esp32/issues/3325

You will definitely have some limitations with hidden networks in the future. I would also agree with the suggestion there, try not to use hidden networks if you can, security is high enough nowadays to not use hidden networks. Is just a recommendation, I'll still include the option to disable the scan of networks if the user want to.

**Comment by joaquinbvw** [comment]
I've made a quick fix to the code. It seems that the WiFiScan function supports hidden networks if you set a parameter. Please try this code:

https://github.com/revoxhere/duino-coin/blob/64da14a9c36a3c7fdbb7cb8718a68f57053a28f8/ESP32_Code/ESP32_Code.ino

I've made the pull request but haven't tested yet. @revoxhere please wait for the testing before approving the pull request.

**Comment by modfiles** [comment]
its working now, thank you.
