### ISSUE TITLE
Make source-code open source for improving chain.

### ISSUE THREAD

**Issue by KaffinPX** [duino-coin/duino-coin#521]
^^

**Comment by revoxhere** [comment]
Hey, all codes are open-source, you even posted this on the GitHub where most of the things are located. You can check my profile for checking out things like the webwallet.

**Comment by KaffinPX** [comment]
I want DuinoCoins server open-source

**Comment by revoxhere** [comment]
I said everything is open source, server too, maybe reading the README would help? 
![image](https://user-images.githubusercontent.com/50244265/118546582-700f7b80-b758-11eb-9b40-79ea9bee172c.png)

**Comment by KaffinPX** [comment]
Thanks
