### ISSUE TITLE
High estimate, low income

### ISSUE THREAD

**Issue by Nickster2828** [duino-coin/duino-coin#524]
I've been running my rig for 2 days now (just 2 arduino Uno comparable boards) and my daily estimate had been right around 9-17 coins per day, but so far after running for 2 days straight I've only made 5 coins in total. Does anyone know how I could go about fixing this issue? Also on a unrelated note, is there a way to overclock these boards? Mine aren't even getting warm right now... so I think I could turn it up a little if that's possible. Thanks!![image](https://user-images.githubusercontent.com/84460784/118835142-f672ad00-b87f-11eb-9818-fd1413b32e33.png)

**Comment by revoxhere** [comment]
Hmm, looks like there's something wrong with the estimated profit then. I will take a look later. You can try using Lulaschkas' mining dashboard for (possibly) more accurate estimated profit values

**Comment by BastelPichi** [comment]
> 
> 
> I've been running my rig for 2 days now (just 2 arduino Uno comparable boards) and my daily estimate had been right around 9-17 coins per day, but so far after running for 2 days straight I've only made 5 coins in total. Does anyone know how I could go about fixing this issue? Also on a unrelated note, is there a way to overclock these boards? Mine aren't even getting warm right now... so I think I could turn it up a little if that's possible. Thanks!![image](https://user-images.githubusercontent.com/84460784/118835142-f672ad00-b87f-11eb-9818-fd1413b32e33.png)

Sometimes there a lot of errors and the miner restarts every 20sec. That lowers the profil drastically. Try and check the console.
