### ISSUE TITLE
[Request] Add £ support. 

### ISSUE THREAD

**Issue by ghost** [duino-coin/duino-coin#527]
Are there plans to add GBP (£) support?

**Comment by dansinclair25** [comment]
@MrHallway0 that depends entirely on the exchanges that are willing to trade DUCO. As far as I'm aware, there's no immediate plans to trade in GBP, but if the demand increases then maybe.

**Comment by ghost** [comment]
Thanks, that makes sense.

**Comment by revoxhere** [comment]
I see this maybe in the distant future. Closing for now
