### ISSUE TITLE
Vulnerability: Can mine as an Arduino with a PC

### ISSUE THREAD

**Issue by vojta-horanek** [duino-coin/duino-coin#531]
I've been trying out this project for a few days and I was just now able to discover (in my opinion) a pretty serious vulnerability. It is very simple to reproduce. Just modify [these lines](https://github.com/revoxhere/duino-coin/blob/40172e14078f14e03444224a4b1967e8a0ec05e2/PC_Miner.py#L902-L913)  in `PC_Miner.py` to
```python
soc.sendall(bytes(
    str(ducos1res)
    + ","
    + str(threadhashcount * 1000)
    + ",Official AVR Miner (DUCO-S1A) v"
    + str(MINER_VER)
    + ","
    + str("None")	
    + ","
    +str("DUCOID1231231231231231231"),
    encoding="utf8"))
```
(You might need to replace the DUCOID string with a valid id, I just randomly generated this one).

This modification allows the PC miner to identify as a AVR miner and thus having a much higher effectiveness eliminating Kolka.
I would suggest verifying actual Arduinos on the server, that could fix this issue.

Bellow is a screenshot of Duino-Coin Mining-dashboard with the modified PC_Miner running:
![duino-dash](https://user-images.githubusercontent.com/12630566/119147556-00490b80-ba4c-11eb-816d-d5763f0bb433.png)
![duco-list](https://user-images.githubusercontent.com/12630566/119147561-0212cf00-ba4c-11eb-9710-ef4b313711f6.png)

**Comment by revoxhere** [comment]
You are not mining on the AVR difficulty.

**Comment by vojta-horanek** [comment]
So this does not circumvent Kolka? The server thinks this is a computer and it reduces its efficiency accordingly? Is just this dashboard wrong?

**Comment by YeahNotSewerSide** [comment]
You are getting high hashrate, because kolka determines, you are not mining with AVR, so your efficiency decreases.

**Comment by vojta-horanek** [comment]
Alright, thanks for the explanation. I guess the dashboard should be fixed then :D

**Comment by torralbaa** [comment]
Well, the dashboard just gets the identifier string your miner sends, there's no "fix", it's a merely visual thing. Kolka should still use the hashrate and requests per second to assign your difficulty, as others here said.
