### ISSUE TITLE
ESP's not showing true hash-rate

### ISSUE THREAD

**Issue by kickshawprogrammer** [duino-coin/duino-coin#532]
@cryptosc0ps_NL#5959 posted this message on DISCORD 

https://discord.com/channels/677615191793467402/677615906322382862/845434155710021633

I've been having this problem too over the last couple of days. I've gone searching through the server code to see if something in there could be causing the confusion and I come across the following code snippet:

```
        try:
            reported_hashrate = round(float(result[1]))
            hashrate_is_estimated = False
        except:
            reported_hashrate = hashrate
            hashrate_is_estimated = True

        if abs(reported_hashrate - hashrate) > 5000:
            reported_hashrate = hashrate
```

I suspect this to be the problem because of latency. As an example: my reported hash-rate of 9.1K - your calculated 3.2K is greater than 5000 and triggers your assumption in the code. If this is the intended result, then maybe just ignore the reported value? But then I guess we'd be back to paying for latency again...

I understand the reasoning for this: you're trying to ensure that the requested difficulty is appropriate for the hardware; but what if you just use the the larger value (our reported value vs your calculated value)? That way, the award would always be the smallest of the two possible values (assuming share-time/hash-rate is still a factor - that is)

It would appear that only ESP's seem to have this issue since only ESP's see a difference of 5K in hash-rates; AVR's are only in the 100's and PC are in the millions so will they see a difference of a mere 5K? I don't know what the true resolution is.

**Comment by revoxhere** [comment]
Should be fixed now, more or less
