### ISSUE TITLE
Error:  'charmap' codec can't encode character '\u2713'

### ISSUE THREAD

**Issue by JPG-Consulting** [duino-coin/duino-coin#533]
Hi,

I keep getting this error on a Raspberry PI. The error is:

(mining err: 'charmap' codec can't encode character '\u2713' in position 53: character maps to <undefined>)

I Also get the same error on the greeting message and don't know how to solve it. My current locale is:

LANG=es_ES@euro
LANGUAGE=
LC_CTYPE="es_ES@euro"
LC_NUMERIC="es_ES@euro"
LC_TIME="es_ES@euro"
LC_COLLATE="es_ES@euro"
LC_MONETARY="es_ES@euro"
LC_MESSAGES="es_ES@euro"
LC_PAPER="es_ES@euro"
LC_NAME="es_ES@euro"
LC_ADDRESS="es_ES@euro"
LC_TELEPHONE="es_ES@euro"
LC_MEASUREMENT="es_ES@euro"
LC_IDENTIFICATION="es_ES@euro"
LC_ALL=

What am I missing?

**Comment by revoxhere** [comment]
How are you launching the miner? Updating python doesn't help?

**Comment by DaanKrug** [comment]
> How are you launching the miner? Updating python doesn't help?

Me have same problem but when running by source (after compiled version fail).
It seems that encoding error. I tried put # coding: utf8  after first line and generate other problems.

In Compiled version show
[16439] Error loading Python lib '/tmp/_MEI7eVMGy/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEI7eVMGy/libpython3.8.so.1.0)

![print_01](https://user-images.githubusercontent.com/26380119/119395152-81510e80-bca9-11eb-89ef-77714695557a.png)

I use Ubuntu 18.04. Unfortunatelly  I cannot use the miner.

**Comment by revoxhere** [comment]
Launch the miner from source and then it will work.
