### ISSUE TITLE
ESP8266 with cp2102

### ISSUE THREAD

**Issue by manicz** [duino-coin/duino-coin#535]
hello! I hope your doing well.

I have an ESP8266 cp2102 can it do mining?

beginner here

**Comment by revoxhere** [comment]
Yes, the process is described for example on the [getting started](https://duinocoin.com/getting-started) page.

**Comment by manicz** [comment]
now i cant upload the code it says crypto.h no such.. i already followed the instructions to replace arduino files

**Comment by revoxhere** [comment]
Replace arduino files? I'm not sure what you're talking about, but make sure you have ESP8266 selected as a board and your ESP8266 Core for Arduino IDE is on the latest version.

**Comment by manicz** [comment]
i cant download the python3 get.py on esp8266/tools using git

what should i do?

**Comment by revoxhere** [comment]
Are you following these instructions? https://github.com/esp8266/Arduino#installing-with-boards-manager

**Comment by manicz** [comment]
yes. it says

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by revoxhere** [comment]
What are you doing that requires python?

**Comment by manicz** [comment]
downloading the binary tools

**Comment by revoxhere** [comment]
Installation with Arduinos board manager doesn't require any binary tools.
From the README I linked earlier:

> Installing with Boards Manager
> Starting with 1.6.4, Arduino allows installation of third-party platform packages using Boards Manager. We have packages available for Windows, Mac OS, and Linux (32 and 64 bit).
> 
> Install the current upstream Arduino IDE at the 1.8.9 level or later. The current version is on the Arduino website.
> Start Arduino and open the Preferences window.
> Enter https://arduino.esp8266.com/stable/package_esp8266com_index.json into the File>Preferences>Additional Boards Manager URLs field of the Arduino IDE. You can add multiple URLs, separating them with commas.
> Open Boards Manager from Tools > Board menu and install esp8266 platform (and don't forget to select your ESP8266 board from Tools > Board menu after installation).
> Boards manager link: https://arduino.esp8266.com/stable/package_esp8266com_index.json

This will give you the ESP support for Arduino IDE.
