### ISSUE TITLE
Pi Pico Mining?

### ISSUE THREAD

**Issue by robtech21** [duino-coin/duino-coin#540]
Is it possible to mine Duino-Coin using a Raspberry Pi Pico? I've got one laying around, but I don't have anything to use it for.

**Comment by dansinclair25** [comment]
It is. I got it working only a few days ago, but it's far from ready to be released. I only managed to get it mining on one core though so it's probably not being fully utilised. I imagine someone with greater Pico coding skills/knowledge than myself will get it working soon.

**Comment by joaquinbvw** [comment]
I don't have a Pico right now and the latest code is not ready for that, you'll see an error if you try to compile it. Maybe in the future though...

**Comment by robtech21** [comment]
> It is. I got it working only a few days ago, but it's far from ready to be released. I only managed to get it mining on one core though so it's probably not being fully utilised. I imagine someone with greater Pico coding skills/knowledge than myself will get it working soon.

@dansinclair25 I don't know a whole lot about the pico but I am willing to help test code if needed.

**Comment by joaquinbvw** [comment]
Good! The only thing that we should worry about is the unique ID library, it seems that there is a unique ID for the Pico so I will take a look into it this week.

https://www.raspberrypi.org/forums/viewtopic.php?t=302147

**Comment by joaquinbvw** [comment]
> > It is. I got it working only a few days ago, but it's far from ready to be released. I only managed to get it mining on one core though so it's probably not being fully utilised. I imagine someone with greater Pico coding skills/knowledge than myself will get it working soon.
> 
> @dansinclair25 I don't know a whole lot about the pico but I am willing to help test code if needed.

You can test it now, the latest code should support the Pico. I have compile it without problems but I haven't tested it yet since I don't have that board.

**Comment by robtech21** [comment]
> You can test it now, the latest code should support the Pico. I have compile it without problems but I haven't tested it yet since I don't have that board.

Okay, I'll try to get it on there within a week or two (Keeping in mind that I'm fairly busy at the moment)

**Comment by robtech21** [comment]
Also, two other things would be cool:

* Utilization of both of the Pico's cores
* A MicroPython version (for easier setup or new users)

**Comment by McTonderski** [comment]
Is there code somewhere to test it on pico ?

**Comment by joaquinbvw** [comment]
> Is there code somewhere to test it on pico ?

The latest version of Arduino_Code should work on the Pico too. I haven't test it yet but another user has, you can try it.

**Comment by robtech21** [comment]
> The latest version of Arduino_Code should work on the Pico too. I haven't test it yet but another user has, you can try it.

@joaquinbvw I've been trying to get it to work on the pico but I've been running into an issue where I can't install support for the board (Install seems to "freeze" at `installing tools 3/5`) and it won't let me try to install it again after multiple errors. It's frustrating.

If anyone has solutions I will be willing to try them, but for now, it's a no.

**Comment by ernesto75** [comment]
Hi all, i started to use my Pico to mine Duco from a while, i have the latest Arduino_Code.ino on Pico and i can use the AVR_Miner.py v2.49 without problems. So i guess is possible to mine with Pico. The only issue is that makes around 2700H/s and so i get some warnings in Dashboard that my Arduino is mining too fast, hope it doesn't get banned! I see the diff is automagically adjusted from 6 to 300, but i cannot do further adjustments like setting ARM diff via config file (not working). I am open to suggestions on how fine tune this board and improve the actual 2 coins/day. Also if you want me to test something, let me know. Thanks

**Comment by revoxhere** [comment]
@ernesto75 Yes, this is intended, Pi Pico was added in 2.49. The difficulty gets automatically adjusted for AVR - 300, so everything is fine.

**Comment by joaquinbvw** [comment]
The Pi Pico is already supported and tested. I believe this issue can be closed now.

**Comment by suchdolteam** [comment]
> Is there code somewhere to test it on pico ?

I tested it on RPi pico but it says "Arduino with Rigname: malina1 and Softwarename: Official AVR Miner 3.0 with Hashrate: 3115H/s is mining too fast (thats not better). "

**Comment by tomasthedev** [comment]
> Is there code somewhere to test it on pico ?

I tested it on RPi pico but it says "Arduino with Rigname: malina1 and Softwarename: Official AVR Miner 3.0 with Hashrate: 3115H/s is mining too fast (thats not better). "
I trying figure out wheres problem

**Comment by raymate** [comment]
Anyone have a tutorial on how to get this on the Pico running... I have a few regular Pi running the Python miner, I have some Picos I want to try, what kind of h/s can the Pico do out of interest ?

**Comment by SebastianMaung** [comment]
I also need a tutorial on this
