### ISSUE TITLE
Serial Monitor Speed in v2.52 is incompatible with Arduino IDE 

### ISSUE THREAD

**Issue by scyto** [duino-coin/duino-coin#546]
**Describe the bug**
When connecting to an ESP32 running 2.52 I was getting garbage on the serial port at all speeds the Arduino IDE Serial Monitor UI supports in Windows.
I eventually discovered changing `Serial.begin(500000); // Start serial connection` to `Serial.begin(115200); // Start serial connection`  solved the issue

**To Reproduce**
1. Download 2.52 ESP32_code
2. Setup wifi params
3. Compile and upload in Arduino IDE
4. Open Arduino IDS serial monitor set to 115200
5. Observer random ascii connections

**Expected behavior**
For  one of the Arduino IDE on windows supported com port speeds to work.
I expected 115200 to work as it had been working and seemed to be the hard coded value.

**Screenshots/photos**
![image](https://user-images.githubusercontent.com/11369180/119441871-b8401800-bcdb-11eb-95df-ca67f513d736.png)

**System (please complete the following information):**
 - OS: Windows 10 - Arduino IDE
 - Software ESP32 Miner
 - Version 2.52

**Additional context**
no other context, i can do a PR to change the hard coded value back if needed?
or I guess i could figure out how to parametrize it so it can be specified in the header (this is my first time tinkering with Arduino code - i managed to parametrize the wifi host name as an example of the limited extent of my skills)

**Comment by joaquinbvw** [comment]
That serial speed is totally compatible with Arduino IDE, if you don't see that speed on your IDE please try updating the ESP32 core or updating the Arduino IDE.

**Comment by scyto** [comment]
I am running the 1.0.6 cores from https://dl.espressif.com/dl/package_esp32_index.json - are those the latest?
I am using M5Stack-ATOM Core
I am running the latest v2.0.0.beta7 IDE.

I don't see any way to influence what appears in the drop down on the right  of this picture (and google searching seemed to indicate it wasn't possible to go higher than this in the serial monitor UI?)

I am new to Arduino IDE (been using esphome before this), so apologies for being dumb.
Not sure what to do next.
this image shows everything working when i changed the code to the lower speed.

![image](https://user-images.githubusercontent.com/11369180/119552817-cfb8e880-bd4f-11eb-9eb9-b5f5f906a364.png)

**Comment by scyto** [comment]
ok I see this is an issue with the beta IDE, shame as the normal IDE breaks on compilation for me (even after uninstall and re-install)

**Comment by joaquinbvw** [comment]
That's weird, are you using PlatformIO by chance? PlatformIO is known to break the Arduino IDE configuration, I don't know what's wrong with them.

But you can always change the baudrate manually back to 115200 there is nothing wrong using that speed, just maybe a little bit slower hashrate. Or you can even disable the serial interface if you are using the ESP32 alone. Disabling the serial interface can be made commenting line 43, you can save some tens of milliamperes disabling it, maybe 100 mA I don't remember the exact value.

**Comment by scyto** [comment]
I have no idea what PlatformIO is or how to change (i will go do some googling :-) )

I am using wifi for the connection to the servers, so i am a little confused how serial speed affect hashing rate (unless software communicates to hardware via serial?)
The upload speed worked fine at 5000000 or whatever the max speed was in the board definition file.

Is it me or is the IDE just janky? For example the 1.x IDE was working perfectly one day and then another day on compilation it told me about missing libraries - its why i switched to IDE2. sigh.  Uninstall and re-install of IDE1 didn't fix ¯\(°_o)/¯ (and i tried windows store version and normal installer version)

So i will use IDE2 to compile and upload the new sketch and then used IDE1 to connect over the network (an option that appeared i assumed because the one unit on latest sketch supports OTA? - which is cool)  IDE 2 had no network option.

anyhoo thanks for the help, appreciate it, will the docs be updated when this releases to state the new speed? (rather than the 115200 it states now - might be wise or you will get a whole bunch of darn noobs like me asking dumb questions :-)

--edit--
OIC its an alternate IDE.
No i am not using atom text editor, so not using PlatformIO
Can I use vscode to edit, compile code and connect to serial without bothering with official arduio IDE?
