### ISSUE TITLE
What about creating a real blockchain?

### ISSUE THREAD

**Issue by KaffinPX** [duino-coin/duino-coin#548]
^^

**Comment by revoxhere** [comment]
You can submit a PR if you've done it, I personally don't see what's wrong with the current one. Closing for now

**Comment by KaffinPX** [comment]
i created a complete cryptocurrency in nodejs, so prob i can integrate it to python too

**Comment by KaffinPX** [comment]
it can be proccess for cold-wallets.

**Comment by MPM1107** [comment]
I don't see any benefit a real blockchain would have, as this is a centralised coin by design and will always have to be. You wouldn't gain anything with a blockchain.
