### ISSUE TITLE
I have a problem with the use aruduino uno

### ISSUE THREAD

**Issue by suphat060841** [duino-coin/duino-coin#551]
I have been using it for 2 days and it says:

**"Arduino is taking longer than expected, resubmitting work. (errorCounter> 5:)**"

How should I fix the problem?

**Comment by revoxhere** [comment]
Try reconnecting your board or trying to re-upload the code for it. Also, what version are you using?

**Comment by suphat060841** [comment]
> Try reconnecting your board or trying to re-upload the code for it. Also, what version are you using?

The board I use the Arduino Uno R3, the duino-coin I use version 2.4.5

**Comment by BastelPichi** [comment]
Try with the latest source code, its more stable but you need python on your pc.

**Comment by suphat060841** [comment]
> Try with the latest source code, its more stable but you need python on your pc.

Okay, now I have edited it using the latest source code. Can be used
