### ISSUE TITLE
I can't trade using Node-S exchange.

### ISSUE THREAD

**Issue by suphat060841** [duino-coin/duino-coin#552]
This message appears after entering Nodes exchange, what should I do?
![Capture](https://user-images.githubusercontent.com/44937883/119913306-cade7980-bf87-11eb-8cc5-f42578559bb7.PNG)

**Comment by connorhess** [comment]
Node-S has fallen victim to a ddos/(http request) attack due to a vulnerability with one of the older api endpoints. No data is compromised. But 1 part of the database has been flooded with random data. This issue is being resolved and we will be running normally before 1 June

**Comment by suphat060841** [comment]
> Node-S has fallen victim to a ddos/(http request) attack due to a vulnerability with one of the older api endpoints. No data is compromised. But 1 part of the database has been flooded with random data. This issue is being resolved and we will be running normally before 1 June

The system DUCO exchange  also crashes, right?

**Comment by connorhess** [comment]
You need to ask @revoxhere

But as far as I know it is also offline currently

**Comment by suphat060841** [comment]
> You need to ask @revoxhere
> 
> But as far as I know it is also offline currently

ok

**Comment by sys-256** [comment]
@suphat060841 It should be fully working now (it does for me at least).
