### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by Kukorcraft** [duino-coin/duino-coin#554]
Hi, when I logged in to the website it says "loading" and 30 minutes later "loading".
I tried it on the application too.
I think that problem is because this server is down.
When goes online the server and when goes offline?
Thanks for reading!

**Comment by primitt** [comment]
> Hi, when I logged in to the website it says "loading" and 30 minutes later "loading".
> 
> I tried it on the application too.
> 
> I think that problem is because this server is down.
> 
> When goes online the server and when goes offline?
> 
> Thanks for reading!

yes the server has been down

**Comment by Kukorcraft** [comment]
But, when goes online and when goes offline?

**Comment by revoxhere** [comment]
Should be working fine now. I'm trying to figure out what's causing it
