### ISSUE TITLE
I'm using python on windows and it crashes

### ISSUE THREAD

**Issue by suphat060841** [duino-coin/duino-coin#558]
I am using python 3.9.5 on windows 64bit, how should this be fixed?

![10](https://user-images.githubusercontent.com/44937883/120125577-9cf57100-c1e3-11eb-9b25-4b1c96499ac8.PNG)

**Comment by LDarki** [comment]
Hi, you tryed enabling the NTVDM feature ?
```c
Win + r
optionalfeatures.exe
<Legacy Components>
NTVDM

After that:
Win + r
FONDUE.exe /enable-feature:NTVDM
```

**Comment by sys-256** [comment]
Looks like the donation program is causing the issue. Try deleting the AVR_Miner_2.49_recourses folder, and run avr_miner.py again.

When it ask you how much you want to donate, type 0. If you do so, it wont download and execute the donate_executeable.exe, so you should get no errors.

**Comment by suphat060841** [comment]
> Looks like the donation program is causing the issue. Try deleting the AVR_Miner_2.49_recourses folder, and run avr_miner.py again.
> 
> When it ask you how much you want to donate, type 0. If you do so, it wont download and execute the donate_executeable.exe, so you should get no errors.

Okay, now it works fine, but I still have one more problem, net0 can't contact the server, what is the solution ?

**Comment by sys-256** [comment]
> > Looks like the donation program is causing the issue. Try deleting the AVR_Miner_2.49_recourses folder, and run avr_miner.py again.
> > When it ask you how much you want to donate, type 0. If you do so, it wont download and execute the donate_executeable.exe, so you should get no errors.
> 
> Okay, now it works fine, but I still have one more problem, net0 can't contact the server, what is the solution ?

Maybe the server were down. If you are in the discord server, you can check it with "!serverstatus".

All servers are online right now. Does it work now?

**Comment by suphat060841** [comment]
> > > Looks like the donation program is causing the issue. Try deleting the AVR_Miner_2.49_recourses folder, and run avr_miner.py again.
> > > When it ask you how much you want to donate, type 0. If you do so, it wont download and execute the donate_executeable.exe, so you should get no errors.
> > 
> > 
> > Okay, now it works fine, but I still have one more problem, net0 can't contact the server, what is the solution ?
> 
> Maybe the server were down. If you are in the discord server, you can check it with "!serverstatus".
> 
> All servers are online right now. Does it work now?

It works but still can't contact the server sometimes

**Comment by sys-256** [comment]
> It works but still can't contact the server sometimes

@suphat060841 That is usual. There are some issues with the server, and it crashes sometimes. If that happens, the server has te be restarted, which isn't done immediately after it crashes, so it takes some more time until it's fixed.

**Comment by kaiiwaii** [comment]
The server is being ddosed and revox is busy

**Comment by BastelPichi** [comment]
> I am using python 3.9.5 on windows 64bit, how should this be fixed?
> 
> ![10](https://user-images.githubusercontent.com/44937883/120125577-9cf57100-c1e3-11eb-9b25-4b1c96499ac8.PNG)

someone messed up the compiling, just ignore it for now.

**Comment by BastelPichi** [comment]
set donate to 0. Then it should work

**Comment by suphat060841** [comment]
> set donate to 0. Then it should work

yeah it works
