### ISSUE TITLE
More device support

### ISSUE THREAD

**Issue by robtech21** [duino-coin/duino-coin#561]
So I own a Raspberry Pi Pico and it doesn't really work with the official AVR miner (difficulty is always at 6). Changing the difficulty to `ESP8266` and the `SOCKET_TIMEOUT` and `AVR_TIMEOUT`  to 30. Even so, it doesn't really work. My suggestion is to add more difficulty groups or different device miners.

**Comment by revoxhere** [comment]
Have you tried the `ARM` difficulty?

**Comment by robtech21** [comment]
> Have you tried the `ARM` difficulty?

@revoxhere I had no clue that was a thing, I'll give it a try.
