### ISSUE TITLE
split mined amounts?

### ISSUE THREAD

**Issue by VatsaDev** [duino-coin/duino-coin#573]
im trying to make a javascript miner [Mineuino](https://mineuino.vercel.app/), and id like to know how i could setup a 1% goes to specific acccount after mining

EX.
users mines 100 ducos
1% or 1 duco goes to some duino account
id like to this during the mining process, not after

**Comment by VatsaDev** [comment]
similar to how some amount of monero miners goes to coinimp or something, but during the mining process

**Comment by sys-256** [comment]
i'm making one too (https://github.com/Hoiboy19/Duino-JS) as you can see in the non-minified version, I use sharesCorrect++; and sharesWrong++; when a share is wrong or good.

what you could do is that when sharesCorrect reaches 99, you change the username to the specific account, if the share for that specific account is correct, you go again to the account you started with, and set the sharesCorrect to 0. and if it reaches 99 again, you do the same proces again.


But keep in mind it would take a while until they reach 99 shares, and by that time, the user is probably at another website.

**Comment by revoxhere** [comment]
It's not possible currently, and isn't planned, at least for now, so the solution of just asking for a different username for every N-th job is the best idea.

**Comment by VatsaDev** [comment]
thanks
