### ISSUE TITLE
STM32 mining?

### ISSUE THREAD

**Issue by BAZESHOT** [duino-coin/duino-coin#574]
I want mining at STM32, this project have this?

**Comment by izonu** [comment]
there is currently no stm32 miner but you can make one if you want :)

**Comment by BAZESHOT** [comment]
> there is currently no stm32 miner but you can make one if you want :)

I want, but I do not have enough experience for this =(

**Comment by sys-256** [comment]
> I want, but I do not have enough experience for this =(

[I found this tutorial](https://stm32-base.org/guides/getting-started.html), and it looks like you can just run plain C code on a STM32.

If so, you can use [the d-cpuminer](https://github.com/phantom32-0/d-cpuminer) by @phantom32-0.

**Comment by izonu** [comment]
yeah it should work with some modifications since the d-cpuminer is made for pc and uses openssh sha libraries, if you can find a replacement for sha libraries and implement duco s1a serial protocol it should work

**Comment by pankleks** [comment]
STM32 minter added to unofficial miners - have fun!

**Comment by pankleks** [comment]
@revoxhere due to hash rate limit, AVR_Minter only works with slowest STM32, faster ones are rejected by the server (probably as they have comparable hash rate to ESP's) - that's ok. But how to connect AVR_Minter to different pool which would accept these hash rates?

**Comment by revoxhere** [comment]
> @revoxhere due to hash rate limit, AVR_Minter only works with slowest STM32, faster ones are rejected by the server (probably as they have comparable hash rate to ESP's) - that's ok. But how to connect AVR_Minter to different pool which would accept these hash rates?

NODE_ADDRESS and AVAILABLE_PORTS can be changed to use the pool IP and address

**Comment by pankleks** [comment]
@revoxhere when doing that it is saying: AVR mining is disabled for pools.

**Comment by izonu** [comment]
change the AVR to ARM in AVR_Miner.py's 715th line so it receives ARM starting difficulty and it should hopefully fix it

**Comment by pankleks** [comment]
changed - still getting `AVR mining is disabled for pools.`

**Comment by izonu** [comment]
try changing it to ESP8266 then
