### ISSUE TITLE
D1 Mini connected, not mining

### ISSUE THREAD

**Issue by visham667** [duino-coin/duino-coin#575]
Uploaded ESP8266 code to two D1Minis but they keep resetting with this sown in the serial monitor:

> 07:26:50.615 -> Connecting to Duino-Coin server...
> 07:26:55.710 -> Connection failed.
> 07:26:55.710 -> Resetting ESP...
> 07:26:56.221 -> 
> 07:26:56.221 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> 07:26:56.221 -> 
> 07:26:56.221 -> load 0x4010f000, len 3656, room 16 
> 07:26:56.221 -> tail 8
> 07:26:56.221 -> chksum 0x0c
> 07:26:56.221 -> csum 0x0c
> 07:26:56.221 -> v9c56ed1f
> 07:26:56.221 -> ~ld
> 07:26:56.274 -> 
> 07:26:56.274 -> Duino-Coin ESP8266 Miner v2.4
> 07:26:56.274 -> Connecting to:
> 
And when it does connect it gets max 10 shares and does not show up on my miner list. I also have two Unos connected doing 160H/s each, but only got 30duco in 3 days.
After it connects, this is what it shows:

> 07:20:04.166 -> Connecting to Duino-Coin server...
> 07:20:12.158 -> Connected to the server. Server version: 
> 07:20:12.456 -> Asking for a new job for user: 
> 07:20:27.456 -> Job received:   1
> 07:20:27.456 -> Asking for a new job for user: 
> 07:20:42.461 -> Job received:   1
> 07:20:42.461 -> Asking for a new job for user: 
> 07:20:57.462 -> Job received:   1
> 07:20:57.462 -> Asking for a new job for user: 
> 07:21:12.446 -> Job received:   1
> 07:21:12.446 -> Asking for a new job for user: 
> 07:21:27.448 -> Job received:   1
> 07:21:27.448 -> Asking for a new job for user: 
> 07:21:42.472 -> Job received:   1

``

 - OS: [Windows]
 - Software [ AVR Miner]
 - Version [2.45]

**Comment by revoxhere** [comment]
Try now
