### ISSUE TITLE
ESP32 constantly rebooting with "Task watchdog got Triggered"

### ISSUE THREAD

**Issue by Leniwcowaty** [duino-coin/duino-coin#576]
I am using ESP32 (LilyGo TTGo T-Display) to mine, but very frequently I get "Task watchdog got triggered", after which ESP reboots. Is this some kind of bug, or error in code? I don't think it's server issue, Arduino and PC miners are running normally.

E(69681) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (69681) task_wdt:  - Task1 (CPU 0)
E (69681) task_wdt: Tasks currently running:
E (69681) task_wdt: CPU 0: IDLE0
E (69681) task_wdt: CPU 1: loopTask
E (69681) task_wdt: Aborting.
abort() was called at PC 0x40139134 on core 0

ELF file SHA256: 0000000000000000

Backtrace: 0x4008f2ec:0x3ffbfb40 0x4008f569:0x3ffbfb60 0x40139134:0x3ffbfb80 0x4008da15:0x3ffbfba0 0x4015e313:0x3ffbc100 0x4013a987:0x3ffbc120 0x40091d29:0x3ffbc140 0x4009057a:0x3ffbc160

Rebooting...

**Comment by revoxhere** [comment]
Please try now

**Comment by Leniwcowaty** [comment]
> Please try now

Now ESP is able to do 70-80 jobs before rebooting
