### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cozfirto** [duino-coin/duino-coin#578]
net0  Error retrieving data from GitHub! Retrying in 10s. (git err: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /revoxhere/duino-coin/gh-pages/serverip.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xefee0390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))) 

is there any way to change the Host?

maybe if the miners had some way to change the host I believe it would be easier to connect to the server

**Comment by sys-256** [comment]
What miner are you using (eg: avr, pc, minimal)?

**Comment by kaiiwaii** [comment]
if you're using a pc miner, wait. Pc mining is disabled due to the high load

**Comment by cozfirto** [comment]
Ya right its PC

**Comment by primitt** [comment]
PC Mining is currently disabled due to server overloading, more info on the duinocoin discord server. (https://discord.gg/CybTZ66J)

**Comment by raymate** [comment]
Im using Raspberry Pis and I thought they are not High powered, now my 4 Pis are not mining getting errors. Unless the Pis are causing high load, who knows.

**Comment by VatsaDev** [comment]
what about js miners?
the js miners arent working either

**Comment by izonu** [comment]
raspberry pies also use pc miner because, well they are pcs
and the js webminer is counted as pc miner too

**Comment by VatsaDev** [comment]
ok, my problem started today

**Comment by VatsaDev** [comment]
yesterday was fine

**Comment by VatsaDev** [comment]
and I tried with the diff set to "AVR" but it still didnt work after 1 share

**Comment by revoxhere** [comment]
Should work now.
