### ISSUE TITLE
when will Pc mining restart?

### ISSUE THREAD

**Issue by VatsaDev** [duino-coin/duino-coin#582]
when will Pc mining restart?

**Comment by kaiiwaii** [comment]
Probably when the database migration and maybe other things are ready

**Comment by connorhess** [comment]
We will try get it running smoothly with the new database. And once that is done it will be re-enabled.

**Comment by VatsaDev** [comment]
oh, the new github project?
ok

**Comment by connorhess** [comment]
https://github.com/connorhess/Duino-Coin-Server/tree/Database-migration
