### ISSUE TITLE
Arduino Mega 2560 is spitting out error "(error reading result from the board: string index out of range, please check connection and port setting)"

### ISSUE THREAD

**Issue by Doofus4ever** [duino-coin/duino-coin#586]
Flash new arduino code 2.4.9 to arduino Mega 2560 and gives error
if u use old arduino code the previous release code it works fine no issue
so i am guessing the new code has a bug.
![arduino_Mega2560_Error](https://user-images.githubusercontent.com/56180193/121931220-5474a200-cd11-11eb-9059-3fb3c5478f22.PNG)
![arduino_Mega2560_Error-Debug](https://user-images.githubusercontent.com/56180193/121931559-ca790900-cd11-11eb-87b5-fe872727a8c8.PNG)

**Comment by Doofus4ever** [comment]
this is when i uploaded the old code 2.4.5 to the Mega 2560 works fine 
![arduino_Mega2560_2 4 5](https://user-images.githubusercontent.com/56180193/121934110-e16d2a80-cd14-11eb-80c6-3fe0b0e170f7.PNG)

**Comment by joaquinbvw** [comment]
Hi, are you using the latest python code for both of them? Please make sure you have all the latest files updated, with the master branch, not the releases.

https://github.com/revoxhere/duino-coin/archive/refs/heads/master.zip

**Comment by Doofus4ever** [comment]
yes i am using the latest code for arduino and avr miner

**Comment by revoxhere** [comment]
Try now, you should get moved to a better difficulty tier. For now - closing.
