### ISSUE TITLE
Cannot find PC_Miner.py file

### ISSUE THREAD

**Issue by Xalex79** [duino-coin/duino-coin#589]
---
name: Bug report
about: Create a report to help us improve
title: 'PC_Miner.py cannot be found'
labels: ''
assignees: ''

---

**Describe the bug**
The code requests a file directory -> /data/data/com.termux/files/home/PC_Miner.py I did that path so the code can find the .py file but It's not working.

**To Reproduce**
1. Write this code '-sudo apt install python3 python3-pip git # Install python3 and git
git clone https://github.com/revoxhere/duino-coin # Clone duino-coin repo
cd duino-coin
pip3 install -r requirements.txt
pip install py-cpuinfo
python3 PC_Miner.py # Launch the official miner
'
2. Error will appear
3. Rewrite the code
4. Code will ask you to accept (y/n) the install of python in the smartphone.
5. Write the code again, error with this path /data/data/com.termux/files/home/PC_Miner.py will appear saying that PC_Miner.py cannot be found "python3: can't open file '/data/data/com.termux/files/home/PC_Miner.py': [Errno 2] No such file or directory 
6. Create those folders and add the files inside home folder 
7. Rewrite the code
8. Bug

**Expected behavior**
In theory it should find the file and open a Duinocoin Miner

**Screenshots/photos**
No needed.

**System (please complete the following information):**
 - OS: Android 7.0
 - Software Termux and Python inside
 - Version Termux 0.101 , Python 21.1.1 (code asks to update via this extra code "'/data/data/com.termux/files/usr/bin/python3: -m pip install --upgrade pip'" to 21.1.2)

**Additional context**
I'm trying to mine Duinocoin with old Android Smartphones that I have laying around, but using the WebMiner is not an option because after 30min-1h it stops mining.

**Comment by kaiiwaii** [comment]
This is not an issue related to duinocoin, it's a termux issue.
