### ISSUE TITLE
Cannot mine with LGT8 board

### ISSUE THREAD

**Issue by donnytakeshi** [duino-coin/duino-coin#592]
Hi, thanks for your awesome project.
Can you please provide code for LGT8 board? (Logic Green). its cheaper and claimed faster than arduino. Thanks a lot.

**Comment by izonu** [comment]
i wouldnt recommend mining with lgt8 boards
1. they have an atmega clone microcontroller chip on them and its not reliable and when kolka v4 comes out it wont pass the chip id test and earn less
2. they work at 32MHz which is too much for a typical arduino and kolka will move you to the next difficulty tier and it will earn much less

**Comment by revoxhere** [comment]
Mining with these boards isn't officially supported but may be in the future. For now - closing.
