### ISSUE TITLE
avr_miner.py fails to run on fresh install on PT language

### ISSUE THREAD

**Issue by Drakis71** [duino-coin/duino-coin#593]
**Describe the bug**
On a fresh install of the AVR miner in windows, when AVR_miner.EXE is run for the first time, on a PT language computer, it fails with this error:

Traceback (most recent call last):
  File "AVR_Miner.py", line 1142, in <module>
  File "AVR_Miner.py", line 169, in get_string
KeyError: 'portugese'
[19220] Failed to execute script AVR_Miner

Should be **portuguese**, it's mispelled.

**System (please complete the following information):**
 - OS: WINDOWS 10 PRO, PT language
 - Software AVR Miner
 - Version 2.49

**Comment by kaiiwaii** [comment]
Fixed
