### ISSUE TITLE
ESP8266 Can't Connecting to Duino-Coin server

### ISSUE THREAD

**Issue by noip184** [duino-coin/duino-coin#596]
Yesterday I was able to use the ESP8266 to mine DUCO coins, but today I can't mine. The status of the ESP8266 says it can't connect to the server. My network is perfect. I don't know what's going on.?

**Comment by primitt** [comment]
Mining is closed temporarily, check the discord for more info (discord.gg/duinocoin)

**Comment by revoxhere** [comment]
Try again now
