### ISSUE TITLE
possible update issue on 0.6.2

### ISSUE THREAD

**Issue by gam3t3chelectronicshobbyhouse** [duino-coin/duino-coin#6]
> 
===========================================
    Duino-Coin PC miner version 0.6.2
 https://github.com/revoxhere/duino-coin
   copyright by MrKris7100 & revox 2019
===========================================

[2019-10-04 21:20:43] Successfully connected to pool on tcp://serveo.net:14808
[2019-10-04 21:21:21] Miner is outdated, please download latest version from https://github.com/revoxhere/duino-coin/releases/
[2019-10-04 21:21:21] Exiting in 5 seconds.

> 

started with this

Then I tried redownload it and starting again now getting 

> python3 Wallet.py
Connected to the server
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "Wallet.py", line 107, in CheckLogin
    key = s.recv(3)
ConnectionResetError: [Errno 104] Connection reset by peer

>

**Comment by revoxhere** [comment]
Our tcp tunnel provider, Serveo is having some technical issues lately. Connection serveo.net:14808 is still active (so you indeed can successcully connect like the miner says) but it doesn't reach our pool. If you see that miner connected successfully, started logging in or checking version and it takes longer than a few seconds that means there is a problem with serveo. If there was a problem with pool, miner would say that it can't connect and will retry in 30s.

**Comment by MrKris7100** [comment]
Czemu bakłażanie nie dałeś tam try except...
