### ISSUE TITLE
i am start web mining ,but it doesnt display in wallet. and not display rig name in wallet.. pls help

### ISSUE THREAD

**Issue by manojj006** [duino-coin/duino-coin#609]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by revoxhere** [comment]
API is updated every 5 sucessfull shares, are you sure you waited this long?

**Comment by BastelPichi** [comment]
Closed due to no reply for 10 days.
