### ISSUE TITLE
esp 32 program loading issue

### ISSUE THREAD

**Issue by manojj006** [duino-coin/duino-coin#610]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by revoxhere** [comment]
What's the issue exactly? You haven't described anything

**Comment by manojj006** [comment]
os: windows 7
software: esp32
version:2.5.1
when compiling esp32 error is occured.
![Screenshot_4](https://user-images.githubusercontent.com/22288001/123656149-495f5d00-d84d-11eb-8429-cc0137183503.jpg)

[Screenshot_4](https://user-images.githubusercontent.com/22288001/123666972-5123ff00-d857-11eb-807b-b4cbfe5a61bc.jpg)

**Comment by revoxhere** [comment]
You don't have the latest ESP32 core installed

**Comment by manojj006** [comment]
thanks
