### ISSUE TITLE
I'm uploaded 2.5.1 But Duino-Coin server  not connect.  And Loop WDT Failed

### ISSUE THREAD

**Issue by jj-col** [duino-coin/duino-coin#611]
![Screenshot_2021-06-29-10-13-52-91_a41d81d6bad02094d3fb80ff0f84e859](https://user-images.githubusercontent.com/83895110/123738416-62eebc00-d8c2-11eb-93db-2e4395870d47.jpg)

**Comment by revoxhere** [comment]
try now

**Comment by jj-col** [comment]
Ok, Thanks
