### ISSUE TITLE
Esp8266

### ISSUE THREAD

**Issue by damselkiwi72** [duino-coin/duino-coin#613]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: windows 10
 - Software esp8266
 - Version 2.5.1

**Additional context**
All of 5 of my esp8266 do not connect since the upgrade, flashed them all they connect and then immediately disconnect.

**Comment by revoxhere** [comment]
try now

**Comment by damselkiwi72** [comment]
Ok, I reloaded the file and now they are up and working. Yea!

**Comment by revoxhere** [comment]
Coolio

**Comment by damselkiwi72** [comment]
I am having the same problem loop WDT failed, so I turned off my miners
today😥
