### ISSUE TITLE
Error connecting to the server. Retrying 

### ISSUE THREAD

**Issue by strannik37** [duino-coin/duino-coin#617]
![image](https://user-images.githubusercontent.com/58545853/123978703-c105c700-d9c8-11eb-9e09-223ec9e1a650.png)
Help me solve the connection error
windows 7 64

**Comment by revoxhere** [comment]
Try now

**Comment by strannik37** [comment]
the same error friend nothing works

**Comment by strannik37** [comment]
![image](https://user-images.githubusercontent.com/58545853/123993710-573fea00-d9d5-11eb-9233-0c0c84753fcd.png)

**Comment by strannik37** [comment]
What is the problem? When will mining work

**Comment by revoxhere** [comment]
Wait for the pools, it should be done soon

**Comment by revoxhere** [comment]
Should work with 2.5.5. Reopen if more help is needed
