### ISSUE TITLE
ablility to ask for more jobs in AVR miner

### ISSUE THREAD

**Issue by pankleks** [duino-coin/duino-coin#623]
Hello,

As far I understand today AVR miner works:
1. AVR sends job via Serial
2. chip calculates
3. chip sends result via Serial
4. goto 1

I'm working on pico miner with 2 cores - I don't think it will work with above.

Is it possible to add additional function to ask for more jobs?

Thanks - awesome job!

**Comment by iwanowski91** [comment]
you can try to overclock it

**Comment by Shreyas-Dev-ITB** [comment]
How to overclock an Arduino Uno can u tell

**Comment by ernesto75** [comment]
@pankleks in this issue we are talking about mining with raspberry pico https://github.com/revoxhere/duino-coin/issues/540

Would be nice to add ability to use both core for mining!

I don't know if overclocking/underclocking the pico can help,i guess Kolka will complain with that.

Not sure how it works, is kolka checking the uniqueid and knowing the id, knows that you are using some type of hardware, so will expect some hashrate with the default clock speed? If you overclock and you have higer hashrate ,kolka will reject?

**Comment by pankleks** [comment]
Gents I don't think we are on the same page.

I'm able to mine on pico using single core.
It's asking AVR miner software for job via serial interface, do hash work and send back results to AVR miner software, then loop is repeated. Till now it's exactly same as UNO.

If I would like to run same on second core - it won't work as today there is no way (as far I understand) to send second job via same serial interface.

In order to do so - there would need to be "protocol" improvement in AVR miner to introduce some kind of asynchronous communication on single serial. Posibly something like this:

- board ask for job (board -> AVR miner)
- AVR sends job (hash,hash,diff + some job id)
- when board finish calculation it sends job result + job id received before

AVR miner is able to interact with multiple of above in async. fashion on single serial

Today AVR miner sends job, and waits for job results - no way to get send job until sending result.

Hope this clarify my request.

**Comment by revoxhere** [comment]
I'm not sure what would be a way to do it. Probably a custom AVR miner would need to be written. Also two socket connections would have to be opened to receive two jobs

**Comment by pankleks** [comment]
in a sense very similar to esp32 implementation.

**Comment by pankleks** [comment]
I will try to write something like that ...

BTW sorry for offtopic - but for a few days now I'm not able to mine anything (timeouts etc.) - what's going on?

**Comment by iwanowski91** [comment]
> How to overclock an Arduino Uno can u tell

https://www.youtube.com/watch?v=93dSfEczqgk&t=686s&ab_channel=JoopBrokking
please watch this guy in action

**Comment by revoxhere** [comment]
> I will try to write something like that ...
> 
> BTW sorry for offtopic - but for a few days now I'm not able to mine anything (timeouts etc.) - what's going on?

Wait until pools take the load
