### ISSUE TITLE
possible inccorect chip id ! 

### ISSUE THREAD

**Issue by merlinz9** [duino-coin/duino-coin#624]
when i mine using arduino  i always had this error possible incorrect chip id and then its stop mining. so i need to restart it again and after 10 mins of mining its happen again 

 window 
AVR 
2.5.2

**Comment by sys-256** [comment]
This is not a server-side problem or a problem in the software, this is a problem of the Arduino you are using. Are you sure you are using a original Arduino?

**Comment by merlinz9** [comment]
I thought its okay to use clone one because when i ask in discord some of
them are using clone arduino

**Comment by sys-256** [comment]
@merlinz9 yeah, most clones work, but some have "a possible incorrect chip id", it isn't yet a problem (as in that you won't get banned, you maybe will in a future release) apart from that it stops mining.

To resolve the issue, you could make a script the restarts the miner every 10 minutes or so.

**Comment by merlinz9** [comment]
can you help me what script should i write

**Comment by sys-256** [comment]
You could use this code, and save it as a .bat file (eg. miner.bat):
```batch
@echo off
cd \path\to\duino\coin\folder

:loop
Start "" /b AVR_Miner.exe
timeout /T 600 /nobreak >nul
taskkill /IM AVR_Miner.exe /F
goto loop
```

NOTE: This only works with the .exe version (the one from the releases page)
NOTE 2: Remember to change the path name (for me it would be C:\Users\Bram\Downloads\Duino-Coin_2.5.2_windows)
NOTE 3: If you want change the default timeout of 10 minutes, you can change `600` with another number (in seconds)

**Comment by merlinz9** [comment]
Thanks, I'll check it out.
