### ISSUE TITLE
Stuck in "Searching for fastest connection"

### ISSUE THREAD

**Issue by modfiles** [duino-coin/duino-coin#625]
**Describe the bug**
When the server is down, and will try to reconnect, it will just stuck in "Searching for fastest connection" regardless if server is up again

**To Reproduce**

**Expected behavior**

A timeout when in "Searching for fastest connection" then redo the searching

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.
[IMG_20210703_192704](https://user-images.githubusercontent.com/11314888/124353062-b3557900-dc36-11eb-85ae-18f1f60ee764.jpg)

**System (please complete the following information):**
 - OS: [e.g. Windows]
          PI, mobile, router
 - Software [e.g. AVR Miner]
          Latest Minimal_PC.py
 - Version [e.g. 2.4]

**Additional context**
!

**Comment by revoxhere** [comment]
That may be happening because of long response time of the server. Please wait for the pools to get released.

**Comment by revoxhere** [comment]
Should be fixed in 2.5.5/2.5.6
