### ISSUE TITLE
Webwallet Account does not exist

### ISSUE THREAD

**Issue by mondorescue1** [duino-coin/duino-coin#628]
I tried to login to https://wallet.duinocoin.com/
today. And now I got a "Account does not exist" message.
Is this an issue at the moment? 

Best regards

**Comment by Shreyas-Dev-ITB** [comment]
Same here bro when I wanted to transfer bot coins to my wallet the bot told this account does not exist then I went to wallet.duinocoin.com same thing happened it said this account does not exist
![Screenshot_2021-07-05-01-05-54-877](https://user-images.githubusercontent.com/86125687/124397946-c187c000-dd30-11eb-8863-49fe1c93507b.jpeg)

**Comment by is-the-king** [comment]
I also had the same problem! I went to log into my wallet and it didn't exist. I created a new wallet with the memo id "King-King" and it was like it never existed. came reset

**Comment by primitt** [comment]
There have been similar reports on the discord (discord.gg/duinocoin) we are currently working on a fix. We are trying to implement pools which may have caused some of these issues. (im not very sure, but i think its that.)

**Comment by revoxhere** [comment]
Try now.

**Comment by mondorescue1** [comment]
Thank you very much for the fast support. I hope you see, that you're mining concept is great. It's great to see that the community is growing fast. Nice job 👍
