### ISSUE TITLE
my wallet has been deleted! What happened?

### ISSUE THREAD

**Issue by is-the-king** [duino-coin/duino-coin#629]
Hello everyone! my name is Gleison. cryptocurrency enthusiast. and I met the DUINO COIN project a few months ago and I was impressed with it and the promising future it has.
But now I'm completely desampotado.I went to log into my wallet and came across the message that it doesn't exist! I saw the usage policies and clearly didn't disrespect any of the rules mentioned there. so I wanted a possicuinamento of why they deleted my account "King-King" I created a new wallet with the same id and it was like it never existed.

**Comment by JiadCools** [comment]
Same thing Happened to me on my account JiadCools. it is nothing special in the wallet i started 2 days ago but if it is a bug and will happened all the time that means it is not worth it to waste time and Processors !
is there any solution for this problem ?

**Comment by revoxhere** [comment]
Try now

**Comment by Verus1989** [comment]
Me too
![Uploading Screenshot_2021-07-05-11-32-21-107_com.android.chrome.jpg…]()

**Comment by Shreyas-Dev-ITB** [comment]
Solved... Try registering with same email , same username , same password that u had or that u were trying to login with, even I got the same problem try doing this u will enter the wallet

**Comment by is-the-king** [comment]
> Tente agora

revoxhere, all right? thanks for listening. I tried to login and my balance is in NaN.undefined. I created a new account with the same username, password and email. when I couldn't log in yesterday. this will be the reason my previous balance was 98 DUCO.

**Comment by mrgh14** [comment]
Thank You Revox Manager and Duino Coin
my problem is Solved
every thing is fine ###

**Comment by revoxhere** [comment]
If anyone still has problems, reach out to me but I think it should be fixed automatically in short amount of time. We're currently preparing the server for pools.
