### ISSUE TITLE
Latin American Brazilian Pool.

### ISSUE THREAD

**Issue by is-the-king** [duino-coin/duino-coin#632]
Hi. the development and implementation of the pools is in full swing, congratulations. I'm from BRAZIL and would love to see a Brazilian pool duino coin. my question is as follows. can anyone host a DUINO COIN pool? if yes i will do it. what hardware specs would you need. I have an excellent network structure and hardware that I can ta using to contribute to the project.
Regards:
Gleison O.

**Comment by kaiiwaii** [comment]
Afaik pools will need to be trusted by the server, so they won't be available to be hosted by random people

**Comment by revoxhere** [comment]
We may reach out to a few random people that will host them though.

**Comment by Bilaboz** [comment]
The current pools can only be ran by trusted users
But we may release pools that can be hosted by anyone in the future

**Comment by is-the-king** [comment]
What requirements do you ask for third party pool analysis and implementation? analyze this question among you administrators and get in touch with me.
