### ISSUE TITLE
Ghost miners

### ISSUE THREAD

**Issue by a2bme** [duino-coin/duino-coin#636]
When I rerun the miner with latest release it creates ghost miners. I am not sure but I think profit from ghosts still counts. 
![SmartSelect_20210706-231207_Duino-Coin](https://user-images.githubusercontent.com/76058298/124654439-9a0b3180-deaf-11eb-9296-e567b8699eef.jpg)

**Comment by revoxhere** [comment]
Looks like some connections don't get properly closed, we'll try to solve that shortly - thanks for noticing

**Comment by Josstri** [comment]
I will add that I am also having a similar issue with esp8266 devices.

**Comment by revoxhere** [comment]
Hey is the problem still appearing?

**Comment by Josstri** [comment]
Yes. I have 12 esp8266 devices. The wallet is showing 28 connections 
![Screenshot_20210706-173034](https://user-images.githubusercontent.com/87039299/124669204-ffdfc500-de7f-11eb-979b-3022e27256c6.jpg)

**Comment by Josstri** [comment]
Looks like there server reset just now might have fixed it? give me few minutes to see if it persists.

**Comment by primitt** [comment]
It could have been a visual glitch..... @Josstri, what type of miners are they now? Still PC, or ESP?

**Comment by Josstri** [comment]
@primitt I'm using only esp8266

**Comment by primitt** [comment]
@Josstri as you said before (server restart fixed it), is it still appearing?

**Comment by Josstri** [comment]
So far, no Ghost accounts. Looks good on my end

**Comment by revoxhere** [comment]
Cool
