### ISSUE TITLE
Duino Coin on Orange Pi PC

### ISSUE THREAD

**Issue by forerunner18** [duino-coin/duino-coin#637]
So I tried to run the PC_Miner on the orange pi PC using the instructions that anyone would use on a Raspberry pi, but after I type the python program to run it gives me back this:
![IMG_20210706_224106](https://user-images.githubusercontent.com/45952479/124659179-59121d80-dead-11eb-883d-ed0b91e7fe27.jpg)

**Comment by revoxhere** [comment]
sudo apt install python3 python3-pip

**Comment by forerunner18** [comment]
It gave me the same errors that are on top of the picture

**Comment by revoxhere** [comment]
python3 -m ensurepip

**Comment by BastelPichi** [comment]
> It gave me the same errors that are on top of the picture

Somehow your package mirrors don't seem to be correct. Try to run 'sudo apt update' and afterwards the install command again, or change them.

**Comment by BastelPichi** [comment]
Closed due to inactivity
