### ISSUE TITLE
Microchip Atmega4809 Xplained Pro is not minning

### ISSUE THREAD

**Issue by Doofus4ever** [duino-coin/duino-coin#639]
When i flashed the new Arduino code to my avr device it is not connecting and mining with the new server and avr miner
it should work since it was working before the server migration and pools

see the pic attached

to recreate error load the code to any Atmega 4809 device like mine or Arduino nano every which has Atmega4809

![Microchip_Atmega4809_Xplained_Pro_Error](https://user-images.githubusercontent.com/56180193/124696849-cb85fc00-deb3-11eb-8c33-5962e638ec20.PNG)

**Comment by Shreyas-Dev-ITB** [comment]
Please restart the miner or unplug the board from the computer and plug it back in..

**Comment by Doofus4ever** [comment]
> Please restart the miner or unplug the board from the computer and plug it back in..

i have done that already, i flashed latest release onto the board and using the latest avr miner i have tried both windows and linux avr miners both spit out the same issue

**Comment by Doofus4ever** [comment]
Ok found out where i f uped on the arduino code for this special board i had to change where it had Serial -> Serial1 now its working (i.e Serial.read, Serial.print ... etc)
