### ISSUE TITLE
My coins are gone after the update.

### ISSUE THREAD

**Issue by is-the-king** [duino-coin/duino-coin#644]
Hello, I hope you are alright! previously i had had a problem accessing my duino coin wallet. and I was told to wait for the end of the pool updates and implementation. My wallet already had a total of ~98 DUCO and now that it seems to have normalized my wallet is zero.
![Capturar](https://user-images.githubusercontent.com/59968178/124837732-d1cfb300-df5b-11eb-9c11-a4d43f0ea930.PNG)

**Comment by BastelPichi** [comment]
Hmmm maybe there is some db error, @revoxhere can help you.

**Comment by revoxhere** [comment]
You must've registered when I was changing the database, I was able to check the backups and recover your wallet. enjoy
