### ISSUE TITLE
Pc mining disable no able to connect to server says please switch node

### ISSUE THREAD

**Issue by Imraven21** [duino-coin/duino-coin#645]
any idea how to fix this im running the miner on my pc is saying "Server message: PC mining is disabled on the Master server. Please switch node"

**Comment by Traction6131** [comment]
Please get the newest release or make a git pull in your duino-coin folder(Git may will have to be installed) 
This should fix the problem.

**Comment by BastelPichi** [comment]
Get the newest miner from the releases page. Then it should work.
