### ISSUE TITLE
AVR_Miner won't reconnect to board after disconnection

### ISSUE THREAD

**Issue by pankleks** [duino-coin/duino-coin#649]
**Describe the bug**
AVR_Miner won't reconnect to the board

**To Reproduce**
1. PC (windows) running AVR_Miner, connected to the board
2. Mining ok
3. Unplug + plug USB cable

**Expected behavior**
AVR_Miner should reconnect

**Screenshots/photos**
![image](https://user-images.githubusercontent.com/14176066/124945103-26cc0180-e00e-11eb-8ed2-394cdab54b04.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Software: AVR Miner
 - Version: 2.55

**Additional context**
COM port is not changed after plugging in. After closing and opening AVR_Miner again - all is fine

**Comment by revoxhere** [comment]
Hey, can you try running the latest AVR miner from source (2.56) and tell me if the error still persists?

**Comment by BAZESHOT** [comment]
I also had this problem. Downloaded firmware to stm32 and AVRMiner cannot connect to board

**Comment by pankleks** [comment]
@BAZESHOT which firmware? the one recently added in unofficial miners?

if so please check LED on STM board -> it's:
- constant light (after reset) -> waiting for connection over serial
- then it's only on during hash calculation

so if it's constant light it means that there was no attempt to connect

You can also connect FTDI serial to A9/A10 pins and see messages

**Comment by pankleks** [comment]
Original issue of the ticket is solved with 2.56 so I'm closing.

@BAZESHOT if you need something for STM32 please let me know.
