### ISSUE TITLE
How to withdraw Duino-Coin.

### ISSUE THREAD

**Issue by jj-col** [duino-coin/duino-coin#651]

**Comment by kaiiwaii** [comment]
https://exchange.duinocoin.com

**Comment by jj-col** [comment]
direct withdraw is possible

**Comment by kaiiwaii** [comment]
What?

**Comment by jj-col** [comment]
Without exchange

**Comment by izonu** [comment]
Duino-Coin is a coin like any other, you can't "withdraw" duco, you can trade with it other people
