### ISSUE TITLE
Duco API isn't working

### ISSUE THREAD

**Issue by robtech21** [duino-coin/duino-coin#652]
So I recently pulled the most recent version of the [useful-tools](https://github.com/revoxhere/duino-coin/tree/useful-tools) branch, and it doesn't even work.

Here's what I did to attempt to connect:

```python
import duco_api
api_connection = duco_api.Wallet()
```

It throws me this output:

```
  File "<stdin>", line 1, in <module>
  File "F:\Downloads-New\duinostuff\duino-coin\duco_api.py", line 160, in __init__
    self._connect_socket()
  File "F:\Downloads-New\duinostuff\duino-coin\duco_api.py", line 165, in _connect_socket
    self.sock.recv(3)
socket.timeout: timed out
```

Could this be fixed? Also, the documentation is now outdated if this is how the API now works.

**Comment by revoxhere** [comment]
Python API wasn't updated for some time, I don't have time yet to do anything about it, but I'll let someone know to try and fix it

**Comment by robtech21** [comment]
> Python API wasn't updated for some time, I don't have time yet to do anything about it, but I'll let someone know to try and fix it

Okay, thank you

**Comment by naphob** [comment]
i have tried this and it works 
`import ducoapi`

**Comment by robtech21** [comment]
> i have tried this and it works
> `import ducoapi`

Well it was mostly an issue on the backend, not with the code itself, it works fine now.
