### ISSUE TITLE
PC_miner error when run with nohup

### ISSUE THREAD

**Issue by naphob** [duino-coin/duino-coin#655]
I am running PC_Miner.py on my Raspberry Pi4 8GB.  It's working well when I execute it with` python3 PC_Miner.py`

But it got an error when I ran this command `nohup python3 PC_Miner.py &`

The below pic is from nohup.out

![image](https://user-images.githubusercontent.com/1431095/125149725-cb605780-e164-11eb-975a-347cfb04bc24.png)

**Comment by revoxhere** [comment]
Looks like the title setter is causing this - you can uncomment all lines that are calling title() and try again

**Comment by naphob** [comment]
I have commented on all the lines calling title(). It works !!!

but there is another error as in the below pic. Anyway it's working after this error

![image](https://user-images.githubusercontent.com/1431095/125159199-28c5ca00-e1a0-11eb-94f9-fc39f09174eb.png)
