### ISSUE TITLE
7773e21 breaks my code, please undo!

### ISSUE THREAD

**Issue by cablegunmaster** [duino-coin/duino-coin#664]
These 2 commits are breaking my setup, please undo , or I have to fork it in to keep it working.

https://github.com/revoxhere/duino-coin/commit/7773e215c1b98011bd4d898d0bb9d8a68d48a80d
https://github.com/revoxhere/duino-coin/commit/3c24c1492cfcd71c4dfbe6f7f2c8f0baf7ec6bd0

I found the solution and it is very simple, just  undo the commit, and it works with my setup again.
Who can make a pull request to fix this?

Since noone replied I can make it myself and I added it below;

It just needs a code review and a confirm:
https://github.com/revoxhere/duino-coin/pull/665

**Comment by wczapkowicz** [comment]
I think, that donations need to be enabled

**Comment by modfiles** [comment]
this is . . . . . . . 
a selfish request at its finest, if you can do it yourself, then do and you should not include those who cannot code but want to enable donation

**Comment by cablegunmaster** [comment]
Yes, yes you are right. It is a selfish request wanting to get paid for your own project.
Even though its a very very very small amount, lower as a hourly wage, maybe its not even 1 hour wage in total. 
But wouldn't you want to get paid if its your project?
