### ISSUE TITLE
I mining with 40 Arduinos and I only mine 8 duco a day

### ISSUE THREAD

**Issue by andreabetter** [duino-coin/duino-coin#666]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by KnowTheFuture** [comment]
Too many boards. Max is 24.

**Comment by andreabetter** [comment]
The max is 50 boards.

**Comment by Lulaschkas** [comment]
> Too many boards. Max is 24.

The max is 50 connections since the first pool was introduced.

**Comment by KnowTheFuture** [comment]
Ok. I guess things have changed.

Speaking of change... given the current DUCO price of $0.00000, what is your ROI for 40 boards?

8 * 0 = 0

How do you feel about that?

**Comment by andreabetter** [comment]
0.000 .I'm still happy because I know that 1 day duco will reach 1 dollar and maybe I'm gonna have thousands of ducos...right now with 24 Arduinos and 4 pc threads I'm mining 3and half Duco a day.🤷🤷🤷

**Comment by andreabetter** [comment]
Now it says 6and half

**Comment by KnowTheFuture** [comment]
Ok. You and me both...

DUCO to $1
BTC ==> $100k
ETH ==> $20k
DOGE ==> Moon

**Comment by andreabetter** [comment]
Shib= milky way!!

**Comment by andreabetter** [comment]
I think there is a bug on the shares.anytime the shares add up the duco estimate changes it, in 6,3,30,52etc

**Comment by pankleks** [comment]
@andreabetter 
please read carefully whitepaper + multiple posts on what is the motivation behind dc and how number of miners affects mining performance.

@KnowTheFuture 
if you wish to discuss predictions and purpose please join discord channel - GitHub is place for bug/feature reports.

What's definitely needs to be improved is unification of efficiency calculation - to my experience web wallet, earnings calc., wallet app, dashboard (by lukaschkas) are showing sometimes widely different numbers.

**Comment by andreabetter** [comment]
I read everything already...and I'm telling you that1 Arduino does 8 duco a day. 40 Arduinos minimum they do 40-60 I've already done this thing.if I take 20 off I'm earning 3,5 Duco. 100% there is an annoying bug!! The estimate daily profit keep changing everytime the shares add up.

**Comment by pankleks** [comment]
I'm not sure how exactly earnings are calculated, some apps suggest it's not only mathematical formula but it also uses past efficiency to fine tune results. 

Still - it would be good to have unified values around different apps.

At the moment best I can suggest you is to observe real "profit" per day and extrapolate.

**Comment by Lulaschkas** [comment]
> 
> 
> I'm not sure how exactly earnings are calculated, some apps suggest it's not only mathematical formula but it also uses past efficiency to fine tune results.
> 
> Still - it would be good to have unified values around different apps.
> 
> At the moment best I can suggest you is to observe real "profit" per day and extrapolate.

The estimated earnings on the duco mining dashboard are calculated throught the change of the users balance in last 2 minutes and this is pretty accurate. That he is only getting ~8 Ducos is definitly a bug (because i am doing more with one arduino and 2 ESPs)

**Comment by andreabetter** [comment]
Now I only plugged 16 Arduinos and it shows that I'll do 51 duco and I can see the shares add up quickly together to form the coin. I'll come back tomorrow at this time and tell you what append. For now I'm having 830 Ducos.

**Comment by andreabetter** [comment]
Ok today at 7 PM I had 32 ducos and from 52 daily it went down to 24...🤷🤷🤷🤷

**Comment by pankleks** [comment]
suggestion to make it less confusing:

maybe wallet/dashboard apart from estimated daily value, should show last day real value, or best history of last 7 days.

**Comment by andreabetter** [comment]
All good now!😁😁😁

**Comment by parthao** [comment]
Try Esp32 much awesome than Arduino
