### ISSUE TITLE
How to apply for "MORE NODES"?

### ISSUE THREAD

**Issue by Flight1530** [duino-coin/duino-coin#669]
were can we get info on how to apply for "More Nodes"? 

I would like to know what kind of computer/server specs we need? Min, recommended and overkill (lol).
-CPU GHz  with how many cores?
-How much ram?
-How much HHD space you need?
-what OS is best? (Windows serve for 24 cores is to expensive for me)
-What internet download/upload speed?
-How you plan on getting into Node with a leased IP address?
-How you plan on using it?
-And what ever else that might be relevant to have a good stable Node.

I might be interested in supplying my 1 rack sever for this project.

**Comment by sys-256** [comment]
The current Pulse Pool has 4 cores, and 4GB of RAM. And as you can see on the dashboard (http://149.91.88.18:6001/), the CPU is usually under 30% load, and only using about 20% of it's RAM (20% of 4GB is only 800MB), so you really don't need powerful server.

The current Pulse Pool is hosted on a VPS (if I remember correctly), so it probably has a 1gbit internet connection, and runs linux.

**Comment by Flight1530** [comment]
> The current Pulse Pool has 4 cores, and 4GB of RAM. And as you can see on the dashboard (http://149.91.88.18:6001/), the CPU is usually under 30% load, and only using about 20% of it's RAM (20% of 4GB is only 800MB), so you really don't need powerful server.
> 
> The current Pulse Pool is hosted on a VPS (if I remember correctly), so it probably has a 1gbit internet connection, and runs linux.

Ok thanks for the reply, I did not realize how little of a server you need for almost 15,000 registered users, so I guess I don't need to offer my server to help out, well not yet anyways lol.

**Comment by BastelPichi** [comment]
Closed due to fix
