### ISSUE TITLE
Wrong status code and response on /transactions/{hash} REST API endpoint when provided wrong hash

### ISSUE THREAD

**Issue by itedya** [duino-coin/duino-coin#674]
**Description**
If you pass wrong transaction hash in url, server replies with status code 200 and success:true.

**To reproduce**
1. Go to https://server.duinocoin.com/transactions/asdasdasdasdad

**Expected behavior**
Server should reply with status code that indicates wrong data provided by user (for ex. 422 or 400) and success should be false

**System (please complete the following information):**
 - OS: Windows
 - Software: Browser
 - Version: ????

![image](https://user-images.githubusercontent.com/69873350/125831240-53dbf31b-7f7f-466e-8f5b-08c07f25c468.png)

**Comment by itedya** [comment]
I tried more endpoints

https://server.duinocoin.com/balances/asdasdsadada (correct status code, correct status, and weird message in response?)
![image](https://user-images.githubusercontent.com/69873350/125833547-0aaf8afe-3e37-406b-b4dd-57d1f48ffbf8.png)

https://server.duinocoin.com/users/asdasdsadada (wrong status code, wrong status, wrong result)
![image](https://user-images.githubusercontent.com/69873350/125833782-f4cec15e-2428-49ae-bfb6-4bdebff6c37b.png)

**Comment by itedya** [comment]
I tried some more, but this time undocumented routes and I encountered 500 Internal Server Error, woah.

https://server.duinocoin.com/miners/asdasdsaqwerqweqvgfdhgdfvhgcdg
![image](https://user-images.githubusercontent.com/69873350/125834561-4311a009-fdc8-4926-8f15-c4071abe3668.png)

**Comment by revoxhere** [comment]
This issue should be posted in https://github.com/revoxhere/duco-rest-api, but it's not a big deal. I'll push a fix in an hour or two

**Comment by revoxhere** [comment]
Fixed in https://github.com/revoxhere/duco-rest-api/commit/05c6d9311fa8ed6e76b6921fe01b92fc804a1638
