### ISSUE TITLE
increasing the speed of receiving jobs

### ISSUE THREAD

**Issue by BAZESHOT** [duino-coin/duino-coin#675]
I am using ESP8266 at 160 Mhz. Is it possible to increase the speed of receiving jobs to increase productivity?

 - OS: WINDOWS 10
 - Software ESP8266
 - Version 2.5

**Comment by revoxhere** [comment]
Can you elaborate? If you're talking about ping - make sure you're mining on node that's closes to you (Master server - the Netherlands, pulse pool - Germany, soon more nodes)

**Comment by BAZESHOT** [comment]
ok, thanks
