### ISSUE TITLE
 Change in mining efficiency

### ISSUE THREAD

**Issue by BAZESHOT** [duino-coin/duino-coin#676]
I ran into the problem that when mining on the ESP8266, the income is less than when mining on the arduino nano. Why is this done? In all respects, the ESP8266 and ESP 32 are much more energy efficient than the arduino nano and uno. Your project is aimed at maximum energy efficiency of mining.

Why not make the computational complexity equal to the mining efficiency?

For example, arduino draws 0.2 W, ESP8266 draws 0.6 W, and ESP32 draws 1W of power. Why not make the computational complexity proportional?
For Arduino - 6
For ESP8266 - 18
For ESP32 - 30
etc.

**Comment by revoxhere** [comment]
Because this is Ar**duino** coin, not ESP coin

**Comment by BAZESHOT** [comment]
Yes, you're right, but ESP and Arsduino are very similar. I thought it would be nice to do that. In any case, this is just a proposal to increase the energy efficiency of mining.

**Comment by revoxhere** [comment]
I won't be changing the rewards so dramatically at this point. Arduinos remain as the focus and it will stay that way

**Comment by BAZESHOT** [comment]
ok, thanks
