### ISSUE TITLE
Discord "now-playing" feature doesn't show hashrate correctly

### ISSUE THREAD

**Issue by itedya** [duino-coin/duino-coin#677]
**Describe the bug**
Discord "now-playing" feature doesn't show hashrate correctly

**To Reproduce**
1. Open AVR Miner
2. Open discord and check your now-playing activity

**Expected behavior**
Discord now playing should show equal hashrate to what AVR Miner says

**System (please complete the following information):**
 - OS: Windows
 - Software: AVR Miner
 - Version: 2.5.6

![image](https://user-images.githubusercontent.com/69873350/125853853-4bd69259-49ef-49a0-a009-eeaac076ff36.png)

**Comment by revoxhere** [comment]
Fixed in https://github.com/revoxhere/duino-coin/commit/c2b421116c1e79996734c69bb6b258ade960bcb8
