### ISSUE TITLE
Wallet registration: invalid e-mail

### ISSUE THREAD

**Issue by TheMiniMiner** [duino-coin/duino-coin#678]
Hello!

I am trying to register for a wallet, but I keep getting the error message:
'You have provided an invalid e-mail address'

I used my @gmail.com e-mail address to register, however, 
for all three wallet registration possibilities the error keeps occuring.

Could somebody help me out?

**Comment by sys-256** [comment]
What wallet are you using? (web wallet, cli wallet or gui wallet)

**Comment by TheMiniMiner** [comment]
I have tried to register in all three. 
They all give the same error, but I am entering a valid e-mail.

**Comment by primitt** [comment]
> I have tried to register in all three.
> They all give the same error, but I am entering a valid e-mail.

whats the error? the exact error would be good

**Comment by TheMiniMiner** [comment]
<img width="487" alt="Invalid_email" src="https://user-images.githubusercontent.com/87581463/126060043-29b03eeb-a2b7-4bb2-95cc-c5dbc6f69bcc.PNG">

This is the exact error I get after I click on the 'Register' button.
