### ISSUE TITLE
Wallet registration problem

### ISSUE THREAD

**Issue by jacklondon90** [duino-coin/duino-coin#679]
Hi everyone, I was trying to register many time with web, client but was unable to register message appears like "You have used unallowed characters. Please try again"
Thank you beforehand

**Comment by Traction6131** [comment]
I had this issue with an account of a friend, for me it just worked typing it again, maybe also look if you had a space at the end, hopefully is the fix of the problem

**Comment by jacklondon90** [comment]
> I had this issue with an account of a friend, for me it just worked typing it again, maybe also look if you had a space at the end, hopefully is the fix of the problem

Hi and thank you for response, I don't have any whitespace neither username and email address still can't register

**Comment by primitt** [comment]
Do you have any special characters like: -,$&?

**Comment by jacklondon90** [comment]
> Do you have any special characters like: -,$&?

you mean in password? if in password yes I have, but for login no I don't have

**Comment by Traction6131** [comment]
> > Do you have any special characters like: -,$&?
> 
> you mean in password? if in password yes I have, but for login no I don't have

No, i think he meens in your username

**Comment by jacklondon90** [comment]
> > > Do you have any special characters like: -,$&?
> > 
> > 
> > you mean in password? if in password yes I have, but for login no I don't have
> 
> No, i think he meens in your username

for login no I don't have just plain text

**Comment by primitt** [comment]
> > > > Do you have any special characters like: -,$&?
> > > 
> > > 
> > > you mean in password? if in password yes I have, but for login no I don't have
> > 
> > 
> > No, i think he meens in your username
> 
> for login no I don't have just plain text

Why dont we chat over at the discord, https://discord.gg/duinocoin

**Comment by jacklondon90** [comment]
> Do you have any special characters like: -,$&?

try to register for yourself you won't succeed

**Comment by primitt** [comment]
> > Do you have any special characters like: -,$&?
> 
> try to register for yourself you won't succeed
could you take a screenshot of the username you are trying to register?

**Comment by primitt** [comment]
Not password, just the username

**Comment by primitt** [comment]
Or tell me the username, both ways work, but the error would be nice to see too

**Comment by jacklondon90** [comment]
> Or tell me the username, both ways work, but the error would be nice to see too

milkyway7

**Comment by primitt** [comment]
whats the error it gives? (exact)

**Comment by jacklondon90** [comment]
> > > Do you have any special characters like: -,$&?
> > 
> > 
> > try to register for yourself you won't succeed
> > could you take a screenshot of the username you are trying to register?

![err](https://user-images.githubusercontent.com/9272738/126060061-2990f537-65df-4b9a-90c7-2fe5096f7e76.png)

**Comment by primitt** [comment]
try without the numbers in the username...

**Comment by jacklondon90** [comment]
> try without the numbers in the username...

same result

**Comment by jacklondon90** [comment]
> try without the numbers in the username...

![err](https://user-images.githubusercontent.com/9272738/126060143-8d9e14a1-31f6-43ac-896a-b157170523e2.png)

**Comment by BastelPichi** [comment]
i think theer were problems with a & in password, so you cant register with that, but im not shuire if thats already fixed.

**Comment by ktannady** [comment]
I experienced this problem when I tried to register with some special character like * - in the password section.

**Comment by jacklondon90** [comment]
> i think theer were problems with a & in password, so you cant register with that, but im not shuire if thats already fixed.

let me try

**Comment by jacklondon90** [comment]
now I have this problem
![err](https://user-images.githubusercontent.com/9272738/126068730-df979338-34d1-4114-a2a1-e079e1fa97eb.png)

**Comment by Traction6131** [comment]
> now I have this problem
> ![err](https://user-images.githubusercontent.com/9272738/126068730-df979338-34d1-4114-a2a1-e079e1fa97eb.png)
> 

Which OS?

**Comment by jacklondon90** [comment]
> > now I have this problem
> > ![err](https://user-images.githubusercontent.com/9272738/126068730-df979338-34d1-4114-a2a1-e079e1fa97eb.png)
> 
> Which OS?

Win 8.1 I have full privileges

**Comment by Shreyas-Dev-ITB** [comment]
Install colorama by executing pip install colorama

**Comment by jacklondon90** [comment]
> Install colorama by executing pip install colorama

let me try

**Comment by Shreyas-Dev-ITB** [comment]
Ok try it now

**Comment by Traction6131** [comment]
> > > now I have this problem
> > > ![err](https://user-images.githubusercontent.com/9272738/126068730-df979338-34d1-4114-a2a1-e079e1fa97eb.png)
> > 
> > Which OS?
> 
> Win 8.1 I have full privileges 

As far as I'm concerned, the miner is not compatiable, but maybe it was just the exe one

**Comment by Shreyas-Dev-ITB** [comment]
Please install colorama shruuubo

**Comment by jacklondon90** [comment]
> Ok try it now
same result
![err](https://user-images.githubusercontent.com/9272738/126069597-0299081e-e3a3-426a-ba4a-03d8b51cba11.png)

**Comment by sys-256** [comment]
try the .exe version from the releases tab

**Comment by jacklondon90** [comment]
> try the .exe version from the releases tab

it's launches and closes in a moment

**Comment by BastelPichi** [comment]
> > try the .exe version from the releases tab
> 
> it's launches and closes in a moment

Try to to start a terminal, and in terminal start the exe with ```start AVR_Miner.exe```... If there any errors, send a sreenshot.
