### ISSUE TITLE
Increasing the difficulty of mining on arduino

### ISSUE THREAD

**Issue by BAZESHOT** [duino-coin/duino-coin#681]
After starting AVR Miner, the difficulty increases to 16 instead of 6. Why is this happening? The first job is done on difficulty 6, but the server rejects it. The second job is done at difficulty 16. I am using an arduino nano on an Atmega 328 to do the job. Its capacity is 230H / S. Please help fix this problem.

OS: Windows 10
Miner version: AVR Miner v2.56

**Comment by sys-256** [comment]
Are you sure you have an original Arduino? The maximum hashrate for the AVR difficulty is currently 210h/s (last time i checked
), so you will get moved to a higher difficulty.

**Comment by BAZESHOT** [comment]
Is there any way to reduce the hash rate? So, my arduino is Chaina replic =)

**Comment by sys-256** [comment]
Oops, just checked it and the max hashrate for avr is 250h/s, so it would be weird then that you are getting moved to mega difficulty.

**Comment by BAZESHOT** [comment]
Maybe this is some kind of mistake? But in any case, I reinstalled the miner and the server rejects the work.

**Comment by airtikit** [comment]
I have the same problem as you.
![image](https://user-images.githubusercontent.com/86959594/126070000-52fe3a97-f9c4-47fd-826f-d78cc9772bdf.png)

**Comment by revoxhere** [comment]
You're not using a genuine Arduino board, so Kolka moves you to a different difficulty tier. There's nothing wrong with that, but the rewards may be a bit lower.

**Comment by PipeDeveloper** [comment]
same here, difficulty reaches to 16

**Comment by ericddm** [comment]
![微信图片_20210722124608](https://user-images.githubusercontent.com/20798114/126591974-2b8a5d0e-531c-4a97-99b5-226e531264a9.jpg)
same here, difficulty reaches to 16.
and as this pic, it's not  a genuine Arduino board, but it's really Mega328.

**Comment by modfiles** [comment]
im also experiencing the same but to make things clear, same nanos (which is chinese rip off) when use with official duinocoin software (AVR Miner) this clocks at 195H/s on average but when its use in I2C by ricaun, clock goes 215H/s+ so its not a matter of if its genuine or rip off. maybe code optimization? IDK. im aware though that i2c is not official duinocoin software so we are on ourself using it. and with the vision of duinocoin to use low powered device in mining, im quite amuse that it still does not support i2c officialy, in which atm, the most low powered set up someone can use rather than sbc or pc

**Comment by ericddm** [comment]
> im also experiencing the same but to make things clear, same nanos (which is chinese rip off) when use with official duinocoin software (AVR Miner) this clocks at 195H/s on average but when its use in I2C by ricaun, clock goes 215H/s+ so its not a matter of if its genuine or rip off. maybe code optimization? IDK. im aware though that i2c is not official duinocoin software so we are on ourself using it. and with the vision of duinocoin to use low powered device in mining, im quite amuse that it still does not support i2c officialy, in which atm, the most low powered set up someone can use rather than sbc or pc

“which is chinese rip off”？ really? I think you should delete your statement. I don’t want to see political content in the Duino-Coin. And, you know, the Chinese are not easy to mess with. If you don't want to delete it, well, which country are you from?

**Comment by revoxhere** [comment]
Really nice board! I did some research, and it looks like the ESPs handle serial communication better than PCs, thus the hashrate difference, because the hashing codes are practically identical. I will adjust the Kolka system in a minute and I think that should be fixed then

> ![微信图片_20210722124608](https://user-images.githubusercontent.com/20798114/126591974-2b8a5d0e-531c-4a97-99b5-226e531264a9.jpg)
> same here, difficulty reaches to 16.
> and as this pic, it's not a genuine Arduino board, but it's really Mega328.
