### ISSUE TITLE
AVR miner launch issues

### ISSUE THREAD

**Issue by jacklondon90** [duino-coin/duino-coin#683]
Hi everyone who knows why this error appears? latest python version is installed with the colorama
![err](https://user-images.githubusercontent.com/9272738/126080532-eb374575-c1ff-49e8-a41a-ca03c76f28f0.png)

**Comment by revoxhere** [comment]
The .exes are precompiled for 64bit Windows 10 machines and judging from your command prompt look, you're using something older. You can still get it to run by launching from source

**Comment by jacklondon90** [comment]
> The .exes are precompiled for 64bit Windows 10 machines and judging from your command prompt look, you're using something older. You can still get it to run by launching from source

can you please help me with this?

**Comment by sys-256** [comment]
> can you please help me with this?

Just install Windows 10 or download the github repo and execute it with python AVR_Miner.py

**Comment by jacklondon90** [comment]
> > can you please help me with this?
> 
> Just install Windows 10 or download the github repo and execute it with python AVR_Miner.py

thanks

**Comment by revoxhere** [comment]
It's explained in both the README and official Getting Started guides, it would be really easier if people could read a bit more
![image](https://user-images.githubusercontent.com/50244265/126080630-e80c1b61-a2d7-48d8-bc37-db96abf0877f.png)
![image](https://user-images.githubusercontent.com/50244265/126080637-47853c5a-0b18-46a9-997d-f73bce3f444e.png)

**Comment by jacklondon90** [comment]
> It's explained in both the README and official Getting Started guides, it would be really easier if people could read a bit more
> ![image](https://user-images.githubusercontent.com/50244265/126080630-e80c1b61-a2d7-48d8-bc37-db96abf0877f.png)
> ![image](https://user-images.githubusercontent.com/50244265/126080637-47853c5a-0b18-46a9-997d-f73bce3f444e.png)

thanks

**Comment by sys-256** [comment]
Also, I see you are having the duino-coin folder on C:\duino, which is probably why you are getting a permission error. You have 2 options to fix that:

- Run the command prompt as admin by doing this (but then the Windows 8.1 equivalent): 
![image](https://user-images.githubusercontent.com/84628826/126080726-f3d54866-bfb5-41b2-9249-8b7cbf95d6f3.png)


- Run the AVR_Miner from a folder like Downloads or Documents

**Comment by jacklondon90** [comment]
> Also, I see you are having the duino-coin folder on C:\duino, which is probably why you are getting a permission error. You have 2 options to fix that:
> 
> * Run the command prompt as admin by doing this (but then the Windows 8.1 equivalent):
>   ![image](https://user-images.githubusercontent.com/84628826/126080726-f3d54866-bfb5-41b2-9249-8b7cbf95d6f3.png)
> * Run the AVR_Miner from a folder like Downloads or Documents

Not working while running as administrator
