### ISSUE TITLE
Withdraw not working

### ISSUE THREAD

**Issue by jj-col** [duino-coin/duino-coin#686]

**Comment by revoxhere** [comment]
Could you elaborate? I checked the logs and there have been many exchanges completed today:
![image](https://user-images.githubusercontent.com/50244265/126200797-b944b488-59c7-484d-bd4c-c206e733e777.png)

**Comment by cregist** [comment]
I've made a few attempts to exchange to XMG since Monday evening EST. The form doesn't connect to the database - or whatever; and, the site offers to email the form - which has worked in the past, but not at this time(s).
