### ISSUE TITLE
"hwcrypto/sha.h" library either depriciate or remove

### ISSUE THREAD

**Issue by RedErr404** [duino-coin/duino-coin#690]
When working with the Arduino esp32 v2.0.0 version, it is impossible to compile. I found a solution here - https://github.com/espressif/esp-idf/issues/3245

**Comment by revoxhere** [comment]
Can you submit a PR?

**Comment by RedErr404** [comment]
What should I do?

**Comment by Tech1k** [comment]
@RedErr404 you should submit a Pull Request if possible!

**Comment by revoxhere** [comment]
Fixed long time ago
