### ISSUE TITLE
Add multiple arduino boards

### ISSUE THREAD

**Issue by Harveyn4444** [duino-coin/duino-coin#693]
When I first set up the AVR miner I was able to configure and add boards, I was able to then get more boards to mine on, I’m using a raspberry pi to host the mining and when I execute the AVR_Miner program to run it starts mining automatically without the option of being able to add a new board.

Im using a raspberry pi zero using the latest raspberry pi OS
Any help would be appreciated :)

**Comment by revoxhere** [comment]
As it was explained to you in the config tool, you can either remove the AVRMiner_v2.56_resources folder to re-run the configuration tool, or maually add boards to Miner_config.ini file (in that folder), specyfing boards after a comma like so: `avrport = /dev/ttyUSB0,/dev/ttyUSB1,/dev/ttyUSB3` and so on.
