### ISSUE TITLE
Node Crashing

### ISSUE THREAD

**Issue by primitt** [duino-coin/duino-coin#695]
**2 issues are going to be described. **

1. When you start the node it start fine, and stats solving hashes and syncing. After 10 minutes its crashes! 
2. Sometimes when you start it and put your username in, it just crashes after 10 seconds!

**To Reproduce**
1. Click on the node file
2. Put in your username
3. Wait 10-20 minutes
4. Then it should just crash

**OS**
Windows

**Comment by revoxhere** [comment]
Node is curretly more for demonstrational purposes and a more ready to use version will be released soon
