### ISSUE TITLE
No full reconnect capability in the latest PC miner

### ISSUE THREAD

**Issue by YetAnotherRussian** [duino-coin/duino-coin#7]
Hi there! Seems I'm the only miner @ official pool for now (ofc, together with revox)

Sometimes there're some issues with pool, so there is no ability to receive balance or mining "jobs".

I've added job logging right here:

job = soc.recv(1024).decode() # Get work from pool
print(job)

So I see there is no job received sometimes (minig stops), but the miner does not try to reconnect, it tries to receive from socket.

Thank.

P.S. Interestiong project :-) I'm not on Python side btw, but may take a look into adding .NET miner :-)

Are you interested in adding Discord server for this project?

**Comment by revoxhere** [comment]
It might've been when serveo had failed, will check and maybe implement reconnection. More of a serveo problem than our. About discord server - it may be created in some days. Thanks for suggestions!

**Comment by YetAnotherRussian** [comment]
> About discord server

Well, I've asked bout this just to figure out some future plans on development, goals, etc. Not sure where this info could be found right now. Maybe there is some info @ arduino forums btw. Will check it out.

**Comment by revoxhere** [comment]
Sometimes I post news at [duino-coin blog](https://revoxhere.github.io/duino-coin/)

**Comment by revoxhere** [comment]
Okay, now we have a discord channel. Come and join if you want: https://discord.gg/qa88ZYM

**Comment by revoxhere** [comment]
Fixed in [e8f9145b719f911188a7f5078f1af8b74100af7f](https://github.com/revoxhere/duino-coin/commit/e8f9145b719f911188a7f5078f1af8b74100af7f).<br> Will be also included in the upcoming 0.6.4 release. Thanks for submitting bug report!
