### ISSUE TITLE
unattended duino miner update

### ISSUE THREAD

**Issue by WolfRamiO74** [duino-coin/duino-coin#700]
Hi there, i am triying to do unattended duino miner updates using the GIT PULL commnad, the repo updates fine but when you re-launch the miner you need to fill the whole config again, this is because Duino miner read config from a folder "PCMiner_X.XX_resources/", where the X.XX is the version that you are starting...

So, everytime you update duino miner to a new version then run it, the config of the previus version is not readed at all and you have to do a new one for the new version...

All of this cause a break on a  unattended duino miner update process. 

What can we do to find a unattended update solution?

Thanks (sorry for my bad english, i speak spanish)

**Comment by Traction6131** [comment]
I dont think there's a solution, and espacially for bugs its quite good, and also, it isnt that much you have to fill in, so...

**Comment by BastelPichi** [comment]
> Hi there, i am triying to do unattended duino miner updates using the GIT PULL commnad, the repo updates fine but when you re-launch the miner you need to fill the whole config again, this is because Duino miner read config from a folder "PCMiner_X.XX_resources/", where the X.XX is the version that you are starting...
> 
> So, everytime you update duino miner to a new version then run it, the config of the previus version is not readed at all and you have to do a new one for the new version...
> 
> All of this cause a break on a unattended duino miner update process.
> 
> What can we do to find a unattended update solution?
> 
> Thanks (sorry for my bad english, i speak spanish)

Theres no souloution. This is caused by github overwriting all files. I would just recomend to safe the config folders before git pull, or to chnage the config folder location to a different.

**Comment by BastelPichi** [comment]
Closed due to inacativity, feel free to reopen if needed.
