### ISSUE TITLE
AVR_Miner multiple boards

### ISSUE THREAD

**Issue by Mrva007** [duino-coin/duino-coin#703]
Hi,

AVR_miner version 2.5.7 has some problem that I can't fix because it doesn't show any error.

I use Arduino Uno and Mega2560, both boards have code loaded from version 2.5.7 but for some reason only one board works even though it started mining from both boards.
The AVR boards are on port COM5 and COM6, mining has started on both boards but for some reason it only shows the board on port COM6 to work.

Prt scn below ...

<img width="437" alt="avr miner" src="https://user-images.githubusercontent.com/44605065/126874215-be3a4a45-7a46-4393-9b14-4a4eab88242a.png">

Am I doing something wrong?

**Comment by revoxhere** [comment]
Can you try now?
