### ISSUE TITLE
OTA - use rig name, not the chip ID on the ESP32

### ISSUE THREAD

**Issue by nigeljohnson73** [duino-coin/duino-coin#704]
When I installed this on my ESP32 it came up in the port listing with the Chip ID, rather than the rig name... If you have a couple of them, it soon gets messy. Interestingly I didn't have the same problem on the ESP8266. Anyhow, before you run the ArduinoOTA.begin() call, use this:

    ArduinoOTA.setHostname(rigname); // Give port a name not just address

Then the rig name you give the device will appear in the OTA port listing.

Thought this would be useful, and a really easy addition.

**Comment by revoxhere** [comment]
Can you create a PR?

**Comment by nigeljohnson73** [comment]
I'm not really sure how to do that. I'm not used to creating branches and I don't want to be breaking things.

**Comment by nigeljohnson73** [comment]
Ah, looks like I did it. I learned stuff today. No branches required :)
