### ISSUE TITLE
Too low duco per day with AVR BOARD.

### ISSUE THREAD

**Issue by sajadkkkkkk** [duino-coin/duino-coin#705]
hello ,
with using 10 arduino boards, only 5duco/day  is available that it is very little , is there any bug here ?
i got 50 duco/day with 20 arduino board 2week ago.
what is problem about this matter ?
why duco/day is too low for this avrboards?
\thanks in advance.

**Comment by revoxhere** [comment]
Try NOW.

**Comment by sajadkkkkkk** [comment]
that fixed , thank you very much.
