### ISSUE TITLE
McAfee report PC_Miner.exe as Virus

### ISSUE THREAD

**Issue by IamNitinMishra** [duino-coin/duino-coin#706]
**Describe the bug**
Today while starting the "PC_Miner.exe", the McAfee LiveSafe security report this file as virus(please review the screenshot attached). 

**To Reproduce**
1. please have the Latest McAfee LiveSafe security on PC (enabled and running).
2. As soon as you click on 'PC_Miner.exe'
3. the first click disable for the file and second click remove the file from the directory the screenshot attached.... 

**Screenshots/photos**
<img width="647" alt="suspectthreat" src="https://user-images.githubusercontent.com/51865153/126895300-9d1968ad-40be-4531-8b16-17b9a7aabdee.png">

**System (please complete the following information):**
 - OS - Windows 10 Home
 - Software - PC_Miner.exe
 - Version - 2.5.7

**Comment by revoxhere** [comment]
There is nothing we can do about it
