### ISSUE TITLE
Node message: Too many workers

### ISSUE THREAD

**Issue by nigeljohnson73** [duino-coin/duino-coin#711]
**Describe the bug**
Related to #374 ? 

I powered all of my miners off overnight to see if things would time out, but I am seeing this error on all of my miner rigs. Possibly related is the fact that API calls are taking 40 seconds to 1 minute (where they then fail) and I'm getting high rejection rates. This is also happening across multiple accounts.

    06:25:49  net0  MOTD: Welcome to the first Duino-Coin pool!
                    Pool worker limit: 50
    06:25:49  net0  Connected to master Duino-Coin server (v2.5, node: 149.91.88.18:6000)
    06:25:49  sys0  Mining thread #0 is starting using DUCO-S1 algorithm with 95% efficiency
    06:25:50  cpu0  Node message: Too many workers current limit: 50
    06:25:53  net0  Error while mining - most likely a connection error - restarting in 5s. (mining err: list index out of range)

I'm running a Raspberry pi 4b+ with 4 threads using 2.56 of the miner

     ‖ Official Duino-Coin © Python Miner (v2.56) 2019-2021
     ‖ CPU: 4x ARMv7 Processor rev 3 (v7l)

**Comment by nigeljohnson73** [comment]
Ah, I think I have found the 'problem' - the "pool" is related to your home IP address... not username is that right?

**Comment by johnlrhodes757** [comment]
I was getting same error and only have
ESPx10
Arduino x 17
and CPU x 6 cores

**Comment by pankleks** [comment]
@nigeljohnson73 it looks to me like limit is also on client IP (and I think not client IP + user name) - so if someone else is mining from same network (office, dormitory) - all have 50 slots.

to be confirmed by devs ...

**Comment by revoxhere** [comment]
It's both IP and Username. No one will need more than 50 workers, and I'm thinking of going back to 25

**Comment by nigeljohnson73** [comment]
Thanks for the clear up. 

I have 20 ESP32 on a test rig, and then started testing another rig of AVR's when it popped. My daughter and brother are also 'playing' so I wasn't sure if it was related to the server issue of late or my house (over 3 accounts).

Happy to close this issue, or let it carry on if @johnlrhodes757 is still having issues.

**Comment by pankleks** [comment]
@revoxhere 

20 esp32 is connection x 2 -> 40 connections. I'm afraid that if you come back to 25 it will be quite limiting.

"It's both IP and Username" - then I'm pretty sure there is a problem somewhere as according to my tests - it's behaves as global limit for client IP. 

Unless there are some issues at present with the server.

**Comment by revoxhere** [comment]
I don't know how is that implemented in the pool

**Comment by pankleks** [comment]
I'm close to 100% sure that pool has limit per ip and not ip/user name.
I understand reasoning behind - however for situations like described by @nigeljohnson73 or students in dormitory (or office) it will be limiting factor.
