### ISSUE TITLE
Periodic mining report bug

### ISSUE THREAD

**Issue by robtech21** [duino-coin/duino-coin#714]
Just an error when showing the periodic mining report on the most recent commit:

```
20:28:37  sys0 String not found: periodic_mining_reportString not found: report_period62String not found: report_timeString not found: report_body1400String not found: report_body26.5String not found: report_body3String not found: report_body4194 H/sString not found: report_body512070String not found: report_body6String not found: total_mining_time117String not found: uptime_minutes```

This happens with both AVR and PC miners.

**Comment by naphob** [comment]
New strings are added to the langs.json file.  It usually loads everything to the resources file when you have configured the script the first time. If you need everything works well again. Just delete that file. It will download the latest one from this repo.

**Comment by robtech21** [comment]
> New strings are added to the langs.json file. It usually loads everything to the resources file when you have configured the script the first time. If you need everything works well again. Just delete that file. It will download the latest one from this repo.

Okay, thank you. I will try it out.

**Comment by revoxhere** [comment]
Is the problem fixed?

**Comment by robtech21** [comment]
> Is the problem fixed?

Yeah
