### ISSUE TITLE
Hashrate and Web wallet issues

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#722]
The mining hashrates of Arduino, ESP and PC are slowing down since last night. Also, the web wallet can't not access since on last Sunday. Does anyone facing the same problems? I just rebooted my router, Arduino, ESP, PC and my smartphones, but the hashrates are still very slow; the web wallet still can't be accessed.

**Comment by Gloomydemin** [comment]
I have the same trouble

**Comment by marcoduinocoin** [comment]
> I have the same trouble

revox is helping his family and busy for farming at the moment. just wait a few days. he is  farming.

**Comment by primitt** [comment]
Revox is farming Duino-Coin manually, it is very fun (just a joke lol)

**Comment by marcoduinocoin** [comment]
> Revox is farming Duino-Coin manually, it is very fun (just a joke lol)

and I just farming for white rice everyday, and farming for Duino-Coin at night

**Comment by primitt** [comment]
question, are you in the discord?

> > Revox is farming Duino-Coin manually, it is very fun (just a joke lol)
> 
> and I just farming for white rice everyday, and farming for Duino-Coin at night

**Comment by marcoduinocoin** [comment]
> question, are you in the discord?
> 
> > > Revox is farming Duino-Coin manually, it is very fun (just a joke lol)
> > 
> > 
> > and I just farming for white rice everyday, and farming for Duino-Coin at night

what is discord? I just started mining in july

**Comment by marcoduinocoin** [comment]
> question, are you in the discord?
> 
> > > Revox is farming Duino-Coin manually, it is very fun (just a joke lol)
> > 
> > 
> > and I just farming for white rice everyday, and farming for Duino-Coin at night

I don't have an account of discord. is it similar to tiktok? have no idea.

**Comment by sys-256** [comment]
> I don't have an account of discord. is it similar to tiktok? have no idea.

No, it's more like the opposite of tiktok, you can join servers which people made. Those servers usually have multiple text channels and voice channels where you can chat and talk which each other.

This is how the interface looks like:
![image](https://user-images.githubusercontent.com/84628826/127381686-e91c6cf6-6e8e-4a95-9a18-4339b9266d97.png)

**Comment by primitt** [comment]
> > question, are you in the discord?
> > > > Revox is farming Duino-Coin manually, it is very fun (just a joke lol)
> > > 
> > > 
> > > and I just farming for white rice everyday, and farming for Duino-Coin at night
> 
> I don't have an account of discord. is it similar to tiktok? have no idea.

Nono, not at all like tiktok, its more like slack, but here is the link to it

https://discord.gg/duinocoin

**Comment by marcoduinocoin** [comment]
> > I don't have an account of discord. is it similar to tiktok? have no idea.
> 
> No, it's more like the opposite of tiktok, you can join servers which people made. Those servers usually have multiple text channels and voice channels where you can chat and talk which each other.
> 
> This is how the interface looks like:
> ![image](https://user-images.githubusercontent.com/84628826/127381686-e91c6cf6-6e8e-4a95-9a18-4339b9266d97.png)

wow, it looks awesome! thanks bro. will try it later. many thanks.

**Comment by marcoduinocoin** [comment]
> > > question, are you in the discord?
> > > > > Revox is farming Duino-Coin manually, it is very fun (just a joke lol)
> > > > 
> > > > 
> > > > and I just farming for white rice everyday, and farming for Duino-Coin at night
> > 
> > 
> > I don't have an account of discord. is it similar to tiktok? have no idea.
> 
> Nono, not at all like tiktok, its more like slack, but here is the link to it
> 
> https://discord.gg/duinocoin

really awesome. will join later. thanks bro.
