### ISSUE TITLE
Mining problem

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#723]
Generally, I can get more than 20 Duino-Coins a day, but I found that I only can get less than ONE Duino-Coins with same devices since last day. What really happened? Is the Duino-Coin server slowing down or overloading? Any ideas?

**Comment by johnlrhodes757** [comment]
I have been running into the same issue.  My AVG miner is pumping out about 2.4kH and then my ESP are pumping out 39kH with very little reward.  I think I am only making about .44 duino a day....  not good at all... something is seriously wrong.

**Comment by marcoduinocoin** [comment]
Revox and his team are fixed the mining issue. Try to restart the miners and the hashrate will become normally as I tried in this morning. Cheers.
