### ISSUE TITLE
pc miner and web miner

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#727]
kindly add the setting function to let the user to set the donation amount in anytime. I can't find the donation option in web miner, also, can't adjust or increase the donation amount in pc miner once started the first mining in my old pc. thanks.

**Comment by primitt** [comment]
1. If you are doing it for the AVR/PC miner, you can go to the AVR miner resources, or the PC miner resources, and open the miner_config.cfg in notepad. Edit the donation amount of 1-5 (0 will not donate)
2. The web miner does not have donation

**Comment by sys-256** [comment]
The donation mines XMG for revox in the background, so if you would implement that in the webminer, you would mine 2 coins at the same time, which the already limited processing power the browser can give a website.

Aside that, except webchain, I haven't seen any other profitable coin (as in profitable when cpu mining) which relies on a algorithm which is already implemented in javascript.

**Comment by revoxhere** [comment]
All donations were removed some time ago, stop spreading misinformation

**Comment by marcoduinocoin** [comment]
> All donations were removed some time ago, stop spreading misinformation

Thanks Revox. Got it.

**Comment by marcoduinocoin** [comment]
> All donations were removed some time ago, stop spreading misinformation

Hi Revox! Do you like the cats? Any wild cats in your farms? We're petting 3 cats in our farms

**Comment by marcoduinocoin** [comment]
I will become a cat father soon, the cat babies will be born soon. I'm really happy to living with my parents and cute cats.
