### ISSUE TITLE
Miner rate fall to 0.46 and all my miner are working 

### ISSUE THREAD

**Issue by liubergarcia** [duino-coin/duino-coin#728]
**Describe the bug**  miner  rate is very low 
I have 4.7 hash and only 0.46 coin by day
**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by marcoduinocoin** [comment]
Everything is okay now. I can mining normally.
Also, the Web Wallet can access quickly now. Very awesome.
