### ISSUE TITLE
The Issue of Web Miner 

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#731]
The Web Miner can not mining since last night.
I tried to restart my old computer for several times but still can't start to mine. Any idea?
![FB_IMG_1627657342071](https://user-images.githubusercontent.com/88106006/127672875-f80e23b6-4b5a-4906-b572-b1d0ec39adf7.jpg)

**Comment by BastelPichi** [comment]
![grafik](https://user-images.githubusercontent.com/63782569/127742572-f159556b-1f3b-4815-a9bf-b168a4d6d84f.png)

I would reccomend using the python miner for now, also its much more efficiant than the webminer.

**Comment by marcoduinocoin** [comment]
> ![grafik](https://user-images.githubusercontent.com/63782569/127742572-f159556b-1f3b-4815-a9bf-b168a4d6d84f.png)
> 
> I would reccomend using the python miner for now, also its much more efficiant than the webminer.

My oversea friends told me that all the miners in the world can't mining due to the server issue.

**Comment by revoxhere** [comment]
Should work now

**Comment by marcoduinocoin** [comment]
Thanks Revox
