### ISSUE TITLE
Connection timeouts and zero revenue when using nonceMiner

### ISSUE THREAD

**Issue by colonelwatch** [duino-coin/duino-coin#732]
**Describe the bug**
As reported in colonelwatch/nonceMiner#17. When connecting to pulse-pool, shares are being accepted when running nonceMiner, but no reward is credited. There is also frequent connection timeouts, and the mining threads don't appear in the miners panel in the wallet. None of the issues occur with the official PC miner.

**To Reproduce**
1. Download/compile and run nonceMiner as normal

**Expected behavior**
Accepted shares should be rewarded and the threads should appear in the miners panel.

**Screenshots/photos**
See colonelwatch/nonceMiner#17.

**System (please complete the following information):**
 - OS: WIndows
 - Software: nonceMiner
 - Version: v2.1.1

**Additional context**
nonceMiner is a community-made miner.

**Comment by revoxhere** [comment]
Hello, childish behavior expert here, since nonceMiner is not an official miner, there's nothing we can do about it. And since you,re so good at everything, I'm sure you can fix it yourself. Now, just like you did with leaving the dev team some time ago, I'm closing this issue. Cheers!!!!

**Comment by colonelwatch** [comment]
Putting aside the personal comments, I don't think this is a problem I can solve myself. The shares are being accepted by the server, so, at the very least, it's the server's responsibility from there to credit the user. If it helps, I've just noticed that withholding the name of the program when submitting the response allows the user to be credited as usual.

And now, I truly don't understand how I offended you @revoxhere, but is it about why I left the Discord server?

**Comment by revoxhere** [comment]
I don't know, after all, I don't have that much experience. I'm sure you'll come up with something on your own!

**Comment by nigeljohnson73** [comment]
This wasn't / isn't related to 'other' miners, I'm using the standard ESP32 code, and during the recent hiccup, the ESP32 boards were all reporting accepts and doing their usual thing at the usual speed... but my balance wasn't going up even close to the usual rate. Here is a 48-hour window on my balance, you can see when things burst back into life about 24 hours ago.

![image](https://user-images.githubusercontent.com/6493525/127735452-dda43d65-5a93-413e-bfaa-d020b7eda40e.png)

I'm curious about what's happening. The "accepted" message on the board means that it thought the share was written to the blockchain? The ESP32 would be using the pool, not the main server, so does that mean there are some unassigned blocks out there? or the accepted doesn't mean it was written to the blockchain, or is there just some synchronising that needs to go on?

Apologies if I'm using all the wrong words, ledgering is not my first language :)

**Comment by revoxhere** [comment]
"There is no blockchain, this project is a joke", also, I think you should ask travelmode, he is the best here it seems. For real though, there is a queue, and maybe the queue was too long to credit the miner. I don't fucking know, I know nothing, ask someone who is better
