### ISSUE TITLE
The PC Miner can't start on Win8

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#733]
Just install led the Python 3.9 and added Path and Pip, but the PC Miner can't run successfully.
![Uploading 16276962667018775067648493000582.jpg…]()

**Comment by marcoduinocoin** [comment]
![Uploading 1627696322065577907126160919093.jpg…]()

**Comment by marcoduinocoin** [comment]
![16276963746618147155111802526492](https://user-images.githubusercontent.com/88106006/127725196-a1f4b3eb-5d34-43d9-9e0b-84b46a007c7b.jpg)

**Comment by revoxhere** [comment]
As described in the getting started guide, EXEs are compiled for Windows 10, so you will need to [launch the miner from source](https://github.com/revoxhere/duino-coin/releases/latest) for older michaelsoft bimbows versions

**Comment by marcoduinocoin** [comment]
Thanks Revox.
