### ISSUE TITLE
Arduino, ESP and PC mining problem

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#736]
I found that the amount of wallet isn't updating since 43 minutes ago. But I confirmed that all Arduino boards, ESP8266 boards and PCs are mining normally without any error messages. Is the Duino-Coin Server facing the overload / issue again?
![Screenshot_20210731-190618_Samsung Internet](https://user-images.githubusercontent.com/88106006/127738156-8cd00ef1-4a22-46d5-96e0-8475c2cd34cc.jpg)

**Comment by BastelPichi** [comment]
The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?

**Comment by marcoduinocoin** [comment]
> The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?

Just stopped all miners and sent all my coins to one of duino-coin users right here. That's wasting our electric to do the stupid things.

**Comment by primitt** [comment]
> > The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?
> 
> 
> 
> Just stopped all miners and sent all my coins to one of duino-coin users right here. That's wasting our electric to do the stupid things. 

You know, this project was not intended for 15000 people. It was a side hobby for 100 people. Also arduinos use 0.5W of energy per hour which in the long term is quite good. Now, we are trying to fix profits as the server was fine a week ago. Revox is also dealing with his farm and has little time to work.

**Comment by marcoduinocoin** [comment]
> > > The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?
> > 
> > 
> > Just stopped all miners and sent all my coins to one of duino-coin users right here. That's wasting our electric to do the stupid things.
> 
> You know, this project was not intended for 15000 people. It was a side hobby for 100 people. Also arduinos use 0.5W of energy per hour which in the long term is quite good. Now, we are trying to fix profits as the server was fine a week ago. Revox is also dealing with his farm and has little time to work.

Nope, not at all. Some of users like me is also using the old computers as miners, so the electric consumption is greater than 50W per hour. The DUCO Server must be upgraded or add more servers for currently situation ASAP. Otherwise, the deadly mining problem will only more worst than now. This is my opinion. I and our friends are already stopped mining and donated all our boards to the IT workshops in our city. We should issue a video to tell the people not to try the Duino-Coin because they even can't earn for their electric bills.

**Comment by primitt** [comment]
> > > > The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?
> 
> > > 
> 
> > > 
> 
> > > Just stopped all miners and sent all my coins to one of duino-coin users right here. That's wasting our electric to do the stupid things.
> 
> > 
> 
> > You know, this project was not intended for 15000 people. It was a side hobby for 100 people. Also arduinos use 0.5W of energy per hour which in the long term is quite good. Now, we are trying to fix profits as the server was fine a week ago. Revox is also dealing with his farm and has little time to work.
> 
> 
> 
> Nope, not at all. Some of users like me is also using the old computers as miners, so the electric consumption is greater than 50W per hour. The DUCO Server must be upgraded or add more servers for currently situation ASAP. Otherwise, the deadly mining problem will only more worst than now. This is my opinion. I and our friends are already stopped mining and donated all our boards to the IT workshops in our city. We should issue a video to tell the people not to try the Duino-Coin because they even can't earn for their electric bills. 

I dont think you understood duinocoin at all. Your just complaining. The project was not MEANT for 15000 people. We dont have a lot of money to spend on a beast VPS. The rewards were WORKING FINE 1 week ago

**Comment by primitt** [comment]
> > > > The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?
> 
> > > 
> 
> > > 
> 
> > > Just stopped all miners and sent all my coins to one of duino-coin users right here. That's wasting our electric to do the stupid things.
> 
> > 
> 
> > You know, this project was not intended for 15000 people. It was a side hobby for 100 people. Also arduinos use 0.5W of energy per hour which in the long term is quite good. Now, we are trying to fix profits as the server was fine a week ago. Revox is also dealing with his farm and has little time to work.
> 
> 
> 
> Nope, not at all. Some of users like me is also using the old computers as miners, so the electric consumption is greater than 50W per hour. The DUCO Server must be upgraded or add more servers for currently situation ASAP. Otherwise, the deadly mining problem will only more worst than now. This is my opinion. I and our friends are already stopped mining and donated all our boards to the IT workshops in our city. We should issue a video to tell the people not to try the Duino-Coin because they even can't earn for their electric bills. 

Also, the coin is for arduino boards. Not old computer, hell, we were once thinking to remove the pc miner! We are trying to fix the rewards atm.

**Comment by marcoduinocoin** [comment]
> > > > > The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Just stopped all miners and sent all my coins to one of duino-coin users right here. That's wasting our electric to do the stupid things.
> > 
> > 
> > > 
> > 
> > 
> > > You know, this project was not intended for 15000 people. It was a side hobby for 100 people. Also arduinos use 0.5W of energy per hour which in the long term is quite good. Now, we are trying to fix profits as the server was fine a week ago. Revox is also dealing with his farm and has little time to work.
> > 
> > 
> > Nope, not at all. Some of users like me is also using the old computers as miners, so the electric consumption is greater than 50W per hour. The DUCO Server must be upgraded or add more servers for currently situation ASAP. Otherwise, the deadly mining problem will only more worst than now. This is my opinion. I and our friends are already stopped mining and donated all our boards to the IT workshops in our city. We should issue a video to tell the people not to try the Duino-Coin because they even can't earn for their electric bills.
> 
> Also, the coin is for arduino boards. Not old computer, hell, we were once thinking to remove the pc miner! We are trying to fix the rewards atm.

Well, the pc miner is a great thing for any users to start their mining at first. This is an awesome miner we ever used when the Duion-Coin Server is in good condition. We were started to use an old computer for mining, then started to purchase 100 boards of ESP8266 for 10 members, and I also purchased a Arduino Uno, that's mean I have to connect my Uno to computer for mining. You know, the Arduino Uno don't have the WiFi function, so the mining must be connected with any kind of pc. So, even a Arduino Uno will totally draws greater than 76W per hours as I measured. In this moment, Duino-Coin need to enhance the servers, also add more servers if the DUCO creators want to keep developing for the long term. More than 10000 users right now, and my suggestion is to upgrade the servers and add more servers to handle all user connections in the world. Don't think the past and just looking for the future.

**Comment by marcoduinocoin** [comment]
many users feeling upset but don't have the brave to post anything right here, because they are afraid their accounts will be cancelled that they are really concerning. So you even discovered that only I just posted for many times when I found any problems and issues about the Duino-coin server. So, this is the time to have a discussion between the DUCO masters and users that how to keep the DUCO growing up healthy but not to ignore or feeling unhappy and reject any users who comments and adviced right here.

**Comment by primitt** [comment]
> > > > > > The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Just stopped all miners and sent all my coins to one of duino-coin users right here. That's wasting our electric to do the stupid things.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > You know, this project was not intended for 15000 people. It was a side hobby for 100 people. Also arduinos use 0.5W of energy per hour which in the long term is quite good. Now, we are trying to fix profits as the server was fine a week ago. Revox is also dealing with his farm and has little time to work.
> 
> > > 
> 
> > > 
> 
> > > Nope, not at all. Some of users like me is also using the old computers as miners, so the electric consumption is greater than 50W per hour. The DUCO Server must be upgraded or add more servers for currently situation ASAP. Otherwise, the deadly mining problem will only more worst than now. This is my opinion. I and our friends are already stopped mining and donated all our boards to the IT workshops in our city. We should issue a video to tell the people not to try the Duino-Coin because they even can't earn for their electric bills.
> 
> > 
> 
> > Also, the coin is for arduino boards. Not old computer, hell, we were once thinking to remove the pc miner! We are trying to fix the rewards atm.
> 
> 
> 
> Well, the pc miner is a great thing for any users to start their mining at first. This is an awesome miner we ever used when the Duion-Coin Server is in good condition. We were started to use an old computer for mining, then started to purchase 100 boards of ESP8266 for 10 members, and I also purchased a Arduino Uno, that's mean I have to connect my Uno to computer for mining. You know, the Arduino Uno don't have the WiFi function, so the mining must be connected with any kind of pc. So, even a Arduino Uno will totally draws greater than 76W per hours as I measured. In this moment, Duino-Coin need to enhance the servers, also add more servers if the DUCO creators want to keep developing for the long term. More than 10000 users right now, and my suggestion is to upgrade the servers and add more servers to handle all user connections in the world. Don't think the past and just looking for the future.

I mean, we will ofc, we did just recently buy a new server! (tbh the restAPI mostly causes the overloads) Thats also the reason we got ads! But then again, we are all young people and its the summer, you cant expect us to work all the time.

**Comment by primitt** [comment]
> many users feeling upset but don't have the brave to post anything right here, because they are afraid their accounts will be cancelled that they are really concerning. So you even discovered that only I just posted for many times when I found any problems and issues about the Duino-coin server. So, this is the time to have a discussion between the DUCO masters and users that how to keep the DUCO growing up healthy but not to ignore or feeling unhappy and reject any users who comments and adviced right here.

We dont ban people for posting here. We ban users who dont follow the TOS, like free vps mining such as repl

**Comment by primitt** [comment]
Also its not like people dont like to comment, most people ask for help on the discord, https://discord.gg/duinocoin

**Comment by marcoduinocoin** [comment]
> > > > > > > The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > Just stopped all miners and sent all my coins to one of duino-coin users right here. That's wasting our electric to do the stupid things.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > You know, this project was not intended for 15000 people. It was a side hobby for 100 people. Also arduinos use 0.5W of energy per hour which in the long term is quite good. Now, we are trying to fix profits as the server was fine a week ago. Revox is also dealing with his farm and has little time to work.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Nope, not at all. Some of users like me is also using the old computers as miners, so the electric consumption is greater than 50W per hour. The DUCO Server must be upgraded or add more servers for currently situation ASAP. Otherwise, the deadly mining problem will only more worst than now. This is my opinion. I and our friends are already stopped mining and donated all our boards to the IT workshops in our city. We should issue a video to tell the people not to try the Duino-Coin because they even can't earn for their electric bills.
> > 
> > 
> > > 
> > 
> > 
> > > Also, the coin is for arduino boards. Not old computer, hell, we were once thinking to remove the pc miner! We are trying to fix the rewards atm.
> > 
> > 
> > Well, the pc miner is a great thing for any users to start their mining at first. This is an awesome miner we ever used when the Duion-Coin Server is in good condition. We were started to use an old computer for mining, then started to purchase 100 boards of ESP8266 for 10 members, and I also purchased a Arduino Uno, that's mean I have to connect my Uno to computer for mining. You know, the Arduino Uno don't have the WiFi function, so the mining must be connected with any kind of pc. So, even a Arduino Uno will totally draws greater than 76W per hours as I measured. In this moment, Duino-Coin need to enhance the servers, also add more servers if the DUCO creators want to keep developing for the long term. More than 10000 users right now, and my suggestion is to upgrade the servers and add more servers to handle all user connections in the world. Don't think the past and just looking for the future.
> 
> I mean, we will ofc, we did just recently buy a new server! (tbh the restAPI mostly causes the overloads) Thats also the reason we got ads! But then again, we are all young people and its the summer, you cant expect us to work all the time.

I'm happy to hear that you're already bought the new server for the DUCO. Yep, the RestAPI causes overloading now, you're really smart.

I am also young, I just 17 years old now, and I'm working in  our farms and adding the solar panels to selling the clean energy to the society, mostly likely USD570 monthly.

If the DUCO servers are stable and running smoothly, this is possible to mining with the Arduino boards and ESP boards which powered by solar panel system!

**Comment by marcoduinocoin** [comment]
> > many users feeling upset but don't have the brave to post anything right here, because they are afraid their accounts will be cancelled that they are really concerning. So you even discovered that only I just posted for many times when I found any problems and issues about the Duino-coin server. So, this is the time to have a discussion between the DUCO masters and users that how to keep the DUCO growing up healthy but not to ignore or feeling unhappy and reject any users who comments and adviced right here.
> 
> We dont ban people for posting here. We ban users who dont follow the TOS, like free vps mining such as repl

Good to hear that.

**Comment by marcoduinocoin** [comment]
> Also its not like people dont like to comment, most people ask for help on the discord, https://discord.gg/duinocoin

This is the time to buy a microphone set then.

**Comment by marcoduinocoin** [comment]
> The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?

My Singapore friends said their miners are normal but the amount of wallet isn't updated for more than 4 hours from last night.

**Comment by BastelPichi** [comment]
> > > > > > The Main server is overloaded constantly, so it may not update. Also, you may get rewarded less if the server is overloaded. For me it works, maybe you can try again?
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > Just stopped all miners and sent all my coins to one of duino-coin users right here. That's wasting our electric to do the stupid things.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > You know, this project was not intended for 15000 people. It was a side hobby for 100 people. Also arduinos use 0.5W of energy per hour which in the long term is quite good. Now, we are trying to fix profits as the server was fine a week ago. Revox is also dealing with his farm and has little time to work.
> > > 
> > > 
> > > Nope, not at all. Some of users like me is also using the old computers as miners, so the electric consumption is greater than 50W per hour. The DUCO Server must be upgraded or add more servers for currently situation ASAP. Otherwise, the deadly mining problem will only more worst than now. This is my opinion. I and our friends are already stopped mining and donated all our boards to the IT workshops in our city. We should issue a video to tell the people not to try the Duino-Coin because they even can't earn for their electric bills.
> > 
> > 
> > Also, the coin is for arduino boards. Not old computer, hell, we were once thinking to remove the pc miner! We are trying to fix the rewards atm.
> 
> Well, the pc miner is a great thing for any users to start their mining at first. This is an awesome miner we ever used when the Duion-Coin Server is in good condition. We were started to use an old computer for mining, then started to purchase 100 boards of ESP8266 for 10 members, and I also purchased a Arduino Uno, that's mean I have to connect my Uno to computer for mining. You know, the Arduino Uno don't have the WiFi function, so the mining must be connected with any kind of pc. So, even a Arduino Uno will totally draws greater than 76W per hours as I measured. In this moment, Duino-Coin need to enhance the servers, also add more servers if the DUCO creators want to keep developing for the long term. More than 10000 users right now, and my suggestion is to upgrade the servers and add more servers to handle all user connections in the world. Don't think the past and just looking for the future.

Were working on the Server. Also, if you look at the pool whicj just has 4cores and 4gb ram, it handles 15000 conections quite well. And if youre complainng because you cant mine for a week, just go to a other crypto were your miner draw 100x as much. And if you want a fix faster, why dont fix it yourself???
