### ISSUE TITLE
Free Duino-coin transfer for you

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#737]
Since the Duino-Coin mining problem occurs many times, we have decided to stop all our mining machines. I would like to transfer all my account 95.14 coins for free , anyone interested? Please provide your account name then I will transfer 95.14 coins to you.

**Comment by mrgh14** [comment]
plz give me 
my wallet is mrgh14

**Comment by marcoduinocoin** [comment]
> plz give me
> my wallet is mrgh14

Amount 95.14 sent to you.

**Comment by mrgh14** [comment]
tank u i got ur coin

**Comment by marcoduinocoin** [comment]
> tank u i got ur coin

Already sent to you.
