### ISSUE TITLE
Server and Pool

### ISSUE THREAD

**Issue by YogaVanHalen** [duino-coin/duino-coin#738]
Hi There, Can we contribute to reducing server load, by creating another server in our country? or anything else like node or pulse pool maybe, because the project you are working on is very interesting, due to the low consumption of electrical power, to support green energy mining

**Comment by BastelPichi** [comment]
> Hi There, Can we contribute to reducing server load, by creating another server in our country? or anything else like node or pulse pool maybe, because the project you are working on is very interesting, due to the low consumption of electrical power, to support green energy mining

At the moment not. The pool owner can give any Person DUCO, as the public pools arent ready yet. The pulse pool also manages the load quite well. So we would need a new main-server and that one would need a lot of power...

**Comment by marcoduinocoin** [comment]
> Hi There, Can we contribute to reducing server load, by creating another server in our country? or anything else like node or pulse pool maybe, because the project you are working on is very interesting, due to the low consumption of electrical power, to support green energy mining

This is a big joke to let us waste a lot of money to buy the Arduino boards and ESP boards for a poor mining with a damn coin server at all. This mining just wasting our time and electric.

**Comment by Bilaboz** [comment]
This is not possible at the moment, pichi explained the first problem, the second one is that adding more pools will add more load on the server (because more sync)

**Comment by noobflix** [comment]
AQUI NO BRASIL TENHO MINHA RIG COM MAS 1MIL PESSOAS TODAS ELAS COM 25 ARDUINO E 10 Celulares MINERANDO ... QUERO PODER TE AJUDAR REVOXHERE
