### ISSUE TITLE
Automatic Picker ESP - https://server.duinocoin.com/getPool

### ISSUE THREAD

**Issue by ricaun** [duino-coin/duino-coin#739]
Hello @revoxhere

I was trying to fix the I2C project after the 2.6 version. 

And I found some problems then fixing them all.

One problem was the server IP and port like the esp code.

https://github.com/revoxhere/duino-coin/blob/3a0e7602acd7266aa0c050592eabceec1e9cd330/ESP8266_Code/ESP8266_Code.ino#L53-L55

But looking on the AVR miner I found this:

https://github.com/revoxhere/duino-coin/blob/3a0e7602acd7266aa0c050592eabceec1e9cd330/AVR_Miner.py#L1131-L1136

I believe you want to create an automatic picker like the AVR miner using the 'https://server.duinocoin.com/getPool' link.

I tried this code on the ESP8266 => `httpGetString("https://server.duinocoin.com/getPool");`

``` C#
String httpGetString(String URL)
{
  String payload = "";
  HTTPClient http;
  http.begin(URL);
  int httpCode = http.GET();
  if (httpCode > 0)
  {
    if (httpCode == HTTP_CODE_OK)
    {
      payload = http.getString();
    }
  }
  else
  {
    Serial.printf("[HTTP] GET... failed, error: %s\n", http.errorToString(httpCode).c_str());
  }
  http.end();
  return payload;
}
```

But have a big connection refused, HTTPS does not work very well... 

One solution is using HTTP instead, but the server forces to HTTPS.

Other is to use the IP directly `51.15.127.80`, but the server does not found the path...

I tested with other API call and works 100% on the ESP8266 => `http://51.15.127.80/miners/ricaun`

If the link http://51.15.127.80/getPool works should be easy to implement the `automatic picker` on the ESP.

See Yaa

**Comment by revoxhere** [comment]
Hey, thanks for nicely documenting the problem, I'll try to reconfigure nginx in a second

**Comment by revoxhere** [comment]
You can use `http://51.15.127.80:4242/getPool`

**Comment by ricaun** [comment]
> 
> 
> You can use `http://51.15.127.80:4242/getPool`

Timeout 😢

**Comment by revoxhere** [comment]
Whoops, wait

**Comment by oli737** [comment]
cool we have a fix soon. i cant wait start my i2c miner again :)

**Comment by oli737** [comment]
could you guys integrate the i2c in the main release as option? that would be nice.

**Comment by Bilaboz** [comment]
The port wasn't open, you can now access http://51.15.127.80:4242/getPool

**Comment by ricaun** [comment]
> 
> 
> The port wasn't open, you can now access http://51.15.127.80:4242/getPool

This works! `httpGetString("http://51.15.127.80:4242/getPool");` 

Response:
`{"name":"pulse-pool-1","ip":"149.91.88.18","port":"6000","connections":22245}`

**Comment by ricaun** [comment]
You should consider doing something like this in the future:

`http://api.duinocoin.com/getPool` & `https://api.duinocoin.com/getPool`
`http://api.duinocoin.com/miners` & `https://api.duinocoin.com/miners`

Without forcing to HTTPS.

**Comment by ricaun** [comment]
I was using an old version of the Esp8266 board, this code should work on the Esp8266 board version 3.0.2

``` C#
String httpGetString(String URL)
{
  String payload = "";
  WiFiClient client;
  HTTPClient http;
  if (http.begin(client, URL))
  {
    int httpCode = http.GET();
    if (httpCode == HTTP_CODE_OK)
    {
      payload = http.getString();
    }
    else
    {
      Serial.printf("[HTTP] GET... failed, error: %s\n", http.errorToString(httpCode).c_str());
    }
    http.end();
  }
  return payload;
}
```
