### ISSUE TITLE
Hashing but no reward

### ISSUE THREAD

**Issue by johnlrhodes757** [duino-coin/duino-coin#740]
I am using AVR miner (22@15.3kH/s), CPU miner (8@3.1mH/s), and ESP miner (10@92.6kH/s) and throughout most of the day the coins earned have been close to none for hour at a time.  Is there a limit to how much can be mined a day?

12:24 AM Edit, wallet rewards still not gone up.... 2 hours from original post.  I will leave it running in hopes that things will pan out...

**Comment by thienduongtungtang** [comment]
### I have the same problem as you ###

**Comment by ygboucherk** [comment]
does it show accepted shares ?

**Comment by thienduongtungtang** [comment]
I thank you it worked fine
I love duino coin

Vào 6:20, Th 2, 2 thg 8, 2021 ygboucherk ***@***.***> đã viết:

**Comment by BastelPichi** [comment]
> I am using AVR miner ([22@15.3kH](mailto:22@15.3kH)/s), CPU miner ([8@3.1mH](mailto:8@3.1mH)/s), and ESP miner ([10@92.6kH](mailto:10@92.6kH)/s) and throughout most of the day the coins earned have been close to none for hour at a time. Is there a limit to how much can be mined a day?
> 
> 12:24 AM Edit, wallet rewards still not gone up.... 2 hours from original post. I will leave it running in hopes that things will pan out...

This is probably caused by the api not working correctly and also the rewards being lower.

**Comment by johnlrhodes757** [comment]
> > I am using AVR miner ([22@15.3kH](mailto:22@15.3kH)/s), CPU miner ([8@3.1mH](mailto:8@3.1mH)/s), and ESP miner ([10@92.6kH](mailto:10@92.6kH)/s) and throughout most of the day the coins earned have been close to none for hour at a time. Is there a limit to how much can be mined a day?
> > 12:24 AM Edit, wallet rewards still not gone up.... 2 hours from original post. I will leave it running in hopes that things will pan out...
> 
> This is probably caused by the api not working correctly and also the rewards being lower.

Seems like things are back to normal now!  just freaking out thinking it was me.  Happy Mining
