### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by bjax-22** [duino-coin/duino-coin#742]
**Describe the bug**
Received ToS violation email and all Duco vanished.
I recall the last thing I did was issuing bot command in discord to exchange bot coin to duco. and also upgrading to 2.6.
Not sure what went wrong that a permanent ban was served.

Mining still allowed on the account though. If the ban is permanent, shouldn't mining also be disabled? meaning AVR_Miner should not be able to receive job.
The Duco balance is increasing too after the ban, albeit very slowly

account: `bjax22`

**To Reproduce**
Discord message: [link](https://discord.com/channels/677615191793467402/678301439835111455/870982443665072138)
bjax22 — Yesterday at 6:53 PM
`!exchange 2000 bjax22`
Duino Stats
BOT
 — Yesterday at 6:53 PM
bjax22
Successfully exchanged 2000 coins to 20 DUCO and sent to bjax22
[View transaction in the explorer](https://explorer.duinocoin.com/?search=17ea3428eaf4e459fdf61dc0422e5a8853d6bd9a)

**Expected behavior**
20 Duco should appear in my account, but instead, the link shows some unrelated transaction?

Results for: 17ea3428eaf4e459fdf61dc0422e5a8853d6bd9a

 Type: transaction (DUCO-S1)
 Timestamp: 01/08/2021 04:49:11 (UTC)
 Sender: Wuddy268
 Recipient: Faucet_Furimos69420
 Amount: 5 DUCO (≈$0.0023)
 Message: Raffle_Funds

**Screenshots/photos**

**System (please complete the following information):**
 - OS: Raspbian
 - Software AVR Miner
 - Version 2.6

**Additional context**

**Comment by BastelPichi** [comment]
Try pinging a admin. They should be able to refund that. @Bilaboz can maybe explain that error, as he created duino-stats.
