### ISSUE TITLE
my account banned and my balance 

### ISSUE THREAD

**Issue by sajadkkkkkk** [duino-coin/duino-coin#744]
I recieved email Tos violation today , 200 duco gone.\

I think it is a rule to steal our duco.
please solve this problem.

user : sajadkk

**Comment by BastelPichi** [comment]
> I recieved email Tos violation today , 200 duco gone.\
> 
> I think it is a rule to steal our duco.
> please solve this problem.
> 
> user : sajadkk

hmmm @revoxhere should be able to help you, if this was a mistake.

**Comment by sajadkkkkkk** [comment]
Thanks for your reply,
revox told me that multiple accounts have banned my account .
I think it is not good idea to limit people accounts ,
if duco wants to increase price and users should be free about this matter
,
limiting the number of connections to 50 is very bad.

any transaction to another account seems by revox as multiple accounts ,
and allows himself to ban my balance.

\
thanks a lot;

**Comment by BastelPichi** [comment]
> limiting the number of connections to 50 is very bad.

No. We already got server issues, so limiting to 50 connections is just fair. And i also dont think you have 50 arduinos. Also, you can just use a sub-server, to bypass that limit.

**Comment by sajadkkkkkk** [comment]
Thanks a lot.

در تاریخ پنجشنبه ۵ اوت ۲۰۲۱،‏ ۲۲:۲۰ Robert Piotrowski <
***@***.***> نوشت:

**Comment by Yogi0104** [comment]
why is my account banned, I'm only mining with 1 esp32 and occasionally use a cellphone browser, what was my mistake..I log in every day, and staking. I'm disappointed, because there is no confirmation

**Comment by BastelPichi** [comment]
Wrong issue.

**Comment by BastelPichi** [comment]
> why is my account banned, I'm only mining with 1 esp32 and occasionally use a cellphone browser, what was my mistake..I log in every day, and staking. I'm disappointed, because there is no confirmation

Email DuinoCoin.

**Comment by Leonaldt** [comment]
Hi friends, My account has been blocked, but I didn't understand why, I've been a miner for almost two years, Can someone help me?

**Comment by BastelPichi** [comment]
Write an email to [duino.coin@gmail.com](mailto:duino.coin@gmail.com)

**Comment by Leonaldt** [comment]
thanks bro
