### ISSUE TITLE
No user found ..

### ISSUE THREAD

**Issue by vivaman2** [duino-coin/duino-coin#749]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**
------
![exp-00](https://user-images.githubusercontent.com/43667916/127813112-b8b4d64e-da34-4f24-bc79-c865ee985319.png)
![exp-03](https://user-images.githubusercontent.com/43667916/127813886-e4dada0d-7942-4d1b-a3c8-7cbda52a6a94.png)
![exp-02](https://user-images.githubusercontent.com/43667916/127813910-c9a741a5-ae4f-4460-b48d-23d00bfd951a.png)

What's happening? :(

**Comment by Traction6131** [comment]
Thats a bug many users have right now, just wait, they will fix it :)

**Comment by vivaman2** [comment]
> Thats a bug many users have right now, just wait, they will fix it :)
-----
Thank you for your quick reply.
Shall we continue mining? -Using Google Translator -

**Comment by Traction6131** [comment]
> > Thats a bug many users have right now, just wait, they will fix it :)
> -----
> Thank you for your quick reply.
> Shall we continue mining? -Using Google Translator -
> 

Right now, I would actually say, no since there are a lot of bugs and then you only waste power -not the mind of the coin - but I would defently have an eye on this great project, for faster annoucements, for example when mining is "fixed", you can also join their discord server:
https://discord.gg/ywweWMPQXw
Hope I could help!

**Comment by revoxhere** [comment]
~~Can you try now?~~ Something's wrong still

**Comment by revoxhere** [comment]
Should be fixed now.
