### ISSUE TITLE
Mining problem reported from Singapore and Norway

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#754]
It looks like the DUCO Main Server has the serious issue that causes no mining in the world, which reported by my friends from Singapore and Norway.

**Comment by marcoduinocoin** [comment]
![Uploading 16279970759747292923294233586031.jpg…]()

**Comment by marcoduinocoin** [comment]
![16279971267291831848069789914018](https://user-images.githubusercontent.com/88106006/128023100-d63c0dce-29b0-46e6-a668-943b649d4a20.jpg)

**Comment by marcoduinocoin** [comment]
![16279972447054308502540485396815](https://user-images.githubusercontent.com/88106006/128023476-da0346df-4a2a-411b-a184-586df0827f81.jpg)

**Comment by Traction6131** [comment]
Yeah, the duino-coin server is having some issues right now, but the devs are working hard to fix the problems and the load.

**Comment by marcoduinocoin** [comment]
> Yeah, the duino-coin server is having some issues right now, but the devs are working hard to fix the problems and the load.

I'm sorry to hear that. There has over 17000 members that mining day by day, the server is extremely overloaded. Damn, it's August now, that's the time for summer time!

**Comment by Traction6131** [comment]
> > Yeah, the duino-coin server is having some issues right now, but the devs are working hard to fix the problems and the load.
> 
> I'm sorry to hear that. There has over 17000 members that mining day by day, the server is extremely overloaded. Damn, it's August now, that's the time for summer time!

Yeah :D

**Comment by revoxhere** [comment]
I announced on discord an in the news section in the wallet that pulse pool is not working but I have no control over it and can't do anything

**Comment by marcoduinocoin** [comment]
Hi Revox! Just relax. This is the summer time now. Take your time! Relax.

**Comment by marcoduinocoin** [comment]
> > > Yeah, the duino-coin server is having some issues right now, but the devs are working hard to fix the problems and the load.
> > 
> > 
> > I'm sorry to hear that. There has over 17000 members that mining day by day, the server is extremely overloaded. Damn, it's August now, that's the time for summer time!
> 
> Yeah :D

The Duino-Coin is so popular in the world. This is a big challenge to Revox Master to take care the server system, that is not an easy job. So everyone kindly wait.

**Comment by Febriansyah1997** [comment]
Hi revox, good job for you,
Iam from indonesian

**Comment by marcoduinocoin** [comment]
> I announced on discord an in the news section in the wallet that pulse pool is not working but I have no control over it and can't do anything

Kindly take a break and enjoy the summer time with your family and friends. Don't worry about the Duino-Coin Main Server now. Because it takes a couple hours to fix the issues and rollback to fix the wallet problems. Enjoy the summer first please.

**Comment by vivaman2** [comment]
안녕하세요.
I'm from Korea.

**Comment by marcoduinocoin** [comment]
> 안녕하세요.
> I'm from Korea.

Annyonhaseyo! How are you?

**Comment by vivaman2** [comment]
Hi ..
It's hot here, too. It's summer.
I'm drinking a cold beer.
-sorry- Using Google Translator -

**Comment by marcoduinocoin** [comment]
It looks like the PC-Miner and the AVR Miner can start mining now. And the ESP Miner won't start to mine due to the miner can't find the Duino-Coin Server, which reported by friends in the past 30 minutes.

**Comment by marcoduinocoin** [comment]
It looks like the DUINO-COIN Server is very healthy now.
Congratulations! Enjoy the summer time! Cheers!

**Comment by Shreyas-Dev-ITB** [comment]
Yes it seems healthy and very powerful now thankx for all the developers who paid money 💰 for the node to work 😘😘😘😘😘😘

**Comment by marcoduinocoin** [comment]
Let's enjoy the Duino-Coin mining!
