### ISSUE TITLE
Can't mine and login to Web Wallet

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#761]
All kinds of miners can't mining, also the Web Wallet can't login. Is the DUCO Main Server overloading?

**Comment by primitt** [comment]
I'm updating the main VPS to debian 11 so the earnings will not be credited until the process is finished, mining will still work and pool will smartly sync the rewards later. This will take up to 20 minutes
Update: it may take a bit longer

-Revox (on the discord)

**Comment by marcoduinocoin** [comment]
> I'm updating the main VPS to debian 11 so the earnings will not be credited until the process is finished, mining will still work and pool will smartly sync the rewards later. This will take up to 20 minutes
> Update: it may take a bit longer
> 
> -Revox (on the discord)

Thanks Primitt. The ESP Miners can not mining. Any idea?

**Comment by primitt** [comment]
Idk, try again when the main server is online

**Comment by marcoduinocoin** [comment]
> Idk, try again when the main server is online

Thanks Primitt.

**Comment by primitt** [comment]
yw, but i do recommend you join the discord

**Comment by marcoduinocoin** [comment]
> yw, but i do recommend you join the discord

Thanks, I will.
