### ISSUE TITLE
The Duino-Coin Dashboard can't access and check the user balance

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#762]
The Duino-Coin Dashboard also can't access and view the user balance.

**Comment by noobflix** [comment]
Servidor caiu

**Comment by noobflix** [comment]
look at my content I'm bringing a system of mine along with yours to mine with Android mobile and now Ios. I want to help the community with that.

**Comment by primitt** [comment]
Your making a IOS miner?

**Comment by noobflix** [comment]
yes I'm creating a mined for IOS. WHEN I ALREADY DO IT ON ANDROID

**Comment by marcoduinocoin** [comment]
> yes I'm creating a mined for IOS. WHEN I ALREADY DO IT ON ANDROID

This is amazing to mine on iPhones! Hope the iOS Miner development will be succeeded! Cheers.
