### ISSUE TITLE
mining err: 'NoneType' object has no attribute 'set_title'

### ISSUE THREAD

**Issue by HeniuGG** [duino-coin/duino-coin#768]
I run in the background on raspbery pi3 PC_Miner.py
I have this message from the logo:

12:28:13 Xxhash is not installed - Xxhash support will be disabled
] 0; Duino-Coin Python Miner (v2.6)
 ‖ Official Duino-Coin Excavator © ️ (v2.6) 2019-2021
 ‖ Https://github.com/revoxhere/duino-coin
 ‖ Polish translation: revox
 ‖ CPU: 4x ARMv7 Processor rev 4 (v7l)
 ‖ Level of grant for developers: 1
 ‖ Algorithm: DUCO-S1: gear: Low difficulty
 ‖ Excavator ID: Duino-Blynk
 ‖ Have a nice noon, HeniuGG!

12:28:19 net0 Finding the fastest server ...
12:28:20 net0 Retrieved mining node: pulse-pool-1
12:28:20 sys3 Excavator thread # 3 is started using DUCO-S1 algorithm and 95% intensity
12:28:20 sys1 Excavator thread # 1 is started using DUCO-S1 algorithm and 95% intensity
12:28:20 sys2 Excavator thread # 2 is started using DUCO-S1 algorithm and 95% intensity
12:28:25 net0 MOTD: Welcome to the first Duino-Coin pool!
        Pool worker limit: 64
12:28:25 net0 Connected to the main Duino-Coin server (v2.6, node: 149.91.88.18:6000)
12:28:25 sys0 Excavator thread # 0 is started using DUCO-S1 algorithm and 95% intensity
12:28:28 net2 Error while digging - probably connection problem - retry in 5s. (mining err: 'NoneType' object has no attribute 'set_title')
12:28:29 net1 Error while digging - probably connection problem - retry in 5s. (mining err: 'NoneType' object has no attribute 'set_title')
12:28:31 net0 Error while digging - probably connection problem - retry in 5s. (mining err: 'NoneType' object has no attribute 'set_title')

**Comment by naphob** [comment]
if you want it to work again just comment on all the lines that call title() function. The code will break if you run it in the background. There is no code detection running in the background yet. 

You may consider running it with nohup instead 
`nohup python3 PC_Miner.py &`
