### ISSUE TITLE
ESP8266 stopped working after almost wk of mining Also PC miner experiencing some errors

### ISSUE THREAD

**Issue by Turaak** [duino-coin/duino-coin#771]
Error connecting to mining node: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond, retrying in 5s

**Comment by jonnycn** [comment]
> Error connecting to mining node: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond, retrying in 5s

server down~!

**Comment by johnlrhodes757** [comment]
tried to connect to all my hardware (ESP, AVR, and CPU) nothing is mining at all.  Coming up with same node code

**Comment by BastelPichi** [comment]
The pulse pool is currently down. Theyre working on fixing that. As the main server is not made to take PC Miners, you will probably get errors. Bila should fix the pool in the next days.

**Comment by Bernoli0215** [comment]
> The pulse pool is currently down. Theyre working on fixing that. As the main server is not made to take PC Miners, you will probably get errors. Bila should fix the pool in the next days.

There! Thanks for the info buddy! I thought my ESPs were broken for non stop mining w/o fan LOL. Anyways, thanks again.

**Comment by revoxhere** [comment]
Should be working now
