### ISSUE TITLE
setup new server

### ISSUE THREAD

**Issue by fellboy42** [duino-coin/duino-coin#773]
is it possible  i can help to setup a new server for duino-coin for this projects on my server

**Comment by jonnycn** [comment]
> is it possible i can help to setup a new server for duino-coin for this projects on my server

Previously, there was a nods file for testing, using more people's computers as node servers. This function is not supported yet, which may cause more congestion in the main service, I think

**Comment by BastelPichi** [comment]
The pulse pool is currently down. Theyre working on fixing that. As the main server is not made to take PC Miners, you will probably get errors. Bilaboz should fix the pool in the next days. Also, public nodes arent ready yet. If the pulse pool is back up, it will just work back fine.

**Comment by revoxhere** [comment]
We will ask some people to host nodes in the future, for now we're good
