### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by brottobhmg** [duino-coin/duino-coin#777]
With last update the ESP32 code don't be able to connect to the server (both CORE)
Only for me ?

**Comment by marcoduinocoin** [comment]
Same. No connections between the ESP and DUCO Server. Maybe the DUCO Server down.

**Comment by panayotovip** [comment]
Same here, CPU miner working normal, ARV no connection.

**Comment by marcoduinocoin** [comment]
Well. Just keep the devices on and kindly wait for the Developer Team to solve the issue.

**Comment by johnlrhodes757** [comment]
Ohhh okay, cool.  Was unsure what was going on and this definitely cleared the air for me.  Thank you so much!!!

**Comment by SForney54** [comment]
Look like I'm not only one who has the connection errors after upgraded to 2.6 on AVR mining with Raspberry Pi as host.
