### ISSUE TITLE
miner don't connect to server 

### ISSUE THREAD

**Issue by liubergarcia** [duino-coin/duino-coin#778]
**Describe the bug**  miner say error connecting to server

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by johnlrhodes757** [comment]
My miner has been like this for a few days.  I did take a screen shot of the miners for you and here they are.
OS: Windows
Software: AVR Miner & Python Miner
Version: 2.6

![image](https://user-images.githubusercontent.com/61529998/128776222-0c4bb241-e39e-4791-842b-d6691118aa40.png)

**Comment by liubergarcia** [comment]
Yes like my we have the same problem

**Comment by gsrbr** [comment]
Hello, 
Some parts of Duino Coin like pulse pool are with some problems. 
I think you can try to downgrade temporarily your AVR miner to 2.57 to continue to mining, this work for me
![image](https://user-images.githubusercontent.com/27559775/128783975-bc5a58ef-2c78-43a5-8c5c-a7190a8680a7.png)

**Comment by liubergarcia** [comment]
Thanks it works for arduino one board .

**Comment by noobflix** [comment]
Eo PC MINER está com erro

**Comment by johnlrhodes757** [comment]
I just tried to do that but it definitely ain't working for me,  I will let time sort things out.  Thanks for turning me onto a temp fix.  wish it worked for me...

**Comment by noobflix** [comment]
BOM ESTOU USANDO O UBUNTU MINIMAL PARA RESOLVER ALGUNS ERROS

**Comment by BastelPichi** [comment]
The pulse pool is currently down. Theyre working on fixing that. As the main server is not made to take PC Miners, you will probably get errors. Bila should fix the pool in the next days.

**Comment by marcoduinocoin** [comment]
Same. The ESP8266 and ESP32 Miners can't connect to the Duino-Coin Server in this few days. The PC Miner and Web Miner also ain't work. I don't have the AVR boards so don't know if the AVR Miner might working very well at the moment.

**Comment by mxuser** [comment]
remove the duino-coin directory, re-download it from git and configure the rig again.
it worked for me.

**Comment by marcoduinocoin** [comment]
Thanks. I've already downloaded the latest version 2.6 and unzipped, then updated the ESP8266_Code onto my ESP8266 board, but it looks like can't connect to the Duino-Coin Server.

**Comment by marcoduinocoin** [comment]
By the way, do you know how to transfer the MAGI XMG to the Binance Account? I hope to try to exchange the DUCO to XMG. I never tried to exchange any types of Crypto before.

**Comment by naphob** [comment]
> Thanks. I've already downloaded the latest version 2.6 and unzipped, then updated the ESP8266_Code onto my ESP8266 board, but it looks like can't connect to the Duino-Coin Server.

change the port to 2811

**Comment by marcoduinocoin** [comment]
It's worked. Thank you so much.

**Comment by BastelPichi** [comment]
> > Thanks. I've already downloaded the latest version 2.6 and unzipped, then updated the ESP8266_Code onto my ESP8266 board, but it looks like can't connect to the Duino-Coin Server.
> 
> change the port to 2811

wtf

**Comment by BastelPichi** [comment]
![grafik](https://user-images.githubusercontent.com/63782569/129051273-c6efaa34-c2ef-4104-8605-f0aab3def3f8.png)
2811 is not for mining
