### ISSUE TITLE
Unable to login to Node-S for exchange

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#780]
1. Go to Node-S
2. Click on Duino-Coin Account Login
3. Scroll down to Login
Application Error

Unable to login to Node-S for DUCO-USD exchange.

**Comment by marcoduinocoin** [comment]
![Screenshot_20210811-013613_Samsung Internet](https://user-images.githubusercontent.com/88106006/128907936-9254ca4e-7775-4683-a952-2a9a6d575681.jpg)

**Comment by primitt** [comment]
Node-S is currently closed

**Comment by marcoduinocoin** [comment]
Thanks Primitt. Will Node-S available again?

**Comment by revoxhere** [comment]
This issue is not related with Duino-Coin directly. Closing
