### ISSUE TITLE
cant connect to servers on miner for esp32 and esp8266

### ISSUE THREAD

**Issue by Suhartati** [duino-coin/duino-coin#782]
cant connect to servers on miner for esp32 and esp8266

**Comment by marcoduinocoin** [comment]
Kindly open the ESP8266_Code with Arduino IDE,
then change the server port from 2820 to 2811,
(the other server ip with port 6000 is not working at the moment, kindly change the server ip as remarked inside the ESP8266_Code).
Finally update the code onto your ESP8266 board via the USB cable or OTA wirelessly.
You will find that the board can be connect to the DUSO-1 Server and starts mining.

You can check the status, just click the Serial Monitor on the Tools menu inside the Arduino IDE software.

Cheers.

**Comment by pankleks** [comment]
this does not work too -> Connection reset by peer

**Comment by gsrbr** [comment]
Hello,
Try to mining now, because the pulsepool(149.91.88.18) mining issue has been fixed with help from bilaboz and revox
For use the pulsepool use this config with the last realease of the esp8266 and esp32 code:
```
const char * host = "149.91.88.18"; // Static server IP
const int port = 6000; 
```

**Comment by marcoduinocoin** [comment]
> this does not work too -> Connection reset by peer

Kindly try to change the pulse server address and port as Gsrbr mentioned on this page.
