### ISSUE TITLE
Mining but no DUCO earned

### ISSUE THREAD

**Issue by johnlrhodes757** [duino-coin/duino-coin#786]
Thanks for fixing the mining fix for the AVR, PC, and ESP miner.  I finally got them up.  There does seem to look like there is one more issue.  Been mining for the past few hours now and the balance for DUCO has not moved at all.  Not sure what I would call it but I am guessing rewards are not being issued out to miners.

**Comment by thienduongtungtang** [comment]
### I have the same problem as you, I bet everyone does too ###

**Comment by marcoduinocoin** [comment]
Same.

**Comment by marcoduinocoin** [comment]
The users are too much to mining at the same time that might causes the Duino-Coin Main Server overloading and down. Maybe that's the main reason causes all types of miners can't reach the server for mining, even not able to login to the Web Wallet and check the user balance on the Exchange Page.

**Comment by revoxhere** [comment]
Is the issue fixed now?

**Comment by thienduongtungtang** [comment]
> Sự cố hiện đã được khắc phục chưa?
not yet
