### ISSUE TITLE
Main site seems to be down

### ISSUE THREAD

**Issue by TimyIsCool** [duino-coin/duino-coin#793]
![image](https://user-images.githubusercontent.com/74112751/129189823-d4df23c9-daa1-45d1-a00a-42a55bc85524.png)

**Comment by revoxhere** [comment]
@Tech1k needs to check as he's hosting it

**Comment by TimyIsCool** [comment]
> @Tech1k needs to check as he's hosting it

alr

**Comment by Tech1k** [comment]
@TimyIsCool we are currently under a massive DDoS attack and I was asleep until now. I'm currently investigating this issue.

**Comment by Tech1k** [comment]
I'm going to keep this issue opened for the time being to keep others updated here on GitHub.

**Comment by TimyIsCool** [comment]
okay

**Comment by revoxhere** [comment]
Should be fixed
