### ISSUE TITLE
DUCO Pulse Pool Server overloading

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#794]
The ESP and AVR Miners can connect to the DUSO Server, but the mining speed is extremely slow than normal. 

The Kolka pulse server ip 149.91.88.18 port 6000 can be connected but mining extremely slow.
Master server ip 51.15.127.80 port 2820 cannot be connected.

**Comment by revoxhere** [comment]
Fixed by launching a second pool instance
