### ISSUE TITLE
  File "<ipython-input-26-fb1c27c0aadc>", line 5     get_ipython().system(' python3 PC_Miner.py')     ^ IndentationError: unexpected indent

### ISSUE THREAD

**Issue by TimyIsCool** [duino-coin/duino-coin#795]
Im getting a 
  File "<ipython-input-26-fb1c27c0aadc>", line 5
    get_ipython().system(' python3 PC_Miner.py')
    ^
IndentationError: unexpected indent
when i try to run the PC_Miner.py

**Comment by revoxhere** [comment]
Please stick to the issue template, you haven't provided any info, we don't know what OS is this and where are you trying to run it

**Comment by TimyIsCool** [comment]
> Please stick to the issue template, you haven't provided any info, we don't know what OS is this and where are you trying to run it

it was on google colab (a free thing) so i dont know the os and stuff and it was the latest version of the miner

**Comment by revoxhere** [comment]
Mining on VPS services is not allowed and may lead to your account being banned. Closing
