### ISSUE TITLE
Keep mining but can't earning the Duino-Coins

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#797]
Don't know may be the server is down? Anyone can help?
![Screenshot_20210812-210921_Samsung Internet](https://user-images.githubusercontent.com/88106006/129202746-4b7a40f5-9a98-4d0b-894e-37731cfd18fb.jpg)

**Comment by BastelPichi** [comment]
Is the username really right? And are there any errors in the miner?

**Comment by johnlrhodes757** [comment]
Just checked.  Seems like the API server is down.  Can’t reach it

**Comment by marcoduinocoin** [comment]
I entered the right username. The server is not stable and can't mine or enter to the Web Wallet at the moment.
My ESP boards are keeping turning on the blue lights and off frequently. Also the AVR Miner is down.

**Comment by marcoduinocoin** [comment]
Still not fixed.

**Comment by primitt** [comment]
> Still not fixed.

I think it will be credited in the morning, all the mined funds should be here, but i think it is crediting but the main server is not giving the webserver info http://149.91.88.18:6001/rewards

**Comment by marcoduinocoin** [comment]
thanks bro
