### ISSUE TITLE
lost duco in transaction to bscDUCO(very important)

### ISSUE THREAD

**Issue by sajadkkkkkk** [duino-coin/duino-coin#798]
hello dear revox,

I sent some duco to bscDUCO according to the your instruction , i has done this before successfully,

but at this time, 
 i filled message textbox from my web wallet with my current bscWallet address
after sending the ducos , i never recieved them in my bscwallent ,
i see the transaction with shorted wallet address in transaction list ,

my full wallet address isvv 0x1D671754b9ccC8A33b48612db973EBe7904Dc90C
but in transaction list it is  0x1D671754b9ccC8A33b48612db973

i thinks there is bug in transaction,please fix my problem and send me those ducos,

user: javadkk
https://explorer.duinocoin.com/?search=5a9bc05a7ad027b581d866ff28c0a684792d0c15
https://explorer.duinocoin.com/?search=bcbe0cb073dd7e37
https://explorer.duinocoin.com/?search=c03165a4261d1829
https://explorer.duinocoin.com/?search=28972c7def79c09c9d79319583a7cde87e596bde
https://explorer.duinocoin.com/?search=c0d56eb7d1421a5d
https://explorer.duinocoin.com/?search=4d06c651387ca2c5

**Comment by Mariusz696** [comment]
I have the same problem

in transaction list: 0x557D5b0F3d46722273a1A667E0e0
my address: 0x557D5b0F3d46722273a1A667E0e002a90BA631Eb

https://explorer.duinocoin.com/?search=e3fdf87ba397effe27e7aae90e0d54006d1ab62c

**Comment by primitt** [comment]
THE BOT IS CURRENTLY DOWN!! PLEASE DONT DO ANY TRASACTIONS WITH BSCDUCO! ONCE YANIS COMES BACK FROM HIS TRIP, HE WILL FIX THE BOT AND WILL "MASS TX". YOU WILL ALL GET YOUR BSCDUCO WHEN THE BOT COMES BACK ONLINE BUT I WOULD NOT TRY TO SEND MORE!

Thank you.

**Comment by Mariusz696** [comment]
So maybe write about it on the page somewhere where it is easily visible :D

**Comment by sajadkkkkkk** [comment]
now transaction is OK,
thanks a lot .

**Comment by sksns160786** [comment]
lost my 500duco to bscDUCO still not received. how to get?
https://explorer.duinocoin.com/?search=cf159981e6f83adf66dfc47a8234588782fbc4bb
please solve this problem.
![duinocoin 1](https://user-images.githubusercontent.com/95843154/155851699-d0d3e08b-2b16-45b3-8062-45ecdd33ef87.png)
![duinocoin 2](https://user-images.githubusercontent.com/95843154/155851712-30350a49-f865-4091-8ac1-cdb05ce2a225.png)

**Comment by LDarki** [comment]
Hi, please don't write in closed issues.

There is a fee of 500 DUCOS in order to use this wrapper.
So you don't receive anything from that wrap.

I'll send you those 500 ducos.

**Comment by sajadkkkkkk** [comment]
thanks alot
i dont need that , thanks
