### ISSUE TITLE
Sub-zero pool workers count

### ISSUE THREAD

**Issue by YetAnotherRussian** [duino-coin/duino-coin#8]
https://revoxhere.github.io/duco-statistics/

Pool workers: -217

That's not expected :D

**Comment by revoxhere** [comment]
Yeah 😄

**Comment by revoxhere** [comment]
Fixed in [b618463ba879a8e6b1238ec539abf974419ae8c4](https://github.com/revoxhere/duino-coin/commit/b618463ba879a8e6b1238ec539abf974419ae8c4). Will update the server/pool in a few minutes and negative counter shouldn't happen anymore. Thanks for submitting bug report.
