### ISSUE TITLE
Hi Revox! How are you?

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#802]
Hi Revox. How are you? Sorry to hear that the Duino-Coin Server was attacked by hackers for many times, really upset to hear that.
Besides, I found that my miners are keep mining but the can not earning any coins. Are you trying to fix the server? How can I change the setting for my miners to mine the DuCO correctly. Thank you.

**Comment by KingUndeadCodes** [comment]
Try updating the miner. 
If you wan't to ask Revox a personol question maybe do it on discord. 
Don't be very annoying thoe :)

**Comment by primitt** [comment]
> Hi Revox. How are you? Sorry to hear that the Duino-Coin Server was attacked by hackers for many times, really upset to hear that.
> 
> Besides, I found that my miners are keep mining but the can not earning any coins. Are you trying to fix the server? How can I change the setting for my miners to mine the DuCO correctly. Thank you.

I really do recommend you to come talk on the discord server as a lot more stuff happens there, idk why you talk so much in the github issues XD

**Comment by KingUndeadCodes** [comment]
> I really do recommend you to come talk on the discord server as a lot more stuff happens there, idk why you talk so much in the github issues XD

Same... GitHub issues are for discussing improvments, new features and questions people have that cant be awnsered for some reason on discord (I guess).

**Comment by marcoduinocoin** [comment]
yep, you're right. I already signed up on discord. thank you.
