### ISSUE TITLE
Error :|

### ISSUE THREAD

**Issue by romanmajorov** [duino-coin/duino-coin#804]
The miner does not work :(

Traceback (most recent call last):
  File "pc_miner.py", line 1350, in <module>
    loadConfig()
  File "pc_miner.py", line 420, in loadConfig
    print(
  File "C:\Users\Server\AppData\Local\Programs\Python\Python3
ges\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\Server\AppData\Local\Programs\Python\Python3
ges\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\Server\AppData\Local\Programs\Python\Python3
ges\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\Server\AppData\Local\Programs\Python\Python3
ges\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
PermissionError:

**Comment by gsrbr** [comment]
Hello, ~i've never see this erros~, can you tell me somethings for help me to undertand this
1. Are you using pc_miner.py on v2.6?
2. What version of colorama are you using? You can see this with the command `pip list`
3. What system(OS) and version are you using?
4. What your python version.


Edit: have [another issue](https://github.com/revoxhere/duino-coin/issues/770) with this same error, you can read

**Comment by romanmajorov** [comment]
1 - +
2 - 0.4.4
3 - Windows 7 
4 - 3.8.10

**Comment by revoxhere** [comment]
Are you running from the source or are you using the precompiled exe?

**Comment by romanmajorov** [comment]
source

**Comment by romanmajorov** [comment]
source code

**Comment by romanmajorov** [comment]
Heeeeelp.... :(

**Comment by gsrbr** [comment]
Forgive me the delay, I'm running a virtual machine here to try to find a plausible solution

**Comment by romanmajorov** [comment]
So what?

**Comment by gsrbr** [comment]
Hello, 
I just rewrite the latest version of the miner to not use special characters, it worked perfectly on my virtual machine, could you please test it?
[Link to download the Simple miner](https://github.com/gsrbr/somecodes/tree/main/duinocoin/simple)
![image](https://user-images.githubusercontent.com/27559775/129992308-bba20bb8-6f35-46f0-9e1f-6f2d1b5e995e.png)
_Visually is far from good, but it is functional, and the errors were intentionally generated in this screenshot to ensure there were no surprise characters_
This was the best alternative I found, as the others required a lot of changes to the machine...

**Comment by romanmajorov** [comment]
Everything works, thank you <3

**Comment by Tech1k** [comment]
> Everything works, thank you <3

Glad everything is working, please let us know if you encounter any other issues, thanks!

**Comment by romanmajorov** [comment]
Hi, there's some mistake again...
![image](https://user-images.githubusercontent.com/57148482/131232620-0834a92d-2cff-428f-81eb-12f32db0594b.png)
