### ISSUE TITLE
ESP32_Code.ino => esp32/sha.h is deprecated, please use sha_parallel_engine.h instead

### ISSUE THREAD

**Issue by GMGassner** [duino-coin/duino-coin#809]
Thank you for your great project! I stumbled uppon a tiny error in the ESP32_Code.ino which can be resolved in less than a minute.

**Describe the bug**
According to [ESP-IDF](https://github.com/espressif/esp-idf/blob/master/components/mbedtls/port/include/esp32/sha.h) the sha.h library is deprecated and is replaced by sha_parallel_engine.h.

The correct line in code shoule therefore be:
`#include "sha/sha_parallel_engine.h" // Include hardware accelerated hashing library`

**To Reproduce**
1. Compile ESP32-Code.ino
2. Warning in the Console
3. Check documentation

Keep up you great Work!

**Comment by revoxhere** [comment]
Thanks for noticing, corrected!
