### ISSUE TITLE
Wallet website registration error

### ISSUE THREAD

**Issue by Kocarik** [duino-coin/duino-coin#810]
Hello,

Please see screenshot.
![Screenshot 2021-08-15 165955](https://user-images.githubusercontent.com/15687687/129483086-e24e74e7-2613-4b22-9cf4-4e0cf0f375b4.png)

**Comment by revoxhere** [comment]
Hello, please just try again

**Comment by Kocarik** [comment]
@revoxhere please try you now with some test email address. Allready I have registred account.

**Comment by Tech1k** [comment]
@Kocarik, please try again and if possible, join our Discord server (link on the website) if you have further issues registering with your email address. Thank you and let me know if it works now!

**Comment by Kocarik** [comment]
@Tech1k & @revoxhere working Fine. But performance after registration is very very low. I must wait 20 sec for creating account and another 20 sec waiting for loggining.

**Comment by Kocarik** [comment]
Working Fine. But **performance after registration is very very low**. I must wait **20 sec for creating account** and **another 20 sec waiting for loggining.**

**Comment by Tech1k** [comment]
> Working Fine. But **performance after registration is very very low**. I must wait **20 sec for creating account** and **another 20 sec waiting for loggining.**

Reopened the issue to reference this comment.

We will take this into consideration and add performance improvements to our task list! Do keep in mind most of the latency is caused from the API, not the wallet site itself!

**Comment by revoxhere** [comment]
This will be fixed as soon as there will be less load on the master server that's coming from pulsepool
