### ISSUE TITLE
Ip blocked

### ISSUE THREAD

**Issue by Soutak1984** [duino-coin/duino-coin#812]
I was mining with one esp32 from last 4 days. Today when i wat to login my web wallet, it says "wallet api not accessible". And my esp32 shows duino coin server login error. But when I try to connect with other public ip(using my 4g connection) it all works perfectly. 
Please solve my issues. My user name is " soutak", and my public ip 223.223.141.78(which is not working).

**Comment by Soutak1984** [comment]
![Uploading Screenshot_2021-08-16-23-34-50-425_com.android.chrome.jpg…]()

**Comment by sajadkkkkkk** [comment]
i had same problem , connection to the server by using adsl connection doesnt work but when i connect to hotspot connection of my mobile ,this problem doesnt appear,
mining with the pool server works perfectly,

**Comment by Soutak1984** [comment]
Problem solved... Thanx for quick response by admin.. 
Revox(founder) on discord.
