### ISSUE TITLE
About 0.5 duco per day for 1 avrMiner.

### ISSUE THREAD

**Issue by sajadkkkkkk** [duino-coin/duino-coin#818]
hello

I started mining using 1 avrMiner and it can give me only 0.5 duco per day , i think if this rate and duco per rate continue , many of users leave the duino , 

It is better to stop kolka system to increase mining duco and users.

![Untitled](https://user-images.githubusercontent.com/87924032/129689940-af745aa8-2414-4133-8c54-37ad06a97370.png)
 
please solve this problem.

**Comment by Tech1k** [comment]
The Kolka system is in place to help make Duinocoin mineable by anyone and almost anything. Remember, Duinocoin isn't a crypto like Bitcoin, instead, it's supposed to be a project for users new and old in the crypto space to learn more about how cryptocurrencies work without great financial risk. Duinocoin isn't a project to make money on in that sense. Hope this clears things up and let me know if you have anymore questions or comments!

**Comment by sajadkkkkkk** [comment]
thanks for your reply,
I understand the purpose of  duinoCoin project but when i started mining at about 1 months ago, for each avr miner 8 duco/day was in available , but at this time ,....

Anyway , duino coin can easily act like other cryto , we know there are 5000 crypto in the world , adding duco to them can make duco profitable. 

best regards

**Comment by Tech1k** [comment]
Duinocoin can be like another crypto and it kind of is (in regards to wDUCO and bscDUCO), but the main coin at this time isn't like any other crypto per-say (that is what makes the project unique). Thank you for your input and I'm going to close this issue as it seems like your question has been answered!
