### ISSUE TITLE
ESP32 not working

### ISSUE THREAD

**Issue by RonSchLabs** [duino-coin/duino-coin#819]
Hello. The ESP32 have stopped working since yesterday. Is there a new code for that too? There is a new one for the ESP8266.
I still use the ESP32 with version 2.55.
THANK YOU

**Comment by Tech1k** [comment]
Are you using Pulsepool? Also, the pool server has been experiencing significant downtime lately, please try reconnecting the miner and let me know if it works, thanks!

**Comment by RonSchLabs** [comment]
I don't know if the "Pulsepool" is ??? I only ever install the code directly from Gibthub. How can you see that ??? Sorry

**Comment by Tech1k** [comment]
@RonSchRonSch I just realized, you're using an outdated version (2.55), please upgrade to the latest released version (2.6.1), here: https://github.com/revoxhere/duino-coin/releases/tag/2.6.1

**Comment by Tech1k** [comment]
> I don't know if the "Pulsepool" is ??? I only ever install the code directly from Gibthub. How can you see that ??? Sorry

Please reference my other comment and let me know if it fixes your issue!

**Comment by RonSchLabs** [comment]
Thanks for the link. I don't understand something. Version 2.6.1 is under your LINK. But the ESP32 code says version 2.55. Is that right?

**Comment by revoxhere** [comment]
Tech1k kinda mislead you, cause while 2.6.1 is the latest release, ESP32 code hasn't been updated since 2.5.5. I will prepare a new release for ESP32s soon with the pool fetching similar to ESP8266s.

**Comment by Tech1k** [comment]
My apologies @RonSchRonSch, I'll let @revoxhere take this issue over, but I'll be here if you need anything related to the websites or other services!

**Comment by RonSchLabs** [comment]
Now I understand it. Many Thanks

**Comment by Tech1k** [comment]
Seems like this issue has been resolved, I'm going to close it for now, but feel free to comment if any other problems arise!

**Comment by RonSchLabs** [comment]
I would like to say "GOOD JOB AND PLEASE GO ON!"
