### ISSUE TITLE
Pool disabled - AVR Miner then breaks

### ISSUE THREAD

**Issue by nigeljohnson73** [duino-coin/duino-coin#821]
**Describe the bug**
Not sure it's specific to the StarPool

When starting the AVR Miner it connected to the pool and then attempted to download a job. It looks like it didn't get one (in this case because the node is disabled??) but there is still an attempt to send this non-existent job off to the AVRs which result in a failure that isn't trapped correctly. There is no indication that the process restarts after the 10 seconds it said it was going to wait, and kicks out error messages every second in the mean time.

The error I am getting is here:

10:39:50  net0  Searching for the fastest node to connect to...
10:39:50  net0  Connected to master Duino-Coin server (v2.6)
10:39:50  sys1  AVR mining thread is starting using DUCO-S1A algorithm (/dev/ttyUSB1)
10:39:50  net0  MOTD: ★ You are mining on the StarPool, have fun!
		Pool worker limit: 150
10:39:50  sys0  AVR mining thread is starting using DUCO-S1A algorithm (/dev/ttyUSB0)
10:39:50  usb1  Node message: AVR mining is disabled for pools.
10:39:50  usb0  Node message: AVR mining is disabled for pools.
10:39:53  usb1  Error connecting to the AVR! Retrying in 10s (error reading result from the board: local variable 'result' referenced before assignment, please check connection and port setting)
10:39:53  usb0  Error connecting to the AVR! Retrying in 10s (error reading result from the board: local variable 'result' referenced before assignment, please check connection and port setting)
10:39:54  usb1  Error connecting to the AVR! Retrying in 10s (error reading result from the board: local variable 'result' referenced before assignment, please check connection and port setting)

**To Reproduce**
Start the AVR miner. the pool it chooses is up to it.

**Expected behavior**
Not to continually loop throwing this error and attempt a reconnect in 10 seconds... or, better still to try the next pool in the list because no job was received.

**Screenshots/photos**
Error trapped above

**System (please complete the following information):**
RAspbian running with 2 Arduino nano clones that have worked well today.

**Additional context**
While there is an outage currently, this issue is more around the error handling issue it presents. A failure to detect the non-connectedness and try the next server to see if it is better.

**Comment by revoxhere** [comment]
This isn't probably related to the starpool, I'll try to clean-up the PC and AVR miner codes soon and check what may be causing it

**Comment by BastelPichi** [comment]
This should be fixed now.
