### ISSUE TITLE
"sha / sha_parallel_engine.h" error message

### ISSUE THREAD

**Issue by RonSchLabs** [duino-coin/duino-coin#824]
Hello. I ask for help again. I want to install the new ESP32 code (version 2.6.3). Unfortunately I always get the following error message: "sha / sha_parallel_engine.h: No such file or directory".
I can't find this library anywhere. Do you have a LINK for that? Thanks so much!!!

**Comment by revoxhere** [comment]
Looks like you're using an older version of the ESP32 code, in that case you can change the import from this:
`#include "sha/sha_parallel_engine.h"`
to this:
`#include "esp32/sha.h"`
or this:
`#include "hwcrypto/sha.h"`

**Comment by RonSchLabs** [comment]
THANK YOU. It worked with this code: #include "hwcrypto / sha.h"
But only this one. I don't quite understand what the difference between the 3 variants is. I use this library for my ESP32: https://dl.espressif.com/dl/package_esp32_index.json
Is this then "out of date"? Since there is no "sha_parallel_engine.h" in it. Thank you very much for your effort. AND please keep it up !!!!!!!!!!!

**Comment by revoxhere** [comment]
I'm not sure what's the exact difference as I haven't looked much into these libraries but it all depends on the ESP32 Core version. 
They probably organized some files and made some optimizations during the releases, thus the difference. 

The newest version for ESP32 Core (2.0.0) can be found here: `https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json`

**Comment by Tech1k** [comment]
@RonSchRonSch please let me know if Revox's answer solved your issue! Thanks!

**Comment by RonSchLabs** [comment]
Hello. Thanks for the answer. I integrated the new library. Unfortunately, you can only #include "hwcrypto/sha.h". The other two #include "esp32/sha.h" and #include "sha/sha_parallel_engine.h" are not recognized.
Greetings RonSch

**Comment by RonSchLabs** [comment]
One more question: can I merge all accounts now? Is there no longer a worker limit? When I started an AVR miner I read that there is a worker limit of 150. Is that correct or is there none left? THANK YOU

**Comment by Tech1k** [comment]
> Hello. Thanks for the answer. I integrated the new library. Unfortunately, you can only #include "hwcrypto/sha.h". The other two #include "esp32/sha.h" and #include "sha/sha_parallel_engine.h" are not recognized.
> Greetings RonSch

If one imported, the code should hopefully work!

**Comment by Tech1k** [comment]
> One more question: can I merge all accounts now? Is there no longer a worker limit? When I started an AVR miner I read that there is a worker limit of 150. Is that correct or is there none left? THANK YOU

There is still a worker limit and yes, 150 is the current worker limit! Please let me know if you have any other questions or problems, until then, I'm going to close this issue, but feel free to re-open it if needed!
