### ISSUE TITLE
wallet duinocoin

### ISSUE THREAD

**Issue by Naveen823** [duino-coin/duino-coin#825]
https://wallet.duinocoin.com/
Not working properly i have 30 miners working and wallet show only 6 or 8 pzzz fix i am very irited of this issue

**Comment by scribas78** [comment]
A similar thing happens to me too, the wallet does not read my miners correctly. I use arduino uno and nano

**Comment by SForney54** [comment]
I am on same boat as you guys, wallet doesn't read any of my UNOs and NANOs but Raspberry PIs... 

If must know what's version: I'm mining with AVR 2.6 version

**Comment by scribas78** [comment]
he's setting it all up to make esp32 etc go better, but that's how he messes up the arduinos

**Comment by BastelPichi** [comment]
If youre miners arent shown in  the wallet, theres either a api error(very unlikely) or your miners arent really mining. So check the serial monitors of them. Also, they will only get listed if they do at least 5 accepted shares, so if they restart to often, that may be the problem.

**Comment by scribas78** [comment]
![DUINO WALLET](https://user-images.githubusercontent.com/89088790/129942832-3beca68f-04ef-4bcf-8cff-f20155845aa3.png)
new problem with the wallet, see the picture

**Comment by scribas78** [comment]
![DUINO WALLET](https://user-images.githubusercontent.com/89088790/129943060-b8fb4aec-91fb-4b2a-9e3d-4327f505532e.png)
new problem with the wallet, when I try to log in.
in these days of testing and renewals it is a continuous one

**Comment by Tech1k** [comment]
@scribas78 could you please email us your username to kristian@duinocoin.com and we will check your accounts' status? Thanks!

**Comment by Tech1k** [comment]
> https://wallet.duinocoin.com/
> Not working properly i have 30 miners working and wallet show only 6 or 8 pzzz fix i am very irited of this issue

The pool and master server has had some issues with ESP32 boards, are you using ESP32s? If not, is this issue still occurring?

**Comment by scribas78** [comment]
@Tech1k thanks for your answer, currently everything is fine, I take advantage of your availability by asking you if by chance I might encounter problems if I add ESP32s to my arduino uno and nano for mining.

thank you very much

**Comment by Tech1k** [comment]
@SForney54 I'm glad I could help! Now with ESP32s, I believe @revoxhere has updated the ESP32 miner code and it should be okay if you add them, if not please let me know by opening another issue! Thank you!

**Comment by Osmodia666** [comment]
> ![DUINO WALLET](https://user-images.githubusercontent.com/89088790/129943060-b8fb4aec-91fb-4b2a-9e3d-4327f505532e.png)
> new problem with the wallet, when I try to log in.
> in these days of testing and renewals it is a continuous one

I have exact the same Problem, I cant log in. 
It worked find for a hour or so, since then I cant log in. I use ESP8266.

**Comment by scribas78** [comment]
@Tech1k 

![DUINO WALLET](https://user-images.githubusercontent.com/89088790/129971741-014d5cbe-e8ca-4700-90f2-0384e43d1b3f.png)
I sent the email, but now I have problems again ...

**Comment by scribas78** [comment]
![DUINO WALLET](https://user-images.githubusercontent.com/89088790/129972143-99b3887b-31a3-485d-a04a-1ea022b515f1.png)
is the one highlighted in the image normal?

**Comment by revoxhere** [comment]
I see nothing wrong, why do you think it's not normal?

**Comment by scribas78** [comment]
two miners with the same thread instead of being progressive, just for that ...
thank you

**Comment by Tech1k** [comment]
Seems like this has been answered and seeing your email, your account is in good standing so there isn't anything abnormal happening server-sided. If there's an issue on the websites, please try clearing your cache! Other than that, I'm going to close this issue as it looks like it has been resolved. If you encounter any other issues, please feel free to open another one, thanks!
