### ISSUE TITLE
ESP32 not connecting to Duino-Coin server

### ISSUE THREAD

**Issue by Bastiaan-Sw** [duino-coin/duino-coin#826]
ESP32 isn't connecting to the Duino-Coin server for days. I uploaded the new update today but still nothing. 
Had to change from sha/sha_parallel_engine.h to hwcrypto/sha.h because otherwise it wouldn't compile. 

Previous they where working all 4 fine but not more anymore.

More people having problems with ESP32's or does anybody know how to fix? Thank you already! 

Down under the screenshot of the serial plot. 

![image](https://user-images.githubusercontent.com/89106619/129802780-81c87cbe-67b4-4528-8dab-ab01e505059b.png)

**Comment by revoxhere** [comment]
Can you try now?

**Comment by Bastiaan-Sw** [comment]
Its fixed! Thank you so much! What was the problem?

**Comment by gsrbr** [comment]
We had a small problem with the pools, If everything is ok, could you please close this issue
