### ISSUE TITLE
ESP8266_Code:31:10: fatal error: ArduinoJson.h: No such file or directory    31 | #include <ArduinoJson.h> // https://github.com/bblanchon/ArduinoJson       |          ^~~~~~~~~~~~~~~ compilation terminated. exit status 1 ArduinoJson.h: No such file or directory

### ISSUE THREAD

**Issue by suradetch** [duino-coin/duino-coin#830]
ESP8266_Code:31:10: fatal error: ArduinoJson.h: No such file or directory
   31 | #include <ArduinoJson.h> // https://github.com/bblanchon/ArduinoJson
      |          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1
ArduinoJson.h: No such file or directory
![77777](https://user-images.githubusercontent.com/22225876/129953887-bacdbf26-5712-45a9-a137-02471b3b335d.PNG)

**Comment by revoxhere** [comment]
You don't have arduinojson installed, the link to install it is in the error you posted

**Comment by Tech1k** [comment]
Seems like all was fixed, I'll be closing this issue, but feel free to re-open it if any further package-related problems were to arise!
