### ISSUE TITLE
mining with two usb

### ISSUE THREAD

**Issue by dazmolybiz** [duino-coin/duino-coin#836]
Hi All

im very new here would just like to know i can get my 2 nanos mining from 2 different ports 
i can get it mining from but not 2 thanks for any help :)

**Comment by BastelPichi** [comment]
hmmm. yous hould be able. Can you give more information? Liek do they show up and not work, etc.

**Comment by dazmolybiz** [comment]
yes they are fine i have one on com6 that i am mining with and one in com9 
i just don't know how to get the mining program to both of them it is just picking 
up com6 miner i found a video but it is out of date

**Comment by dazmolybiz** [comment]
ok so i need to type some stuff in the avr miner but it starts mining as soon as i open it how do i stop it from mining so i can add more pots

**Comment by dazmolybiz** [comment]
ok i have found some info i have found the config file but not sure what i need to now
avrport = COM9
? how do i list the rest of my ports ?

**Comment by BastelPichi** [comment]
> 
> 
> ok i have found some info i have found the config file but not sure what i need to now
> avrport = COM9
> ? how do i list the rest of my ports ?

delte the config file

**Comment by sajadkkkkkk** [comment]
hello 
you can add multiple board for mining port .
just edit config file :
avrport =COM1 COM9

if you want to add third board, change to this 
avrport =COM1 COM9 COM6

dont forget to add space after each comport in config file.

**Comment by gsrbr** [comment]
Hello @sajadkkkkkk ! I think something are wrong.
This it's the code responsable to load the config 
`avrport = avrport.replace(" ", "").split(',')`
You need to put comas to separate the COMs, something like this:
`avrport = COM6,COM7`

Hello @dazmolybiz try to do something like this, with your respective ports(on the `Miner_config.cfg`):
`avrport = COM6,COM7`

**Comment by sajadkkkkkk** [comment]
hello @gsrbr ,
I am sorry about my mistake , you do right , comma is need for separating multiple port, 
thanks for your correction about my mistake.
