### ISSUE TITLE
ERROR: Connecting to Duino-Coin server... Loop WDT Failed!

### ISSUE THREAD

**Issue by Osmodia666** [duino-coin/duino-coin#837]
I have a NodeMCU V3, flashed with the latest sketch for mining DUINO Coin.
WiFi works, it is connected as I can see via serial and in my Fritzbox.

But I get "Connecting to Duino-Coin server..." and after some time "Loop WDT Failed!"
When I track the ESP with my online Wallet, I dont see any workers and nothing is happening. 

Arduino and ESP Library are both up to date.

Someone with similiar issues?

**Comment by Osmodia666** [comment]
Update:
It seems to be a bug with the up to date version (3.0.2) of the ESP8266 Board library. With Version 2.7.4 it works flawlessly. But any other version above this one doesn't work.

**Comment by BastelPichi** [comment]
Closed due to solve
