### ISSUE TITLE
i wan to mine with nodemcu but this error happen when i upload code to nodemcu pls help

### ISSUE THREAD

**Issue by Brahmashirsha** [duino-coin/duino-coin#844]
Arduino: 1.8.1 (Windows 8.1), Board: "NodeMCU 1.0 (ESP-12E Module), 160 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\CHAUDHRY-PC\Downloads\duino-coin-master\duino-coin-master\ESP8266_Code\ESP8266_Code.ino:31:10: fatal error: ArduinoJson.h: No such file or directory
   31 | #include <ArduinoJson.h> // https://github.com/bblanchon/ArduinoJson
      |          ^~~~~~~~~~~~~~~
compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by gsrbr** [comment]
Hello, The newest update for ESP boards (2.6.3) requires ArduinoJSON library, please read this tutorial/issue https://github.com/revoxhere/duino-coin/issues/832
