### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by PaleoAgTech** [duino-coin/duino-coin#848]
Connecting to Duino-Coin server...
Connected to the server. Server version: 2.6
Asking for a new job for user: agtech
Job received: BAD Please mine on the pool 1

On my ESP8266 it will give me this stuff and can someone please tell me what is pool 1 and how to get it?

Official Master Server: 51.15.127.80 port 2820. did work when I changed port. Gives me that message BAD Please mine on pool 1.
Official Kolka Pool: 149.91.88.18 port 6000. didnt even connect with server so what the hell I am doing wrong here?

**Comment by revoxhere** [comment]
You're not using the latest code. Please update to 2.6.3

**Comment by Gloomydemin** [comment]
![ShooterScreenshot-29-21-08-21](https://user-images.githubusercontent.com/52195266/130310756-5a5f226c-9ddd-444d-a320-7152d8c078db.png)
how to fix ?!

**Comment by gsrbr** [comment]
Hello @Gloomydemin , i think you are using the code [DuinoCoinI2C from ricaun](https://github.com/ricaun/DuinoCoinI2C) correct? If yes, open a issue in the  [project's own repository](https://github.com/ricaun/DuinoCoinI2C), there they can help you better

**Comment by BastelPichi** [comment]
> 1

use the latest PC miner, r cnnect manually to a different pool.
