### ISSUE TITLE
Multiple problems, significantly decreased effort

### ISSUE THREAD

**Issue by sp4m4r** [duino-coin/duino-coin#851]
Dears,

I'm a big fan of the project and started building my first rigs some weeks ago. Currently, it is about 10 ESP32's and 6 Arduino's using ricauns's setup. For the last weeks, that setup was mining an amount of around 150 DUCOs per day. Now, since the versions were updated to 2.6.3 with automatic pool switching I am facing several problems that I can't fix, whatever I am trying. 

I updated all ESP's with the latest version, not changing anything but WLAN-credentials. Setup is exactly the same then before. Libraries are all updated, no issues when compiling the code.

Main problems now are:

- significantly lowered income (now just 2-3 DUCOs per day)
- rejected shares of over 60% for every worker
- ESP's are reconnecting after submitting some shares due to watchdog restart what leads to
- much larger amounts of miners are shown in dashboard (nearly every ESP is counted twice so 10 ESP's are showing 40+ miners) what then leads to
- even more reduced income due to miner count penalty
- ricaun's setup can not fetch a working pool anymore

As I think the root cause to all problems is mostly likely the same I merged it all in one thread. Any advice or support is very welcome. Maybe others are facing similar problems? Anyway, thank you for the wonderful project and keep up the work revox et. al. !

examplary pictures
![image](https://user-images.githubusercontent.com/74241471/130317683-a5304b44-0cd2-4715-a3c5-111eb8e1f842.png)

![image](https://user-images.githubusercontent.com/74241471/130317712-9ac9ba61-87bb-434e-8611-604b26847611.png)

**Comment by n0t-f0ur13r** [comment]
There have been issues lately, and for now, mining is disabled, i hope that when all works to normal, your rigs work just as fine or even better than before u had this issue. plz be patient.

**Comment by n0t-f0ur13r** [comment]
You should check this post, maybe helps, but not now, because as i said, mining is disabled.
[Post By Beyondtoshi](https://github.com/revoxhere/duino-coin/issues/832)

**Comment by Tech1k** [comment]
Mining has since be reenabled and this should be fixed now! Please feel free to open another issue if you encounter any other issues!
