### ISSUE TITLE
not run PC_Miner.py to TERMUX Android 

### ISSUE THREAD

**Issue by redsun69** [duino-coin/duino-coin#855]
![WhatsApp Image 2021-08-21 at 21 57 26](https://user-images.githubusercontent.com/88141841/130325916-151aa80d-9853-4182-affb-60256c382906.jpeg)

Duino Json version 2.7

Version 2.6.1 Its ok run to Termux no Problem

**Comment by naphob** [comment]
What's your python version?

[edited] I can see from the log it's 3.9  

I suggest you try with 3.7. because my mac m1 also have an issue with python 3.9

**Comment by redsun69** [comment]
im update pyhton 3.9.2

ok thanks im check downgrade python 3.7

**Comment by gsrbr** [comment]
Hello @redsun69 , thanks for reporting this, are you still with problems? but just clearing things up we're re-writing the miner and the version 2.7 are unstable yet... U can use normally the last [stable release](https://github.com/revoxhere/duino-coin/releases) of the PC_Miner(2.6.1)

**Comment by BastelPichi** [comment]
The PCminer is nt fully supported on termux. Try to launch the minimal pc miner, or use the miner app: https://github.com/DoctorEenot/DUCOAndroidMiner/releases/tag/2.0

**Comment by Siddu012210** [comment]
can any one share me codes which any of you used to mine duco on termux pls

**Comment by gsrbr** [comment]
Hello @Siddu012210 , as said by BastelPichi the Pc miner does not have full compatibility with termux, I believe you are using Android and as already mentioned you can use the Android miner APK

https://github.com/revoxhere/duino-coin/issues/855#issuecomment-903985464
