### ISSUE TITLE
Is there a way to

### ISSUE THREAD

**Issue by dazmolybiz** [duino-coin/duino-coin#856]
i am running 5 nanos on 5 deferent usb ports is there a way to run like 4 nanos though 1 usb port ?

**Comment by gsrbr** [comment]
Hello @dazmolybiz , currently the codes developed by the Duinocoin community  dont have this functionality, you can use a usb hub, or take a look at this [project(by ricaun)](https://github.com/ricaun/DuinoCoinI2C) that connects some arduinos using esp as a host, and if you want you can try to develop this new functionality

**Comment by dazmolybiz** [comment]
@gsrbr Ok so i can just use a standard usb hub and say run 4 of them though the usb hub ?

**Comment by gsrbr** [comment]
Yes as long as the hub's power supply and USB's port power supply specifications support the number of arduinos

**Comment by dazmolybiz** [comment]
@gsrbr do you no any of the models number of the hubs that support this ?

**Comment by gsrbr** [comment]
You can enter our [server at discord](https://discord.gg/kvBkccy), there other users will be able to help you better based on their own experiences.

**Comment by BastelPichi** [comment]
Just use a usbhub.
