### ISSUE TITLE
Python script stops

### ISSUE THREAD

**Issue by Hiraviel** [duino-coin/duino-coin#857]
I'm using:

Termux
Python 3.8
PC_Miner (latest until today)

Description:

The script runs good, but I notice that when the miner get a Reject status, shows this error:

![IMG_20210821_110022515_HDR](https://user-images.githubusercontent.com/42154581/130327956-27cef535-f330-408c-a824-6300307fa5e9.jpg)

And, sometimes, the script stops.

This only happened to me with the new version (2.7),with the older one not.

**Comment by gsrbr** [comment]
Hello, thanks for reporting this, we are re-writing the miner and the version 2.7 are unstable yet... U can use normally the last [stable release](https://github.com/revoxhere/duino-coin/releases) of the PC_Miner(2.6.1)

**Comment by Hiraviel** [comment]
Thanks a lot champs.

**Comment by mcsham** [comment]
Process Process-5:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 315, in _bootstrap
  File "multiprocessing/process.py", line 108, in run
  File "PC_Miner.py", line 650, in mine
    result = Algorithms.DUCOS1(job[0], job[1], int(job[2]),
IndexError: list index out of range
Process Process-7:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 315, in _bootstrap
  File "multiprocessing/process.py", line 108, in run
  File "PC_Miner.py", line 650, in mine
    result = Algorithms.DUCOS1(job[0], job[1], int(job[2]),
IndexError: list index out of range
.....

 PC_Miner(2.7)

**Comment by gsrbr** [comment]
Hello @mcsham , thanks for reporting this, we are re-writing the miner and the version 2.7 are unstable yet... U can use normally the last [stable release](https://github.com/revoxhere/duino-coin/releases) of the PC_Miner(2.6.1)

**Comment by mcsham** [comment]
thx, but in 2.6.1
[2891541] Error loading Python lib '/tmp/_MEI9Zuz3I/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/_MEI9Zuz3I/libpython3.9.so.1.0)
my python version 3.8
os: linux

**Comment by BastelPichi** [comment]
> 
> 
> thx, but in 2.6.1
> [2891541] Error loading Python lib '/tmp/_MEI9Zuz3I/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/_MEI9Zuz3I/libpython3.9.so.1.0)
> my python version 3.8
> os: linux

Run `pip3 install GLIBC` and start again.
