### ISSUE TITLE
how to sell

### ISSUE THREAD

**Issue by dazmolybiz** [duino-coin/duino-coin#859]
what is the best way to sell these coins i am going to keep 50% and sell the other 50% but what is the best why what have you guys been doing ?

**Comment by ghost** [comment]
maths

**Comment by dazmolybiz** [comment]
not my strong point :)

**Comment by ghost** [comment]
go back to school

**Comment by gsrbr** [comment]
Hello @dazmolybiz , this channel(issues) is aimed at problems with the project,  you can talk with another users/miners on the [discord server](https://discord.gg/kvBkccyl) and you can read [this](https://duinocoin.com/getting-started#exchanges) too 
If it helped you, close the issue please.

And @business-goose take it easy
