### ISSUE TITLE
I got a new Miner by LabVIEW,which can be recorded by Unofficial miners

### ISSUE THREAD

**Issue by ericddm** [duino-coin/duino-coin#860]
https://github.com/ericddm/DuinoCoinbyLabVIEW

thanks to Revox and the team

**Comment by revoxhere** [comment]
Haha amazing, I'll add it in a second

**Comment by revoxhere** [comment]
Added in https://github.com/revoxhere/duino-coin/commit/388cb1136b8e3f6708e92ac8442a80c46aedbc49
