### ISSUE TITLE
Beyond-pool-2 doesn't work properly

### ISSUE THREAD

**Issue by naphob** [duino-coin/duino-coin#862]
I found that when my PC Miner v. 2.7 connects to Beyond-pool-2, it always crashes. Then I try debugging and found that the first job request will return [': 150'] that's supposed to be a return of worker limit instead of a worker's job. Please double-check. There might be a misconfiguration with this pool. 

I also found that there is no handler to validate the return job. I will request PR soon.

![Screen Shot 2564-08-22 at 19 00 00](https://user-images.githubusercontent.com/1431095/130354688-40eb9bab-75f0-4043-af9b-88fc4f4d4fa9.png)

**Comment by Tech1k** [comment]
Hello @naphob, I am also the operator of [BeyondPool](https://beyondpool.io) and this seems like a bug. I'll work with Revox to patch this, in the meantime, I may redeploy the 2nd node in hopes that it'll temporarily fix the bug!

**Comment by Tech1k** [comment]
Closing due to this issue most likely being resolved and due to inactivity.
