### ISSUE TITLE
ESP32 chooses a pool that cannot be connected to

### ISSUE THREAD

**Issue by nigeljohnson73** [duino-coin/duino-coin#864]
**Describe the bug**
Starting the ESP32 miner and it appears to attempt to connect to a pool before it has found one. Then the one it finds cannot be connected to, and no other one is then chosen after that. The ESP will reboot when the watchdog times out... Then it seems to choose the same pool again.

CORE1 Connecting to Duino-Coin server...
CORE1 connection failed

CORE2 Connecting to Duino-Coin server...
CORE2 connection failed
Fetched pool: winner-pool-1 193.164.7.180 6000

CORE1 Connecting to Duino-Coin server...

CORE2 Connecting to Duino-Coin server...
CORE2 connection failed
CORE1 connection failed

CORE2 Connecting to Duino-Coin server...

CORE1 Connecting to Duino-Coin server...
CORE2 connection failed

**To Reproduce**
Start the ESP32 miner.

**Expected behavior**
Wait until it chooses a pool. the choosing should, ideally, be done based on a time for a PING/PONG check on the designated port with a 5 second timeout.

**Screenshots/photos**
N/A

**System (please complete the following information):**
ESP32 running Duino-Coin ESP32 Miner v2.63

**Additional context**

**Comment by revoxhere** [comment]
Could you please try the new code? I think I fixed it https://github.com/revoxhere/duino-coin/blob/master/ESP32_Code/ESP32_Code.ino

**Comment by nigeljohnson73** [comment]
I'm sure I have the code in the link, significant changes to things like rigname now rig_identifier so pretty sure I got the latest copy, although it does say 2.6.3 in the startup.
Still doing it:

```
Duino-Coin ESP32 Miner v2.63

WiFi disconnected!
Scanning for WiFi networks
Scan done
21 networks found
4: NjMnr (-54)*

Please, check if your WiFi network is on the list and check if it's strong enough (greater than -90).
ESP32 will reset itself after 60 seconds if can't connect to the network
Connecting to: NjMnr...........
Connected to WiFi!
Local IP address: 10.10.1.152

Fetching pool... 

CORE1 Connecting to Duino-Coin server...
CORE1 connection failed
Fetched pool: winner-pool-1 - 193.164.7.180:6000

CORE1 Connecting to Duino-Coin server...

CORE2 Connecting to Duino-Coin server...
CORE1 connection failed
CORE2 connection failed

```

**Comment by revoxhere** [comment]
Hmm, so something's still wrong. It's hard for me to push any changes to this code as I don't own an esp32

**Comment by nigeljohnson73** [comment]
Ok, I'll have a bit of a think, not sure if I'm confident to tackle it, I might give it a try :)

Does the server handle a PING/PONG response on the job request  port? Otherwise I might just try a connection and see what happens.

**Comment by modfiles** [comment]
pool selection is base on pool load as i was informed and not base on ping/pong 
so by logic, a down server will have a 0% load hence, the pool selector system will try to connect to that. I havent seen the source code yet to check if it has a secondary or maybe primary check of pool server is implemented (a ping/pong maybe) to check if pool is up. i've experince same behaviour when auto pool select was 1st release always trying to connect to pulse pool the fact that it was down.

**Comment by nigeljohnson73** [comment]
My thinking so far is in the wifi reconnect function is to do a quick poll round the servers with a 2 second timeout

* get the pool list, foreach host/port:
* attempt a connect to the host/port and send some data ("PING")
* wait for the Response ("PONG")
* check the HTTP return status 
* if it's 200, check if the time is best yet
* Set a connectable flag so threads can use the best yet
* Threads wait for connectable flag, then can connect to the best yet

If the server later disconnects, the ESP will timeout on the watchdog, so should then find a new server.

If all the servers are up, the duration of this check in the wifi reconnect function will be low, if there are some outages, then a couple seconds per down server isn't that bad.

Pseudocode is easy though, let's see if I can put my fingers where my mouth is... so to speak :)

**Comment by revoxhere** [comment]
> pool selection is base on pool load as i was informed and not base on ping/pong
> so by logic, a down server will have a 0% load hence, the pool selector system will try to connect to that. I havent seen the source code yet to check if it has a secondary or maybe primary check of pool server is implemented (a ping/pong maybe) to check if pool is up. i've experince same behaviour when auto pool select was 1st release always trying to connect to pulse pool the fact that it was down.

Down servers are not available in the pool picker

**Comment by Tech1k** [comment]
This should have been fixed by now - closing, feel free to open a new issue if needed!
