### ISSUE TITLE
QUEREMOS TE AJUDAR REVOX

### ISSUE THREAD

**Issue by noobflix** [duino-coin/duino-coin#874]
Hello, how are you . . ? I am Brazilian and I am willing to help you with the security and failure of your system. in between. contact please.

**Comment by gsrbr** [comment]
Olá, tudo bem @noobflix ? o projeto é opensource sinta-se livre para ajudar

Hi, how are you? the project is opensource feel free to help

**Comment by primitt** [comment]
the entire project is open source, so you can commit something and start a pull request

**Comment by Tech1k** [comment]
Yep, as both @gsrbr and @primitt stated, the Duino-Coin project is open-source and you may contribute to it by opening a pull request!
