### ISSUE TITLE
 some duco's missing

### ISSUE THREAD

**Issue by hashArun** [duino-coin/duino-coin#875]
hi my duco missing my wallet please check the problam

**Comment by uhakito** [comment]
> hi my duco missing my wallet please check the problam

![Uploading Screenshot_20210824-014514.png…]()
Shut down your miners..! 😁

**Comment by Mikailelele** [comment]
hello, had to roll back the account data for the day

**Comment by Tech1k** [comment]
Yep, that is what has happened due to someone abusing the mining system using an unpatched bug - we are working on fixing that. Sadly, we had to rollback the data from the other day in order to keep duinocoin equal and fair. I hope this solves your issue!
