### ISSUE TITLE
register fail

### ISSUE THREAD

**Issue by maysrp** [duino-coin/duino-coin#876]
I can not register by cli_wallet.

**Comment by Tech1k** [comment]
This is most likely due to the master server having some temporary downtime, please try again and in a few hours and if it still doesn't work, please let me know!

**Comment by Channilee** [comment]
hey, when are you going to fix it? i cant wait to start mine ;)

**Comment by BastelPichi** [comment]
> 
> 
> hey, when are you going to fix it? i cant wait to start mine ;)

does it work over the webwallet?

**Comment by Channilee** [comment]
no. saying it will be fixed, until then no new wallets

**Comment by Channilee** [comment]
oh error is gone. but keep loading

**Comment by maysrp** [comment]
raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.

**Comment by BastelPichi** [comment]
Registering is currently disabled
