### ISSUE TITLE
Linux mining problem: "IndexError: list index out of range"

### ISSUE THREAD

**Issue by wenshenwang0416** [duino-coin/duino-coin#890]
Hi all, after I started "python3 PC_Miner.py" on linux, it shows up "IndexError: list index out of range" within couple minutes.
Can anyone help me to solve this issue?
thanks!

**Comment by n0t-f0ur13r** [comment]
Hi, we gotta know more, u should give the next info:
1. OS.
2. Version of the miner.
3. python version.
Suggestion: A screenshot of the problem would be amazing.

**Comment by bardoczs** [comment]
Hi. Same problem with Linux mint 19.3 Tricia, Duino-Coin PC miner 2.7, Python 3.6.9
![Képernyőkép 2021-08-29 19-16-35](https://user-images.githubusercontent.com/89741965/131257968-e7bfea98-9505-4e95-b215-da78bdcefc66.png)

**Comment by gsrbr** [comment]
Hello @wenshenwang0416 and @bardoczs  your issue was resolved into the [latest version](https://github.com/revoxhere/duino-coin/releases/latest)?

**Comment by wenshenwang0416** [comment]
Yes, thank you all!!
