### ISSUE TITLE
esp always resetting

### ISSUE THREAD

**Issue by xhanxoi** [duino-coin/duino-coin#892]
![COM8 8_26_2021 2_20_09 PM_LI](https://user-images.githubusercontent.com/89575247/130928537-a781fce0-e3d6-460f-bdad-0845a04d4f56.jpg)
after i upload the code its become like that(sry if im dumb im new at this thing)

**Comment by revoxhere** [comment]
Are you using an ESP32? if so, could you please try this code: https://github.com/revoxhere/duino-coin/blob/4bc69d9d1901807734ae9d7be44cce426b74f87c/ESP32_Code/ESP32_Code.ino

**Comment by xhanxoi** [comment]
> Are you using an ESP32? if so, could you please try this code: https://github.com/revoxhere/duino-coin/blob/4bc69d9d1901807734ae9d7be44cce426b74f87c/ESP32_Code/ESP32_Code.ino
im using ESP8266

**Comment by xhanxoi** [comment]
or maybe im wrong at the setting

**Comment by fionnh1** [comment]
I'm having the same problem
![ESP mining](https://user-images.githubusercontent.com/34201079/130975567-fd1651ee-bae8-4012-b79b-93f52c1d34d3.PNG)

**Comment by pinokio240** [comment]
> I'm having the same problem
> ![ESP mining](https://user-images.githubusercontent.com/34201079/130975567-fd1651ee-bae8-4012-b79b-93f52c1d34d3.PNG)

Hi, I also have esp8266 (NodeMCU v0.9). Everything works fine. Arduino IDE 1.8.0

**Comment by gsrbr** [comment]
Hello @pinokio240 and @fionnh1 the version v2.55 doesn't work anymore, try to use the last version of the code ([ESP32](https://github.com/revoxhere/duino-coin/tree/master/ESP32_Code) / [ESP8266](https://github.com/revoxhere/duino-coin/tree/master/ESP8266_Code)) if you have some issue with arduino json see [this](https://github.com/revoxhere/duino-coin/issues/832) or if you have some problem with parallel engine see [this](https://github.com/revoxhere/duino-coin/issues/841), and @xhanxoi is your problem resolved:heavy_check_mark:? if yes close this issue please

**Comment by xhanxoi** [comment]
yes thx u
