### ISSUE TITLE
Job received: BAN  1

### ISSUE THREAD

**Issue by PaleoAgTech** [duino-coin/duino-coin#906]
Now what is that? Got banned by mining ESP8266?

**Comment by nizarkb** [comment]
![IMG_20210828_000829](https://user-images.githubusercontent.com/73494354/131163994-014040f8-5c3a-4052-9079-2c39e1f91266.jpg)

BAD Share ? whats thats mean ?

**Comment by PaleoAgTech** [comment]
<img width="725" alt="Screenshot 2021-08-27 at 20 47 01" src="https://user-images.githubusercontent.com/61265195/131168963-3d806491-88cd-4ef1-bb09-59118e31d1ab.png">
I have exactly same issue now

workes with PC_Miner.py with ESP not working

**Comment by WLeon911** [comment]
Mine is the same. The damage time is about 7:00 am on August 26, 2021 Pacific Daylight Time (PST)
![001](https://user-images.githubusercontent.com/47353913/131205255-42eee291-0714-4c46-aefe-f0af893b2d82.png)

**Comment by oli737** [comment]
Same Problem with ESP8266. ESP32 Working fine. Both running 2.63 Version.

**Comment by nizarkb** [comment]
![image](https://user-images.githubusercontent.com/73494354/131213344-c237a5a1-a3b4-42db-9744-7b28badf0d9c.png)

thanx my esp8266 and pc miner / web miner back to online,
