### ISSUE TITLE
web wallet login 

### ISSUE THREAD

**Issue by rhjdjcbcz** [duino-coin/duino-coin#909]
When will webwallet login work? I am silent about the rest of the problems. For more than a week I have not been able to enter. constantly writes - wrong password.

**Comment by revoxhere** [comment]
Contact us at duino.coin@gmail.com with your username - we will see what's the problem

**Comment by rhjdjcbcz** [comment]
> 
> 
> Contact us at [duino.coin@gmail.com](mailto:duino.coin@gmail.com) with your username - we will see what's the problem

**Comment by rhjdjcbcz** [comment]
Hi!
my login is rhjdjcbcz.
I have been unable to log into the web wallet for a long time.
error on the screenshot in the attachment 

29.08.2021 10:37, Robert Piotrowski ***@***.***>
>Contact us at ***@***.*** with your username - we will see what's the problem
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/revoxhere/duino-coin/issues/909#issuecomment-907745509


-- реклама -----------------------------------------------------------
30 років Незалежності. Важливі дати в історії країни, які стали
двигуном на шляху до успіху і процвітання.https://bit.ly/3AYUN1e

**Comment by pankleks** [comment]
Hello - I have the same problem - can't login to my account for a few days - either hangs or say user not exist or it's banned.

**Comment by BastelPichi** [comment]
> Hello - I have the same problem - can't login to my account for a few days - either hangs or say user not exist or it's banned.

contact them with your username at duino.coin@gmail.com
