### ISSUE TITLE
Web Waller Login Failed

### ISSUE THREAD

**Issue by nizarkb** [duino-coin/duino-coin#913]
![Screenshot_20210829_123601](https://user-images.githubusercontent.com/73494354/131239878-d88edc71-a033-4781-834a-bff33800257b.jpg)

wallet login failed

**Comment by Traction6131** [comment]
Well as writen there, the wallet api isnt reachable, so just wait.

**Comment by nizarkb** [comment]
ok, thanx @shruuub

**Comment by nizarkb** [comment]
finnaly its back to online
