### ISSUE TITLE
Duinocoin amount not shown @ Pancakeswap 

### ISSUE THREAD

**Issue by Osmodia666** [duino-coin/duino-coin#917]
I want to trade Duinocoin on Pancakeswap. If I open the link via the Webwallet, the contract is added, but it doesn't show any amount of Duinocoin I mined, just 0.

Pancakeswap is connected with my Browser, all other tokens I have are shown correctly.
I have about 80 duco's, but I guess it's not the problem.

**Comment by Boatkungg** [comment]
https://github.com/revoxhere/duino-coin/wiki/bscDUCO-Tutorial

You have to wrap it first

**Comment by Osmodia666** [comment]
Thx, that was it.
