### ISSUE TITLE
Shouldn't you stop FUJICoin Support?

### ISSUE THREAD

**Issue by sp4m4r** [duino-coin/duino-coin#921]
Dears,

I'm not very deep into the "financial" part of the project because I'm much more interested in building the stuff. Anyway, I noticed that the coin support increased from 6M something on friday to nearly 8M DUCO's right now. There are several big stack holders with >100k I did not noticed within the last weeks. So, I found that buying DUCO's with FJC might be an explanation, as it is veeery cheap it seems.

Please check it yourself and please excuse if I'm wrong and everything is fine with FJC.

![image](https://user-images.githubusercontent.com/74241471/131261246-dc762c86-80e9-4b78-b8d1-5f6a0971dcec.png)

I think there is something wrong with the coin, as the market broke down today.

![image](https://user-images.githubusercontent.com/74241471/131261304-a0610c02-1aba-46e4-a84e-f84a9813e329.png)

**Comment by revoxhere** [comment]
I'll just raise the buy prices, thanks for notifying me!

**Comment by sp4m4r** [comment]
Dear Revox,

I do not want to annoy you or the others, but I think increasing to 300FJC for 1DUCO is still way to low, please see below.

![image](https://user-images.githubusercontent.com/74241471/131261908-b3c1986b-55b5-4c14-89a1-9b586a788aab.png)

![image](https://user-images.githubusercontent.com/74241471/131261919-43e40b8b-5bae-4f70-b79d-b00fe561e641.png)

Kind regards! :)

**Comment by primitt** [comment]
What is the ideal rate?
