### ISSUE TITLE
My ESP8266 cannot connect to the server

### ISSUE THREAD

**Issue by xbb-mcl** [duino-coin/duino-coin#925]
**My ESP8266 cannot connect to the server.
My serial monitor displays:**

13:56:35.598 -> Duino-Coin ESP8266 Miner v2.55
13:56:35.598 -> Connecting to:    EXAMPLE SSID
13:56:39.843 -> 
13:56:39.843 -> Connected to WiFi!
13:56:40.051 -> Local IP address: 192.168.1.101
13:56:40.258 -> 
13:56:40.258 -> Connecting to Duino-Coin server...
13:59:00.053 -> Loop WDT Failed!
13:59:00.053 -> Resetting ESP...
13:59:00.053 -> 
13:59:00.053 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
13:59:00.053 -> 
13:59:00.053 -> Exception (9):
13:59:00.053 -> epc1=0x40105ca0 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000003 depc=0x00000000
13:59:00.053 -> 
13:59:00.053 -> >>>stack>>>
13:59:00.053 -> 
13:59:00.053 -> ctx: sys
13:59:00.053 -> sp: 3fffece0 end: 3fffffb0 offset: 0190
13:59:00.053 -> 3fffee70:  00000000 00000002 3ffe8a2a 40207a24  
13:59:00.053 -> 3fffee80:  40105ed1 02b12ab5 3ffeead4 00000000  
13:59:00.053 -> 3fffee90:  3ffee350 3ffeead4 3ffee928 60000600  
13:59:00.053 -> 3fffeea0:  00000000 02b0edac 40207158 00000032  
13:59:00.053 -> 3fffeeb0:  3ffeead4 0000000a 00000001 401004bc  
13:59:00.053 -> 3fffeec0:  089d0893 00000001 00000000 40201170  
13:59:00.053 -> 3fffeed0:  00000000 0010001f 00000000 60000600  
13:59:00.053 -> 3fffeee0:  089d0893 3ffee350 3ffee928 40100258  
13:59:00.053 -> 3fffeef0:  3fff011c 0010001f 80000000 40217735  
13:59:00.053 -> 3fffef00:  089d0723 3ffee350 3ffee7dc 4020deea  
13:59:00.053 -> 3fffef10:  402414e8 3ffee7dc 3ffee350 4020e236  
13:59:00.053 -> 3fffef20:  60000600 3ffee7dc 3ffee350 402414f5  
13:59:00.053 -> 3fffef30:  4024153a 3fffdab0 00000000 3fffdcb0  
13:59:00.053 -> 3fffef40:  3ffee360 3fffdad0 3ffeea6c 4020674e  
13:59:00.053 -> 3fffef50:  40000f49 40000f49 3fffdab0 40000f49  
13:59:00.053 -> 3fffef60:  40000e19 0004f7c0 00000000 00000005  
13:59:00.053 -> 3fffef70:  3fffefc0 aa55aa55 000000ed 401055f5  
13:59:00.086 -> 3fffef80:  401055fb 00000000 00000005 40100b60  
13:59:00.086 -> 3fffef90:  4010000d 40207050 0004f7c0 401000ac  
13:59:00.086 -> 3fffefa0:  40231830 3fffef3c 402317e9 3ffffdf8  
13:59:00.086 -> 3fffefb0:  3fffffc0 00000000 00000000 feefeffe  
13:59:00.086 -> 3fffefc0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3fffefd0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3fffefe0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3fffeff0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff000:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff010:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff020:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff030:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff040:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff050:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff060:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff070:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff080:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff090:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff0a0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff0b0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff0c0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff0d0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff0e0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff0f0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff100:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff110:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff120:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.086 -> 3ffff130:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff140:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff150:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff160:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff170:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff180:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff190:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff1a0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff1b0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff1c0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff1d0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff1e0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff1f0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff200:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff210:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff220:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff230:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff240:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff250:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff260:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff270:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff280:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff290:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff2a0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff2b0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff2c0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff2d0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff2e0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff2f0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.121 -> 3ffff300:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff310:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff320:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff330:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff340:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff350:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff360:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff370:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff380:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff390:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff3a0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff3b0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff3c0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff3d0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff3e0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff3f0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff400:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff410:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff420:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff430:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff440:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff450:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff460:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff470:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff480:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff490:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff4a0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff4b0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff4c0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.156 -> 3ffff4d0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff4e0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff4f0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff500:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff510:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff520:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff530:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff540:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff550:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff560:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff570:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff580:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff590:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff5a0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff5b0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff5c0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff5d0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff5e0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff5f0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff600:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff610:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff620:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff630:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff640:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff650:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff660:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff670:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff680:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff690:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.191 -> 3ffff6a0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff6b0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff6c0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff6d0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff6e0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff6f0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff700:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff710:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff720:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff730:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff740:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff750:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff760:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff770:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff780:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff790:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff7a0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff7b0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff7c0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff7d0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff7e0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff7f0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff800:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff810:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff820:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff830:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff840:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff850:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff860:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.226 -> 3ffff870:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff880:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff890:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff8a0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff8b0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff8c0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff8d0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff8e0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff8f0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff900:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff910:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff920:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff930:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff940:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff950:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff960:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff970:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff980:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff990:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff9a0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff9b0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff9c0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff9d0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff9e0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffff9f0:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffffa00:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffffa10:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffffa20:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffffa30:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffffa40:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.261 -> 3ffffa50:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.296 -> 3ffffa60:  feefeffe feefeffe feefeffe feefeffe  
13:59:00.296 -> 3ffffa70:  00000000 00000000 0000001f 4010030c  
13:59:00.296 -> 3ffffa80:  feefeffe feefeffe 3fffc228 40105d8d  
13:59:00.296 -> 3ffffa90:  4000050c feefeffe feefeffe feefeffe  
13:59:00.296 -> 3ffffaa0:  401002e4 00000030 0000001b ffffffff  
13:59:00.296 -> 3ffffab0:  4023cafa 00000020 3ffeea5a 00000020  
13:59:00.296 -> 3ffffac0:  00000001 ffffffc3 3ffe901c 00000000  
13:59:00.296 -> 3ffffad0:  3ffec938 3ffe90b4 000000a0 3ffec918  
13:59:00.296 -> 3ffffae0:  3ffef42c 00000001 3fff00ac 00000030  
13:59:00.296 -> 3ffffaf0:  4000050c feefeffe 3fffc228 40105d8d  
13:59:00.296 -> 3ffffb00:  4000e190 00000030 00000010 ffffffff  
13:59:00.296 -> 3ffffb10:  400018ac 3ffed090 00000000 00000020  
13:59:00.296 -> 3ffffb20:  3ffec8c8 00000000 3fff01c2 00000001  
13:59:00.296 -> 3ffffb30:  00000003 00000001 00000002 3ffefc2c  
13:59:00.296 -> 3ffffb40:  3ffec918 3ffefc2c 4023d9fb 00000001  
13:59:00.296 -> 3ffffb50:  ffffffff 00000000 3ffe92d1 00000008  
13:59:00.296 -> 3ffffb60:  4023da4a 3ffec8f0 3ffef42c 00000001  
13:59:00.296 -> 3ffffb70:  00000002 00000000 00000020 4010030c  
13:59:00.296 -> 3ffffb80:  00000005 00000005 00000002 4010225c  
13:59:00.296 -> 3ffffb90:  3ffe9182 4023cb07 3ffec8f0 3fff00ac  
13:59:00.296 -> 3ffffba0:  00000000 40226153 3ffedc70 3ffef42c  
13:59:00.296 -> 3ffffbb0:  00000000 00000002 4023d9fb 00000001  
13:59:00.296 -> 3ffffbc0:  ffffffff 00000000 3ffe92d1 00000008  
13:59:00.296 -> 3ffffbd0:  4023da4a 3ffec918 3ffef42c 00000001  
13:59:00.296 -> 3ffffbe0:  4023db56 3ffec918 3ffef42c 3ffec918  
13:59:00.296 -> 3ffffbf0:  00000005 00000005 00000008 3fff01a8  
13:59:00.296 -> 3ffffc00:  3ffe9182 4023cb07 3ffec918 3fff018c  
13:59:00.296 -> 3ffffc10:  00000000 40226153 3ffedc70 3ffef42c  
13:59:00.296 -> 3ffffc20:  00000000 00000002 00000000 3ffec918  
13:59:00.296 -> 3ffffc30:  3fff01c2 40105b37 3ffefc2c 3ffeed70  
13:59:00.331 -> 3ffffc40:  00000005 00000000 00000020 4010030c  
13:59:00.331 -> 3ffffc50:  3ffeed88 40217009 00000005 4010225c  
13:59:00.331 -> 3ffffc60:  3ffe9185 401054f3 3ffecbe8 4010225c  
13:59:00.331 -> 3ffffc70:  40102de7 3ffecbe8 3ffecbe8 3ffeed88  
13:59:00.331 -> 3ffffc80:  ffffffed 08613989 3ffed4a4 40102fc4  
13:59:00.331 -> 3ffffc90:  3ffe9a18 00000000 00000000 40217692  
13:59:00.331 -> 3ffffca0:  ffffffed 08613989 4010347e 00000100  
13:59:00.331 -> 3ffffcb0:  3ffe9a18 7fffffff 00002200 00000001  
13:59:00.331 -> 3ffffcc0:  00000001 00000080 3ffef098 4021d240  
13:59:00.331 -> 3ffffcd0:  3ffe9a18 3ffeffec 000000ff 08613989  
13:59:00.331 -> 3ffffce0:  3ffe9a24 2c9f0300 4000050c 3fffc278  
13:59:00.331 -> 3ffffcf0:  401031a0 3fffc200 00000022 3fff018c  
13:59:00.331 -> 3ffffd00:  401002e4 00000030 00000017 ffffffff  
13:59:00.331 -> 3ffffd10:  40105ed4 00000020 3ffeea5a 00000000  
13:59:00.331 -> 3ffffd20:  00000001 3ffeead4 000035af 00000000  
13:59:00.331 -> 3ffffd30:  3ffeead4 3ffee328 3ffeead4 029e4023  
13:59:00.331 -> 3ffffd40:  3ffeead4 00000000 3ffee350 00000030  
13:59:00.331 -> 3ffffd50:  00000006 3ffef198 3ffe85e0 00000000  
13:59:00.331 -> 3ffffd60:  00000011 3ffeffec 00000020 3fff0204  
13:59:00.331 -> 3ffffd70:  3ffeed88 3ffeffec 00000000 4021ecac  
13:59:00.331 -> 3ffffd80:  3ffeed88 00000000 00000000 4021f711  
13:59:00.331 -> 3ffffd90:  4020162b 00000030 00000064 4021ecd2  
13:59:00.331 -> 3ffffda0:  3ffeed88 00000000 00000000 4021f837  
13:59:00.331 -> 3ffffdb0:  0000009f 00000000 00000040 4021ad6a  
13:59:00.331 -> 3ffffdc0:  40105c4d 02b0ec39 00000000 4021f711  
13:59:00.331 -> 3ffffdd0:  00f42400 0e7d9a2e 02b0ec00 00000000  
13:59:00.331 -> 3ffffde0:  40105ed1 02b0ed74 3ffeead4 00000000  
13:59:00.331 -> 3ffffdf0:  3ffee350 3ffeead4 00000001 3ffeead4  
13:59:00.331 -> 3ffffe00:  0000117d 00001770 402067d4 3fffefa0  
13:59:00.331 -> 3ffffe10:  3ffeead4 0000117d 00001770 40207166  
13:59:00.331 -> 3ffffe20:  00000000 3ffef8c4 3ffee808 40202a16  
13:59:00.331 -> 3ffffe30:  3ffeffec 3ffee82c 00000000 3ffeea6c  
13:59:00.366 -> 3ffffe40:  40204674 3ffe8a29 3ffee928 3ffeea6c  
13:59:00.366 -> 3ffffe50:  00001770 40202930 3ffee808 40202194  
13:59:00.366 -> 3ffffe60:  4020eacc 12585b95 4020eacc 12585b95  
13:59:00.366 -> 3ffffe70:  3ffe8902 00000000 4020eacc 40204d24  
13:59:00.366 -> 3ffffe80:  3fffdad0 3ffee928 3ffee808 4020162b  
13:59:00.366 -> 3ffffe90:  00000000 3ffefedc 3ffeffbc 4020a506  
13:59:00.366 -> 3ffffea0:  00000000 00000000 00000000 4020a370  
13:59:00.366 -> 3ffffeb0:  3ffef210 0000204a 00000000 00000000  
13:59:00.366 -> 3ffffec0:  3ffef210 3ffe8be5 3ffefec4 4020a5e0  
13:59:00.366 -> 3ffffed0:  3ffe8bb5 00000000 00000000 402086ec  
13:59:00.366 -> 3ffffee0:  00000005 00000006 3fffff60 40205c98  
13:59:00.366 -> 3ffffef0:  3ffe8887 00011170 3fffff60 40205dbd  
13:59:00.366 -> 3fffff00:  3fffff20 00011170 3fffff60 4021255c  
13:59:00.366 -> 3fffff10:  00000004 3ffeead4 3fffff60 40205e6e  
13:59:00.366 -> 3fffff20:  65393939 00006635 00000001 40207166  
13:59:00.366 -> 3fffff30:  0000119d 00000004 3fffff60 40205cec  
13:59:00.366 -> 3fffff40:  3ffe88d4 00011170 3ffee7f0 40205d8e  
13:59:00.366 -> 3fffff50:  3ffe8887 00011170 3ffee7c8 402014a0  
13:59:00.366 -> 3fffff60:  00000000 00006635 00000000 00000000  
13:59:00.366 -> 3fffff70:  00000000 001f001f 00000000 40201070  
13:59:00.366 -> 3fffff80:  4020eacc 6501a8c0 feefeffe feefeffe  
13:59:00.366 -> 3fffff90:  feefeffe feefeffe feefeffe 3ffeea6c  
13:59:00.366 -> 3fffffa0:  3fffdad0 00000000 3ffeea58 40206900  
13:59:00.366 -> <<<stack<<<
13:59:00.366 -> 
13:59:00.366 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------

**The serial monitor displays them over and over again!**

**Comment by gsrbr** [comment]
Hello, you are using the old version of the code(v2.55), please try to download and flash the [latest release](https://github.com/revoxhere/duino-coin/releases/latest)

**Comment by xbb233** [comment]
Thanks.It worked!

**Comment by xbb-mcl** [comment]
Thanks.It worked!
