### ISSUE TITLE
The miner does not work

### ISSUE THREAD

**Issue by romanmajorov** [duino-coin/duino-coin#928]
Hi, there's some mistake again...

![image](https://user-images.githubusercontent.com/57148482/131322984-ea1cf9ad-2f67-44c4-b287-92e6a8647485.png)

**Comment by gsrbr** [comment]
Hi, thanks for reporting this, you are using the simple miner, correct? probably by the end of this week I should release an update to it to support the new changes, but we are already working so that in the future you can use the official miner

**Comment by gsrbr** [comment]
Hello @romanmajorov ,we have updated the official miner, and now it works on windows 7/8
![image](https://user-images.githubusercontent.com/27559775/132268122-83bc7d50-45e8-4c34-b813-30e3f88c72b9.png)
Can you test it please?

**Comment by romanmajorov** [comment]
The miner is working stably, thank you ;)
