### ISSUE TITLE
Too many workers

### ISSUE THREAD

**Issue by RonSchLabs** [duino-coin/duino-coin#934]
Hello. After the update to 2.7 there is again the limitation of workers. Will that stay at 50 or will it increase? When increases from when? THANKS

**Comment by BastelPichi** [comment]
> 
> 
> Hello. After the update to 2.7 there is again the limitation of workers. Will that stay at 50 or will it increase? When increases from when? THANKS

For now it will stay at that low, but due to kolka a lot more than 50 dont makes sence anyway
