### ISSUE TITLE
Notify-py is not installed. Continuing without notification system.

### ISSUE THREAD

**Issue by shenbushou** [duino-coin/duino-coin#935]
![image](https://user-images.githubusercontent.com/64524981/131361561-8d57a83a-e782-4e8a-8da9-8988b52eccc9.png)
Notify-py is not installed. Continuing without notification system.

why！！！！

**Comment by ghost** [comment]
Hi, I don't get the highlighted part of the screenshot so I'm basing what I'm about to say on 

> Notify-py is not installed. Continuing without notification system.

notify-py is a python module that you can install by doing "python3 -m pip install notify-py". Also, notify-py is an optional module which means that you can use the wallet without it and ignore the message ^^

Cheers
