### ISSUE TITLE
Getting sick and tired with always having issues with this system

### ISSUE THREAD

**Issue by PaleoAgTech** [duino-coin/duino-coin#936]
Fetched pool: beyond-pool-2 35.173.194.122 6000

Connecting to Duino-Coin server...
Asking for a new job for user: agtech
Job received: 05b7406b3909071b2d85b2d2958ad07a0d52bd12 fd1712d654fa18863316523dfe7219623133028f 47202201

its getting stuck here and will reset after a minute or so.

WILL YOU PLEASE RELEASE SOMETHING STABLE SOON

**Comment by revoxhere** [comment]
> WILL YOU PLEASE RELEASE SOMETHING STABLE SOON

No

**Comment by PaleoAgTech** [comment]
too bad son

**Comment by DuinocoinMiner** [comment]
paleoagtech for it and release something stable yourself

**Comment by gravedigger21** [comment]
revoxhere,

Не можешь срать - не мучай жопу
You can't shit - don't torture your ass

**Comment by PaleoAgTech** [comment]
Well who ever is wondering. I have watt hour counter hooked up to my ESP8266 and its my experiment. But I cant get accurate numbers of it's always buggy...

**Comment by revoxhere** [comment]
> revoxhere,
> 
> Не можешь срать - не мучай жопу
> You can't shit - don't torture your ass

xd?

**Comment by DuinocoinMiner** [comment]
Well who ever is wondering. I have watt hour counter hooked up to my ESP8266 and its my experiment. But I cant get accurate numbers of it's always buggy...

why are you telling us? we did not ask and we dont care
