### ISSUE TITLE
Nano issue 

### ISSUE THREAD

**Issue by dazmolybiz** [duino-coin/duino-coin#937]
i am getting the following when i am trying to upload the new code to my nano 

Arduino: 1.8.15 (Windows 10), Board: "Arduino Nano, ATmega328P (Old Bootloader)"

Arduino_Code:1:1: error: stray '`' in program

 `/*

 ^

exit status 1

stray '`' in program

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by gsrbr** [comment]
Hello, as reported I compiled the source code and didn't get any problem, I believe you have accidentally typed an invalid character in the middle of the code, to ensure this download the [latest version](https://github.com/revoxhere/duino-coin/releases/latest) again and try to compile, if the problem persists just make a new comment, if resolved close the issue please
![image](https://user-images.githubusercontent.com/27559775/131580957-9498961f-e388-4833-a948-73e5df0f808f.png)

**Comment by BastelPichi** [comment]
Try to update the miner, and upload again

**Comment by gsrbr** [comment]
Hello @dazmolybiz , is your problem resolved?

**Comment by BastelPichi** [comment]
Closed due to inactivity, feel free to reopen if needed.
