### ISSUE TITLE
duino coin from 0.018 to 0.00476 ?

### ISSUE THREAD

**Issue by domotic2002** [duino-coin/duino-coin#948]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by domotic2002** [comment]
What's the point in mining Duino coin ,Somethimes stuck on bad shares than again ok .
It's no fun anymore. 
The software is so fragile that when putting a simple print in comment ,you get stuck on bad shares afterwards.

**Comment by PaleoAgTech** [comment]
Had same issue try using lwIP variant "v2 higher bandwidth"

**Comment by domotic2002** [comment]
Thankx , i try it tomorrow.

Op wo 1 sep. 2021 18:15 schreef PaleoAgTech ***@***.***>:

**Comment by BastelPichi** [comment]
> What's the point in mining Duino coin ,Somethimes stuck on bad shares than again ok .
> It's no fun anymore.
> The software is so fragile that when putting a simple print in comment ,you get stuck on bad shares afterwards.

just make it better and commit, or just use the newest versiion and it should be fine aswell.
