### ISSUE TITLE
Specific system library version

### ISSUE THREAD

**Issue by bardoczs** [duino-coin/duino-coin#949]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bardoczs** [comment]
Hi. your  latest closed source pc miner version ask for a specific glibc library version, 2.29. Glibc  is a system library, upgrading  a system library to a newer version is not so easy. Your previous Pc_Miner version does not have specific system library dependencies. If you plan to go closed source, try to compile your binaries  more generic, without specific dependency requirements.
###@###:~/Asztal/DuinoCoin2.7$ ./PC_Miner
[28119] Error loading Python lib '/tmp/_MEIMF9uc2/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIMF9uc2/libpython3.9.so.1.0)

**Comment by ghost** [comment]
Hm? PC_Miner.py isn't and (I think) will never be closed source. It's a python script and as such a text file. Also, the "closed source plan" was only for the AVR sketch files and not for the classic miners for non-AVR boards. Can you explain what system you're using? Ubuntu? Arch? Can you try running "cat /etc/os-release" and "ldd --version"?

**Comment by bardoczs** [comment]
My mistake, I downloaded the Duino-Coin_2.7_linux.zip archive which contains PC_Miner binary file. PC_Miner.py from source code is working.
