### ISSUE TITLE
I am used pc miner on kali linux 

### ISSUE THREAD

**Issue by Brahmashirsha** [duino-coin/duino-coin#951]
I am use pc miner on kali linux everything is fine miner is running without any issue
But the balance is not shown in my wallet and not detected miner in wallet pls help

**Comment by zybertech07** [comment]
for me also from yesterday no rewards and miners not showing

**Comment by zybertech07** [comment]
for me also, this problem is begin from 29\aug\2021. i have report this issue in this [contact page](https://duinocoin.com/contact) so you also report this issue

**Comment by revoxhere** [comment]
Check now.
