### ISSUE TITLE
No miners visible in wallet?

### ISSUE THREAD

**Issue by Arun0k** [duino-coin/duino-coin#952]
I'm fairly new to DUCO mining but have tried it in the past so there is a small balance on my wallet.

Although: today i've restarted mining on 2x raspberry pi and 1x windows GUI miner.

On both web wallet as windows wallet there's no active miners, although i can see my PC and 2x raspi miners active. Anyone?

**Comment by zybertech07** [comment]
for me also, this problem is begin from 29\aug\2021. i have report this issue in this [contact page](https://duinocoin.com/contact) so you also report this issue

**Comment by revoxhere** [comment]
Try now.

**Comment by Arun0k** [comment]
Thanks. Works like a charm after verification
