### ISSUE TITLE
When will this fuc*ing end?

### ISSUE THREAD

**Issue by gravedigger21** [duino-coin/duino-coin#960]
I'm tired of the constant problems: it is impossible to enter the wallet, the miners hang in the reboot more than they work. For a day, 1 coin runs with difficulty. You can’t do the normal work of the resource - close the fuck up this project and don’t fool people.

**Comment by revoxhere** [comment]
I'm not closing anything, it's my project I take care of in my free time, and correct me if I'm wrong, but I don't think anybody is forcing you to use duino.

**Comment by Tech1k** [comment]
I side with Revox on this, we are doing the best we can and if you have a problem with that, just don't use duinocoin, simple as that.
