### ISSUE TITLE
Wallets don't work.

### ISSUE THREAD

**Issue by rhjdjcbcz** [duino-coin/duino-coin#962]
A few days ago, I wrote about the problem with entering the web wallet - https://github.com/revoxhere/duino-coin/issues/909. I contacted duino.coin@gmail.com. There is still no answer or solution to the problem. In addition, from today, no wallet works at all, neither the web wallet, nor the CLI_Wallet 2.7.1. Before that, at least in Wallet.exe, you could see the balance and statistics of my miners. Today it shows a balance of 0 and not a single miner is visible.
CLI_wallet constantly writes - Cannot connect to the server. It is probably under maintenance or temporarily down.
Retrying in 15 seconds.

**Comment by revoxhere** [comment]
Hello, please use the Web wallet for now.

**Comment by rhjdjcbcz** [comment]
> 
> 
> Hello, please use the Web wallet for now.

I have already written twice that for some unknown reason I cannot enter the Web wallet. How many more times do I need to write about this?
![web wallet](https://user-images.githubusercontent.com/89688263/132123277-32ae68cb-303f-421f-b20e-b6e27163dc0f.jpg)

**Comment by revoxhere** [comment]
You can write it a million times if you want, I do not have only you to take care of.
What's your username? You can contact me at robik123.345@gmail.com and we will reset your password.

**Comment by rhjdjcbcz** [comment]
If you carefully read the messages of other users, you should have noticed that this is not only my problem.
I am sure that my password is correct since I successfully logged in to Walet.exe a few days ago. But ok, I'll write you a message now to reset my password.

**Comment by alexa212** [comment]
hi friends why is my rig not being read in wab wallet

**Comment by BastelPichi** [comment]
> hi friends why is my rig not being read in wab wallet

Try to restart it

**Comment by revoxhere** [comment]
Closing as the problem has been solved via email
