### ISSUE TITLE
無法註冊錢包

### ISSUE THREAD

**Issue by tyng1977** [duino-coin/duino-coin#963]
你好，我是新手，我註冊錢包延遲很久，我嘗試幾次都無法註冊錢包

**Comment by gsrbr** [comment]
Hello @tyng1977 , try to create your wallet using the [webwallet](https://wallet.duinocoin.com/)

_Note: some characters are not allowed on the username/password, the system only accept `"^[A-Za-z0-9_-]*$"` ->that is, from A to Z (lowercase or uppercase), 0 to 9, the dash and the underline_

**Comment by tyng1977** [comment]
謝謝gsrbr
