### ISSUE TITLE
[AVR_Miner.py] Script freezes after a while v2.7.1/2.7.2

### ISSUE THREAD

**Issue by Hiraviel** [duino-coin/duino-coin#964]
I'm using:

Raspberry Pi Zero
Screen command to run the script
AVR_Miner.py v2.7.2

Description:

While running the script through a screen command, everything seems fine:

![image](https://user-images.githubusercontent.com/42154581/132134655-7d609b48-29b4-47a9-89ba-0560a91db787.png)
![image](https://user-images.githubusercontent.com/42154581/132134699-75147e0f-513b-43b9-b31c-a9b447cdedab.png)

NOTE: Interestingly, I get fewer USB connection errors than >=v2.6

After a while, sometimes earlier than other, the Script "freezes".
The "screen" doesn't update, as well the wallet doesn't show my Arduino Miners (The ones called "Arduinos").

![image](https://user-images.githubusercontent.com/42154581/132135255-a70f0af6-4f06-4d00-8627-88e49b6061d9.png)

So i need to stop the screen, restart a new one, and wait. If not, reboot the pi and start from the beginning.

User JK Rolling commented that could be related with the "ser.close()" loop (v2.7.1), but I'm not that good to identify where it should be changed.

Thanks in advance for your efforts to make this Script stable as possible.

**Comment by revoxhere** [comment]
2.7.2 already has that ser.close implemented

**Comment by Hiraviel** [comment]
Thanks for your response,

I'm using v2.7.2 and continues freezing.

I reinstalled again the OS (raspbian lite), reinstalled Screen (so I believe it's the latest version) and use the "get started" steps to get the latest AVR_Miner.py script.
 
Later I'll try to run it without screen, I need to move some cables, and watch if it stops only with it to update this issue.

Thanks again.

**Comment by revoxhere** [comment]
If you want, enable the debug output in the miner config file, that should show more info when it freezes

**Comment by Hiraviel** [comment]
Since your last reply, the script it's working flawlessly. Debug mode it's activated, just in case.

This issue can be closed, thanks.
