### ISSUE TITLE
Wallet API is unreachable

### ISSUE THREAD

**Issue by eswar159** [duino-coin/duino-coin#973]
**Wallet API is unreachable**
Hi
In new here and this is the first time I'm using ![2021-09-07 (2)](https://user-images.githubusercontent.com/35969578/132376615-19817fd6-50dc-4884-8477-afd495979fdf.png)

1st Everything is working fine but sometimes I'm getting this error "Wallet API is unreachable"
I'm entering the user name correct and password correct even then I'm getting the error
and 

2nd one more thing is my mining update on the web wallet is never been done I need to close the application(that terminal one) multiple times and open multiple times so my device will slowly shown in the active devices 

I'm using pc for mining..

I don't know wether its the case only with me or its a bug 
please once look into it

Thank you 
once when I'm able to log in I will share a video so u can have a look at exactly what I'm facing the 2nd issue

1st issue screen shots have been added
![2021-09-07 (1)](https://user-images.githubusercontent.com/35969578/132376550-79356417-f893-46c4-8529-e09425bfa324.png)

**Comment by eswar159** [comment]
2nd issue I think it is a temporary issue anyway have a look here
Video is made 3x...


https://user-images.githubusercontent.com/35969578/132382438-8d693bbc-486a-4d5e-97c8-c9a5020702a5.mp4

**Comment by gsrbr** [comment]
Hello @eswar159, Duco's API is down at the moment, so the web wallet doesn't work properly... We're working to resolve this as soon as possible

**Comment by eswar159** [comment]
Thank a lot for the response

**Comment by eswar159** [comment]
Hi 
Still the syncing of "Your miners" is  no resolved 
am I the only one facing the issue as the news center says
"Pools are starting to sync again, we will continue to monitor the situation"
Please look into it once

Thank you

**Comment by arbisyahku** [comment]
my Wallet API is unreachable to .. I'm entering the user name correct and password correct even then I'm getting the error.. helm me
