### ISSUE TITLE
錢包 API 無法訪問

### ISSUE THREAD

**Issue by tyng1977** [duino-coin/duino-coin#975]
無法登入網路錢包

**Comment by gsrbr** [comment]
Hello, we're having some instabilities, but we're already working to resolve this, and a warning has already been issued as seen in the "News center" within the wallet login screen or on this [link](https://server.duinocoin.com/news.html)
Please, for easier support you could open it in english, chinese is not among my skills

**Comment by tyng1977** [comment]
謝謝你們的努力，你們都很棒!加油!!
