### ISSUE TITLE
JSONDecodeError when launching AVR_Miner on Raspberry Pi

### ISSUE THREAD

**Issue by Cravati** [duino-coin/duino-coin#978]
**Describe the bug**
After pasting the "Mine with your Arduinos using Raspberry Pi as Host" commands into the Teminal, I get an error and it doesn't move on to asking for my Duino Username.

**To Reproduce**
Fresh install of Raspbian 5.10
Open Terminal
Copy and execute...
     sudo apt update && sudo apt upgrade -y # Update dependencies
     sudo apt install python3 python3-pip git # Install python3 and git
     git clone https://github.com/revoxhere/duino-coin # Clone the duino-coin repository
     cd duino-coin # Enter the duino-coin directory
     python3 AVR_Miner.py # Launch the official miner

**Expected behavior**
Error after Launching AVR_Miner.

**Screenshots/photos**
![TerminalScreenshot](https://user-images.githubusercontent.com/90291521/132429966-1a84e65f-b978-4cc8-a8a9-d683f4c38e14.jpg)

**System (please complete the following information):**
 - OS: Raspberry Pi OS with desktop. Kernel Version 5.10
 - AVR_Miner

**Comment by JK-Rolling** [comment]
to workaround, simply add a comma to end of line 807 in resources/langs.json, save and rerun. I've submitted pull request so need to wait for developer to approve

**Comment by Cravati** [comment]
where is resources/langs.json? Not finding it.

**Comment by JK-Rolling** [comment]
to be exact `AVRMiner_2.72_resources/langs.json`

**Comment by Cravati** [comment]
Thanks. Added comma to the end of line 807 and still have the same issue. What am I doing wrong?

**Comment by deadpool010** [comment]
> Thanks. Added comma to the end of line 807 and still have the same issue. What am I doing wrong?

The line for me was 806, even thought it says 807. 

` "connection_search": "Sunuculara baÄŸlanmak iÃ§in en hÄ±zlÄ± baÄŸlantÄ± aranÄ±yor",`  <-- added a comma here

**Comment by bradbyte** [comment]
FYI, this has been fixed in https://github.com/revoxhere/duino-coin/pull/979.

**Comment by revoxhere** [comment]
Closing since the issue has been fixed
