### ISSUE TITLE
Your miners Syncing Issue

### ISSUE THREAD

**Issue by eswar159** [duino-coin/duino-coin#980]
Hi 
Still the syncing of "Your miners" is  no resolved 
am I the only one facing the issue as the news center says
"Pools are starting to sync again, we will continue to monitor the situation"
Please look into it once

Thank you

_Originally posted by @eswar159 in https://github.com/revoxhere/duino-coin/issues/973#issuecomment-915223217_

**Comment by eswar159** [comment]
the issue has been resolved completely

So I want as a question what difficulty do u suggest me to use 
Below is the screenshot of my pc Specs
![Screenshot_9](https://user-images.githubusercontent.com/35969578/132555903-43169da7-95de-4b7f-a212-5d0ab89e809c.png)
 
 currently using difficulty medium and if u try using hard do I mine more?
 
 
thank you

**Comment by gsrbr** [comment]
I think the better for your hardware it's use the medium difficulty...

**Comment by eswar159** [comment]
thanks for the info
