### ISSUE TITLE
Tkinter GUI Wallet Connection refused

### ISSUE THREAD

**Issue by dapiced** [duino-coin/duino-coin#982]
Each time i try to use the Tkinter GUI Wallet i got this error :

``root@pi4:/home/pi/Documents/duino-coin#` python3  Wallet.py`
                                                                       
`Exception in Tkinter callback`                                                                                                      
`Traceback (most recent call last):`                                                                                                  
`  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__  `                                                          
`    return self.func(*args)   `                                                                                                     
`  File "/home/pi/Documents/duino-coin/Wallet.py", line 283, in _login_btn_clicked  `                                                
`    soc = websocket.create_connection(WS_URI) `                                                                            
`  File "/usr/local/lib/python3.9/dist-packages/websocket/_core.py", line 596, in create_connection `                              
`    websock.connect(url, **options) `                                                                     
`  File "/usr/local/lib/python3.9/dist-packages/websocket/_core.py", line 249, in connect `                                   
`    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options), `                                       
`  File "/usr/local/lib/python3.9/dist-packages/websocket/_http.py", line 130, in connect `                                    
`    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)  `                                      
`  File "/usr/local/lib/python3.9/dist-packages/websocket/_http.py", line 208, in _open_socket      `                                
`    raise err                                                                                                                      `
`  File "/usr/local/lib/python3.9/dist-packages/websocket/_http.py", line 185, in _open_socket        `                              
`    sock.connect(address) `                                                                                 `                        
`ConnectionRefusedError: [Errno 111] Connection refused ``

THank
Dominic

**Comment by gsrbr** [comment]
Hello @dapiced , as seen on the release [2.7.1](https://github.com/revoxhere/duino-coin/releases/tag/2.7.1) -> `GUI Wallet is being deprecated in favor of the Web one` 
Here it's the [link for the webwallet](https://wallet.duinocoin.com/)

**Comment by dapiced** [comment]
thx

**Comment by dapiced** [comment]
thx
