### ISSUE TITLE
Error don´t connect raspberry and PC :(

### ISSUE THREAD

**Issue by chosselxxl** [duino-coin/duino-coin#985]
23:30:56  net0  Searching for the fastest node to connect to
23:31:56  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:32:11  net0  Searching for the fastest node to connect to
23:33:11  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:33:26  net0  Searching for the fastest node to connect to
23:34:27  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:34:42  net0  Searching for the fastest node to connect to
23:35:42  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:35:57  net0  Searching for the fastest node to connect to
23:36:57  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:37:12  net0  Searching for the fastest node to connect to
23:38:13  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:38:28  net0  Searching for the fastest node to connect to
23:39:28  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:39:43  net0  Searching for the fastest node to connect to
23:40:43  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:40:58  net0  Searching for the fastest node to connect to
23:41:59  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:42:14  net0  Searching for the fastest node to connect to
23:43:14  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:43:29  net0  Searching for the fastest node to connect to
23:44:29  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:44:44  net0  Searching for the fastest node to connect to
23:45:45  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s
23:46:00  net0  Searching for the fastest node to connect to
23:47:00  net0  Error retrieving mining node: Expecting value: line 1 column 1 (char 0), retrying in 15s

**Comment by gsrbr** [comment]
Hello @chosselxxl , we are facing some intsbilities in our services and the function that should power getPool is not working properly, affecting the miners who are starting their work at this time, we are already working to find the cause and solve the problem

**Comment by gsrbr** [comment]
Can you try again please, the issue was resolved

**Comment by chosselxxl** [comment]
Is ok now, thanks for all.

A sexta, 10/09/2021, 01:05, gsrbr ***@***.***> escreveu:
