### ISSUE TITLE
PC_Miner.py can not run properly.

### ISSUE THREAD

**Issue by panayotovip** [duino-coin/duino-coin#990]
**Describe the bug**
PC_Miner.py can not run properly.

**To Reproduce**
git clone https://github.com/revoxhere/duino-coin.git
cd duino-coin
python3 PC_Miner.py

**Expected behavior**
normal mining.

**Screenshots/photos**
```
 ‖ Official Duino-Coin © Python Miner (2.73) 2019-2021
 ‖ https://github.com/revoxhere/duino-coin
 ‖ CPU: 1x ARMv7 Processor rev 5 (v7l)
 ‖ Developer donation level: 0
 ‖ Algorithm: DUCO-S1 ⚙ Low diff

00:52:52  net0  Searching for the fastest node to connect to
Traceback (most recent call last):
  File "/root/duino-coin/PC_Miner.py", line 894, in <module>
    Donate.start(int(user_settings["donate"]))
  File "/root/duino-coin/PC_Miner.py", line 284, in start
    pretty_print(
  File "/root/duino-coin/PC_Miner.py", line 379, in pretty_print
    + Style.BRIGHT + bg_color + " " + sender + " "
UnboundLocalError: local variable 'bg_color' referenced before assignment
```

**System (please complete the following information):**

 - OS: Linux pipc1 5.10.43-sunxi 21.05.6 SMP Mon Jun 21 15:07:45 UTC 2021 armv7l armv7l armv7l GNU/Linux
 - Software PC_Miner.py 2.73 (update Saturday, 11 September 2021, 22:01:01 UTC)

**Comment by revoxhere** [comment]
Git pull and try now

**Comment by panayotovip** [comment]
now ok.
👍
