### ISSUE TITLE
ESP32 kolka auto-difficulty issue

### ISSUE THREAD

**Issue by airtikit** [duino-coin/duino-coin#997]
My ESP32 starting difficulty 800, but after a while the difficulty started to go awry.

**System:**
- Arduino IDE v1.8.16
- Arduino core for the ESP32 v2.0.0
- Official code for ESP32 boards version 2.7 (latest version)

![image](https://user-images.githubusercontent.com/86959594/132998276-09a92938-6cad-418a-b18d-212ade4b6de4.png)

**Comment by airtikit** [comment]
- Official code for ESP32 boards version 2.7.3
**Still same problem as version 2.7**

![image](https://user-images.githubusercontent.com/86959594/134721234-bda0d936-b17c-4758-96c4-9cdc755356bf.png)

**Comment by gsrbr** [comment]
Hello @airtikit the difficulty are ajusted auomaticaly by Kolka System, generally the dificult for ESP32 it's arround 800~1500 but it can be changed by your hashrate and/or the `DIFF_MULTIPLIER` parameter (this are defined by the main server).... I thik your hashrate are high, the maximun hashrate for ESP32 it's 16KH/s per core, and you are having 17KH/s Making kolka relocate you for the next difficulty, are you using a overclocked/modified ESP32 ?


**Example**
![image](https://user-images.githubusercontent.com/27559775/134751733-3eacedbd-348c-48f2-8b52-901a47a4b0e5.png)
On the image above you can see one of my ESP32, with a 25.93KH/s(Core 1 - ~14162.08H/s / Core 2 - ~12940.9H/s  as you can see on the API result on the booton) with a normal difficulty...
`"miners":[,{"accepted":195,"algorithm":"DUCO-S1","diff":800,"hashrate":14162.08,"identifier":"None","pool":"null-pool-1","rejected":0,"sharetime":2.062,"software":"Official ESP32 Miner 2.73","threadid":"","username":"","wd":""},{"accepted":191,"algorithm":"DUCO-S1","diff":800,"hashrate":12940.9,"identifier":"None","pool":"null-pool-1","rejected":0,"sharetime":6.338,"software":"Official ESP32 Miner 2.73","threadid":"","username":"","wd":""},]`

**Comment by airtikit** [comment]
I'm using ESP32 NodeMCU, Chip ESP-WROOM-32 not overclocked and modified.
![image](https://user-images.githubusercontent.com/86959594/134760251-67ca2de6-8b66-4f59-9b7b-c29c28351f4b.png)

When using hardware library **"hwcrypto/sha.h"** my ESP32 get hash 12k-14k. **(Arduino core for the ESP32 v1.0.6)**

But I using hardware library **"sha/sha_parallel_engine.h"** my ESP32 hashing up to 16k-18k. **(Arduino core for the ESP32 v2.0.0)**

![image](https://user-images.githubusercontent.com/86959594/134759980-626e0cbe-220b-4393-a3d1-a4e69eb5f872.png)

**Comment by gsrbr** [comment]
Thanks for the info, we will work to resolve this

**Comment by revoxhere** [comment]
I have recently pushed a fix to this in the pools, does the issue still happen?

**Comment by airtikit** [comment]
Thanks a lot, my ESP32 work stably.
